<?php
//
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	if ($this->type==1){
		if (!empty($this->detailscore)){
			$title = $tr->translate('UPDATE_TEST_EXAM_KH_RESULT');
		}else{$title = $tr->translate('CREATE_TEST_EXAM_KH');
		}
	}else if ($this->type==2){
		if (!empty($this->detailscore)){
			$title = $tr->translate('UPDATE_TEST_EXAM_EN_RESULT');
		}else{$title = $tr->translate('CREATE_TEST_EXAM_EN');
		}
	}else if ($this->type==3){
		if (!empty($this->detailscore)){
			$title = $tr->translate('UPDATE_TEST_EXAM_UNIV_RESULT');
		}else{
			$title = $tr->translate('CREATE_TEST_EXAM_UNIV');
		}
	}
	echo $this->headTitle($title);
	$frm = $this->form;
	
	$key = new Application_Model_DbTable_DbKeycode();
	$keySetting = $key->getKeyCodeMiniInv(TRUE);
	$studyInfoSetting=empty($keySetting['study_info_setting']) ? 1 : $keySetting['study_info_setting'];
	$multiProgramClass="d-none";
	if($studyInfoSetting !=1){ 
		$multiProgramClass = "";
	}
?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<div class="card">
	<div class="card-content collapse show">
		<form id='frm_teststudent' action="" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
			<script type="dojo/method" event="onSubmit" enctype="multipart/form-data">			
			if(this.validate()) {
				if(dijit.byId("branch_id").get("value")==''){
                    alert("<?php echo $tr->translate("PLEASE_SELECT_BRANCH");?>");
					dijit.byId("branch_id").focus();
					return false;
				}
				if(dijit.byId("degree").get("value")==''){
                    alert("<?php echo $tr->translate("PLEASE_SELECT_DEGREE");?>");
					dijit.byId("degree").focus();
					return false;
				}
				degree_test = dijit.byId("degree").get("value");
				degree_result = dijit.byId("degree_result").get("value");
				if(isNaN(degree_result)){degree_result=0;}
				if(degree_result>0 && degree_test!=degree_result){
					dijit.byId("degree_result").focus();
					 if (confirm('<?php echo $tr->translate("ARE_YOU_WANT_TO_SAVE_WITH_RESULT_DIFFERENCE_DEGREE");?>') == true) {
					  } else {
						return false;
					  }
					
				}


				var totalScore = dijit.byId('score').get('value'); 
				if(isNaN(totalScore)){
					totalScore=0;
				}
				if(totalScore>0){
					//if(dijit.byId("grade_result").get("value")==''){
                   	 	//alert("<?php echo $tr->translate("PLEASE_SELECT_GRADE");?>");
						//dijit.byId("grade_result").focus();
						//return false;
					//}
				}
				if(dijit.byId('academic_year').get("value")==''){
					alert("<?php echo $tr->translate("PLEASE_SELECT_YEAR");?>");
					dijit.byId("academic_year").focus();
					return false;
				}
				loadingBlock();
				return true;
			}else {
				return false;
			}
			</script>
			<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-file-code-o" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;
		    			<?php echo $title;?>
		    			</h4>
	    			</div>
	    			<div class="col-sm-4 text-right"></div>
	    		</div>
	    	</div>
	    	<div class="card-box">
	        	<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="d-flex"> 
								<div class="settings-main-icon ">
									<i class="glyphicon glyphicon-user" aria-hidden="true"></i>
								</div> 
								<div class="col-md-10 col-sm-10 col-xs-12"> 
									<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("STUDENT_INFO");?></p>
								</div> 
							</div>
							<div class="form-group">
								<label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("BRANCH");?> <span class="required">*</span> :
								</label>
								<div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement("branch_id");?>
									<?php echo $frm->getElement("id");?>
									<input type="hidden" dojoType="dijit.form.TextBox" id="schoolOption" name="schoolOption" value="<?php echo $this->type;?>"/>
									<input type="hidden" name="inFrame" id="inFrame" value="<?php echo $this->inFrame;?>"  dojoType="dijit.form.TextBox" class='fullside'/>
								</div>
							</div>
							<div class="form-group">
								<label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("STUDENT");?> <span class="required">*</span>:
								</label>
								<div class="col-md-7 col-sm-7 col-xs-12">
										<?php echo $frm->getElement("stu_test_id");?>
								</div>
							</div>
							<div class="d-flex"> 
								<div class="settings-main-icon ">
									<i class="fa fa-info" aria-hidden="true"></i>
								</div> 
								<div class="col-md-10 col-sm-10 col-xs-12"> 
									<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("TEST_INFO");?></p>
								</div> 
							</div>
							<div class="form-group">
								<label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("DEGREE");?> <span class="required">*</span>:
								</label>
								<div class="col-md-7 col-sm-7 col-xs-12">
										<?php echo $frm->getElement("degree");?>
								</div>
							</div>
							<div class="form-group">
								<label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("GRADE")?> <span class="required">*</span>:
								</label>
								<div class="col-md-7 col-sm-7 col-xs-12">
										<input id="grade" />
								</div>
							</div>
							<div class="form-group">
								<label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("TEST_TERM")?> :
								</label>
								<div class="col-md-5 col-sm-5 col-xs-12">
										<?php echo $frm->getElement("term_test");?>
								</div>
								<div class="col-md-2 col-sm-2 col-xs-12">
									<input class="button-class button-primary" iconClass="glyphicon glyphicon-refresh" type="button" label="<?php echo $tr->translate('REFRESH');?>" dojoType="dijit.form.Button" onclick="AllRefresh();"/>
								</div>
							</div>
							<div class="form-group">
								<label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("TEST_DATE");?> :
								</label>
								<div class="col-md-7 col-sm-7 col-xs-12">
										<?php echo $frm->getElement("test_date");?>
								</div>
							</div>

						</div>
					</div>
	             </div>

	             <div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="d-flex"> 
								<div class="settings-main-icon ">
									<i class="glyphicon  glyphicon-sound-5-1" aria-hidden="true"></i>
								</div> 
								<div class="col-md-10 col-sm-10 col-xs-12"> 
									<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("RESULT_TEST");?></p>
								</div> 
							</div>
							
							<div class="form-group">
								<label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("ACADEMIC_YEAR");?> <span class="required">*</span>:
								</label>
								<div class="col-md-7 col-sm-7 col-xs-12">
										<input id="academic_year" name="academic_year" />
								</div>
							</div>
							<div class="form-group">
								<label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("ACADIMIC_YEAR_FEE")?> :
								</label>
								<div class="col-md-7 col-sm-7 col-xs-12">
										<input id="fee_id" />
										<input type="hidden" dojoType="dijit.form.TextBox"   id="studentStudyFee" name="studentStudyFee" value="<?php //echo $this->currentFee['id'];?>"/>
								</div>
							</div>
							<div class="form-group">
								<label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("STATUS");?> :
								</label>
								<div class="col-md-7 col-sm-7 col-xs-12">
										<?php echo $frm->getElement("resultStatus");?>
								</div>
							</div>
							<div class="form-group">
								<label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("RESULT_DATE");?> <span class="required">*</span>:
								</label>
								<div class="col-md-7 col-sm-7 col-xs-12">
										<?php echo $frm->getElement("result_date");?>
								</div>
							</div>
								<div class="form-group">
								<label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("SCORE");?> <span class="required">*</span>:
								</label>
								<div class="col-md-7 col-sm-7 col-xs-12">
										<?php echo $frm->getElement("score");?>
								</div>
							</div>
							<div class="form-group">
								<label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("COMMENTS");?> :
								</label>
								<div class="col-md-7 col-sm-7 col-xs-12">
										<?php echo $frm->getElement("comment");?>
								</div>
							</div>
							<div class="form-group">
								<label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("DEGREE");?> :
								</label>
								<div class="col-md-7 col-sm-7 col-xs-12">
										<?php echo $frm->getElement("degree_result");?>
								</div>
							</div>
							<div class="form-group">
								<label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("GRADE")?> :
								</label>
								<div class="col-md-7 col-sm-7 col-xs-12">
										<input id="grade_result" />
								</div>
							</div>
							<div class="form-group">
				            	<label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("PART_TIME_LIST");?></label>
				                <div class="col-md-7 col-sm-7 col-xs-12">
				                   	<input id="part_time_list" />
				                </div>
				            </div>
							<div class="form-group <?php if($studyInfoSetting!=2){echo "d-none";}?>">
								<label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("PROGRAM_TYPE");?>  :
								</label>
								<div class="col-md-7 col-sm-7 col-xs-12">
									<select class="custome-select-opt fullside" onchange="getProgramInfo();"  placeHolder="<?php echo $tr->translate("SELECT_PROGRAM_TYPE"); ?>" required="false" name="programType" id="programType" ></select>
								</div>
							</div>
							
						</div>
					</div>
	             </div>

	             <div class="col-md-4 col-sm-4 col-xs-12">
					 <div class="card-blogform">
						<div class="card-body"> 
							<div class="form-group">
								<label class="control-label col-md-12 col-sm-12 col-xs-12" ><?php echo $tr->translate("NOTE")?> :
								</label>
							</div>
							<div class="form-group">
								<div class="col-md-12 col-sm-12 col-xs-12">
										<?php echo $frm->getElement("note");?>
								</div>
							</div>
						</div>
					 </div>
					 
					 <div class="card card-form mb-4 subClassInfo">
						<div class="card-header bg-label-primary pb-2 rounded">
							<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("SCHOOL_OPTIONS_INFO");?></h5>
							<div class="form-group">
								<div class="col-md-4 col-sm-4 col-xs-12">
									<input id="degreeAddRow" />
								</div>
								<div class="col-md-4 col-sm-4 col-xs-12">
									<input id="gradeAddRow" />
								</div>
								<div class="col-md-4 col-sm-4 col-xs-12">
									<input class="button-class button-warning" iconClass="glyphicon glyphicon-sort-by-attributes" type="button" label="<?php echo $tr->translate('Add Record');?>" dojoType="dijit.form.Button" onclick="addRowStudy();" />
								</div>
							</div>
						</div>
						<div class="card-body p-0">
							<div class="row g-3">
								<table class="collape responsiveTable">
									<thead>
										<tr id="head-title_study" class="head-td" align="right" style="white-space:nowrap;"></tr>
									</thead>
									<tbody id="table_row_study" >
									</tbody>
								</table>
								<input type="hidden" name="identity_study" id="identity_study"  />
							</div>
						</div>
					</div>
					
	              </div>
	         </div>
	         <?php if ($this->type==1){?>
	         <div class="card-box">
	         	<div class="col-md-12 col-sm-12 col-xs-12">
					<div class="card-blogform">
							<div class="card-body"> 
								<div class="d-flex "> 
									<div class="settings-main-icon ">
										<i class="glyphicon glyphicon-list-alt" aria-hidden="true"></i>
									</div> 
									<div class="col-md-10 col-sm-10 col-xs-12"> 
										<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("SUBJECT_RESULT_TEST");?></p>
									</div> 
								</div>
								<div class="form-group mt-10">
										<?php $identity="";?>
										<table  id="table_row" style=" white-space:nowrap; width:100%; border-collapse: collapse; border:1px solid #ccc;">
												<tr id="head-title" class="head-td" align="center" >
													<td><?php echo $tr->translate("N_O");?></td>
													<td><?php echo $tr->translate("SUBJECT");?></td>
													<td><?php echo $tr->translate("SCORE");?></td>
													<td><?php echo $tr->translate("COMMENTS");?></td>
													<td><?php echo $tr->translate("NOTE");?></td>
												</tr>
												<?php if (!empty($this->subjectScore)){?>
													<?php $i=1;  foreach ($this->subjectScore as $rs){ $i++;
															$subjectitle=$rs['subject'];
															if (empty($identity)){
																$identity=$i;
															}else{$identity=$identity.",".$i;
															}
													?>
													<tr>
														<td width="4%" align="center"><?php echo $i;?></td>
														<td>&nbsp;<input  dojoType="dijit.form.TextBox" class="fullside" name="subjecttest_id_<?php echo $i;?>" id="subjecttest_id_<?php echo $i;?>" value="<?php echo $rs['subjecttest_id'];?>" type="hidden"><?php echo $subjectitle;?>&nbsp;</td>
														<td><input dojoType="dijit.form.NumberTextBox" onKeyup="CalculateTotalScore()" class="fullside" name="score_<?php echo $i;?>" id="score_<?php echo $i;?>" value="<?php echo $rs['score'];?>" type="text"></td>	
														<td>
															<select autoComplete="false" queryExpr="*${0}*" dojoType="dijit.form.FilteringSelect" class="fullside" id="comment_<?php echo $i;?>" name="comment_<?php echo $i;?>" style="width:100%;">
																<option value="1" <?php if ($rs['comment']==1){ echo 'selected="selected"';}?>><?php echo $tr->translate("GOOD")?></option>
																<option value="2" <?php if ($rs['comment']==2){ echo 'selected="selected"';}?>><?php echo $tr->translate("GOOD_FAIR")?></option>
																<option value="3" <?php if ($rs['comment']==3){ echo 'selected="selected"';}?>><?php echo $tr->translate("FAIR")?></option>
																<option value="4" <?php if ($rs['comment']==4){ echo 'selected="selected"';}?>><?php echo $tr->translate("WEAK")?></option>
															</select>
															<input  dojoType="dijit.form.TextBox" class="fullside" name="detailid<?php echo $i;?>" id="detailid<?php echo $i;?>" value="<?php echo $rs['id'];?>" type="hidden">
														</td>
														<td><input  dojoType="dijit.form.TextBox" class="fullside" name="note_<?php echo $i;?>" id="note_<?php echo $i;?>" value="<?php echo $rs['note'];?>" type="text"></td>
													</tr>
													<?php }?>
												<?php }else{?>
													<?php 
													$i = 0;
													if(!empty($this->rs_subjecttestkhmer)){foreach($this->rs_subjecttestkhmer as $rs){
															$subjectitle="";
															$i++;
															if (empty($identity)){$identity=$i;}else{$identity=$identity.",".$i;}
													
														?>
													<tr>
														<td width="4%" align="center"><?php echo $i;?></td>
														<td>&nbsp;<input  dojoType="dijit.form.TextBox" class="fullside" name="subjecttest_id_<?php echo $i;?>" id="subjecttest_id_<?php echo $i;?>" value="<?php echo $i;?>" type="hidden"><?php echo $rs['name'];?>&nbsp;</td>
														<td><input dojoType="dijit.form.NumberTextBox" onKeyup="CalculateTotalScore()" class="fullside" name="score_<?php echo $i;?>" id="score_<?php echo $i;?>" value="" type="text"></td>	
														<td>
															<select autoComplete="false" queryExpr="*${0}*" dojoType="dijit.form.FilteringSelect" class="fullside" id="comment_<?php echo $i;?>" name="comment_<?php echo $i;?>" style="width:100%;">
																<option value="1"><?php echo $tr->translate("GOOD")?></option>
																<option value="2"><?php echo $tr->translate("GOOD_FAIR")?></option>
																<option value="3"><?php echo $tr->translate("FAIR")?></option>
																<option value="4"><?php echo $tr->translate("WEAK")?></option>
															</select>
														</td>
														<td><input  dojoType="dijit.form.TextBox" class="fullside" name="note_<?php echo $i;?>" id="note_<?php echo $i;?>" value="" type="text"></td>
													</tr>
													<?php }}?>
												<?php }?>
										</table>
										<input type="hidden" name="identity" id="identity" value="<?php echo $identity;?>"  />
								</div>
							</div>
					</div>
			    </div>
	         </div>
	         <?php }?>
	         <div class="card-box">
               	<div class="col-sm-12 border-top mt-20 ptb-10 text-center">
               		<input label="<?php echo $tr->translate("SAVE_CLOSE")?>" name='saveclose' id='saveclose' value='saveclose' dojoType="dijit.form.Button" type="submit"  class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-remove"/>
	    		</div>
	    	</div>
	    </form>
	 </div>
</div>
<link href="<?php echo $this->baseUrl()."/admin"?>/3.5.0/select2.css" rel="stylesheet">
<script src="<?php echo $this->baseUrl()."/admin"?>/3.5.0/select2.min.js"></script>
<script src="<?php echo $this->baseUrl();?>/admin/js/global.js"  type="text/javascript"></script>
<script type="text/javascript">
    dojo.require("dojo.NodeList-manipulate");
    dojo.require("dojo.data.ItemFileWriteStore");  
    dojo.require("dijit.form.Textarea");
    dojo.require("dijit.form.DateTextBox");
    dojo.require("dijit.form.NumberTextBox");
</script>
<script>
var degree_store = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
var grade_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
var grade_result_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
var student_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
var academic_store= getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
var part_time_list_store = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
require(["dojo/ready"], function(ready){
	dojo.ready(function(){
		new dijit.form.FilteringSelect({
			store: grade_store,
			autoComplete:false,
			queryExpr:'*${0}*',                     
			required: false,
			id: "grade",
			name: "grade",           
			class: "fullside", 
			placeHolder:"<?php echo $tr->translate('SELECT_GRADE');?>",          
			onChange: function() {  
			}
		}, "grade");

		new dijit.form.FilteringSelect({
			store: grade_result_store,
			autoComplete:false,
			queryExpr:'*${0}*',                  
			required: false,
			id: "grade_result",
			name: "grade_result",           
			class: "fullside", 
			placeHolder:"<?php echo $tr->translate('SELECT_GRADE');?>",          
			onChange: function() {  				
			}
		}, "grade_result");

		new dijit.form.FilteringSelect({
			store: academic_store,
			queryExpr: "*${0}*",
			autoComplete: false,                     
			required: true,                     
			id: "academic_year",
			name: "academic_year",
			class: "fullside", 		
			placeHolder:"<?php echo $tr->translate("SELECT_ACADEMIC_YEAR");?>",          
			onChange: function() {  
				getAllFeeByBranch();
			}
		}, "academic_year");


		new dijit.form.FilteringSelect({
			queryExpr: "*${0}*",
			autoComplete:false,                     
			required: false,                     
			id: "fee_id",
			name: "fee_id",
			class: "fullside", 		
			placeHolder:"<?php echo $tr->translate("PLEASE_SELECT_STUDENT_FEE");?>",          
			onChange: function() {  
				fee_id = dijit.byId('fee_id').get('value');
			}
		}, "fee_id");

	    new dijit.form.FilteringSelect({
			store: part_time_list_store,
			autoComplete: false,
			queryExpr:'*${0}*',                        
			required: false,
			id: "part_time_list",
			name: "part_time_list",           
			class: "fullside", 
			placeHolder:"<?php echo $tr->translate('PART_TIME_LIST');?>",          
			onChange: function() {  
			}
		}, "part_time_list");
		
		new dijit.form.FilteringSelect({
			store: degree_store,
			queryExpr: "*${0}*",
			autoComplete: false,                     
			required: false,
			id: "degreeAddRow",
			name: "degreeAddRow",           
			class: "fullside", 
			placeHolder:"<?php echo $tr->translate("SELECT_DEGREE");?>",          
			onChange: function() {  
				getSubGrade();
			}
		}, "degreeAddRow");
		
		new dijit.form.FilteringSelect({
			queryExpr: "*${0}*",
			autoComplete:false,                     
			required: false,                   
			id: "gradeAddRow",
			name: "gradeAddRow",  
			tabindex: "16",  
			class: 'fullside',  
			placeHolder:"<?php echo $tr->translate("SELECT_GRADE");?>",          
			onChange: function() {  
			}
		}, "gradeAddRow");
		
		$(".custome-select-opt").select2(
			{dropdownAutoWidth : true,allowClear: "true"}
		);
		
		var resultStatus = dijit.byId('resultStatus');
		resultStatus.on('change', function(evt) {
			checkQualified();
		});

		getAllGrade();	
		getPartTimeListByDregree();
		getAllGradeResult();
		getAllAcademicByBranch();
		getAllTermStudy();
		getAllFeeByBranch();
		getStudntTestByBranch();
		//AllRefresh();
		checkQualified();
		
		getRefreshItems();
		getProgramTypeList();
		getProgramInfo();
	});
});


function checkQualified(){
	var statusRs = dijit.byId('resultStatus').get('value');
	if(statusRs==2){
		dijit.byId('degree_result').reset();
		dijit.byId('grade_result').reset();
		dijit.byId('score').attr("value",0);
		degree = dijit.byId('degree').get('value');
		dijit.byId('degree_result').set('readOnly',true);
		dijit.byId('degree_result').set('value',degree);
		
		dijit.byId('grade_result').set('readOnly',true);
		dijit.byId('score').set('readOnly',true);
	}else{
		degree = dijit.byId('degree').get('value');
		<?php if (!empty($this->detailscore['degree_result'])){?>
			degree ='<?php echo $this->detailscore['degree_result'];?>';
		<?php }?>
		dijit.byId('degree_result').set('readOnly',false);
		dijit.byId('degree_result').set('value',degree);
		
		grade = dijit.byId('grade').get('value');
		dijit.byId('grade_result').set('readOnly',false);
		dijit.byId('grade_result').set('value',grade);
		
		dijit.byId('score').set('readOnly',false);
	}
}

function getStudntTestByBranch(){
	getAllAcademicByBranch();
	getPartTimeListByDregree();
	getAllTermStudy();

};
function AllRefresh(){
	dijit.byId('term_test').attr("value","");
	getAllTermStudy();
	
}

function addNewTerm(){
	tern_test = dijit.byId('term_test').get('value');
	if(tern_test==-1){
		window.open('<?php echo Zend_Controller_Front::getInstance()->getBaseUrl()."/test/term/add?addterm=1";?>','_blank');
	}
}

url_getFeee = '<?php echo $this->url(array('module'=>'accounting','controller'=>'fee','action'=>'getfeeid'));?>';
	function getAllFeeByBranch(){
		dijit.byId('fee_id').reset();
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id=='' || branch_id==-1){
			var academic_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
			dijit.byId('fee_id').set('store',academic_store);  
			dijit.byId('branch_id').focus();
			return false;
		}
		academicYear = dijit.byId('academic_year').get('value');
		if(academicYear=='' || academicYear==-1){
			dijit.byId('academic_year').focus();
			return false;
		}
		schoolOption=dijit.byId('schoolOption').get('value');
		dojo.xhrPost({
			url: url_getFeee,
			content:{
				'academicYear':academicYear,
				'branch_id':branch_id,
				'school_option':schoolOption,
				'selectOption':1
				},
			handleAs:"json",
			load: function(data){
				academic_store  = getDataStorefromJSON('id','name', data);
				dijit.byId('fee_id').set('store',academic_store);  
				<?php if (!empty($this->detailscore['feeId'])){?>
					dijit.byId('fee_id').set('value',<?php echo $this->detailscore['feeId'];?>);
				<?php }?>
			},
			error: function(err) {
				alter(err);
			}
		});
	}

url_getacademic= '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'get-academicyear'));?>';
function getAllAcademicByBranch(){
	dijit.byId('academic_year').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var academic_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('academic_year').set('store',academic_store);  
		dijit.byId('branch_id').focus();
		return false;
	}
		school_option="<?php echo $this->type ?>";
		contentData = {
			'branch_id':branch_id,
			'school_option':school_option,
		}
		selectedId = '';
		
			<?php if (!empty($this->detailscore['academic_year'])){?>
				selectedId = '<?php echo $this->detailscore['academic_year'];?>';
			<?php }?>
		getAllYear(url_getacademic,contentData,selectedId);
}


url_term_study = '<?php echo $this->url(array('module'=>'test','controller'=>'index','action'=>'gettermstudy'));?>';
<?php $testCondiction = TEST_CONDICTION; 
if ($testCondiction==2){
?>
url_term_study = '<?php echo $this->url(array('module'=>'test','controller'=>'index','action'=>'gettermstudy'));?>';
<?php }?>
function getAllTermStudy(){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		return false;
	}
	dojo.xhrPost({
		url: url_term_study,
		content:{
			'branch_id':branch_id,
			'addNew':1,
			'option':0
		},
		handleAs:"json",
		load: function(data){
			term_store  = getDataStorefromJSON('id','name', data);
			dijit.byId('term_test').set('store',term_store); 
			<?php if (!empty($this->detailscore['study_term'])){?>
				dijit.byId('term_test').set('value',<?php echo $this->detailscore['study_term'];?>);
			<?php }?>
		},
		error: function(err) {
			alert(err);
		}
	});
}

var url_get_parttime = '<?php echo $this->url(array('module'=>'global','controller'=>'parttimelist','action'=>'get-parttime')); ?>';
function getPartTimeListByDregree(){
	degree = dijit.byId('degree').get('value');
	branchId = dijit.byId('branch_id').get('value');
	if(degree==''){
		return false;
	}
	dojo.xhrPost({
		url:url_get_parttime,
		content:{
			'degree':degree,
			'branchId':branchId,
			},
		handleAs:"json",
		load: function(data) {
			part_time_list_store  = getDataStorefromJSON('id','name', data);
			dijit.byId('part_time_list').set('store',part_time_list_store);  

			<?php if (!empty($this->detailscore['part_time_id'])){?>
				dijit.byId('part_time_list').set('value',<?php echo $this->detailscore['part_time_id'];?>);
			<?php }else if (!empty($this->rs['crm_partime_id'])){?>
				dijit.byId('part_time_list').set('value',<?php echo $this->rs['crm_partime_id'];?>);
			<?php }?>
		},
		error: function(err) {
		}
	});
}

var url_get_grade = '<?php echo $this->url(array('module'=>'global','controller'=>'grade','action'=>'get-grade')); ?>';
function getAllGrade(){
	dijit.byId('grade').set('value',''); 
	dept_id = dijit.byId('degree').get('value');
	if(dept_id==''){
		return false;
	}
	<?php if(!empty($this->detailscore['degree_result'])){?>
		dijit.byId('degree_result').set('value','<?php echo $this->detailscore['degree_result'] ?>');
	<?php }else{?>
		dijit.byId('degree_result').set('value',dept_id);
	<?php }?>
	dojo.xhrPost({
		url:url_get_grade,
		content:{
			'dept_id':dept_id,
			'noaddnew':1
			},
		handleAs:"json",
		load: function(data) {
			grade_store  = getDataStorefromJSON('id','name', data);
			dijit.byId('grade').set('store',grade_store);  
			<?php if (!empty($this->detailscore['grade'])){?>
				dijit.byId('grade').set('value',<?php echo $this->detailscore['grade'];?>);
			<?php }else if (!empty($this->rs['crm_grade'])){?>
				dijit.byId('grade').set('value',<?php echo $this->rs['crm_grade'];?>);
			<?php }?>
			getPartTimeListByDregree();
		},
		error: function(err) {
		}
	});
}
var url_get_grade = '<?php echo $this->url(array('module'=>'global','controller'=>'grade','action'=>'get-grade')); ?>';
function getAllGradeResult(){
	dijit.byId('grade_result').set('value',''); 
	dept_id = dijit.byId('degree_result').get('value');
	if(dept_id==''){
		return false;
	}
	dojo.xhrPost({
		url:url_get_grade,
		content:{
			'dept_id':dept_id,
			'noaddnew':1
			},
		handleAs:"json",
		load: function(data) {
			grade_result_store  = getDataStorefromJSON('id','name', data);
			dijit.byId('grade_result').set('store',grade_result_store);  
			<?php if (!empty($this->detailscore['grade_result'])){?>
				dijit.byId('grade_result').set('value',<?php echo $this->detailscore['grade_result'];?>);
			<?php }?>
			getPartTimeListByDregree();
		},
		error: function(err) {
		}
	});
}
function CalculateTotalScore(){
	var rowId = $('#identity').val();
	if(rowId==""){
		return false;
	}
	var totalscore=0;
	var rowIDArray = rowId.split(',');
	for(var n = 0; n < rowIDArray.length; n++) {
		if(isNaN(dijit.byId('score_'+rowIDArray[n]).get('value'))){
			totalscore+=0;
		}else{
			totalscore+= parseFloat(dijit.byId('score_'+rowIDArray[n]).get('value'));
		}
	}
	dijit.byId('score').set('value',totalscore); 
}

function getRefreshItems(){
	var url_getItems = '<?php echo $this->url(array("module"=>"global","controller"=>"degree","action"=>"refreshitems"));?>';										
	dojo.xhrPost({
		url: url_getItems,
		content:{
			'items_type': 1,
			},
		handleAs:"json",
		load: function(data) {
			degree_store  = getDataStorefromJSON('id','name', data);
			dijit.byId('degreeAddRow').set('store',degree_store);
		    HideloadingBlock();
		},
		error: function(err) {
			HideloadingBlock();
		}
	});
}
var grade_store_row  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
var url_dept = '<?php echo $this->url(array('module'=>'global','controller'=>'grade','action'=>'get-grade')); ?>';
function getSubGrade(){
	dept_id = dijit.byId('degreeAddRow').get('value');
	if(dept_id==''){return false;}
	dojo.xhrPost({
		url:url_dept,
		content:{
			'dept_id':dept_id,
			'noaddnew':1
			},
		handleAs:"json",
		load: function(data) {
			grade_store_row  = getDataStorefromJSON('id','name', data);
			dijit.byId('gradeAddRow').set('store',grade_store_row);   
		},
		error: function(err) {
		}
	});
}
function getProgramTypeList() {
	let urlGetProgramList = '<?php echo $this->url(array('module' => 'global', 'controller' => 'programtype', 'action' => 'get-program-list')); ?>';
	contentData = {
		'option':1,
	}
	dojo.xhrPost({
		url: urlGetProgramList,
		content:contentData,
		handleAs:"json",
		load: function(data){
			$('#programType').empty().trigger("change");
			$('#programType').append(data).trigger('change');

			<?php if (!empty($this->detailscore['programType'])){?>

				$("#programType").val(<?php echo $this->detailscore['programType'];?>).change();

			<?php }else if (!empty($this->rs['crm_program_type'])){?>

				$("#programType").val(<?php echo $this->rs['crm_program_type'];?>).change();

			<?php }?>
		},
		error: function(err) {
		}
	});
}

function getProgramInfo(){
	var programType = $('#programType').find(":selected").val();
	if(typeof programType !=="undefined" ){
		if( programType >0){
			var programTypeInfo = ($("#programType").find(':selected').data('record-info'));
			if(programTypeInfo !="undefined" ){
				var isSingleProgram = programTypeInfo.isSingleProgram;
				if(isSingleProgram==1){
					$("div.subClassInfo").addClass("d-none");
					$('#identity_study').val("");
					$('#table_row_study').html("");
				}else{
					$("div.subClassInfo").removeClass("d-none");
					initializeStudy();
				}
				//$('#isSingleProgram').val(programTypeInfo.isSingleProgram);
			}
		}
	}
}

var col_study = 0;
    var no_study = 0;
    var title_study = 0;
    tmp_study = '';
    temp_study='';
    function addRowStudy() {
    	var degreeAddRow = dijit.byId('degreeAddRow').get('value');
		degreelabel = dijit.byId("degreeAddRow").attr('displayedValue');
    	if(degreeAddRow==''){
    		dijit.byId('degreeAddRow').focus();
    		return false;
    	}
    	
    	var gradeAddRow = dijit.byId('gradeAddRow').get('value');
		gradelabel = dijit.byId("gradeAddRow").attr('displayedValue');
    	if(gradeAddRow==''){
    		gradeAddRow = "";
    		gradelabel="";
    	}
    
    	col_study++;
    	no_study++;
    	
    	template_study='';
    	if(title_study!=1){
    		temp_study+='<th><?php echo $tr->translate("DEL");?></th>';
    		temp_study+='<th><?php echo $tr->translate("N_O");?></th>';
    		temp_study+='<th ><?php echo $tr->translate("DEGREE");?></th>';
    		temp_study+='<th ><?php echo $tr->translate("GRADE");?></th>';
    		dojo.query("#head-title_study").append(temp_study);
    		title_study=1;
    	}
    		template_study+='<td width="4%"align="center"><img onclick="deleteRecord_study('+col_study+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
    		template_study+='<td width="4%" align="center">'+no_study+'</td>';
    		template_study+='<td>&nbsp;<input style="width:100%;" placeholder="<?php echo $tr->translate("DEGREE");?>" dojoType="dijit.form.TextBox" class="fullside" name="degree_'+col_study+'" id="degree_'+col_study+'" value="'+degreeAddRow+'" type="hidden">'+degreelabel+'&nbsp;</td>';
    		template_study+='<td>&nbsp;<input style="width:100%;" placeholder="<?php echo $tr->translate("GRADE");?>" dojoType="dijit.form.TextBox" class="fullside" name="grade_'+col_study+'" id="grade_'+col_study+'" value="'+gradeAddRow+'" type="hidden">'+gradelabel+'&nbsp;</td>';
    		
        tmp_study='<tr id="row_study'+col_study+'">';
    	tmp_study+="</tr>";
    	dojo.query("#table_row_study").append(tmp_study);

    	if($("#identity_study").val()!="") {
    		var identity_study = $("#identity_study").val();
    		$("#identity_study").val(identity_study+','+col_study);
    	} else {$("#identity_study").val(col_study);}
    	dojo.html.set(dojo.byId("row_study"+col_study),template_study , {
    	     parseContent: true,
    	});
    	dijit.byId('degreeAddRow').reset();
    	dijit.byId('gradeAddRow').reset();
    
    }
    function deleteRecord_study(index) {
    	var identity = $('#identity_study').val();
    	var arrays = identity.split(',');
    	for(var i=0;i<arrays.length;i++) {
    	if(arrays[i] == index) arrays.splice(i,1);
    	}
    	var strings = arrays.join(',');
    	$('#identity_study').val(strings);
    	dojo.query("#row_study"+index).remove();
    }
	function initializeStudy() {  
	
		<?php if(!empty($this->currentStudy)){ 
			foreach($this->currentStudy as $row){ 
		?>
		col_study++;
		no_study++;
		template_study='';
		if(title_study!=1){
			temp_study+='<th><?php echo $tr->translate("DEL");?></th>';
    		temp_study+='<th><?php echo $tr->translate("N_O");?></th>';
    		temp_study+='<th ><?php echo $tr->translate("DEGREE");?></th>';
    		temp_study+='<th ><?php echo $tr->translate("GRADE");?></th>';
			dojo.query("#head-title_study").append(temp_study);
			title_study=1;
		}

		template_study+='<td width="4%"align="center"><img onclick="deleteRecord_study('+col_study+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
		template_study+='<td width="4%" align="center">'+no_study+'</td>';
		template_study+='<td>&nbsp;<input style="width:100%;" placeholder="<?php echo $tr->translate("DEGREE");?>" dojoType="dijit.form.TextBox" class="fullside" name="degree_'+col_study+'" id="degree_'+col_study+'" value="<?php echo $row['degree'];?>" type="hidden"><?php echo $row['degreeTitle'];?>&nbsp;</td>';
		template_study+='<td>&nbsp;<input style="width:100%;" placeholder="<?php echo $tr->translate("GRADE");?>" dojoType="dijit.form.TextBox" class="fullside" name="grade_'+col_study+'" id="grade_'+col_study+'" value="<?php echo $row['grade'];?>" type="hidden"><?php echo $row['gradeTitle'];?> ';
		template_study+='<input dojoType="dijit.form.TextBox" type="hidden" id="detailid_study'+col_study+'" name="detailid_study'+col_study+'"  value="<?php echo $row['gd_id'];?>" /></td>';
		
		tmp_study='<tr id="row_study'+col_study+'">';
		tmp_study+="</tr>";
		dojo.query("#table_row_study").append(tmp_study);
			
		if($("#identity_study").val()!="") {
			var identity_study = $("#identity_study").val();
			$("#identity_study").val(identity_study+','+col_study);
		} else {$("#identity_study").val(col_study);}
		dojo.html.set(dojo.byId("row_study"+col_study),template_study , {
				parseContent: true,
		});
		<?php }}?>
	}
</script>