<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('Print Student Profile')); 
	echo $this->headTitle(''); 
	$db = new Test_Model_DbTable_DbStudentTest();
	$dateFormat ="d/m/Y";
?>
<style>
	button.btn-export,
	button.btn-search {
		display: none !important;
	}
</style>
<div class="layout-wrapper-report">
	<div id="mainContent" class="main-content-report">
		<div class="report-preview">
			<?php echo $this->controlReport?>
			<div id="main-viewer" class="main-viewer portrait">
				<div id="viewer" class="viewer portrait">
					<div id="divPrint" class="content">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style.css">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style-screen.css">
						<style>
							@media print {
								<?php if(!empty($this->printFormat)){ echo $this->printFormat; } ?>
							}
							.pagebreak {
								page-break-inside: avoid;
								page-break-after: always;
								width:100%;
							}
							table.data-value tbody tr td {
								line-height: 22px;
								padding: 1px 0;
								border-bottom: solid 1px #000;
							}
							table.data-value tbody tr td span.label-title {
								line-height: 22px;
								display: inline-block;
								min-width: 75px;
							}
							table.data-value tbody tr.head-title td
							 {
								text-align: center;
								font-weight: 600;
								border: solid 1px #000;
								border-top: none;
								border-left: none;
							}
							table.data-value tbody tr.row-value td{
								border: solid 1px #000;
								border-left: none;
							}
							table.data-value tbody tr td.borderbottom-none {
								 border-bottom: none;
							}
							table.data-value tbody tr td.borderright-none {
								 border-right: none;
							}
						</style>
						<div class="pagebreak">
							<table width="100%" border="0" style=" font-size:12px;font-family:Tahoma,'Khmer OS Battambang';"> 
								<tr>
									<td colspan="1"><?php echo $this->rsheader;?></td>
								</tr>
								<tr>
									<td>&nbsp;</td>
								</tr>
								<tr>
									<td>
									   <table width="100%" style="font-family: Times New Roman;">
											<tr>
												<td colspan="3" align="center" style="font-size: 20px;">ENTRY APPLICATION FORM</td>
											</tr>
											<tr>
												<td colspan="2"></td>
												<td align="center" style="font-size: 16px;" >Serial# : <span style="color:red;"><?php echo $this->row['serial']?></span></td>
											</tr>
									   </table>
								   </td>
								</tr>
								<style>
									.defaultheight{height: 21px;}
									.border{border:1px solid #000;border-left: none;border-right: none;}
									tr.line td{ border-bottom: 2px solid #000;padding-top: 5px; }
								</style>
								<tr>
									<td>
										<table width="100%" border="1"  style="font-size:12px; border-collapse:collapse;border: 1px solid #000;font-family: Times New Roman , Khmer OS Battambang; white-space: nowrap;">
											<tr style="height: 24px; background: #0077c5;">
												<td colspan="3" style="font-size: 13px;font-weight: bold;color: #fff;">&nbsp; Student Details</td>
											</tr>
											<tr>
												<td>&nbsp; Name (Khmer) : <?php echo $this->row['stu_khname']?></td>
												<td colspan="2">&nbsp; Student Id# : <?php echo $this->row['stu_code']?></td>
											</tr>
											<tr class="defaultheight">
												<td width="50%">&nbsp; Name (Latin) : <?php echo $this->row['stu_enname']." ".$this->row['last_name']?></td>
												<td width="36%">&nbsp; Sex : <?php echo $this->row['sex_title']?></td>
												<td width="14%" rowspan="6" style="border:2px solid #000;">
												<?php 
												$image = $this->baseUrl().'/images/no-profile.png';
												if (!empty($this->row['photo'])){
													if (file_exists(PUBLIC_PATH.'/images/photo/'.$this->row['photo'])){
														$image = $this->baseUrl().'/images/photo/'.$this->row['photo'];
													}
												}?>
												<img  src="<?php echo $image;?>" style="width: 100%;height: 135px;">
												</td>
											</tr>
											<tr class="defaultheight">
												<td>&nbsp; Date of Birth : <?php echo empty($this->row['dob'])?"":date("d-M-Y",strtotime($this->row['dob']));?></td>
												<td>&nbsp; Place of Birth : <?php echo $this->row['pob']?></td>
											</tr>
											<tr class="defaultheight">
												<td>&nbsp; Nationality : <?php echo $this->row['nationality']?></td>
												<td>&nbsp; Student Status : <?php echo $this->row['student_statustitle']?></td>
											</tr>
											<tr class="defaultheight">
												<td>&nbsp; Tel : <?php echo $this->row['tel']?></td>
												<td>&nbsp; E-mail : <?php echo $this->row['email']?></td>
											</tr>
											<tr class="defaultheight">
												<td>&nbsp; If employed, where? : <?php //echo $this->row['if_employed_where']?></td>
												<td>&nbsp; Position : <?php //echo $this->row['position']?></td>
											</tr>
											<tr class="defaultheight">
												<td>&nbsp; Parent's Name(if under 18) : <?php echo $this->row['guardian_khname']?></td>
												<td>&nbsp; Guardian Tel : <?php echo $this->row['guardian_tel']?></td>
											</tr>
											<tr class="defaultheight">
												<td colspan="3" style="font-size: 11px;">&nbsp; Home Address : 
												<?php 
													echo empty($this->row['home_num'])?"":$tr->translate("NUMBER_HOME")." ".$this->row['home_num'];
													echo empty($this->row['street_num'])?"":" ".$tr->translate("STREET")." ".$this->row['street_num'];
													echo empty($this->row['village_name'])?"":" ".$tr->translate("VILLAGE")." ".$this->row['village_name'];
													echo empty($this->row['commune_name'])?"":" ".$tr->translate("COMMUNE")." ".$this->row['commune_name'];
													echo empty($this->row['district_name'])?"":" ".$tr->translate("DISTRICT")." ".$this->row['district_name'];
													echo empty($this->row['province_id'])?"":" ".$this->row['province'];
												?></td>
											</tr>
										</table>
									</td>
								</tr>
								<tr>
									<td>
										<table width="100%" border="1"  style="margin-top:20px; font-size:12px; border-collapse:collapse;border: 1px solid #000;font-family: Times New Roman , Khmer OS Battambang; white-space: nowrap;">
											<tr style="height: 24px; background: #0077c5;">
												<td colspan="2" style="font-size: 13px;font-weight: bold;color: #fff;">&nbsp; Emergency Contact</td>
											</tr>
											<tr class="defaultheight">
												<td colspan="2">&nbsp; List any person whom you would like to be contacted in case of emergency.</td>
											</tr>
											<tr class="defaultheight">
												<td colspan="2">&nbsp; Name : <?php echo $this->row['emergency_name']?></td>
											</tr>
											<tr class="defaultheight">
												<td width="50%">&nbsp; Relationship to student : <?php echo $this->row['relationship_to_student']?></td>
												<td width="50%">&nbsp; Tel : <?php echo $this->row['emergency_tel']?></td>
											</tr>
										</table>
									</td>
								</tr>
								<tr>
									<td>
										<table width="100%" border="1"  style="margin-top:20px; font-size:12px; border-collapse:collapse;border: 1px solid #000;font-family: Times New Roman , Khmer OS Battambang; white-space: nowrap;">
											<tr style="height: 24px; background: #0077c5;">
												<td colspan="2" style="font-size: 13px;font-weight: bold;color: #fff;">&nbsp; Educational Background ( School Name , Grade/Level/Year , Major , Year )</td>
											</tr>
											<tr class="defaultheight">
											 <td colspan="2" style="padding: 5px;">
												<table width="100%" border="1"  style="font-size:12px; border-collapse:collapse;border: 1px solid #000;font-family: Times New Roman , Khmer OS Battambang; white-space: nowrap;">
													<tr style="height: 24px;" class="defaultheight">
														<td style="font-size: 13px; " width="4%">&nbsp; <?php echo $tr->translate("N_O");?></td>
														<td style="font-size: 13px; ">&nbsp; <?php echo $tr->translate("SCHOOL_AND_NAME");?></td>
														<td style="font-size: 13px; ">&nbsp; <?php echo $tr->translate("GRADE_LAVEL");?></td>
														<td style="font-size: 13px; ">&nbsp; <?php echo $tr->translate("YEAR");?></td>
														<td style="font-size: 13px; ">&nbsp;<?php echo $tr->translate("GRADE");?></td>
														<td style="font-size: 13px; ">&nbsp;<?php echo $tr->translate("NOTE");?></td>
													</tr>
													<?php if(!empty($this->row_detail)) foreach($this->row_detail As $key=>$rs){?>
													<tr class="defaultheight">
														<td style="font-size: 13px; ">&nbsp;<?php echo  $key+1;?> </td>
														<td style="font-size: 13px; ">&nbsp;<?php echo $rs['school_name']?> </td>
														<td style="font-size: 13px; ">&nbsp;<?php echo $rs['level']?>  </td>
														<td style="font-size: 13px; ">&nbsp;<?php echo $rs['year']?> </td>
														<td style="font-size: 13px; ">&nbsp;<?php echo $rs['major']?>  </td>
														<td style="font-size: 13px; ">&nbsp;<?php echo $rs['note']?>  </td>
													</tr>
													<?php }?>
												</table>
											 </td>
											</tr>
										</table>
									</td>
								</tr>
								<tr>
									<td>
										<table width="100%" border="0"  style="margin-top:20px; font-size:12px; border-collapse:collapse;border: 1px solid #000;font-family: Times New Roman , Khmer OS Battambang; white-space: nowrap;">
											<tr style="height: 24px; background: #0077c5;border: 1px solid #000;">
												<td colspan="4" style="font-size: 13px;font-weight: bold;color: #fff;">&nbsp; Declaration</td>
											</tr>
											<tr class="defaultheight">
												<td colspan="4" style="padding: 5px;line-height: 22px;">
													&nbsp; * To the best of my knowledge, the information I have given is true and accurate.<br />
													&nbsp; ខ្ញុំសូមសន្យាថាព័ត៌មានខាងលើនេះពិតជាត្រឹមត្រូវពិតប្រាកដមែន។<br />
													&nbsp; * By signing this application, I agree to abide by the policies and regulations of <span style="font-weight:bold;">&nbsp;<?php echo $tr->translate("CUSTOMER_BRANCH");?></span>.<br />
													&nbsp; ខ្ញុំយល់ព្រមគោរពតាមបទបញ្ជាផ្ទៃក្នុងរបស់ <span style="font-weight:bold;">&nbsp;<?php echo $tr->translate("CUSTOMER_BRANCH");?></span> ។<br />
												</td>
											</tr>
											<tr class="defaultheight">
												<td width="8%" style="padding: 5px;line-height: 22px;">
													Signature : 
												</td>
												<td width="42%">
													<u>
														&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
														&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
														&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
														&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
														&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
													</u>
												</td>
												<td width="8%" align="center" style="padding: 5px;line-height: 22px;">
													Date : 
												</td>
												<td width="42%">
													<u>
														&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
														&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
														&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
														&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
														&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
													</u>
												</td>
											</tr>
											<tr class="defaultheight">
												<td colspan="4" style="padding: 5px;line-height: 22px;font-size: 10px;">
													*** Please advise the school of any changes in the information contained on this form.
												</td>
											</tr>
										</table>
									</td>
								</tr>
							</table>
						</div>
						<div class="pagebreak">
							<table width="100%" border="0" style=" font-size:12px;font-family:Tahoma,'Khmer OS Battambang';margin-top:20px;"> 
								<tr>
									<td colspan="1"><?php echo $this->rsheader;?></td>
								</tr>
								<tr>
									<td>&nbsp;</td>
								</tr>
								<tr>
									<td>
									   <table width="100%" style="font-family: Times New Roman,'Khmer OS Muol Light';">
											<tr>
												<td colspan="3" align="center" style="font-size: 16px;"><?php echo $tr->translate("TEST_HISTORY");?></td>
											</tr>
									   </table>
								   </td>
								</tr>
								<?php if (!empty($this->testresultkh)) {?>
								<tr>
									<td>
										<table width="100%" border="1"  style="margin-top:20px; font-size:12px; border-collapse:collapse;border: 1px solid #000;font-family: Times New Roman , Khmer OS Battambang; white-space: nowrap;">
											<tr style="height: 24px; background: #0077c5;">
												<td colspan="2" style="font-size: 13px;font-weight: bold;color: #fff;">&nbsp;<?php echo $tr->translate("KHMER_KNOWLEDGE");?></td>
											</tr>
											<tr >
												 <td >
													<table class="data-value" width="100%" style="font-size:12px; border-collapse:collapse; font-family: Times New Roman , Khmer OS Battambang; white-space: nowrap;">
														<tr class="head-title" >
															<td rowspan="2"><?php echo $tr->translate("NUM");?></td>
															<td colspan="3"><?php echo $tr->translate("REQUEST_FOR");?></td>
															<td colspan="5"><?php echo $tr->translate("RESULT");?></td>
															<td class=" " rowspan="2"><?php echo $tr->translate("NOTE");?></td>
															<td class="borderright-none " rowspan="2"><?php echo $tr->translate("RESULT_BY");?></td>
														</tr>
														<tr class="head-title">
															<td><?php echo $tr->translate("TEST_DATE");?></td>
															<td ><?php echo $tr->translate("DEGREE");?></td>
															<td ><?php echo $tr->translate("GRADE");?></td>
															<td><?php echo $tr->translate("RESULT_DATE");?></td>
															<td ><?php echo $tr->translate("DEGREE");?></td>
															<td ><?php echo $tr->translate("GRADE");?></td>
															<td>&nbsp;<?php echo $tr->translate("SCORE");?>&nbsp;</td>
															<td><?php echo $tr->translate("COMMENTS");?></td>
														</tr>
														<?php $counts=count($this->testresultkh); foreach($this->testresultkh As $key=>$record){?>
														<tr class="row-value">
															<td align="center"  >&nbsp;<?php if ($record['is_current']==1){?><i class="fa fa-check" aria-hidden="true"></i><?php }?> <?php echo $key+1;?>&nbsp;</td>
															<td align="center" >&nbsp;<?php echo date("d/M/Y",strtotime($record['test_date']))?>&nbsp;</td>
															<td align="left" >&nbsp;<?php echo $record['degree_title'];?>&nbsp;</td>
															<td align="center" >&nbsp;<?php echo $record['grade_title'];?>&nbsp;</td>
															<td align="center" >&nbsp;<?php echo empty($record['result_date'])?"":date("d/M/Y",strtotime($record['result_date']));?>&nbsp;</td>
															<td align="center" >&nbsp;<?php echo $record['degree_result_title'];?>&nbsp;</td>
															<td align="center" >&nbsp;<?php echo $record['grade_result_title'];?>&nbsp;</td>
															<td align="center" >&nbsp;<?php echo $record['score'];?>&nbsp;</td>
															<td align="center" >&nbsp;<?php echo $record['comment_title'];?>&nbsp;</td>
															<td align="center" class="">&nbsp;<?php echo $record['note'];?>&nbsp;</td>
															<td align="center" class="borderright-none ">&nbsp;<?php echo $record['result_by'];?>&nbsp;</td>
														</tr>
														<?php $subject = $db->getSubjectScoreByTest($record['id']);
															if (!empty($subject)) foreach ($subject as $ss){
																$title=$ss["subject"];
														?>
														<tr class="row-value">
															<td colspan="4" class="borderbottom-none" style="border-top: none;">&nbsp;</td>
															<td align="left" colspan="3" class="<?php if ($counts==$key+1){ echo "borderbottom-none";}?>">&nbsp;<?php echo $title;?></td>
															<td align="center"  class="<?php if ($counts==$key+1){ echo "borderbottom-none";}?>">&nbsp;<?php echo $ss['score']?>&nbsp;</td>
															<td align="center"  class=" <?php if ($counts==$key+1){ echo "borderbottom-none";}?>"><?php echo $ss['comment_title'];?></td>
															<td align="center"  class=" <?php if ($counts==$key+1){ echo "borderbottom-none";}?>"><?php echo $ss['note'];?></td>
														</tr>
														<?php }?>
														<?php }?>
													</table>
												 </td>
											</tr>
										</table>
									</td>
								</tr>
								<?php }?>
								<?php if (!empty($this->testresulteng)) {?>
								<tr>
									<td>
										<table width="100%" border="1"  style="margin-top:20px; font-size:12px; border-collapse:collapse;border: 1px solid #000;font-family: Times New Roman , Khmer OS Battambang; white-space: nowrap;">
											<tr style="height: 24px; background: #0077c5;">
												<td colspan="2" style="font-size: 13px;font-weight: bold;color: #fff;">&nbsp;<?php echo $tr->translate("ENGLISH");?></td>
											</tr>
											<tr >
												 <td >
													<table class="data-value" width="100%" style="font-size:12px; border-collapse:collapse; font-family: Times New Roman , Khmer OS Battambang; white-space: nowrap;">
														<tr class="head-title" >
															<td rowspan="2"><?php echo $tr->translate("NUM");?></td>
															<td colspan="3"><?php echo $tr->translate("REQUEST_FOR");?></td>
															<td colspan="5"><?php echo $tr->translate("RESULT");?></td>
															<td class=" " rowspan="2"><?php echo $tr->translate("NOTE");?></td>
															<td class="borderright-none " rowspan="2"><?php echo $tr->translate("RESULT_BY");?></td>
														</tr>
														<tr class="head-title">
															<td><?php echo $tr->translate("TEST_DATE");?></td>
															<td ><?php echo $tr->translate("DEGREE");?></td>
															<td ><?php echo $tr->translate("GRADE");?></td>
															<td><?php echo $tr->translate("RESULT_DATE");?></td>
															<td ><?php echo $tr->translate("DEGREE");?></td>
															<td ><?php echo $tr->translate("GRADE");?></td>
															<td>&nbsp;<?php echo $tr->translate("SCORE");?>&nbsp;</td>
															<td><?php echo $tr->translate("COMMENTS");?></td>
														</tr>
														<?php $counts=count($this->testresulteng); foreach($this->testresulteng As $key=>$record){?>
														<tr class="row-value">
															<td align="center" class="<?php if ($counts==$key+1){ echo "borderbottom-none";}?>" >&nbsp;<?php if ($record['is_current']==1){?><i class="fa fa-check" aria-hidden="true"></i><?php }?> <?php echo $key+1;?>&nbsp;</td>
															<td align="center" class="<?php if ($counts==$key+1){ echo "borderbottom-none";}?>">&nbsp;<?php echo date("d/M/Y",strtotime($record['test_date']))?>&nbsp;</td>
															<td align="left" class="<?php if($counts==$key+1){ echo "borderbottom-none";}?>">&nbsp;<?php echo $record['degree_title'];?>&nbsp;</td>
															<td align="center" class="<?php if ($counts==$key+1){ echo "borderbottom-none";}?>">&nbsp;<?php echo $record['grade_title'];?>&nbsp;</td>
															<td align="center" class="<?php if ($counts==$key+1){ echo "borderbottom-none";}?>">&nbsp;<?php echo empty($record['result_date'])?"":date("d/M/Y",strtotime($record['result_date']));?>&nbsp;</td>
															<td align="center" class="<?php if ($counts==$key+1){ echo "borderbottom-none";}?>">&nbsp;<?php echo $record['degree_result_title']; echo empty($record['partTimeTitle']) ? "" : "<br />".$record['partTimeTitle']; ?>&nbsp;</td>
															<td align="center" class="<?php if ($counts==$key+1){ echo "borderbottom-none";}?>">&nbsp;<?php echo $record['grade_result_title'];?>&nbsp;</td>
															<td align="center" class="<?php if ($counts==$key+1){ echo "borderbottom-none";}?>">&nbsp;<?php echo $record['score'];?>&nbsp;</td>
															<td align="center" class="<?php if ($counts==$key+1){ echo "borderbottom-none";}?>">&nbsp;<?php echo $record['comment_title'];?>&nbsp;</td>
															<td align="center" class=" <?php if ($counts==$key+1){ echo "borderbottom-none";}?>">&nbsp;<?php echo $record['note'];?>&nbsp;</td>
															<td align="center" class="<?php if ($counts==$key+1){ echo "borderbottom-none";}?> borderright-none ">&nbsp;<?php echo $record['result_by'];?>&nbsp;</td>
														</tr>
														<?php }?>
													</table>
												 </td>
											</tr>
										</table>
									</td>
								</tr>
								<?php }?>
								<?php if (!empty($this->testresultuniver)) {?>
								<tr>
									<td>
										<table width="100%" border="1"  style="margin-top:20px; font-size:12px; border-collapse:collapse;border: 1px solid #000;font-family: Times New Roman , Khmer OS Battambang; white-space: nowrap;">
											<tr style="height: 24px; background: #0077c5;">
												<td colspan="2" style="font-size: 13px;font-weight: bold;color: #fff;">&nbsp;<?php echo $tr->translate("UNIVERSITY");?></td>
											</tr>
											<tr >
												 <td >
													<table class="data-value" width="100%" style="font-size:12px; border-collapse:collapse; font-family: Times New Roman , Khmer OS Battambang; white-space: nowrap;">
														<tr class="head-title" >
															<td rowspan="2"><?php echo $tr->translate("NUM");?></td>
															<td colspan="3"><?php echo $tr->translate("REQUEST_FOR");?></td>
															<td colspan="5"><?php echo $tr->translate("RESULT");?></td>
															<td class=" " rowspan="2"><?php echo $tr->translate("NOTE");?></td>
															<td class="borderright-none " rowspan="2"><?php echo $tr->translate("RESULT_BY");?></td>
														</tr>
														<tr class="head-title">
															<td><?php echo $tr->translate("TEST_DATE");?></td>
															<td ><?php echo $tr->translate("DEGREE");?></td>
															<td ><?php echo $tr->translate("GRADE");?></td>
															<td><?php echo $tr->translate("RESULT_DATE");?></td>
															<td ><?php echo $tr->translate("DEGREE");?></td>
															<td ><?php echo $tr->translate("GRADE");?></td>
															<td>&nbsp;<?php echo $tr->translate("SCORE");?>&nbsp;</td>
															<td><?php echo $tr->translate("COMMENTS");?></td>
														</tr>
														<?php $counts=count($this->testresultuniver); foreach($this->testresultuniver As $key=>$record){?>
														<tr class="row-value">
															<td align="center" class="<?php if ($counts==$key+1){ echo "borderbottom-none";}?>" >&nbsp;<?php if ($record['is_current']==1){?><i class="fa fa-check" aria-hidden="true"></i><?php }?> <?php echo $key+1;?>&nbsp;</td>
															<td align="center" class="<?php if ($counts==$key+1){ echo "borderbottom-none";}?>">&nbsp;<?php echo date("d/M/Y",strtotime($record['test_date']))?>&nbsp;</td>
															<td align="left" class="<?php if ($counts==$key+1){ echo "borderbottom-none";}?>">&nbsp;<?php echo $record['degree_title'];?>&nbsp;</td>
															<td align="center" class="<?php if ($counts==$key+1){ echo "borderbottom-none";}?>">&nbsp;<?php echo $record['grade_title'];?>&nbsp;</td>
															<td align="center" class="<?php if ($counts==$key+1){ echo "borderbottom-none";}?>">&nbsp;<?php echo empty($record['result_date'])?"":date("d/M/Y",strtotime($record['result_date']));?>&nbsp;</td>
															<td align="center" class="<?php if ($counts==$key+1){ echo "borderbottom-none";}?>">&nbsp;<?php echo $record['degree_result_title'];?>&nbsp;</td>
															<td align="center" class="<?php if ($counts==$key+1){ echo "borderbottom-none";}?>">&nbsp;<?php echo $record['grade_result_title'];?>&nbsp;</td>
															<td align="center" class="<?php if ($counts==$key+1){ echo "borderbottom-none";}?>">&nbsp;<?php echo $record['score'];?>&nbsp;</td>
															<td align="center" class="<?php if ($counts==$key+1){ echo "borderbottom-none";}?>">&nbsp;<?php echo $record['comment_title'];?>&nbsp;</td>
															<td align="center" class=" <?php if ($counts==$key+1){ echo "borderbottom-none";}?>">&nbsp;<?php echo $record['note'];?>&nbsp;</td>
															<td align="center" class="<?php if ($counts==$key+1){ echo "borderbottom-none";}?> borderright-none ">&nbsp;<?php echo $record['result_by'];?>&nbsp;</td>
														</tr>
														<?php }?>
													</table>
												 </td>
											</tr>
										</table>
									</td>
								</tr>
								<?php }?>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
						
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script src="<?php echo $this->baseUrl();?>/admin/js/report.js"  type="text/javascript"></script>
<script type="text/javascript">
document.addEventListener("DOMContentLoaded", function(e) {
	setTimeout(function() {
		setPrintOrientation('portrait');
	}, 500);
});	
function doPrint(contentId = "divPrint") {
	
	var currentTitle = $(document).attr('title');
	var w = 1000;
	var h = 600;
	var left = Number((screen.width/2)-(w/2));
	var tops = Number((screen.height/2)-(h/2));

	var winPrint = window.open(' ', '', 'toolbar=0,scrollbars=0,status=0,width='+w+', height='+h+', top='+tops+', left='+left);
	winPrint.document.write('<title>'+currentTitle+'</title>'+dojo.byId(contentId).innerHTML);
	winPrint.document.close();

	setTimeout(function () {
		winPrint.focus();
		winPrint.print();
		winPrint.close();
		
	}, 800);
	
}
</script>