<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("ADD_SCAN_SETTING"));
	$baseurl = $this->baseUrl();
	$frm_items= $this->frm_items;
//	print_r($this->rs);

	$session = '';
	if (!empty($this->rs['sessionList'])) {
		$session =  explode(",", $this->rs['sessionList']);
	}
	$array = array();
	if (!empty($session)) {
		foreach ($session as $ss) {
			$array[$ss] = $ss;
		}
	}

?>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
       		<div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
	    			<h4 class="m-b-0"><i class="glyphicon glyphicon-hourglass" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT_SCAN_SETTING');?> <small id="msg_deplicate" class="red italic"></small></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
    	<form  id='edit-major' action="" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
			<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
					branch_id=dijit.byId("branch_id").get("value");
					if(branch_id==-1 || branch_id==""){
						alert("<?php echo $tr->translate("PLEASE_SELECT_BRANCH");?>!!!");
						dijit.byId("branch_id").focus();
						return false;
					}
					loadingBlock();
					return true;
				}else {
					return false;
				}
			</script>
			<div class="card-box">
				<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-hourglass" aria-hidden="true"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("SCORE_ENTRY_SETTING");?></p>
										</div> 
									</div>
									<div class="form-group">
									   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("BRANCH");?> <span class="required">*</span>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm_items->getElement("branch_id");?>
											<?php echo $frm_items->getElement("id");?>
									   </div>
									</div>
									<div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12">
										<?php echo $tr->translate("SHIFT_TIME");?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm_items->getElement("shift");?>
										</div>
									 </div>
									<div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("TITLE");?> <span class="required">*</span></label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm_items->getElement("title");?>
										</div>
									 </div>
									 <div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("TITLE_EN");?> <span class="required">*</span></label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm_items->getElement("titleEn");?>
										</div>
									 </div>
									 <div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("TYPE");?> <span class="required">*</span></label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm_items->getElement("type");?>
										</div>
									 </div>
									 <div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12">
											<?php echo $tr->translate("FROM_TIME");?> <span class="required">*</span>
										</label>
										<div class="col-md-3 col-sm-3 col-xs-12">
											<?php echo $frm_items->getElement("fromTime");?>
										</div>
										<label class="control-label text-center col-md-1 col-sm-1 col-xs-12">
											<?php echo $tr->translate("TO");?>
										</label>
										<div class="col-md-3 col-sm-3 col-xs-12">
											<?php echo $frm_items->getElement("toTime");?>
										</div>
									 </div>
									 <div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("condictionTime");?> <span class="required">*</span></label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm_items->getElement("condictionTime");?>
										</div>
									 </div>
									 <div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("STATUS");?></label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm_items->getElement("status");?>
										</div>
									 </div>
									
								</div>
							</div>
						</div>
					</div>
		         </div>
				 <div id="partimtelist" class="col-md-4 col-sm-4 col-xs-12">
					<div class="card-blogform">
						<div class="card-body">
							<div class="row">
								<div class="col-md-12 col-sm-12 col-xs-12">
									<div class="d-flex">
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-indent-left" aria-hidden="true"></i>
										</div>
										<div class="col-md-10 col-sm-10 col-xs-12">
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("PART_TIME_LIST"); ?></p>
										</div>
									</div>
									<br />
									<div class="custom-control custom-checkbox ">
										<input type="checkbox" class="checkbox custom-control-input" onchange="checkall();" class="checkbox" id="check_all" name="check_all">
										<label class="custom-control-label" for="check_all">
											<?php echo $tr->translate('CHECK_ALL'); ?>
										</label>
									</div>
									<div class="form-group">
										<ul class="optListRow">
											<?php
											if (!empty($this->faculty)) foreach ($this->faculty as $rs) {
											?>
												<li class="opt-items">
													<div class="custom-control custom-checkbox">
														<input <?php if (in_array($rs['id'], $array)) {
																	echo "checked";
																} ?> type="checkbox" class="checkbox custom-control-input" id="session<?php echo $rs['id']; ?>" value="<?php echo $rs['id']; ?>" name="selector[]">
														<label class="custom-control-label" for="session<?php echo $rs['id']; ?>">
															<?php echo $rs['name']; ?>
														</label>
													</div>
												</li>

											<?php } ?>
										</ul>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
		        <div class="clearfix"></div>
			         <div class="card-box mt-20">
		               	<div class="col-md-6 col-sm-6 col-xs-12 border-top mt-20 ptb-10 text-center">
							<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-remove"  value="save_close" name="save_close" id="save_close" label="<?php echo $tr->translate('SAVE_CLOSE');?>" dojoType="dijit.form.Button" />
							<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" value="save_new" name="save_new" id="save_new" label="<?php echo $tr->translate('SAVE_NEW');?>" dojoType="dijit.form.Button"  />
		           		 </div>
		       		 </div>
				</div>
		</form>
    </div>
</div>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script type="text/javascript">
    dojo.require("dojo.NodeList-manipulate");
    dojo.require("dijit.form.Textarea");
    dojo.require('dijit.form.NumberTextBox');
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.TimeTextBox");

	function checkall(){
		if ($('#check_all').is(':checked')) {
			$(".checkbox").prop('checked', true);
		}else{
			$(".checkbox").prop('checked', false);
		}
	}
</script>