<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("សលាកបត្រព័ត៌មាន"));
	
	$frm =  $this->form_search;
	$db = new Allreport_Model_DbTable_DbRptAllStudent();
	
	$start_date = $this->datasearch['start_date'];
	$end_date = $this->datasearch['end_date'];
	$date1 = date("d-m-Y",strtotime($start_date));
	$date2 = date('d-m-Y',strtotime($end_date));
	$diff = abs(strtotime($date2) - strtotime($date1));
	$years = floor($diff / (365*60*60*24));
	$months = floor(($diff - $years * 365*60*60*24) / (30*60*60*24));
	$days = floor(($diff - $years * 365*60*60*24 - $months*30*60*60*24)/ (60*60*24));
	$amount_day =$diff/ (60*60*24);
	$amount_day = $amount_day + 1;
	
	$month = array("01"=>"មករា","02"=>"កុម្ភៈ","03"=>"មីនា","04"=>"មេសា","05"=>"ឧសភា","06"=>"មិថុនា","07"=>"កក្កដា","08"=>"សីហា","09"=>"កញ្ញា","10"=>"តុលា","11"=>"វិច្ឆិកា","12"=>"ធ្នូ");
	$number = array(0=>"០",1=>"១",2=>"២",3=>"៣",4=>"៤",5=>"៥",6=>"៦",7=>"៧",8=>"៨",9=>"៩","."=>".",","=>",","-"=>"-","+"=>"+","$"=>"$");
	$db_mistack = new Allreport_Model_DbTable_DbMistakeCertificate();
	$stu_id = $this->stu_id;
	$group_id = $this->group_id;
	
	$image = $this->baseUrl().'/images/no-profile.png';
	if(!empty($this->student_info['photo'])){
		if (file_exists(PUBLIC_PATH."/images/photo/".$this->student_info['photo'])){
			$image = $this->baseUrl().'/images/photo/'.$this->student_info['photo'];
		}
		
	}
	$dateFormat ="d/m/Y";
?>
<style>
	button.btn-search {
		display: none !important;
	}
</style>
<div class="layout-wrapper-report">
	<div id="mainContent" class="main-content-report">
		<div class="report-preview">
			<?php echo $this->controlReport?>
			<div id="main-viewer" class="main-viewer portrait">
				<div id="viewer" class="viewer portrait">
					<div id="divPrint" class="content">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style.css">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style-screen.css">
						<style>
							@media print {
								<?php if(!empty($this->printFormat)){ echo $this->printFormat; } ?>
							}
							col:nth-child(1){ width:100px;box-sizing: border-box;}
							col:nth-child(2),
							col:nth-child(3),
							col:nth-child(4),
							col:nth-child(5),
							col:nth-child(6)
							,col:nth-child(7),col:nth-child(9)
							 { 
								width:55px;
								text-align: center;
								box-sizing: border-box;
							}
							col:nth-child(8) { width:280px;}
							.fontkh-bold{font-family: Khmer OS Muol Light;}
							.font-14{font-size:14px !important;}
						</style>
						<table border="0" style="background:#fff; margin: 0 auto; width: 100%; ">
							<tr>
								<td >
									<table class="content-data text-color-black text-h16px text-size-12px" width="100%" border="0" style="padding:15px;">
										<tr>
											<td colspan="3"><?php echo $this->rsheader;?></td>
										</tr>
										<tr>
											<td align="center" colspan="3" >
												<div class="fontkh-bold text-h20px text-size-14px">សលាកបត្រព័ត៌មាន<br />
												 <span>ឆ្នាំសិក្សា <?php 
													$academic_year='';
													$sp_academic_year = str_split($this->student_info['academic_year']);
													foreach ($sp_academic_year as $cos){
														$academic_year.= empty($number[$cos])?$cos:$number[$cos];
													}
													echo $academic_year;
												?><span>
												</div>
											</td>
										</tr>
										<?php 
											$dob_year='';
											$sp_dob_year = str_split(date("Y",strtotime($this->student_info['dob'])));
											foreach ($sp_dob_year as $cos){
												$dob_year.=$number[$cos];
											}
											$dob_m='';
											$sp_dob_m = str_split(date("m",strtotime($this->student_info['dob'])));
											foreach ($sp_dob_m as $cos){
												$dob_m.=$number[$cos];
											}
											$dob_d='';
											$sp_dob_d = str_split(date("d",strtotime($this->student_info['dob'])));
											foreach ($sp_dob_d as $cos){
												$dob_d.=$number[$cos];
											}
										?>
										<tr>
											<td colspan="3" align="left">
												<table class="content-data text-color-black text-h16px text-size-12px"  cellpadding="5" style="margin:0 auto;border:0px solid #000;white-space: nowrap;"  border="0" >
													<tr>
														<td>
															<div style="width: 70%;display: inline-block;">
																ឈ្មោះ &nbsp; <?php echo $this->student_info['stu_khname']?> &nbsp; ជាអក្សរឡាតាំង &nbsp;<?php echo $this->student_info['last_name']." ".$this->student_info['stu_enname']?> &nbsp;ភេទ &nbsp;<?php echo $this->student_info['sex']?> &nbsp;ថ្ងៃខែឆ្នាំកំណើត &nbsp;<?php echo $dob_d."/".$dob_m."/".$dob_year;?> <br />
																ទីកន្លែងកំណើត &nbsp;<?php echo $this->student_info['pob']?><br />
																ថ្នាក់ទី &nbsp;<?php echo $this->student_info['grade']?> &nbsp;ឆ្នាំសិក្សា &nbsp;<?php echo $academic_year;?>
																<span style=" display: block;  white-space: normal;">
																អាសយដ្ឋានបច្ចុប្បន្នផ្ទះលេខ &nbsp;<?php echo $this->student_info['home_num']?> ផ្លូវ <?php echo $this->student_info['street_num']?> សង្កាត់ <?php echo $this->student_info['commune_name']?> ខណ្ឌ <?php echo $this->student_info['district_name']?> រាជធានី <?php echo $this->student_info['province_name']?>
																</span>
																ឈ្មោះឪពុក &nbsp; <?php echo $this->student_info['father_khname']?> &nbsp; មុខរបរ &nbsp; <?php echo $this->student_info['fa_job']?> &nbsp; លេខទូរសព្ទ&nbsp; <?php echo $this->student_info['father_phone']?><br />
																ឈ្មោះម្តាយ &nbsp; <?php echo $this->student_info['mother_khname']?> &nbsp; មុខរបរ &nbsp; <?php echo $this->student_info['mo_job']?> &nbsp; លេខទូរសព្ទ&nbsp; <?php echo $this->student_info['mother_phone']?><br />
																លេខទូរសព្ទផ្ទះ.......................................................................................................<br />
																ប្រវត្តិសុខភាព ........................................................................................................
															</div>
															<div style="width: 28%;display: inline-block;vertical-align: bottom;">
																<div style="border:1px solid #000;height: 130px;width:100px;margin: 0 auto;margin-bottom: 10px;">
																<img style=" width: 100%;   height: 100%;" id="profile_wiew" src="<?php echo $image;?>" alt=""  />
																</div>
															</div>
														</td>
													</tr>
												</table>	
											</td>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td>
									<table class="content-data text-color-black text-h16px text-size-12px" width="100%" border="1" style="border-collapse:collapse; border:1px solid #000; font-family: Khmer OS Battambang; ">
										<colgroup>
											<col>
											<col>
											<col>
											<col>
											<col>
											<col>
											<col>
											<col>
											<col>
										</colgroup>
										<tr>
											<td rowspan="2" align="center" style="font-family: Khmer OS Muol Light;">
												កាលបរិច្ឆេទ
											</td>
											<td colspan="4" align="center" style="font-family: Khmer OS Muol Light;">
												កំហុស
											</td>
											<td colspan="2" align="center" style="font-family: Khmer OS Muol Light;">
												អវត្តមាន
											</td>
											<td rowspan="2" align="center" style="font-family: Khmer OS Muol Light;">
												របាយបញ្ហា
											</td>
											<td rowspan="2" align="center" style="font-family: Khmer OS Muol Light;">
												ផ្សេងៗ
											</td>
										</tr>
										<tr>
											<td align="center">ស្រាល</td>
											<td align="center">មធ្យម</td>
											<td align="center">ធ្ងន់</td>
											<td align="center">ផ្សេងៗ</td>
											<td align="center">ច្បាប់</td>
											<td align="center">ឥតច្បាប់</td>
										</tr>
										<tr>
											<td class="text-bold text-h18px" colspan="9">&nbsp;ឆមាសទី១</td>
										</tr>
										<?php 
											$i=0;
											$s=0;$m=0;$l=0;
											$o=0;
											$at=0;
											$p=0;
											$totalSmall=0;
											$totalMedium=0;
											$totalBig=0;
											$totalOther=0;
											$totalA=0;
											$totalP=0;
											//$attendences = $db_mistack->getAttendenceBydate(1, $group_id, $stu_id);
											$arr = [
												'academic_year' => $this->student_info['academicYearId'],
												'stu_id' => $stu_id,
											];
											$attendences = $db_mistack->getAttendenceBydateNew(1, $arr);
										?>	
										<?php 
											if (!empty($attendences)){
												foreach ($attendences as $attendence){
													
													$groupCode ="";
													if($attendence['group_id']!=$group_id){
														$groupCode =$attendence['groupCode']." ";
													}
									
												$attendence_year='';
												$sp_attendence_year = str_split(date("Y",strtotime($attendence['date_attendence'])));
												foreach ($sp_attendence_year as $cos){
													$attendence_year.=$number[$cos];
												}
												$att_m='';
												$sp_att_m = str_split(date("m",strtotime($attendence['date_attendence'])));
												foreach ($sp_att_m as $cos){
													$att_m.=$number[$cos];
												}
												$att_d='';
												$sp_att_d = str_split(date("d",strtotime($attendence['date_attendence'])));
												foreach ($sp_att_d as $cos){
													$att_d.=$number[$cos];
												}
												$permission = "";
												$absent = "";
												$small = "";
												$medium = "";
												$big = "";
												$other = "";
												$descri_added="";
												if ($attendence['type']==1){ // attendence
													if($attendence['attendence_status']==3){
														$permission = $number['1'];$p++;
													}
													if($attendence['attendence_status']==2){
														$absent = $number['1'];$at++;
													}
													if($attendence['attendence_status']==4){
														$small = $number['1'];$s++;
														if ($attendence['for_session']==1){
															$descri_added = "(មកយឺត ពេលព្រឹក)";
														}else if ($attendence['for_session']==2){
															$descri_added = "(មកយឺត ពេលល្ងាច)";
														}
													}
													if($attendence['attendence_status']==5){
														$small = $number['1'];$s++;
														if ($attendence['for_session']==1){
															$descri_added = "(ចេញមុន  ពេលព្រឹក)";
														}else if ($attendence['for_session']==2){
															$descri_added = "(ចេញមុន  ពេលល្ងាច)";
														}
													}
												}else{ // mistake
													if($attendence['attendence_status']==1){
														$small = $number['1'];$s++;
													}
													if($attendence['attendence_status']==2){
														$medium = $number['1'];$m++;
													}
													if($attendence['attendence_status']==3){
														$big = $number['1'];$l++;
													}
													if($attendence['attendence_status']==4){
														$other = $number['1'];$o++;
													}
												}
											?>
											<tr class="hover">
												<td align="center"><?php echo $att_d."-".$att_m."-".$attendence_year;?></td>
												<td align="center"><?php echo $small;?></td>
												<td align="center"><?php echo $medium;?></td>
												<td align="center"><?php echo $big;?></td>
												<td align="center"><?php echo $other;?></td>
												<td align="center"><?php echo $permission;?></td>
												<td align="center"><?php echo $absent; ?></td>
												<td><?php echo $groupCode.$attendence['description']." ".$descri_added;?></td>
												<td></td>
											</tr> 
										<?php }
									}?>
									<?php 
										$count_s='';
										$sp_count_s = str_split($s);
										foreach ($sp_count_s as $cos){
											$count_s.=$number[$cos];
										}
										$count_m='';
										$sp_count_m = str_split($m);
										foreach ($sp_count_m as $cm){
											$count_m.=$number[$cm];
										}
										$count_l='';
										$sp_count_l = str_split($l);
										foreach ($sp_count_l as $cl){
											$count_l.=$number[$cl];
										}
										
										$count_o='';
										$sp_count_o = str_split($o);
										foreach ($sp_count_o as $co){
											$count_o.=$number[$co];
										}
										
										$count_p='';
										$sp_count_p = str_split($p);
										foreach ($sp_count_p as $cp){
											$count_p.=$number[$cp];
										}
										$count_at='';
										$sp_count_at = str_split($at);
										foreach ($sp_count_at as $cat){
											$count_at.=$number[$cat];
										}
										$totalSmall=$totalSmall+$s;
										$totalMedium=$totalMedium+$m;
										$totalBig=$totalBig+$l;
										$totalOther=$totalOther+$o;
										$totalA=$totalA+$at;
										$totalP=$totalP+$p;
									?>
										<tr align="center" style="white-space: nowrap;">
											<td>សរុប</td>
											<td>&nbsp;<?php echo $count_s." ដង";?>&nbsp;</td>
											<td>&nbsp;<?php echo $count_m." ដង";?>&nbsp;</td>
											<td>&nbsp;<?php echo $count_l." ដង";?>&nbsp;</td>
											<td>&nbsp;<?php echo $count_o." ដង";?>&nbsp;</td>
											<td>&nbsp;<?php echo $count_p." ដង";?>&nbsp;</td>
											<td>&nbsp;<?php echo $count_at." ដង";?>&nbsp;</td>
										</tr>
										<tr>
											<td class="text-bold text-h18px" colspan="9">&nbsp;ឆមាសទី២</td>
										</tr>
										<?php 
											$i=0;
											$s=0;$m=0;$l=0;
											$o=0;
											$at=0;
											$p=0;
											//$attendences = $db_mistack->getAttendenceBydate(2, $group_id, $stu_id);
											$attendences = $db_mistack->getAttendenceBydateNew(2, $arr);
										?>	
										<?php 
											if (!empty($attendences)){
												foreach ($attendences as $attendence){
													
													$groupCode ="";
													if($attendence['group_id']!=$group_id){
														$groupCode =$attendence['groupCode']." ";
													}
												$attendence_year='';
												$sp_attendence_year = str_split(date("Y",strtotime($attendence['date_attendence'])));
												foreach ($sp_attendence_year as $cos){
													$attendence_year.=$number[$cos];
												}
												$att_m='';
												$sp_att_m = str_split(date("m",strtotime($attendence['date_attendence'])));
												foreach ($sp_att_m as $cos){
													$att_m.=$number[$cos];
												}
												$att_d='';
												$sp_att_d = str_split(date("d",strtotime($attendence['date_attendence'])));
												foreach ($sp_att_d as $cos){
													$att_d.=$number[$cos];
												}
												$permission = "";
												$absent = "";
												$small = "";
												$medium = "";
												$big = "";
												$other = "";
												$descri_added="";
												if ($attendence['type']==1){ // attendence
													if($attendence['attendence_status']==3){
														$permission = $number['1'];$p++;
													}
													if($attendence['attendence_status']==2){
														$absent = $number['1'];$at++;
													}
													if($attendence['attendence_status']==4){
														$small = $number['1'];$s++;
														if ($attendence['for_session']==1){
															$descri_added = "(មកយឺត ពេលព្រឹក)";
														}else if ($attendence['for_session']==2){
															$descri_added = "(មកយឺត ពេលល្ងាច)";
														}
													}
													if($attendence['attendence_status']==5){
														$small = $number['1'];$s++;
														if ($attendence['for_session']==1){
															$descri_added = "(ចេញមុន  ពេលព្រឹក)";
														}else if ($attendence['for_session']==2){
															$descri_added = "(ចេញមុន  ពេលល្ងាច)";
														}
													}
												}else{ // mistake
													if($attendence['attendence_status']==1){
														$small = $number['1'];$s++;
													}
													if($attendence['attendence_status']==2){
														$medium = $number['1'];$m++;
													}
													if($attendence['attendence_status']==3){
														$big = $number['1'];$l++;
													}
													if($attendence['attendence_status']==4){
														$other = $number['1'];$o++;
													}
												}
											?>
											<tr class="hover">
												<td align="center"><?php echo $att_d."-".$att_m."-".$attendence_year;?></td>
												<td align="center"><?php echo $small;?></td>
												<td align="center"><?php echo $medium;?></td>
												<td align="center"><?php echo $big;?></td>
												<td align="center"><?php echo $other;?></td>
												<td align="center"><?php echo $permission;?></td>
												<td align="center"><?php echo $absent; ?></td>
												<td style="max-width:100px; word-wrap:break-word;">&nbsp;<?php echo $groupCode.$attendence['description']." ".$descri_added;?></td>
												<td><?php echo "";?></td>
											</tr> 
										<?php }
									}?>
									<?php 
										$count_s='';
										$sp_count_s = str_split($s);
										foreach ($sp_count_s as $cos){
											$count_s.=$number[$cos];
										}
										$count_m='';
										$sp_count_m = str_split($m);
										foreach ($sp_count_m as $cm){
											$count_m.=$number[$cm];
										}
										$count_l='';
										$sp_count_l = str_split($l);
										foreach ($sp_count_l as $cl){
											$count_l.=$number[$cl];
										}
										
										$count_o='';
										$sp_count_o = str_split($o);
										foreach ($sp_count_o as $co){
											$count_o.=$number[$co];
										}
										
										$count_p='';
										$sp_count_p = str_split($p);
										foreach ($sp_count_p as $cp){
											$count_p.=$number[$cp];
										}
										$count_at='';
										$sp_count_at = str_split($at);
										foreach ($sp_count_at as $cat){
											$count_at.=$number[$cat];
										}
										$totalSmall+=$s;
										$totalMedium+=$m;
										$totalBig+=$l;
										$totalOther+=$o;
										$totalA+=$at;
										$totalP+=$p;
									?>
										<tr align="center" style="white-space: nowrap;">
											<td>សរុប</td>
											<td>&nbsp;<?php echo $count_s." ដង";?>&nbsp;</td>
											<td>&nbsp;<?php echo $count_m." ដង";?>&nbsp;</td>
											<td>&nbsp;<?php echo $count_l." ដង";?>&nbsp;</td>
											<td>&nbsp;<?php echo $count_o." ដង";?>&nbsp;</td>
											<td>&nbsp;<?php echo $count_p." ដង";?>&nbsp;</td>
											<td>&nbsp;<?php echo $count_at." ដង";?>&nbsp;</td>
										</tr>
										<tr class="bg-light-blues text-bold" align="center" style="white-space: nowrap;">
											<td>សរុបរួម</td>
											<td>&nbsp;<?php echo $totalSmall." ដង";?>&nbsp;</td>
											<td>&nbsp;<?php echo $totalMedium." ដង";?>&nbsp;</td>
											<td>&nbsp;<?php echo $totalBig." ដង";?>&nbsp;</td>
											<td>&nbsp;<?php echo $totalOther." ដង";?>&nbsp;</td>
											<td>&nbsp;<?php echo $totalP." ដង";?>&nbsp;</td>
											<td>&nbsp;<?php echo $totalA." ដង";?>&nbsp;</td>
											<td colspan="2"></td>
										</tr>
									</table>
								</td>
							</tr>
							
							<tr>
								<td>
									<table class="content-data text-color-black text-h16px text-size-12px">
										<tr>
											<td width="40%"></td>
											<td width="60%">
												<table width="100%" border="0">
												<?php 
													$now_year='';
													$sp_now_year = str_split(date("Y"));
													foreach ($sp_now_year as $y){
														$now_year.=$number[$y];
													}
													$now_day='';
													$sp_now_day = str_split(date("d"));
													foreach ($sp_now_day as $d){
														$now_day.=$number[$d];
													}
													?>
													<tr>
														<td colspan="3">
															&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; រាជធានីភ្នំពេញ ថ្ងៃទី &nbsp;&nbsp;<?php echo $now_day;?>&nbsp;&nbsp; ខែ &nbsp;&nbsp;<?php echo $month[date("m")];?>&nbsp;&nbsp; ឆ្នាំ &nbsp;&nbsp;<?php echo $now_year;?>
														</td>
													</tr>
													<tr>
														<td></td>
														<td colspan="2" class="fontkh-bold">
															ប្រធានផ្នែក វិន័យ
														</td>
													</tr>
													<tr>
														<td colspan="3">&nbsp;</td>
													</tr>
													<tr>
														<td width="30%"></td>
														<td width="30%" align="right" class="fontkh-bold">ឈុំ សារិ</td>
														<td width="40%" colspan="1"></td>
													</tr>
												</table>
											</td>
										</tr>
									</table>
								</td>
							</tr>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script>
document.addEventListener("DOMContentLoaded", function(e) {
  setTimeout(function() {
		setPrintOrientation('portrait','A4',true);
	}, 500);
});	
</script>