<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("RPT_STUDENT_MISTAKE")); 
	$frm =  $this->form_search;
	$dateFormat ="d/m/Y";
?>	
<style>
.hover:hover{ background:#ccc;}</style>
<div class="layout-wrapper-report">
	<div id="mainContent" class="main-content-report">
		<div class="report-preview">
			<?php echo $this->controlReport?>
			<div id="main-viewer" class="main-viewer portrait">
				<div id="viewer" class="viewer portrait">
					<div id="divPrint" class="content">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style.css">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style-screen.css">
						<style>
							@media print {
								<?php if(!empty($this->printFormat)){ echo $this->printFormat; } ?>
								
							}
							
							.w-300{width: 300px;
										box-sizing: border-box;}
							.header span{display: flex;
							justify-content: center;font-size:12px;}
							.description{
								white-space: normal;
							}
							.content-data thead tr td{
								vertical-align: middle !important;
							}
							.content-data tr td{
								vertical-align: top !important;
							}
						</style>
						<table style="margin: 0 auto; width: 100%; ">
							<tr class="header">
								<td colspan="3"><?php echo $this->rsheader;?></td>
							</tr>
							<tr>
								<td colspan="3" align="center" class="header">
									<span style="color:#000; font-size: 12px;font-family: 'Times New Roman','Khmer OS Muol light';"><?php echo $tr->translate("STUDENT_MISTAKE");?></span>
									<span><?php if(!empty($this->search['start_date'])){?><?php echo date($dateFormat,strtotime($this->search['start_date']));?> <?php echo $tr->translate("TO");?> <?php echo date($dateFormat,strtotime($this->search['end_date']));}?> </span>
								</td>
							</tr>
							<tr>
								<td colspan="3">
									<div id="exportExcel">
										<table class="content-data bd-dark-grey text-color-black text-h16px text-size-12px" border="1">
											<thead>
												<tr class="styleheader bg-head text-bold hpx-30 " align="center">
													<td class="wpx-20"><?php echo $tr->translate("NUM");?></td>
													<td class="wpx-50"><?php echo $tr->translate("STUDENT_ID");?></td>
													<td class="wpx-100"><?php echo $tr->translate("STUDENT");?></td>
													<td class="wpx-30"><?php echo $tr->translate("SEX");?></td>
													<td class="wpx-130"><?php echo $tr->translate("TEL");?></td>
													<td class="wpx-80"><?php echo $tr->translate("GROUP_CODE");?></td>
													<td class="wpx-80"><?php echo $tr->translate("DATE");?></td>
													<td class="wpx-60"><?php echo $tr->translate("DISCIPLINE_TYPE");?></td>
													<td class="wpx-200"><?php echo $tr->translate("DESCRIPTION");?></td>
												</tr>
											</thead>
											<?php $i=0;
											
											if (!empty($this->student)) foreach ($this->student as $key => $rs){
												$sex = $rs['sex']==1?$tr->translate("MALE_SHORT"):$tr->translate("FEMALE_SHORT");
												$i++;
											?>
											<tr>
												<td align="center"><?php echo $i;?></td>
												<td ><?php echo $rs['stu_code'];?></td>
												<td><span class="w-px-100 wrapcontent text-truncate"><?php echo $rs['stu_khname'];?></span></td>
												<td align="center"><?php echo $sex;?></td>
												<td><span class="w-px-130 wrapcontent text-truncate"><?php echo $rs['tel'];?></span></td>
												<td ><?php echo $rs['group_code'];?></td>
												<td class="text-center"><?php echo date($dateFormat,strtotime($rs['disciplineDate']));?></td>
												<td class="text-center"><?php echo $rs['disciplineType'];?></td>
												<td >
													<span class="wrapcontent wpx-200 text-size-10px text-h14px"><?php echo $rs['description'] ;?></span>
												</td>
											</tr>
											<?php }?>
										</table>	
									</div>	
								</td>
							</tr>
							<tr >
								<td colspan="3"><?php echo $this->rsfooter;?></td>
							</tr>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="right-panel-report" id="rightPanel">
		<div class="card-box">
			<div class="card-search-head col-sm-12 border-botom">
				<div class="col-sm-6 text-left pd-0">
					<h4 class="m-b-0">
						<?php echo $tr->translate("SEARCH");?> 
						<i class="fa fa-search "></i> 
					</h4>
				</div>
				<div class="col-sm-6 text-right pd-0">
					<button onclick="closeRightPanel()" title="<?php echo $tr->translate("CLOSED");?> " class="btn-close">
						<i class="fa-solid fa-xmark"></i>
					</button>
				</div>
			</div>
			<form  id='foundation_class' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
				<div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("adv_search");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("branch_id");?>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm->getElement("degree");?>
					</div>
					<div class="col-md-6 col-sm-6 col-xs-12">
						<input id="grade" />
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm->getElement("academic_year");?>
					</div>
					<div class="col-md-6 col-sm-6 col-xs-12">
						<input id="group" />
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<input id="session" />
						<?php //echo $frm->getElement("session");?>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm->getElement("start_date");?>
					</div>
					<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm->getElement("end_date");?>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<button class="button-class button-primary fullside" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
				</div>
			</form>
		</div>	
	</div>
</div>

<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script type="text/javascript">
	document.addEventListener("DOMContentLoaded", function(e) {
		setTimeout(function() {
			setPrintOrientation('portrait');
		}, 500);
	});
	dojo.require("dojo.data.ItemFileWriteStore"); 
	var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
	dojo.ready(function(){
		
		new dijit.form.FilteringSelect({
			store: group_store,
		    queryExpr: "*${0}*",
			autoComplete: false,                     
		    id: "group",
		    name: "group",  
		    class: 'fullside', 
		    readonly:false,
		    required:false,
		    placeHolder:"<?php echo $tr->translate("SELECT_GROUP");?>",          
		}, "group");
		
		new dijit.form.FilteringSelect({
			queryExpr: "*${0}*",
			autoComplete: false,                     
			required: false,                        
			id: "grade",
			name: "grade",  
			class: 'fullside',  
			placeHolder:"<?php echo $tr->translate("SELECT_GRADE");?>",          
		}, "grade");
		
		new dijit.form.FilteringSelect({
			queryExpr: "*${0}*",
			autoComplete: false,                     
			required: false,                        
			id: "session",
			name: "session",  
			class: 'fullside',  
			placeHolder:"<?php echo $tr->translate("SELECT_SESSION");?>",          
			onChange: function() {  

			}
		}, "session");
	
		 var branch_id = dijit.byId('branch_id');
		 branch_id.on('change', function(evt) {
			 getAllGroupByBranch();
	    });
		 var academic_year = dijit.byId('academic_year');
		 academic_year.on('change', function(evt) {
			 getAllGroupByBranch();
	    });
		var degree = dijit.byId('degree');
		degree.on('change', function(evt) {
			getAllSession();
		});
	
		getAllSession();
		 getallGrade();
		 getAllGroupByBranch();
	});
	var oldBranch = "<?php echo $this->search['branch_id']?>";
	url_getgroup = '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'getallgroup'));?>';
	function getAllGroupByBranch(){
		dijit.byId('group').reset();
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id=='' || branch_id==-1){
			var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
			dijit.byId('group').set('store',group_store);  
			dijit.byId('branch_id').focus();
			return false;
		}
		degree = dijit.byId('degree').get('value');
		if(degree=='' || degree==-1){degree ="";}
		grade = dijit.byId('grade').get('value');
		if(grade=='' || grade==-1){grade ="";}
		academic_year = dijit.byId('academic_year').get('value');
		if(academic_year=='' || academic_year==-1){academic_year ="";}
		
		dojo.xhrPost({
			url: url_getgroup,
			content:{
				'branch_id':branch_id,
				'degree':degree,
				'grade':grade,
				'academic_year':academic_year,
				'noaddnew':1,'forfilter':1
				},
			handleAs:"json",
			load: function(data) {
			    group_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('group').set('store',group_store);   
			    if(oldBranch==branch_id){
			    	dijit.byId('group').set('value','<?php echo $this->search['group']?>');  
			    }
			},
			error: function(err) {
			}
		});
	}
	var url_dept = '<?php echo $this->url(array('module'=>'global','controller'=>'grade','action'=>'get-grade')); ?>';
	function getallGrade(){
		getAllGroupByBranch();  
		dept_id = dijit.byId('degree').get('value');
		if(dept_id=='' || dept_id==-1){return false;}
			dojo.xhrPost({
				url:url_dept,
				content:{
					'dept_id':dept_id,
					'noaddnew':1
					},
				handleAs:"json",
				load: function(data) {
					dijit.byId('grade').attr('value','');
					grade_store  = getDataStorefromJSON('id','name', data);
				    dijit.byId('grade').set('store',grade_store); 
				    dijit.byId('grade').attr('value','<?php echo $this->search['grade']?>');  
				},
				error: function(err) {
				}
			});
	}
	
	var url_getSession = '<?php echo $this->url(array('module'=>'global','controller'=>'parttimelist','action'=>'get-parttime')); ?>';
	function getAllSession(){
		dijit.byId('session').set('value',''); 
		degree = dijit.byId('degree').get('value');
		if(degree==''){
			sessionStore  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
			dijit.byId('session').set('store',sessionStore);  
			return false;
		}
		dojo.xhrPost({
			url:url_getSession,
			content:{
				'degree':degree,
			},
			handleAs:"json",
			load: function(data) {
				sessionStore  = getDataStorefromJSON('id','name', data);
				dijit.byId('session').set('store',sessionStore);  
				<?php if(!empty($this->search['session'])){ ?>
				dijit.byId('session').set('store','<?php echo $this->search['session']?>');  
				<?php } ?>
			},
			error: function(err) {
			}
		});
	}
</script>