<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('RPT_STUDENT_GOT_PRODUCT')); 
	$frm = $this->form_search;
	$classHideHeight=classHideHeight;
	$dateFormat ="d/m/Y";
?>	
<style>
.hover:hover{ background:#ccc;}
</style>
<div class="layout-wrapper-report">
	<div id="mainContent" class="main-content-report">
		<div class="report-preview">
			<?php echo $this->controlReport?>
			<div id="main-viewer" class="main-viewer portrait">
				<div id="viewer" class="viewer portrait">
					<div id="divPrint" class="content">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style.css">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style-screen.css">
						<style>
							@media print {
								<?php if(!empty($this->printFormat)){ echo $this->printFormat; } ?>
							}
							table tr td ul li {
								text-align: center;
								list-style: none;
								line-height: 25px;
							}
						</style>
						<table border="0" style="background:#fff; margin: 0 auto; width: 100%; ">
							<tr>
								<td colspan="3"><?php echo $this->rsheader;?></td>
							</tr>
							<tr>
								<td></td>
							</tr>
							<tr>
								<td width="15%" align="center">
								</td>
								<td width="70%"  align="center">
									<ul>
										<li><span <?php echo TITLE_REPORT;?> ><?php echo $tr->translate("RPT_STUDENT_GOT_PRODUCT");?></span></li>
										<li><?php if(!empty($this->search['start_date'])){echo date($dateFormat,strtotime($this->search['start_date'])).' '.$tr->translate('TO').' ';} echo date($dateFormat,strtotime($this->search['end_date']));?></li>
									</ul>
								</td>
								<td width="15%" align="center">
								</td>
							</tr>
							<tr>
								<td></td>
							</tr>
							<tr>
								<td colspan="3">
								<div id="exportExcel">
									<table cellpadding="4" class="content-data bd-dark-grey text-color-black text-h16px text-size-11px"  border="1" >
										<thead>
											<tr class="styleheader bg-head text-bold hpx-25 " align="center">
												<td scope="col"  rowspan="2"><?php echo $tr->translate("NUM");?></td>
												<td scope="col"  rowspan="2"><?php echo $tr->translate("BRANCH");?></td>
												<td scope="col"  colspan="3"><?php echo $tr->translate("STUDENT_INFO");?></td>
												<td scope="col"  colspan="7"><?php echo $tr->translate("GETPRODUCT_INFO");?></td>
												<td scope="col"  rowspan="2"><?php echo $tr->translate("STOCK_STATUS");?></td>
												<td scope="col"  rowspan="2"><?php echo $tr->translate("STATUS");?></td>
												<td scope="col"  rowspan="2"><?php echo $tr->translate("USER");?></td>
											</tr>
											<tr class="styleheader bg-head text-bold hpx-25 " align="center">
												<td scope="col" ><?php echo $tr->translate("STUDENT_CODE");?></td>
												<td scope="col" ><?php echo $tr->translate("STUDENT_NAME");?></td>
												<td scope="col" class="w-px-120" ><?php echo $tr->translate("PHONE");?></td>

												<!-- <td scope="col" ><?php echo $tr->translate("Ref Receipt No");?></td> -->
												<td scope="col" ><?php echo $tr->translate("Receipt Num");?></td>
												<td scope="col" ><?php echo $tr->translate("PURCHASE_DATE");?></td>

												<td scope="col" ><?php echo $tr->translate("PRODUCT_NAME");?></td>
												<td scope="col" ><?php echo $tr->translate("CURRENT_STOCK_QTY");?></td>
												<td scope="col" ><?php echo $tr->translate("QTY_ORDER");?></td>
												<td scope="col" ><?php echo $tr->translate("RECEIVE_QTY");?></td>
												<td scope="col" ><?php echo $tr->translate("QTY_AFTER");?></td>
											</tr>
										</thead>
										<?php $i=0; if (!empty($this->rs)) foreach ($this->rs as $key=> $row){$i++;?>
										<tr class="style hover" align="center" >
											<td data-label="<?php echo $tr->translate("NUM");?>" align="center"><?php echo $i;?></td>
											<td data-label="<?php echo $tr->translate("BRANCH");?>"><?php echo $row['branch_name'];?></td>

											<td data-label="<?php echo $tr->translate("STUDENT_CODE");?>" align="center"><?php echo $row['student_code'];?></td>
											<td data-label="<?php echo $tr->translate("STUDENT_NAME");?>" align="left"><?php echo $row['student_name'];?></td>
											<td data-label="<?php echo $tr->translate("PHONE");?>"  align="left">
												<span class="w-px-120 wrapcontent text-truncate"><?php echo $row['tel'];?></span>
											</td>

											<!-- <td data-label="<?php echo $tr->translate("Ref Receipt No");?>" align="center"><a style="text-decoration: none; color: red;" href="<?php echo $this->baseUrl()."/stock/cutstock/receipt/id/".$row['cutstock_id'];?>"><?php echo $row['serailno'];?></a></td> -->
											<td data-label="<?php echo $tr->translate("Receipt Num");?>" align="center"><a style="text-decoration: none; color: red;" ></a><?php echo $row['receipt_number'];?></a></td>
											<td data-label="<?php echo $tr->translate("Received Date");?>" align="center"><?php echo date($dateFormat,strtotime($row['create_date']))?></td>
											<td data-label="<?php echo $tr->translate("PRODUCT_NAME");?>" align="left"><?php echo $row['product_name'];?></td>
											<td data-label="<?php echo $tr->translate("CURRENT_STOCK_QTY");?>"  align="center"><?php echo $row['current_qty'];?></td>
											<td data-label="<?php echo $tr->translate("QTY_ORDER");?>" align="center"><?php echo $row['qty'];?></td>
											<td data-label="<?php echo $tr->translate("RECEIVE_QTY");?>" align="center">
											<?php
												$qtyReceived = $row['qty']-$row['qty_after'];
												 echo number_format($qtyReceived,2);
											 ?></td>
											<td data-label="<?php echo $tr->translate("QTY_AFTER");?>" align="center"><?php echo $row['qty_after'];?></td>
											<td data-label="<?php echo $tr->translate("STATUS");?>"  align="center" <?php if($row['qty_after']>0 ){?> class="text-bold text-color-red"<?php } ?> ><?php if($row['qty_after']==0){ echo $tr->translate("RECEIVED_ALL");}else if($row['qty_after']>0){ echo $tr->translate("IDEPTED");}?></td>
											<td data-label="<?php echo $tr->translate("STATUS");?>"  align="center"  <?php if($row['is_void']==1 ){?> class="text-bold text-color-red"<?php } ?> ><?php if($row['is_void']==1){ echo $tr->translate("VOID");}else if($row['is_closed']==1){ echo $tr->translate("CLOSED");}else{ echo $tr->translate("ACTIVE");}?></td>
											<td data-label="<?php echo $tr->translate("USER");?>" align="left" ><?php if($row['is_closed']==1){ echo $row['user_close'];}else if($row['status']==1){ echo $row['user_enter'];}else{ echo "-";}?></td>
										</tr>
										<?php }?>
									</table>	
								</div>	
								</td>
							</tr>
							<tr>
								<td colspan="3"></td>
							</tr>
							<tr>
								<td colspan="3"></td>
							</tr>
							<tr >
								<td colspan="3" width="100%">
									<table width="100%" style="font-family:'Khmer OS Battambang';">
										<tr>
											<td  width="25%" align="center">
												<span style=" font-size: 14px;"><?php echo $tr->translate('VERIFIED_BY')?></span>
											</td>
											<td  width="50%">
												
											</td>
											<td align="center"  width="25%">
												<span style="font-size: 14px;text-align: right;"><?php echo $tr->translate('PREPARED_BY')?></span>
											</td>
										</tr>
									</table>
								</td>
							</tr>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="right-panel-report" id="rightPanel">
		<div class="card-box">
			<div class="card-search-head col-sm-12 border-botom">
				<div class="col-sm-6 text-left pd-0">
					<h4 class="m-b-0">
						<?php echo $tr->translate("SEARCH");?> 
						<i class="fa fa-search "></i> 
					</h4>
				</div>
				<div class="col-sm-6 text-right pd-0">
					<button onclick="closeRightPanel()" title="<?php echo $tr->translate("CLOSED");?> " class="btn-close">
						<i class="fa-solid fa-xmark"></i>
					</button>
				</div>
			</div>
			<form action=""	dojoType="dijit.form.Form" method="post">
				<script type="dojo/method" event="onSubmit">			
					if(this.validate()) {
							start_date = dijit.byId('start_date').get('value');
							if(start_date==null){
								alert("<?php echo $tr->translate("PLEASE_SELECT_START_DATE");?>");
								dijit.byId("start_date").focus();
								return false;
							}
							loadingBlock();
							return true;
					} else {
						return false;
					}
				</script>
				<div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
                   		<?php echo $frm->getElement("adv_search");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
                   		<?php echo $frm->getElement("branch_id");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
                   		<input id="student_id" />
                   </div>
				</div>
				<div class="form-group">
					<div class="col-md-6 col-sm-6 col-xs-12">
                   		<?php echo $frm->getElement("start_date");?>
                   </div>
					<div class="col-md-6 col-sm-6 col-xs-12">
                   		<?php echo $frm->getElement("end_date");?>
                   </div>
                </div>
				<div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
                   		<?php echo $frm->getElement("stock_status");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<button class="button-class button-primary fullside" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button"
						showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
                   </div>
                </div>
			</form>
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dojo.NodeList-manipulate");
	dojo.require("dijit.form.Textarea");
	dojo.ready(function(){
		new dijit.form.FilteringSelect({
			autoComplete: false,
			queryExpr: "*${0}*",                     
			id: "student_id",
			name: "student_id",   
			value:"<?php echo $this->search['student_id'];?>",
			required:false,        
			class: 'fullside', 
			placeHolder:"<?php echo $tr->translate("SELECT_STUDENT_NAME");?>",          
		}, "student_id");
		getAllStudentBranch();
			var branch_id = dijit.byId('branch_id');
		 	branch_id.on('change', function(evt) {
		 		getAllStudentBranch();
		    });
			
		setTimeout(function() {
			setPrintOrientation('landscape');
		}, 500);
	});
	var url_getstudent = '<?php echo $this->url(array('module'=>'foundation','controller'=>'register','action'=>'getallstudentdata'));?>';
	function getAllStudentBranch(){
		dijit.byId('student_id').reset();
		branch_id = dijit.byId('branch_id').get('value');
		var student_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('student_id').set('store',student_store);  
		if(branch_id=='' || branch_id==-1){
			return false;
		}
		dojo.xhrPost({
			url: url_getstudent,
			content:{
				'branch_id':branch_id,'typeQuery':1
				},
			handleAs:"json",
			load: function(data) {
				student_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('student_id').set('store',student_store);  
			    dijit.byId('student_id').set('value','<?php echo $this->search['student_id']?>');  
			},
			error: function(err) {
				
			}
		});
	}
</script>