<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('RPT_PRODUCT_SELLOUT')); 
	$frm = $this->form_search;
	$classHideHeight=classHideHeight;
	$dateFormat ="d/m/Y";
?>	
<style>
	.hover:hover{ background:#ccc;}
	table.content-data tr.style-head,
	
</style>
<div class="layout-wrapper-report">
	<div id="mainContent" class="main-content-report">
		<div class="report-preview">
			<?php echo $this->controlReport?>
			<div id="main-viewer" class="main-viewer portrait">
				<div id="viewer" class="viewer portrait">
					<div id="divPrint" class="content">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style.css">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style-screen.css">
						<style>
							@media print {
								<?php if(!empty($this->printFormat)){ echo $this->printFormat; } ?>
							}
							tr.voidclass {
								background: #fff7f7;
							}
						</style>
						<table style=" width:90%; margin: 0 auto;white-space: nowrap;width: 100%;font-family:'Times New Roman','Khmer OS Battambang';" >
							<tr>
								<td colspan="3"><?php echo $this->rsheader;?></td>
							</tr>
							<tr>
								<td width="15%" align="center">
								</td>
								<td align="center"  width="70%">
									<span <?php echo TITLE_REPORT;?>><?php echo $tr->translate('RPT_PRODUCT_SELLOUT');?></span><br />
									<span style="color:#000; font-size: 12px;"><?php if(!empty($this->search['start_date'])){?><?php echo date($dateFormat,strtotime($this->search["start_date"]))?> <?php echo $tr->translate('TO');?> <?php echo date($dateFormat,strtotime($this->search["end_date"]));}?></span> 
								</td>
								<td width="15%" align="center">
								</td>
							</tr>
							<tr>
								<td colspan="3" id="exportExcel">
								
									<table class="content-data bd-dark-grey text-color-black text-h16px text-size-12px" cellpadding="5" border="1" >
										<thead>
											<tr class="styleheader bg-head text-bold hpx-25 " align="center">
												<td scope="col" rowspan="2"><?php echo $tr->translate("NUM");?></td>
												<td scope="col" rowspan="2"><?php echo $tr->translate("BRANCH");?></td>
												<td scope="col" colspan="2"><?php echo $tr->translate("STUDENT_INFO");?></td>
												<td scope="col" colspan="2"><?php echo $tr->translate("PRODUCT_INFO");?></td>
												<td scope="col" colspan="10"><?php echo $tr->translate("SALE_INFO");?></td>
											</tr>
											<tr class="styleheader bg-head text-bold hpx-25 " align="center">
												<td scope="col"><?php echo $tr->translate('STUDENT_ID');?></td>
												<td scope="col"><?php echo $tr->translate('STUDENT_NAME');?></td>
												<td scope="col"><?php echo $tr->translate('PRODUCT_CATEGORY');?></td>
												<td scope="col"><?php echo $tr->translate('PRODUCT_NAME');?></td>
												<td scope="col"><?php echo $tr->translate('QTY');?></td>
												<td scope="col"><?php echo $tr->translate('UNIT_COST');?></td>
												<td scope="col"><?php echo $tr->translate('TOTAL_COST');?></td>
												<td scope="col"><?php echo $tr->translate('SELL_PRICE');?></td>
												<td scope="col"><?php echo $tr->translate('TOTAL');?></td>
												<td scope="col"><?php echo $tr->translate('PROFIT');?></td>
												<td scope="col"><?php echo $tr->translate('RECEIPT_NO');?></td>
												<td scope="col"> <?php echo $tr->translate('SALE_DATE');?></td>
												<td scope="col"><?php echo $tr->translate('USER');?></td>
										   </tr>
									   </thead>
									<?php $i=0;
										$totalCost=0;
										$totalSell=0;
									if(!empty($this->product_sold)){ foreach ($this->product_sold AS $rs) { $i++;
									?>
										<tr class="style hover" align="left">
											<td align="center" data-label="<?php echo $tr->translate("NUM");?>"><?php echo $i; ?></td>
											<td data-label="<?php echo $tr->translate("BRANCH");?>"> <?php echo $rs['branch_name'];?></td>
											<td data-label="<?php echo $tr->translate("STUDENT_ID");?>"><?php echo $rs['stu_code'];?></td>
											<td data-label="<?php echo $tr->translate("STUDENT_NAME");?>" style="text-align: left;"><?php echo $rs['student_name'];?></td>
											<td data-label="<?php echo $tr->translate("PRODUCT_CATEGORY");?>"><?php echo $rs['category'];?></td>
											<td data-label="<?php echo $tr->translate("PRODUCT_NAME");?>" style="text-align: left;"><?php echo $rs['items_name'];?></td>
											<td data-label="<?php echo $tr->translate("QTY");?>"><?php echo $rs['qty'];?></td>
											<td data-label="<?php echo $tr->translate("UNIT_COST");?>"><?php echo $rs['cost'];?></td>
											<td data-label="<?php echo $tr->translate("TOTAL_COST");?>"><strong>
											<?php 
													$subTotalcost = $rs['qty']*$rs['cost'];
													echo number_format($subTotalcost,2);
													$subTotalSell=$rs['qty']*$rs['price'];
													$totalCost +=$subTotalcost;
													$totalSell+=$subTotalSell;
											?>
											</strong></td>
											<td data-label="<?php echo $tr->translate("SELL_PRICE");?>"><?php echo $rs['price'];?></td>
											<td data-label="<?php echo $tr->translate("TOTAL");?>"><strong><?php echo number_format($subTotalSell,2);?></strong></td>
											<td align="center" data-label="<?php echo $tr->translate("PROFIT");?>"><strong><?php echo number_format($subTotalSell-$subTotalcost,2);?></strong></td>
											<td align="center" data-label="<?php echo $tr->translate("RECEIPT_NO");?>"><strong><?php echo $rs['receipt_number'];?></strong></td>
											<td align="center" data-label="<?php echo $tr->translate("SALE_DATE");?>"><?php echo date($dateFormat,strtotime($rs['create_date']));?></td>
											<td align="center" data-label="<?php echo $tr->translate("USER");?>"><?php echo $rs['user']; ?></td>
										 </tr>
											<?php 
											}}
											?>	  
									</table>
									<table width="40%" class="content-data bd-dark-grey text-color-black text-h16px text-size-12px" border="1" style="width:40% !important; margin-top:15px;float:right"  >
										<tr class="styleheader bg-head text-bold hpx-25 " align="center">
										   <td width="33%"><?php echo $tr->translate('TOTAL_UNIT_PRICE')?></td>
											<td width="33%"><?php echo $tr->translate('TOTAL_SALE')?></td>
										   <td width="33%"><?php echo $tr->translate('TOTAL_PROFIT')?></td>
									   </tr>
										<tr align="center" class="text-bold text-center "  align="center">
										   <td>$ <?php echo number_format($totalCost,2);?></td>
										   <td>$ <?php echo number_format($totalSell,2);?></td>
										   <td>$ <?php echo number_format($totalSell-$totalCost,2);?></td>
									   </tr>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="3">
									<?php echo $this->rsfooteracc;?>
								</td>
							</tr>
						</table>
					</div>	
				</div>	
			</div>	
		</div>	
	</div>	
	<div class="right-panel-report" id="rightPanel">
		<div class="card-box">
			<div class="card-search-head col-sm-12 border-botom">
				<div class="col-sm-6 text-left pd-0">
					<h4 class="m-b-0">
						<?php echo $tr->translate("SEARCH");?> 
						<i class="fa fa-search "></i> 
					</h4>
				</div>
				<div class="col-sm-6 text-right pd-0">
					<button onclick="closeRightPanel()" title="<?php echo $tr->translate("CLOSED");?> " class="btn-close">
						<i class="fa-solid fa-xmark"></i>
					</button>
				</div>
			</div>	
			<form dojoType="dijit.form.Form" method="post">
				<div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("adv_search");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("branch_id");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("category_id");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<input id="product" />
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm->getElement("start_date");?>
					</div>
					<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm->getElement("end_date");?>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("user_id");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<button class="button-class button-primary fullside" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button"
							showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
				</div>
			</form>
		</div>	
	</div>	
</div>	
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script src="<?php echo $this->baseUrl();?>/admin/js/global.js"  type="text/javascript"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");  

	var academic_store= getDataStorefromJSON('id','name',[]);
	var group_store  = getDataStorefromJSON('id','name',[]);
	dojo.ready(function(){
		getProductByCate();
		
		new dijit.form.FilteringSelect({
			store: item_store,
			autoComplete: false,
			queryExpr: "*${0}*",                     
			id: "product",
			name: "product",
			placeholder:'<?php echo $tr->translate("SELECT_PRODUCT");?>',
			required:false,        
			class: 'fullside', 
		}, "product");
		setTimeout(function() {
			setPrintOrientation('landscape');
		}, 500);
	});
	
	var item_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	var url_dept = '<?php echo $this->url(array('module'=>'allreport','controller'=>'stock','action'=>'get-productbycate')); ?>';
	function getProductByCate(){
		cate_id = dijit.byId("category_id").get("value");
			dojo.xhrPost({
				url:url_dept,
				content:{
					'cate_id':cate_id,
					},
				handleAs:"json",
				load: function(data) {
					item_store  = getDataStorefromJSON('id','name', data);
					dijit.byId('product').set('store',item_store);  	
					dijit.byId('product').attr('value','<?php echo $this->search['product']?>');
				},
				error: function(err) {
				}
			});
	}
</script>