<?php $tr = Application_Form_FrmLanguages::getCurrentlanguage();

$pageTitle = $tr->translate("STUDENT_DISCIPLINE_REPORT");
 echo $this->headTitle($pageTitle);
$frm = $this->form_search;
 
?>
<style>
ul.tile_info.ul_info {
    height: 180px;
}
</style>
  <div class="card">
		<div class="card-content collapse show">
			<div class="card-box report-list">
				<div class="row">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<div class="row top_tiles">
							<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
								<h3 style="font-family:Times New Roman,khmer os muol light;font-size:18px;text-align: center; color: #666;padding:2px 0;"><i style="font-size:25px;margin-right:10px;" class="fa fa-gavel " aria-hidden="true"></i><?php echo $pageTitle;?></h3><hr>
							</div>
						</div>
						<div class="row">
							<?php
								   $db_user=new Application_Model_DbTable_DbUsers();
								   $report_url=$db_user->getArrAclReport(1,'studentattendance');
								 
								   if(!empty($report_url)){
									   foreach($report_url as $url){
									   if($url['controller']=='studentattendance' AND $url['action']!='index' 
											AND $url['action']!='rpt-att-list' 
											AND $url['action']!='rpt-totalattendance' 
											AND $url['action']!='mistake-certificate' 
											){
							   ?>
							   <div class="animated flipInY col-lg-3 col-md-3 col-sm-3 col-xs-12">
									<a href="<?php echo $this->url(array('module'=>$url['module'],'controller'=>$url['controller'],'action'=>$url['action'])); ?>">
									 <div title="<?php echo $tr->translate($url['label']);?>" class="tile-stats report-list">
										<div class="icon"><i class="fa fa-book"></i></div>
										<div class="count">&nbsp;</div>
											<h3><?php echo $tr->translate($url['label']);?></h3>
									 </div>
									</a>
								</div>
								<?php }?>
						   <?php }
						  }?>
						</div>
					</div>
					
				</div>
			</div>
		</div>
	</div>
<div style="clear: both;"></div>
