<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("RPT_REQ_PERMISSION")); 
	$frm =  $this->form_search;
	
	$dateFormat ="d/m/Y";
	$dateFormatExpt ="d/M/Y";
?>	
<div class="layout-wrapper-report">
	<div id="mainContent" class="main-content-report">
		<div class="report-preview">
			<?php echo $this->controlReport?>
			<div id="main-viewer" class="main-viewer portrait">
				<div id="viewer" class="viewer portrait">
					<div id="divPrint" class="content">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style.css">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style-screen.css">
						<style>
							@media print {
								<?php if(!empty($this->printFormat)){ echo $this->printFormat; } ?>
							}
						</style>
						<table style="margin: 0 auto; width: 100%; ">
							<tr>
								<td colspan="3" align="center" class="header">
									<?php echo $this->rsheader;?>
									<span class="text-color-black text-h16px text-size-12px" style="font-family: 'Times New Roman','Khmer OS Muol light';"><?php echo $tr->translate("RPT_REQ_PERMISSION");?></span>
									<br />
									<span class="text-color-black text-h16px text-size-11px"><?php if(!empty($this->search['start_date'])){?><?php echo date($dateFormat,strtotime($this->search['start_date']));?> <?php echo $tr->translate("TO");?> <?php echo date($dateFormat,strtotime($this->search['end_date']));}?> </span>
								</td>
							</tr>
							<tr>
								<td colspan="3">
									<div id="exportExcel">
										<table class="content-data bd-dark-grey text-color-black text-h18px text-size-12px" border="1">
											<thead>
												<tr class="styleheader bg-head text-bold hpx-20" align="center">
													<td class="wpx-20" rowspan="2"><?php echo $tr->translate("NUM");?></td>
													<td colspan="4"><?php echo $tr->translate("STUDENT_INFO");?></td>
													<td colspan="4"><?php echo $tr->translate("REQ_PERMISSION_INFO");?></td>
												</tr>
												<tr class="styleheader bg-head text-bold hpx-20" align="center">
													<td class="wpx-50"><?php echo $tr->translate("STUDENT_ID");?></td>
													<td class="wpx-150"><?php echo $tr->translate("STUDENT");?></td>
													<td class="wpx-30"><?php echo $tr->translate("SEX");?></td>
													<td class="wpx-80"><?php echo $tr->translate("GROUP_CODE");?></td>
													
													<td class="wpx-50"><?php echo $tr->translate("AMT_DAY");?></td>
													<td class="wpx-100"><?php echo $tr->translate("DATE");?></td>
													<td class="wpx-200"><?php echo $tr->translate("REASON");?></td>
													<td class="wpx-80"><?php echo $tr->translate("CREATE_DATE");?></td>
												</tr>
											</thead>
											<?php $i=0;
											
											if (!empty($this->rs)) foreach ($this->rs as $key => $rs){
												$sex = $rs['sex']==1?$tr->translate("MALE_SHORT"):$tr->translate("FEMALE_SHORT");
												$i++;
											?>
											<tr>
												<td class="wpx-20" align="center"><?php echo $i;?></td>
												<td ><?php echo $rs['stuCode'];?></td>
												<td><?php echo $rs['stuNameKh'];?></td>
												<td align="center"><?php echo $sex;?></td>
												<td align="center"><?php echo $rs['groupCode'];?></td>
												<td align="center"><?php echo sprintf('%02d',$rs['amountDay']);?></td>
												<td align="center" class="hideExport"><?php echo ($rs['amountDay']>1) ? date($dateFormat,strtotime($rs['fromDate']))." ".$tr->translate("TO")." ".date($dateFormat,strtotime($rs['toDate'])) : date("d-m-Y",strtotime($rs['fromDate']));?></td>
												<td align="center" class="showExport" style="display:none;" ><?php echo ($rs['amountDay']>1) ? date($dateFormat,strtotime($rs['fromDate']))." ".$tr->translate("TO")." ".date($dateFormat,strtotime($rs['toDate'])) : date("d-m-Y",strtotime($rs['fromDate']));?></td>
												<td class="description"><?php echo $rs['reason'];?></td>
												<td align="center" class="hideExport"><?php echo date($dateFormat,strtotime($rs['createDate']));?></td>
												<td align="center" class="showExport" style="display:none;" ><?php echo date($dateFormatExpt,strtotime($rs['createDate']));?></td>
											</tr>
											<?php }?>
										</table>	
										<?php echo $this->rsfooter;?>
									</div>	
								</td>
							</tr>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="right-panel-report" id="rightPanel">
		<div class="card-box">
			<div class="card-search-head col-sm-12 border-botom">
				<div class="col-sm-6 text-left pd-0">
					<h4 class="m-b-0">
						<?php echo $tr->translate("SEARCH");?> 
						<i class="fa fa-search "></i> 
					</h4>
				</div>
				<div class="col-sm-6 text-right pd-0">
					<button onclick="closeRightPanel()" title="<?php echo $tr->translate("CLOSED");?> " class="btn-close">
						<i class="fa-solid fa-xmark"></i>
					</button>
				</div>
			</div>
			<form  id='foundation_class' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
				<div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("adv_search");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("branch_id");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<input id="academic_year" />
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<input id="group" />
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm->getElement("degree");?>
					</div>
					<div class="col-md-6 col-sm-6 col-xs-12">
						<input id="grade" />
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm->getElement("start_date");?>
					</div>
					<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm->getElement("end_date");?>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<button class="button-class button-primary fullside" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>

<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script src="<?php echo $this->baseUrl();?>/admin/js/global.js"  type="text/javascript"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore"); 
	var academic_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
	var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
	dojo.ready(function(){
		new dijit.form.FilteringSelect({
			store: academic_store,
			queryExpr: "*${0}*",
			autoComplete: false,                     
			required: false,                     
			id: "academic_year",
			name: "academic_year",
			class: "fullside", 		
			placeHolder:"<?php echo $tr->translate("SELECT_ACADEMIC_YEAR");?>",          
			onChange: function() {  
				academic_year = dijit.byId('academic_year').get('value');
			}
		}, "academic_year");
		new dijit.form.FilteringSelect({
			store: group_store,
		    queryExpr: "*${0}*",
			autoComplete: false,                     
		    id: "group",
		    name: "group",  
		    class: 'fullside', 
		    readonly:false,
		    required:false,
		    placeHolder:"<?php echo $tr->translate("SELECT_GROUP");?>",          
		}, "group");
		
		new dijit.form.FilteringSelect({
			queryExpr: "*${0}*",
			autoComplete: false,                     
			required: false,                        
			id: "grade",
			name: "grade",  
			class: 'fullside',  
			placeHolder:"<?php echo $tr->translate("SELECT_GRADE");?>",          
		}, "grade");
		
		 var branch_id = dijit.byId('branch_id');
		 branch_id.on('change', function(evt) {
			 getAllAcademicByBranch();
			 getAllGroupByBranch();
	    });
		 var academic_year = dijit.byId('academic_year');
		 academic_year.on('change', function(evt) {
			 getAllGroupByBranch();
	    });
		 getAllAcademicByBranch();
		 getallGrade();
		 getAllGroupByBranch();
		 
		 setTimeout(function() {
			setPrintOrientation('portrait');
		}, 500);
	});
	var oldBranch = "<?php echo $this->search['branch_id']?>";
	
	url_getacademic= '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'get-academicyear'));?>';
	function getAllAcademicByBranch(){
		dijit.byId('academic_year').reset();
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id=='' || branch_id==-1){
			var academic_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
			dijit.byId('academic_year').set('store',academic_store);  
			dijit.byId('branch_id').focus();
			return false;
		}
		
		contentData = {
			'branch_id':branch_id
		}
		selectedId = '';
		if(oldBranch==branch_id){
			selectedId = '<?php echo $this->search['academic_year']?>';
		}
			
		getAllYear(url_getacademic,contentData,selectedId,'academic_year');
		
	}

	url_getgroup = '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'getallgroup'));?>';
	function getAllGroupByBranch(){
		dijit.byId('group').reset();
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id=='' || branch_id==-1){
			var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
			dijit.byId('group').set('store',group_store);  
			dijit.byId('branch_id').focus();
			return false;
		}
		degree = dijit.byId('degree').get('value');
		if(degree=='' || degree==-1){degree ="";}
		grade = dijit.byId('grade').get('value');
		if(grade=='' || grade==-1){grade ="";}
		academic_year = dijit.byId('academic_year').get('value');
		if(academic_year=='' || academic_year==-1){academic_year ="";}
		
		dojo.xhrPost({
			url: url_getgroup,
			content:{
				'branch_id':branch_id,
				'degree':degree,
				'grade':grade,
				'academic_year':academic_year,
				'noaddnew':1,'forfilter':1
				},
			handleAs:"json",
			load: function(data) {
			    group_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('group').set('store',group_store);   
			    if(oldBranch==branch_id){
			    	dijit.byId('group').set('value','<?php echo $this->search['group']?>');  
			    }
			},
			error: function(err) {
			}
		});
	}
	var url_dept = '<?php echo $this->url(array('module'=>'global','controller'=>'grade','action'=>'get-grade')); ?>';
	function getallGrade(){
		getAllGroupByBranch();  
		dept_id = dijit.byId('degree').get('value');
		if(dept_id=='' || dept_id==-1){return false;}
			dojo.xhrPost({
				url:url_dept,
				content:{
					'dept_id':dept_id,
					'noaddnew':1
					},
				handleAs:"json",
				load: function(data) {
					dijit.byId('grade').attr('value','');
					grade_store  = getDataStorefromJSON('id','name', data);
				    dijit.byId('grade').set('store',grade_store); 
				    dijit.byId('grade').attr('value','<?php echo $this->search['grade']?>');  
				},
				error: function(err) {
				}
			});
	}
</script>