<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('បង្កាន់ដៃបង់ប្រាក់'); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
	defined('AMOUNT_RECEIPT') || define('AMOUNT_RECEIPT', Setting_Model_DbTable_DbGeneral::geValueByKeyName('receipt_print'));
?>

<style>
	button#portraitBtn,
	button#landscapeBtn,
	button.btn-search {
		display: none !important;
	}
</style>
<div class="layout-wrapper-report">
	<div id="mainContent" class="main-content-report">
		<div class="report-preview">
			<?php echo $this->controlReport?>
			<div id="main-viewer" class="main-viewer portrait">
				<div id="viewer" class="viewer portrait">
					<div id="divPrint" class="content">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style.css">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style-screen.css">
						<style>
							table.collape.tablesorter {
								white-space: nowrap;
							}
						</style>
						<div id="divPrint1" style="width: 100%;height: 13cm ; padding: 0px; margin: 0px;">
						<?php  echo $this->officailreceipt;?>
						</div>
						<?php if(AMOUNT_RECEIPT>1){?>
							
							<div id="printblog2" class="content"></div>
						 <?php }?>
					</div>	
				</div>	
			</div>	
		</div>	
	</div>	
</div>	
    	
<script type="text/javascript">
require(["dojo/ready"], function(ready){
	 ready(function(){
		 loadingBlock();
		 printSave();
		 setTimeout(function() {
			setPrintOrientation('landscape',"A5",true);
		}, 200);
		 setTimeout(function () {
			 <?php if(AMOUNT_RECEIPT>1){?>
			 dojo.byId('printblog2').innerHTML = dojo.byId('divPrint1').innerHTML;
			 <?php }?>
	        HideloadingBlock();
	    }, 500);
		
	 });
});	 
function printSave(){
	symbal="$ ";
	<?php if (!empty($this->header)){?>
	$( "#header_receipt" ).append( "<?php echo preg_replace( "/\r|\n/", "",$this->header);?>" );
	<?php }?>
	var statusvoid="";
	<?php if ($this->row['status']==0){?>
		statusvoid="<?php echo preg_replace( "/\r|\n/", "", strip_tags("(Void)"));?>";
	<?php }?>
	
	dojo.byId("lbl_branch").innerHTML = '<?php echo preg_replace( "/\r|\n/", "", strip_tags(htmlspecialchars($this->row['branch_name'])));?>';
	dojo.byId("lbl_studentid").innerHTML = '<?php echo preg_replace( "/\r|\n/", "", strip_tags(htmlspecialchars($this->row['stu_code'])));?>';
	dojo.byId("lbl_studentkh").innerHTML = '<?php echo preg_replace( "/\r|\n/", "", strip_tags(htmlspecialchars($this->row['stu_khname'])));?>';
	dojo.byId("lbl_studenten").innerHTML = '<?php echo preg_replace( "/\r|\n/", "", strip_tags(htmlspecialchars($this->row['stu_enname'])));?>';
	dojo.byId("lbl_class").innerHTML = '<?php echo preg_replace( "/\r|\n/", "", strip_tags(htmlspecialchars($this->row['group_name'])));?>';
	
	dojo.byId("receipt_no").innerHTML = '<?php echo preg_replace( "/\r|\n/", "", strip_tags(htmlspecialchars($this->row['invoice'])));?>'+" "+statusvoid;
	dojo.byId("lbl_for_date").innerHTML = '<?php echo preg_replace( "/\r|\n/", "", strip_tags(htmlspecialchars(date("d/m/Y",strtotime($this->row['date'])))));?>';
	dojo.byId("lbl_title_income").innerHTML = '<?php echo preg_replace( "/\r|\n/", "", strip_tags(htmlspecialchars($this->row['title'])));?>';
	dojo.byId("lbl_cate_income").innerHTML = '<?php echo preg_replace( "/\r|\n/", "", strip_tags(htmlspecialchars($this->row['cate_income'])));?>';
	dojo.byId("lbl_payment_method").innerHTML = '<?php echo preg_replace( "/\r|\n/", "", strip_tags(htmlspecialchars($this->row['payment_method'])));?>';
	dojo.byId("lbl_bank").innerHTML = '<?php echo preg_replace( "/\r|\n/", "", strip_tags(htmlspecialchars($this->row['bank_name'])));?>';

	dojo.byId("lbl_total_amount").innerHTML = symbal+'<?php echo preg_replace( "/\r|\n/", "", strip_tags(htmlspecialchars(number_format($this->row['total_amount'],2))));?>';
	dojo.byId("lbl_paid_amount").innerHTML = symbal+'<?php echo preg_replace( "/\r|\n/", "", strip_tags(htmlspecialchars(number_format($this->row['total_amount'],2))));?>';
	dojo.byId("lbl_cheqe_no").innerHTML = '<?php echo preg_replace( "/\r|\n/", "", strip_tags(htmlspecialchars($this->row['cheqe_no'])));?>';
	dojo.byId("lbl_description").innerHTML = '<?php echo preg_replace( "/\r|\n/", "", strip_tags(htmlspecialchars($this->row['description'])));?>';
	dojo.byId("user_sign").innerHTML = '<?php echo preg_replace( "/\r|\n/", "", strip_tags(htmlspecialchars($this->row['userName'])));?>';
}
										

function readMoneyInKhmer(netTotal){
	var str = netTotal.toString();
    str_cent = 'សេន';
	first_decimal = str.substr(-2);
	last_decimal = str.substr(-1);
    if(first_decimal>0){string='និង';}else{string="";str_cent=""}
	if(first_decimal!='00' && first_decimal<10 ){str_zero = "សូន្យ";}else{str_zero='';}
    first_money_decimal = read_in_khmer_from_10_to_99(first_decimal);
    last_money_decimal = read_in_khmer_from_0_to_9(last_decimal)
    money_khmer=read_money_in_khmer(netTotal);

    if(first_decimal>0){string_en='និង';}else{string_en="";str_cent_en=""}
	if(first_decimal!='00' && first_decimal<10 ){str_zero_en = "Zero";}else{str_zero_en='';}
    first_money_decimal_en = read_in_english_from_10_to_99(first_decimal);
    last_money_decimal_en = read_in_english_from_0_to_9(last_decimal)
    money_english=read_money_in_english(netTotal);
    read_eng = money_english.trim()+string+ first_money_decimal+str_zero+last_money_decimal+'ដុល្លារគត់'

    read_eng = '( '+money_english.trim()+string_en+ first_money_decimal_en+str_zero_en+last_money_decimal_en+' Dollar Only )'
    dojo.byId("lbl_moneykhmer").innerHTML = money_khmer.trim()+string+ first_money_decimal+str_zero+last_money_decimal+'ដុល្លារគត់'+read_eng
}

function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
}
function hideleft(){
	(dojo.style("leftmenu","display") == "none") ? 'show':'hide'();
}
function preview()
{ 
  var disp_setting="toolbar=no,status=no,resizable=no,location=no,directories=yes,menubar=no,"; 
      disp_setting+="scrollbars=no,fullscreen=yes, height=700, left=100, top=25"; 
  var content_vlue = document.getElementById("divPrint").innerHTML; 
  var docprint=window.open("","",disp_setting); 
   docprint.document.open(); 
   docprint.document.write('<html><head>'); 
   docprint.document.write('</head><div style=" font-size:16px !important; margin:0px; font-family:Verdana;"><style>table th {font-size:14px !important;} table td{font-size:12px !important;}</style><center>');          
   docprint.document.write(content_vlue);          
   docprint.document.write('</center></div></html>'); 
   docprint.document.close(); 
   docprint.focus(); 
}
function exportExcel(){
	$('#exportExcel').tableExport({type:'excel',escape:'false'});
}
</script>