<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('SERVICE_CHARGE_RPT')); 
	$frm = $this->form_search;
	$classHideHeight=classHideHeight;
?>	
<div class="layout-wrapper-report">
	<div id="mainContent" class="main-content-report">
		<div class="report-preview">
			<?php echo $this->controlReport?>
			<div id="main-viewer" class="main-viewer portrait">
				<div id="viewer" class="viewer portrait">
					<div id="divPrint" class="content">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style.css">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style-screen.css">
						<style>
							@media print {
								<?php if(!empty($this->printFormat)){ echo $this->printFormat; } ?>
								.hide{visibility: visible; height: <?php echo $classHideHeight;?>;}
							}
						</style>
						<table style="margin: 0 auto; white-space: nowrap;width: 100%">
							<tr>
								<td colspan="3"><?php echo $this->rsheader;?></td>
							</tr>
							<tr>
								<td width="15%" align="center">
								</td>
								<td width="70%" align="center">
									<strong style="font-weight:normal;color:#000; font-size: 14px;font-family:Times New Roman,'Khmer OS Muol Light';"><?php echo $tr->translate('SERVICE_CHARGE_RPT');?></strong><br />
								</td>
								<td width="15%" align="center">
								</td>
							</tr>
							
							<tr>
								<td colspan="3" id="exportExcel">
									<table cellpadding="2" class="content-data text-color-black text-h16px text-size-12px" width="100%" border="1" align="center"  >
										<thead>
											<tr class="style bg-ligt-blues text-bold" align="center">
												<td scope="col"><?php echo $tr->translate('N_O')?></td>
												<td scope="col" ><?php echo $tr->translate('BRANCH')?></td>
												<td scope="col"><?php echo $tr->translate('ACADEMIC_YEAR')?></td>
												<td scope="col"><?php echo $tr->translate('SERVICE_CATE')?></td>
												<td scope="col"><?php echo $tr->translate('SERVICE_NAME')?></td>
												<td scope="col"><?php echo $tr->translate('MONTHLY')?></td>
												<td scope="col"><?php echo $tr->translate('TERM')?></td>
												<td scope="col"><?php echo $tr->translate('SEMESTER')?></td>
												<td scope="col"><?php echo $tr->translate('YEAR')?></td>
												<td scope="col"><?php echo $tr->translate('ONE_PAYMENTONLY')?></td>
												<td scope="col"><?php echo $tr->translate('NOTE')?></td>
											</tr>
										</thead>
									<?php $i=0;if(!empty($this->rs))foreach ($this->rs AS $row) { $i++;?>
											<tr class="hover style"  align="center" >
												<td data-label="<?php echo $tr->translate("N_O");?>" ><?php echo $i;?></td>
												<td data-label="<?php echo $tr->translate("BRANCH");?>" ><?php echo @$row['branch_id'];?></td>
												<td data-label="<?php echo $tr->translate("ACADEMIC_YEAR");?>" ><?php echo @$row['academic'];?></td>
												<td data-label="<?php echo $tr->translate("SERVICE_CATE");?>" align="left" >&nbsp;&nbsp;<?php echo @$row['degree'];?></td>	
												<td data-label="<?php echo $tr->translate("SERVICE_NAME");?>" align="left" >&nbsp;&nbsp;<?php echo @$row['class'];?></td>	
												<td data-label="<?php echo $tr->translate("MONTHLY");?>" ><?php echo $row['monthly']>0? number_format(@$row['monthly'],2):"";?></td>
												<td data-label="<?php echo $tr->translate("TERM");?>" ><?php echo $row['quarter']>0? number_format(@$row['quarter'],2):"";?></td>
												<td data-label="<?php echo $tr->translate("SEMESTER");?>" ><?php echo $row['quarter']>0? number_format(@$row['semester'],2):"";?></td>
												<td data-label="<?php echo $tr->translate("YEAR");?>" ><?php echo $row['year']>0? number_format(@$row['year'],2):"";?></td>
												<td data-label="<?php echo $tr->translate("ONE_PAYMENT");?>" ><?php echo $row['one_payment']>0? number_format(@$row['one_payment'],2):"";?></td>
												<td data-label="<?php echo $tr->translate("NOTE");?>" ><?php echo @$row['remark'];?></td>
											</tr>
									<?php }?>	
									</table>	
								</td>
							</tr>
							<tr>
								<td colspan="3" width="100%" >
									<?php echo $this->rsfooteracc;?>
								</td>
							</tr>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="right-panel-report" id="rightPanel">
		<div class="card-box">
			<div class="card-search-head col-sm-12 border-botom">
				<div class="col-sm-6 text-left pd-0">
					<h4 class="m-b-0">
						<?php echo $tr->translate("SEARCH");?> 
						<i class="fa fa-search "></i> 
					</h4>
				</div>
				<div class="col-sm-6 text-right pd-0">
					<button onclick="closeRightPanel()" title="<?php echo $tr->translate("CLOSED");?> " class="btn-close">
						<i class="fa-solid fa-xmark"></i>
					</button>
				</div>
			</div>
			<form  id='foundation_class' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
				<div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<input dojoType="dijit.form.TextBox" class="fullside" id="txtsearch" name="txtsearch" placeholder="<?php echo $tr->translate("SEARCH");?>" value="<?php echo $this->search['txtsearch'];?>" type="text">
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement('branch_id')?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<input id="academic_year" />
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement('degree_bac')?>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement('grade_all')?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement('finished_status')?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<button class="button-class button-primary fullside" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
				</div>
			</form>	
	
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script src="<?php echo $this->baseUrl();?>/admin/js/global.js"  type="text/javascript"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");  
	
	var academic_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
	dojo.ready(function(){
		new dijit.form.FilteringSelect({
			store: academic_store,
			queryExpr: "*${0}*",
			autoComplete: false,                     
			required: false,                     
			id: "academic_year",
			name: "academic_year",
			class: "fullside", 		
			placeHolder:"<?php echo $tr->translate("SELECT_ACADEMIC_YEAR");?>",          
			onChange: function() {  
				
			}
		}, "academic_year");
		getAllAcademicByBranch();
		
		var branch_id = dijit.byId('branch_id');
		branch_id.on('change', function(evt) {
			getAllAcademicByBranch();
		});
		
		setTimeout(function() {
			setPrintOrientation('portrait');
		}, 500);
	});
	
	url_getacademic= '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'get-academicyear'));?>';
	var oldBranch = "<?php echo $this->search['branch_id']?>";
	function getAllAcademicByBranch(){
		dijit.byId('academic_year').reset();
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id=='' || branch_id==-1){
			var academic_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
			dijit.byId('academic_year').set('store',academic_store);  
			dijit.byId('branch_id').focus();
			return false;
		}
		
		contentData = {
			'branch_id':branch_id
		}
		selectedId = '';
		if(oldBranch==branch_id){
			selectedId = '<?php echo $this->search['academic_year']?>';
		}
		getAllYear(url_getacademic,contentData,selectedId);
		
	}
</script>