<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('RPT_OTHER_INCOME')); 
	$frm=$this->form_search;
	$classHideHeight=classHideHeight;
	
	$recordOrdering = empty($this->search['recordOrdering']) ? 1 : $this->search['recordOrdering'];
	$columnTitleRecord = $tr->translate('INCOME_CATEGORY');
	if($recordOrdering==2){
		$columnTitleRecord = $tr->translate('PAYMENT_METHOD');
	}
	$dateFormat ="d/m/Y";
	$dateFormatExp ="d/M/Y";
?>
<style>
.hover:hover{ background:#ccc;}
table.content-data tr.style-head,
table.tb-footer tr.style-head {
   font-weight: bold !important;
}
.hideprintdate{display:none !important;font-size:8px !important;}
</style>	
<div class="layout-wrapper-report">
	<div id="mainContent" class="main-content-report">
		<div class="report-preview">
			<?php echo $this->controlReport?>
			<div id="main-viewer" class="main-viewer portrait">
				<div id="viewer" class="viewer portrait">
					<div id="divPrint" class="content">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style.css">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style-screen.css">
						<style>
							@media print {
								<?php if(!empty($this->printFormat)){ echo $this->printFormat; } ?>
							}
						</style>
						<table width="100%" style="margin: 0 auto; ;white-space: nowrap;width: 100%">
							<tr>
								<td colspan="3"><?php echo $this->rsheader;?></td>
							</tr>
							<tr>
								<td width="20%" align="center">
								</td>
								<td width="60%" align="center">
									<span style="padding-left: 0px;  color:#000; font-size: 12px;font-family:'Times New Roman','Khmer OS Muol Light';"><?php echo $tr->translate('RPT_OTHER_INCOME')?></span><br />
									<lable style="font-size: 12px;font-family:'Times New Roman','Khmer OS Muol Light';" id="lbl_branch"></lable><br />
									<span style="color:#000; font-size: 12px;font-family:'Times New Roman','Khmer OS Muol Light';"><?php if(!empty($this->search['start_date'])){?>&nbsp; <?php echo date($dateFormat,strtotime($this->search["start_date"]))?> <?php echo $tr->translate('TO')?> <?php echo date($dateFormat,strtotime($this->search["end_date"]));}?></span>     
								</td>
								<td width="20%" align="center">
									
								</td>
							</tr>
							<tr>
								<td colspan="3" id="exportExcel">
									<table class="content-data text-color-black text-h14px text-size-11px" width="100%" border="1"  cellspacing="0" cellpadding="0">
										<thead>
											<tr class="styleheader bg-ligt-blues text-bold" align="center">
												<td rowspan="2" scope="col"><?php echo $tr->translate('N_O')?></td>
												<td rowspan="2" scope="col"><?php echo $tr->translate('BRANCH')?></td>
												<td colspan="3" scope="col"><?php echo $tr->translate('STUDENT_INFO')?></td>
												<td colspan="7" scope="col"><?php echo $tr->translate('INCOME_INFO')?></td>
											</tr>
											<tr class="styleheader bg-ligt-blues text-bold" align="center">
												<td scope="col"><?php echo $tr->translate('STUDENT_CODE')?></td>
												<td scope="col" class="w-px-120"><?php echo $tr->translate('STUDENT_NAME')?></td>
												<td scope="col"><?php echo $tr->translate('GROUP_CODE')?></td>
												
												<td scope="col"><?php echo $tr->translate('INCOME_TITLE')?></td>
												<td scope="col"><?php echo $tr->translate('RECEIPT_NO')?></td>
												<td scope="col" class="w-px-120"><?php echo $columnTitleRecord;?></td>
												
												<td scope="col"><?php echo $tr->translate('DATE')?></td>
												<td scope="col"><?php echo $tr->translate('TOTAL')?></td>
												<td scope="col" class="w-px-120"><?php echo $tr->translate('NOTE')?></td>
												<td scope="col"><?php echo $tr->translate('USER')?></td>
											</tr>
										</thead>
										
									<?php 
									
										$summaryInfoArray = array();
										
										$i=0; 
										$amtRc=1; 
										$gTotalIncome = 0;
										$bank = 0;
										$cash=0;
										$cheque=0;
										
										$recordCondiction="";
										$oldMethodTitle="";
										if(!empty($this->row)){ foreach ($this->row AS $kerIndex => $row) { 
											$i++;
											
											
											
											$columnTitleValue = $row['categoryTitle'];
											$headRecordTitle = $row['bank_name'];
											$thisRecordId = $row['bank_name'];
											if($recordOrdering==2){
												$thisRecordId=$row['categoryTitle'];
												$headRecordTitle = $row['categoryTitle'];
												
												$columnTitleValue = $row['bank_name'];
												if($row['payment_methodid']==1){
													$columnTitleValue = $row['payment_method'];
												}
											}else if($recordOrdering==1){
												if($row['payment_methodid']==1){
													$thisRecordId=$row['payment_methodid'];
													$headRecordTitle = $row['payment_method'];
												}
											}
											
									?>
										<?php if($thisRecordId != $recordCondiction ){
											
											if($kerIndex>0){ 
												$arryTotal = array(
													"methodTitle" =>$oldMethodTitle
													,"totalRecord" =>$amtRc-1
													,"totalPaidAmt" =>$totalPaidByMethod
												);
												array_push($summaryInfoArray, $arryTotal);
											
											?>
											<tr class="style total-row">
												<td colspan="9" align="right"><strong><?php echo $tr->translate("TOTAL")." ".$oldMethodTitle;?></strong></td>
											
												<td align="right"><strong><?php echo number_format($totalPaidByMethod,2);?></strong></td>
												<td colspan="2"></td>
											</tr>
											<?php } 
											$totalPaidByMethod=0;
											$amtRc=1;
											?>
											<tr>
												<td colspan="12" align="left" class="boldText"><?php echo $headRecordTitle;?></td>
											</tr>
										<?php } ?>
									
										<tr   <?php if ($row['status']==0){?>  style="background: #ffd9d9;"<?php }?> class="context-menu-one style hover" oncontextmenu="setrowdata(<?php echo $row['id'];?>);return false;">
											<td data-label="<?php echo $tr->translate("N_O");?>" align="center"><?php echo $i;?></td>
											<td data-label="<?php echo $tr->translate("BRANCH");?>"><?php echo $row['branch_name'];?></td>
											<td data-label="<?php echo $tr->translate("STUDETN_CODE");?>"><?php echo $row['stuCode'];?></td>
											<td data-label="<?php echo $tr->translate("STUDENT_NAME");?>">
												<span class="w-px-120 wrapcontent text-truncate"><?php echo $row['stuNameKh'];?>
												</span>
											</td>
											<td data-label="<?php echo $tr->translate("GROUP_CODE");?>"><?php echo $row['group_name'];?></td>
											
											<td data-label="<?php echo $tr->translate("INCOME_TITLE");?>">
												<?php echo $row['title'];?>
											</td>
											<td data-label="<?php echo $tr->translate("RECEIPT_NO");?>" align="center"><?php echo $row['invoice'];?></td>
											<td data-label="<?php echo $columnTitleRecord;?>" align="left">
												<span class="w-px-120 wrapcontent text-h12px text-size-10px"><?php echo $columnTitleValue;?></span>
											</td>	
											<td data-label="<?php echo $tr->translate("DATE");?>" align="center" class="hideExport"><?php echo date($dateFormat,strtotime($row['date']));?></td>
											<td data-label="<?php echo $tr->translate("DATE");?>" align="center" class="showExport" style="display:none;"><?php echo date($dateFormatExp,strtotime($row['date']));?></td>
											<td data-label="<?php echo $tr->translate("TOTAL");?>" class="bold" align="right"><?php echo number_format($row['total_amount'],2);?></td>
											<td data-label="<?php echo $tr->translate("NOTE");?>">
												<span class="text-h12px text-size-9px w-px-120 wrapcontent text-max-line3"><?php echo $row['description'];?></span>
											</td>
											<td data-label="<?php echo $tr->translate("USER");?>" align="center"><?php echo $row['byUser'];?></td>
										</tr>
										<?php 
											$amtRc++;
											if ($row['status']==1){
											
												$totalPaidByMethod = $totalPaidByMethod + $row['total_amount'];
												$gTotalIncome = $gTotalIncome + $row['total_amount'];
											}
											
											
											$recordCondiction=$row['bank_name'];
											$oldMethodTitle = $row['bank_name'];
											if($recordOrdering==2){
												$recordCondiction=$row['categoryTitle'];
												$oldMethodTitle = $row['categoryTitle'];
											}else if($recordOrdering==1){
												if($row['payment_methodid']==1){
													$recordCondiction=$row['payment_methodid'];
													$oldMethodTitle = $row['payment_method'];
												}
											}
										?>
										
									<?php }
									
										$arryTotal = array(
											"methodTitle" =>$oldMethodTitle
											,"totalRecord" =>$amtRc-1
											,"totalPaidAmt" =>$totalPaidByMethod
										);
										array_push($summaryInfoArray, $arryTotal);
									?>
										<tr class="style bg-ligt-blues text-bold">
											<td colspan="9" align="right"><strong><?php echo $tr->translate("TOTAL")." ".$oldMethodTitle;?></strong></td>
										
											<td align="right"><strong><?php echo number_format($totalPaidByMethod,2);?></strong></td>
											<td colspan="2"></td>
										</tr>
										<tr class="style bg-ligt-blues text-bold">
											<td colspan="9" align="right"><strong><?php echo $tr->translate("GRAND_TOTAL");?></strong></td>
											<td align="right"><strong><?php echo number_format($gTotalIncome,2);?></strong></td>
											<td colspan="2"></td>
										</tr>
									<?php }?>
									</table>
									<div style="display: flex; text-align: right;align-content: end;flex-wrap: wrap;flex-direction: column;margin-top: 10px; ">
										<table  class="content-data text-color-black text-h16px text-size-12px" style=" width:30%; text-align: center; margin: 0 auto;  border: 0;">
											<tr>
												<td colspan="4" align="center" class="bg-ligt-blues "><strong><?php echo $tr->translate("incomeSummary");?></strong></td>
											</tr>
											<tr class="text-bold">
												<td width="25%" align="right" style="white-space:nowrap;"><?php echo $tr->translate("GRAND_TOTAL");?></td>
												<td width="25%" align="right"><?php echo sprintf('%02d', count($this->row));?></td>
												<td width="25%" align="right">$</td>
												<td width="25%" align="right"><?php echo number_format($gTotalIncome,2);?></td>
											</tr>
											<?php if(!empty($summaryInfoArray)) foreach($summaryInfoArray as $sum){?>
											<tr class="text-bold">
												<td align="right" style="white-space:nowrap;"><?php echo $sum["methodTitle"];?></td>
												<td align="right" ><?php echo sprintf('%02d', $sum["totalRecord"]);?></td>
												<td align="right">$</td>
												<td align="right"><?php echo number_format($sum["totalPaidAmt"],2);?></td>
											</tr>
											<?php } ?>
										</table>
									</div>
								</td>
							</tr>
							<tr >
								<td colspan="3" width="100%">
									<?php echo $this->rsfooteracc;?>
								</td>
							</tr>
						</table>
					</div>	
				</div>	
			</div>	
		</div>	
	</div>	
	<div class="right-panel-report" id="rightPanel">
		<div class="card-box">
			<div class="card-search-head col-sm-12 border-botom">
				<div class="col-sm-6 text-left pd-0">
					<h4 class="m-b-0">
						<?php echo $tr->translate("SEARCH");?> 
						<i class="fa fa-search "></i> 
					</h4>
				</div>
				<div class="col-sm-6 text-right pd-0">
					<button onclick="closeRightPanel()" title="<?php echo $tr->translate("CLOSED");?> " class="btn-close">
						<i class="fa-solid fa-xmark"></i>
					</button>
				</div>
			</div>
			<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-other-income')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
				<div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<input dojoType="dijit.form.TextBox" class="fullside" id="txtsearch" name="txtsearch" placeholder="<?php echo $tr->translate("SEARCH");?>....." value="<?php echo $this->search['txtsearch'];?>" type="text">
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("branch_id");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("cate_income");?>
					</div>
					
				</div>
				<div class="form-group">
					<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm->getElement("start_date");?>
					</div>
					<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm->getElement("end_date");?>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm->getElement("receiptStatus");?>
					</div>
					<div class="col-md-6 col-sm-6 col-xs-12">
						<input id="userId" />
					</div>
				</div>
				<div class="form-group">
					
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("receipt_order");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("recordOrdering");?>
					</div>
				</div>
				
				<div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<button class="button-class button-primary fullside" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
				 </div>
			</form>	
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl();?>/admin/js/global.js" type="text/javascript"></script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.require("dijit.form.CheckBox"); 
dojo.ready(function(){
	new dijit.form.FilteringSelect({
		queryExpr: "*${0}*",
		autoComplete: false,                     
		required: false,                        
		id: "userId",
		name: "userId",  
		class: 'fullside',  
		placeHolder:"<?php echo $tr->translate("SELECT_USER");?>",          
		
	}, "userId");

	var branch_id = dijit.byId('branch_id');
	branch_id.on('change', function(evt) {
		 getAllStudentByBranch();
		 getAllUser();
	});
	getAllUser();
	
	setTimeout(function() {
		setPrintOrientation('landscape');
	}, 500);
	dojo.byId('lbl_branch').innerHTML = dijit.byId('branch_id').get('displayedValue');
});

function getAllUser(){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		dijit.byId('branch_id').focus();
		return false;
	}
	let url_user = '<?php echo $this->url(array('module'=>'rsvacl','controller'=>'user','action'=>'get-user')); ?>';
	contentData = {
			'branchId':branch_id
		}
		selectedId = '';
		if('<?php echo $this->search['branch_id']?>'==branch_id){
			selectedId = '<?php echo empty($this->search['userId']) ? 0 : $this->search['userId'];?>';
		}
		getAllUserByBranch(url_user,contentData,selectedId);
}
	
var row=0;
var url="";
$(function(){
	$.contextMenu({
		selector: '.context-menu-one', 
		callback: function(key, options) {
			var m = "clicked: " + key;
			if(key=="receipt"){
				url='<?php echo $this->baseUrl()."/allreport/accounting/reprint-other-income/id/";?>';
			}
			gotoAction();
		},
		items: {
			"receipt": {name: "<?php echo $tr->translate("RECEIPT");?>", icon: "fa-money", accesskey: "c"},
		}
	});
});
function setrowdata(index){
	row = index;
}
var recordid ='';
function gotoAction(){
	 window.open(url+row, '_blank');
}
</script>