<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('REPORT_STUDENT_SERVICE')); 
	$frm =  $this->form_search;
	$classHideHeight=classHideHeight;
	$dateFormat ="d/m/y";
	$nearlyPaymetySort = empty($this->search["nearlyPaymetySort"]) ? 1 : $this->search["nearlyPaymetySort"];
?>

<div class="layout-wrapper-report">
	<div id="mainContent" class="main-content-report">
		<div class="report-preview">
			<?php echo $this->controlReport?>
			<div id="main-viewer" class="main-viewer portrait">
				<div id="viewer" class="viewer portrait">
					<div id="divPrint" class="content">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style.css">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style-screen.css">
						<style>
							@media print {
								<?php if(!empty($this->printFormat)){ echo $this->printFormat; } ?>
							}
						</style>
						<table style="width:100%; white-space: nowrap;">
							<tr>
								<td colspan="3"><?php echo $this->rsheader;?></td>
							</tr>
							<tr>
								<td></td>
							</tr>
							<tr>
								<td width="15%" align="center"></td>
								<td align="center" width="70%">
									<strong style="font-weight:normal;font-family: Arial Black;color:#000; font-size: 12px;font-family:'khmer os muol light';"><?php echo $tr->translate('REPORT_STUDENT_SERVICE');?></strong><br />
									<span style="color:#000; font-size: 12px;font-family:'Times New Roman','Khmer OS Battambang';"><?php if(!empty($this->search['end_date'])){?><?php echo date('d-M-Y',strtotime($this->search['end_date']));}?>  </span>
								</td>
								<td width="15%">
								</td>				
							</tr>
							<tr>
								<td></td>
							</tr>
							<tr>
								<td colspan="3" id="exportExcel" >
									<?php if($nearlyPaymetySort == 1){?>
										<table cellpadding="2" class="content-data text-size-11px text-h16px text-color-black bd-dark-grey bd-solid bd-w1px" border="1"  >
											<thead>
												<tr class="text-bold bg-ligt-blues bd-t-w2px bd-t-dark-grey bd-t-solid bd-l-dark-grey" align="center" >
													<td class="bd-dark-grey bd-solid bd-w1px" rowspan="2"><?php echo $tr->translate("N_O"); ?></td>
													<td class="bd-dark-grey bd-solid bd-w1px" colspan="4"><?php echo $tr->translate("STUDENT_INFO"); ?></td>
													<td class="bd-dark-grey bd-solid bd-w1px" colspan="3"><?php echo $tr->translate("SERVICE_INFO"); ?></td>
													<td class="bd-dark-grey bd-solid bd-w1px" colspan="3"><?php echo $tr->translate("VALIDATE_INFO");?></td>
												</tr>
												<tr align="center" class="text-bold bg-ligt-blues bd-b-w2px bd-b-dark-grey bd-b-solid" >
													<td class="bd-dark-grey bd-solid bd-w1px"><?php echo $tr->translate("BRANCH"); ?></td>
													<td class="bd-dark-grey bd-solid bd-w1px"><?php echo $tr->translate("STUDENT_ID"); ?></td>
													<td class="bd-dark-grey bd-solid bd-w1px w-px-150"><?php echo $tr->translate("STUDENT"); ?></td>
													<td class="bd-dark-grey bd-solid bd-w1px w-px-90"><?php echo $tr->translate("TEL"); ?></td>
													<td class="bd-dark-grey bd-solid bd-w1px w-px-120"><?php echo $tr->translate("CATEGORY"); ?></td>
													<td class="bd-dark-grey bd-solid bd-w1px w-px-150" ><?php echo $tr->translate("SERVICE"); ?></td>
													
													<td class="bd-dark-grey bd-solid bd-w1px"><?php echo $tr->translate("START_DATE"); ?></td>
													<td class="bd-dark-grey bd-solid bd-w1px"><?php echo $tr->translate("VALIDATE"); ?></td>
													<td class="bd-dark-grey bd-solid bd-w1px"><?php echo $tr->translate("REMAIN_DAY")."/".$tr->translate("LATE"); ?>(Days)</td>
													
												</tr>
											</thead>
											<?php  
												$studentId="";
												$i=0;
												$totalpaid=0;
												$totalbalance=0; 
												if(!empty($this->row)){ 
													foreach ($this->row AS $key=> $row) { $i++;
													
													
													$end_dat=$row["endDate"];
													$total_day=strtotime($end_dat)-strtotime(date("Y-m-d"));
													$day=(int)($total_day/(60*60*24));
													$daylate =$day;
													$label = $tr->translate("REMAIN");
													$color = "#000";
													if($day>=0){
														$daylate = abs($day);
													}else{
														$label = $tr->translate("EXPIRED");
														$daylate =" ".abs($day);
														$color = "red";
													}
													
													$classTopRow="";
													$classBottomRow="";
													$stringFront="";
													if ($studentId != $row['studentId']) {
														$i++;
														$strFilter =  (string) $row['studentId'];
														$arrRow = $this->row;
														$resultOFStudent = array_filter($arrRow, function ($item) use ($strFilter) {
															if ($item['studentId'] == $strFilter) {
																return $item;
															}
															return;
														});
														
														$amtRecord = count($resultOFStudent);
														$amtRecord = ($amtRecord ==0) ? 1 : $amtRecord;
														$stuName = $row['stuNameKh'];
														$stuName = empty($stuName) ? $row['stuNameEn'] : $stuName;
														$stringFront='
															<td rowspan="'.$amtRecord.'" data-label="'.$tr->translate("N_O").'" align="center" >'.$i.'</td>
															<td class="bd-l-dark-grey bd-l-dashed bd-l-w1px" rowspan="'.$amtRecord.'" data-label="'.$tr->translate("BRANCH").'" align="left" >
															'.$row['branchName'].'
															</td>
															<td class="bd-l-dark-grey bd-l-dashed bd-l-w1px" rowspan="'.$amtRecord.'" data-label="'.$tr->translate("Student Id").'" align="center" >
															'.$row['stuCode'].'
															</td>
															
															<td class="bd-l-dark-grey bd-l-dashed bd-l-w1px" rowspan="'.$amtRecord.'" data-label="'.$tr->translate("Name").'" align="left" >
																<span class="w-px-150 wrapcontent">'.$stuName.'</span>
															</td>
															<td class="bd-l-dark-grey bd-l-dashed bd-l-w1px" rowspan="'.$amtRecord.'" data-label="'.$tr->translate("Tel").'" align="left" >
																<span class="w-px-120 wrapcontent">'.$row['tel'].'</span>
															</td>
														';
														if($key>0){
															$classTopRow="bd-t-dark-grey bd-t-solid bd-l-w1px";
														}
													}
											?>
												
												<tr  class="<?php echo $classTopRow." ".$classBottomRow;?> bd-b-dark-grey bd-b-dashed bd-b-w1px hover"   style="white-space:nowrap;">
													<?php echo $stringFront; ?>	
													<td data-label="<?php echo $tr->translate("CATEGORY");?>">
														<span class="text-truncate w-px-120">
															<?php echo $row['categoryTitle'];?>
														</span>
													</td>
													<td data-label="<?php echo $tr->translate("SERVICE");?>">
														<span class="text-truncate w-px-200">
															<?php echo $row['itemTitle'];?>
														</span>
													</td>
													<td data-label="<?php echo $tr->translate("START_DATE");?>" align="center">
													<?php echo date("d-M-y",strtotime($row['startDate']));?>  
													</td>
													<td data-label="<?php echo $tr->translate("VALIDATE");?>" align="center">
														<?php echo date("d-M-y",strtotime($row['endDate']));?>  
													</td>
												
													<td data-label="<?php echo $tr->translate("REMAIN_DAY");?>"  align="center" style="color: <?php echo $color;?>;">
														<?php echo $label;?> <span style="font-weight: bold;"><?php echo $daylate;?></span>
													</td>
												</tr>
											
												<?php $studentId =$row['studentId']; ?>	 								
											<?php }
												} ?>
										</table>
									<?php }else{?>
										<table cellpadding="2" class="content-data text-size-11px text-h16px text-color-black bd-dark-grey bd-solid bd-w1px" border="1"  >
											<thead>
												<tr class="text-bold bg-ligt-blues bd-t-w2px bd-t-dark-grey bd-t-solid bd-l-dark-grey" align="center" >
													<td class="bd-dark-grey bd-solid bd-w1px w-px-30" rowspan="2"><?php echo $tr->translate("N_O"); ?></td>
													<td class="bd-dark-grey bd-solid bd-w1px" colspan="5"><?php echo $tr->translate("STUDENT_INFO"); ?></td>
													<td class="bd-dark-grey bd-solid bd-w1px w-px-50" rowspan="2"><?php echo $tr->translate("STUDY_INFO");?></td>
													<td class="bd-dark-grey bd-solid bd-w1px" colspan="3"><?php echo $tr->translate("VALIDATE_INFO");?></td>
													
												</tr>
												<tr class="text-bold bg-ligt-blues bd-b-w2px bd-b-dark-grey bd-b-solid" align="center" >
													<td class="bd-dark-grey bd-solid bd-w1px w-px-60"><?php echo $tr->translate("BRANCH"); ?></td>
													<td class="bd-dark-grey bd-solid bd-w1px w-px-120"><?php echo $tr->translate("STUDENT_ID"); ?></td>
													<td class="bd-dark-grey bd-solid bd-w1px w-px-120"><?php echo $tr->translate("STUDENT"); ?></td>
													<td class="bd-dark-grey bd-solid bd-w1px w-px-40"><?php echo $tr->translate("SEX"); ?></td>
													<td class="bd-dark-grey bd-solid bd-w1px w-px-100"><?php echo $tr->translate("PHONE");?></td>
													
													<td class="bd-dark-grey bd-solid bd-w1px w-px-70"><?php echo $tr->translate("START_DATE"); ?></td>
													<td class="bd-dark-grey bd-solid bd-w1px w-px-70"><?php echo $tr->translate("VALIDATE"); ?></td>
													<td class="bd-dark-grey bd-solid bd-w1px w-px-70"><?php echo $tr->translate("REMAIN_DAY")."/".$tr->translate("LATE"); ?>(Days)</td>
													
												</tr>
											</thead>
										<?php  
											$serviceId="";
											$i=0;
											$totalpaid=0;
											$totalbalance=0; 
											if(!empty($this->row)){ 
												foreach ($this->row AS $row) { $i++;
												
												
												$end_dat=$row["endDate"];
												$total_day=strtotime($end_dat)-strtotime(date("Y-m-d"));
												$day=(int)($total_day/(60*60*24));
												$daylate =$day;
												$label = $tr->translate("REMAIN");
												$color = "#000";
												if($day>=0){
													$daylate = abs($day);
												}else{
													$label = $tr->translate("EXPIRED");
													$daylate =" ".abs($day);
													$color = "red";
												}
										?>
										
											<?php if($serviceId != $row['grade']){?>
											<tr class="bg-col-blue bd-b-w1px bd-b-dark-grey bd-b-solid bd-t-w1px bd-t-dark-grey bd-t-solid"  >
												<td  colspan="10" align="center">
													<?php echo $row['categoryTitle'];?>: <strong><?php  echo $row['itemTitle'];?></strong>
												</td>
											</tr>
											<?php } ?>
											<tr  class="hover context-menu-one bd-dark-grey bd-dashed bd-w1px"   style="white-space:nowrap;">
												<td class="bd-l-dark-grey bd-l-dashed bd-l-w1px" data-label="<?php echo $tr->translate("N_O");?>" align="center" ><?php echo $i;?></td>
												<td class="bd-l-dark-grey bd-l-dashed bd-l-w1px" data-label="<?php echo $tr->translate("BRANCH");?>"  >
													<?php echo $row['branchName'];?>
												</td>
												<td class="bd-l-dark-grey bd-l-dashed bd-l-w1px" data-label="<?php echo $tr->translate("STUDENT_ID");?>" align="center">
													<span class="text-truncate w-px-120"><?php echo $row['stuCode'];?></span>
												</td>
												<td class="bd-l-dark-grey bd-l-dashed bd-l-w1px" data-label="<?php echo $tr->translate("STUDENT_NAME");?>"   >
													<span class="text-truncate w-px-120 "><?php echo $row['stuNameKh'];?></span>
												</td>	
												<td class="bd-l-dark-grey bd-l-dashed bd-l-w1px" data-label="<?php echo $tr->translate("SEX");?>"  align="center" ><?php echo $row['sexTitle'];?></td>
												<td class="bd-l-dark-grey bd-l-dashed bd-l-w1px" data-label="<?php echo $tr->translate("PHONE");?>"  align="left">
													<span class="text-truncate w-px-120"><?php echo $row['tel'];?></span>
												</td>
												<td class="bd-l-dark-grey bd-l-solid bd-l-w1px" data-label="<?php echo $tr->translate("GROUP");?>"  align="left"  >
													<span class="text-bold"><?php echo $row['groupCode'];?> <span class="text-normal"><?php echo $row['academicYearTitle'];?></span></span>
												</td>
												
												<td class="bd-l-dark-grey bd-l-dashed bd-l-w1px" data-label="<?php echo $tr->translate("START_DATE");?>" align="center">
													<?php echo date("d-m-y",strtotime($row['startDate']));?>  
												</td>
												<td class="bd-l-dark-grey bd-l-dashed bd-l-w1px" data-label="<?php echo $tr->translate("VALIDATE");?>" align="center">
													<?php echo date("d-m-y",strtotime($row['endDate']));?>  
												</td>
											
												<td class="bd-l-dark-grey bd-l-dashed bd-l-w1px" data-label="<?php echo $tr->translate("REMAIN_DAY");?>"  align="center" style="color: <?php echo $color;?>;">
													<?php echo $label;?> <span style="font-weight: bold;"><?php echo $daylate;?></span>
												</td>
											</tr>
											<?php $serviceId =$row['grade']; ?>	 
											<?php }}?>	 
										</table>
									<?php } ?>					
								</td>
							</tr>
							<tr >
								<td colspan="3">
									<?php echo $this->rsfooteracc;?>
								</td>
							</tr>
						</table>	
					</div>	
				</div>	
			</div>	
		</div>	
	</div>
	<div class="right-panel-report" id="rightPanel">
		<div class="card-box">
			<div class="card-search-head col-sm-12 border-botom">
				<div class="col-sm-6 text-left pd-0">
					<h4 class="m-b-0">
					<?php echo $tr->translate("SEARCH");?> 
					<i class="fa fa-search "></i> 
					</h4>
				</div>
				<div class="col-sm-6 text-right pd-0">
					<button onclick="closeRightPanel()" title="<?php echo $tr->translate("CLOSED");?> " class="btn-close">
						<i class="fa-solid fa-xmark"></i>
					</button>
				</div>
			</div>
			<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-student-service')); if(!empty($this->inFrame)){ echo "?inFrame=true";} ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
				<div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("adv_search");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("branch_id");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("academic_year");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("multiDegree");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<input type="text" id="grade_all" />
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<select required="false" type="text" name="item" id="item" placeHolder="<?php echo $tr->translate('SELECT_CATEGORY');?>" class="fullside" dojoType="dijit.form.FilteringSelect"  autoComplete="false" queryExpr="*${0}*" onchange="getgradebyDegree();" >
							<option value="-1"><?php echo $tr->translate('SELECT_CATEGORY');?></option>
							<?php if(!empty($this->rs_type)){foreach ($this->rs_type as $rs){?>
							<option value="<?php echo $rs['id']?>" <?php if($rs['id']== $this->search['item']){echo "selected";}?>><?php echo $rs['name']?></option>
							<?php }}?>
						</select>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<input id="service" name="service" />
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("nearlyPaymetySort");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<button class="button-class button-primary" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
				</div>
			</form>	
		</div>	
	</div>	
</div>	
<script type="text/javascript">
$(function(){
	<?php if(!empty($this->search['multiDegree'])){ ?>
		var valSelectedList = <?php echo json_encode($this->search['multiDegree']); ?>;
		 $('#multiDegree').val(valSelectedList);
	<?php } ?>
	//$('#multiDegree').multiSelect('select', [1, 2]);

});
</script>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script src="<?php echo $this->baseUrl();?>/admin/js/global.js"  type="text/javascript"></script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.require("dijit.form.Textarea");
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.DateTextBox");
	
var academic_store= getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
var service_store = getDataStorefromJSON('id','name');

dojo.ready(function(){
	new dijit.form.FilteringSelect({
		store: service_store,
		autoComplete: false,
		queryExpr: "*${0}*",                     
		id: "service",
		name: "service",   
		required:false,        
		class: 'fullside',
		placeHolder:'<?php echo $tr->translate('SERVICE');?>',
		onChange: function() {  
		}
	}, "service");
	dojo.ready(function(){
		new dijit.form.FilteringSelect({
			queryExpr: "*${0}*",
			autoComplete: false,                     
			required: false,                        
			id: "grade_all",
			name: "grade_all",  
			class: 'fullside',  
			placeHolder:"<?php echo $tr->translate("SELECT_GRADE");?>",          
			onChange: function() {  
			}
		}, "grade_all");
		getallGrade();
	});
	
	 var branch_id = dijit.byId('branch_id');
	 branch_id.on('change', function(evt) {
		 getAllAcademicByBranch();
    });
	 getAllAcademicByBranch();
	 getgradebyDegree();
	 getallGrade();
	 dijit.byId('nearlyPaymetySort').set('value','<?php echo $nearlyPaymetySort; ?>'); 
	 <?php if(!empty($this->search['academic_year'])){ ?>
		dijit.byId('academic_year').set('value','<?php echo $this->search['academic_year']?>');  	
	<?php } ?>
	setTimeout(function() {
		setPrintOrientation('lanscape');
	}, 500);
});
	
var url_dept = '<?php echo $this->url(array('module'=>'global','controller'=>'grade','action'=>'get-grade')); ?>';
function getallGrade(){
	dept_id = $('#multiDegree').val();
	if(dept_id==null || !dept_id || dept_id.length === 0){
		return false;
	}
	dojo.xhrPost({
		url:url_dept,
		content:{
			'dept_id':JSON.stringify(dept_id),
			'noaddnew':1
			},
		handleAs:"json",
		load: function(data) {
			grade_store  = getDataStorefromJSON('id','name', data);
			dijit.byId('grade_all').set('store',grade_store);   
			dijit.byId('grade_all').attr('value','<?php echo $this->search['grade_all']?>');  
		},
		error: function(err) {
		}
	});
}
	
var oldItems = '<?php echo $this->search['item']?>';
var url_degree = '<?php echo $this->url(array('module'=>'global','controller'=>'grade','action'=>'get-grade')); ?>';
function getgradebyDegree(){
		dept_id = dijit.byId("item").get("value");
		if(dept_id==-1){
			return false;
		}
		dojo.xhrPost({
			url:url_degree,
			content:{
				'dept_id':dept_id,
				'noaddnew':1
				},
			handleAs:"json",
			load: function(data) {
				service_store  = getDataStorefromJSON('id','name', data);
				dijit.byId('service').set('store',service_store);  	
				//if(oldItems==dept_id){
					dijit.byId('service').set('value','<?php echo $this->search['service']?>');  	
				//}
			},
			error: function(err) {
			}
	});
}

</script>