<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$pageTitle = $tr->translate("RPT_INCOME_REPORT");
	echo $this->headTitle($pageTitle);
	
	$frm =  $this->form_search;
	$classHideHeight=classHideHeight;
	$dateFormat ="d/m/y";
	$dateFormatExpt ="d/M/Y";
	
	$parentCol = $this->parentCol;

	$countCol = count($parentCol);
	$dbAcc = new Allreport_Model_DbTable_DbAccountReport();
?>
<style>
	.hideprintdate {
		display: none !important;
	}
	.hover:hover {
		background: #ddd;
	}
</style>
<div class="layout-wrapper-report">
	<div id="mainContent" class="main-content-report">
		<div class="report-preview">
			<?php echo $this->controlReport?>
			<div id="main-viewer" class="main-viewer portrait">
				<div id="viewer" class="viewer portrait">
					<div id="divPrint" class="content">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style.css">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style-screen.css">
						<style>
							@media print {
								<?php if(!empty($this->printFormat)){ echo $this->printFormat; } ?>
							}
						</style>
						<table style="width:100%;">
							<tr>
								<td colspan="3"><?php echo $this->rsheader;?></td>
							</tr>
							<tr>
								<td width="15%" align="center"></td>
								<td align="center" width="70%">
									<div style="width:100%;margin-top: -25px;">
										<div class="text-h16px text-size-12px text-color-black" style="font-family: 'Times New Roman','Khmer OS Muol Light';">
											<?php echo $pageTitle; ?>
										</div>
										<div  class="setfontsize branchName"></div>
											<?php if(!empty($this->search["start_date"])){?>
										<div class="text-h14px text-size-10px text-color-black" style="margin-bottom:5px; font-family: 'Times New Roman', 'Khmer OS Muol Light'; "><?php echo date($dateFormat,strtotime($this->search["start_date"]))?> to <?php echo date($dateFormat,strtotime($this->search["end_date"]));?></div><?php }?>
									</div>
								</td>
								<td width="15%">
								</td>
							</tr>
							<tr>
								<td colspan="3" id="exportExcel" valign="top">
									<?php 
										$i=1;
										$summaryInfoArray = array();
											$oldLabelMethod="";
											$colspanTotal=$countCol;
											if($countCol>1){
												$colspanTotal=$countCol-1;
											}
													
											$paymentMethod="";
											$bankId="";
											
											$totalPaidByMethod=0;
											$totalCreditMemoByMethod=0;
											
											$gTutionTotal=0;
											$gTotalPaid=0;
											$gTotalCreditMemo=0;
											if(!empty($this->rowStDailyPmt)){
									 ?>
									<table class="content-data bd-dark-grey text-color-black text-h14px text-size-9px" width="100%" border="1" align="center">
										<thead>
											<tr class="styleheader bg-head text-bold" align="center">
												<td scope="col"><?php echo $tr->translate("No");?></td>
												<td scope="col" width="50px"><?php echo $tr->translate("Receipt No");?></td>
												<td scope="col" width="100px"><?php echo $tr->translate("Student Name");?></td>
												<td scope="col" width="50px"><?php echo $tr->translate("Paid Date");?></td>
												<td scope="col"><?php echo $tr->translate("Grade");?></td>
												<td scope="col"><?php echo $tr->translate("Type");?></td>
												<td scope="col"><?php echo $tr->translate("Tuition");?></td>
												<td scope="col"><?php echo $tr->translate("Discount");?></td>
												<?php if(!empty($parentCol)) foreach($parentCol AS $k =>$mainParent){?>
												<td scope="col" width="50px"><?php echo $mainParent["title"];?></td>
												<?php } ?>
												<td scope="col"><?php echo $tr->translate("Paid");?></td>
												<td scope="col"><?php echo $tr->translate("Method");?></td>
												<td scope="col"><?php echo $tr->translate("Note");?></td>
												<td scope="col"><?php echo $tr->translate("Teller");?></td>
											</tr>
										</thead>
										<tbody>
											<?php 
											foreach($this->rowStDailyPmt as $kerIndex => $rs){ 
												$i++; 
												$payTerm="";
												$tutionTotalFeeLabel="";
												$tutionFeeDisPer="";
												$tutionFeeDisAmt="";	
												
												$pmtDetailJson = json_decode($rs['pmtDetailJson'], TRUE);
											?>
											
												<?php 
													$strTotalByMethod="";
													$columnTypeStr="";
													if(!empty($parentCol)) foreach($parentCol AS $k =>$mainParent){ 
														$columnClass="";
														$expl = explode(',', $mainParent["listSubId"]);
														$totalPaymentLabel="";
														$totalPayment=0;
														$gTotalPayment = 0;
														if(!empty($pmtDetailJson)) foreach($pmtDetailJson as $detail){
															$category = empty($detail["category"]) ? 0 : $detail["category"];
															$keyIndex = in_array($category, $expl);
															if(in_array($category, $expl)) {
																$thisTotal= empty($detail["totalPayment"]) ? 0 : $detail["totalPayment"];
																$totalPayment = $totalPayment + $thisTotal;
																
															
																if($detail["itemType"]==1){
																	$tutionTotalFeeLabel=$detail["fee"];
																	$payTerm= empty($detail["payTermTitle"]) ?  $tr->translate("OTHER") :  $detail["payTermTitle"];
																	$tutionFeeDisPer=($detail["disPer"]>0) ?  str_replace(".00","",$detail["disPer"])."%" : "";
																	$tutionFeeDisAmt=($detail["disAmt"]>0) ? "+".$detail["disAmt"] : "";
																}
															}
															
														}
														$gTotalPayment = $gTotalPayment + $totalPayment;
														$totalPaymentLabel= empty($totalPayment) ? "" : number_format($totalPayment,2);
														if($totalPayment<0){
															$columnClass="text-color-red";
															$totalPaymentLabel = "(".number_format($totalPayment,2).")";
														}
														
														$currTotalMethod = empty($parentCol[$k]["totalByMethod"]) ? "" : number_format($parentCol[$k]["totalByMethod"],2);
														$strTotalByMethod.= '<td align="right"><strong>'.$currTotalMethod.'</strong></td>';
														if($paymentMethod !=$rs["pmtMethod"] || $bankId !=$rs["bankId"]){
															$parentCol[$k]["totalByMethod"] = 0;
														}
														$parentCol[$k]["totalByMethod"] = $parentCol[$k]["totalByMethod"] + $gTotalPayment;
														$parentCol[$k]["gTotal"] = empty($parentCol[$k]["gTotal"]) ? 0 : $parentCol[$k]["gTotal"];
														$parentCol[$k]["gTotal"] = $parentCol[$k]["gTotal"] + $gTotalPayment;
														
														
														$columnTypeStr.= '<td class="'.$columnClass.'" align="right" data-label="'.$mainParent["title"].'">'.$totalPaymentLabel.'</td>';
													}
												?>
													
												<?php 
													if($paymentMethod !=$rs["pmtMethod"] || $bankId !=$rs["bankId"]){
														$rowLabel = $rs["paymentMethodTitle"];
												?>
												<?php if($kerIndex>0){ 
												$arryTotal = array(
													"methodTitle" =>$oldLabelMethod
													,"totalRecord" =>$i-1
													,"totalCrediMemoAmt" =>$totalCreditMemoByMethod
													,"totalPaidAmt" =>$totalPaidByMethod
												);
												array_push($summaryInfoArray, $arryTotal);
												?>
												<tr class="style bg-grey-blues">
													<td colspan="7" align="right"><strong><?php echo $tr->translate("TOTAL")." ".$oldLabelMethod;?></strong></td>
													<td></td>
													<?php echo $strTotalByMethod;?>
													<td align="right"><strong><?php echo number_format($totalPaidByMethod,2);?></strong></td>
													<td></td>
													<td></td>
													<td></td>
												</tr>
												<?php } 
													$oldLabelMethod = $rowLabel;
													//reset
													
													$totalPaidByMethod=0;
													$totalCreditMemoByMethod=0;
													$i=1;
												?>
												<tr class="style">
													<td colspan="<?php echo 12+$countCol;?>" align="left"><strong><?php echo $rowLabel;?></strong></td>
												</tr>
												<?php }?>
												 <tr class="context-menu-one style hover" oncontextmenu="setrowdata(<?php echo $rs['paymentId'];?>,1);return false;" style="<?php if ($rs['isVoid']==1){echo "background: #ffd9d9;"; }?>" >
													<td data-label="<?php echo $tr->translate("No");?>" align="center"><?php echo $i;?></td>
													<td data-label="<?php echo $tr->translate("Receipt No");?>" class="bold" align="center"><?php echo $rs['receptNo']; ?></td>
													<td data-label="<?php echo $tr->translate("Student Name");?>" ><span class="text-truncate"><?php echo $rs['studentNameKh']; ?></span></td>
													<td data-label="<?php echo $tr->translate("Paid Date");?>" align="center" class="hideExport"><?php echo date($dateFormat, strtotime($rs['createDate'])); ?></td>
													<td data-label="<?php echo $tr->translate("Paid Date");?>" align="center" class="showExport" style="display:none;"><?php echo date($dateFormatExpt, strtotime($rs['createDate'])); ?></td>
													<td data-label="<?php echo $tr->translate("Grade");?>" align="center"><?php echo $rs['gradeTitle']; ?></td>
													<td data-label="<?php echo $tr->translate("Type");?>"><?php echo $payTerm;?></td>
													<td data-label="<?php echo $tr->translate("Tuition");?>" align="right"><?php echo $tutionTotalFeeLabel;?></td>
													<td data-label="<?php echo $tr->translate("Discount");?>" align="center"><?php echo $tutionFeeDisPer.$tutionFeeDisAmt;?></td>
													
													<?php echo $columnTypeStr; ?>
													<?php 
														$creditMemoLabel = "";
														
														if(!empty($rs['creditMemo'])){
															if($rs['creditMemo']>0){
																$creditMemoLabel = "(-".number_format($rs['creditMemo'],2).")";
															}
														}
														$paidAmount = $rs['paidAmt'];
														$paidAmountLabel = number_format($paidAmount,2);
														$paidClass="";
														if($paidAmount<0){
															$paidClass="text-color-red";
															$paidAmountLabel = "(".$paidAmountLabel.")";
														}		
													?>
													
													<td data-label="<?php echo $tr->translate("Paid");?>" align="right" class="<?php echo $paidClass;?>"><?php echo $paidAmountLabel; ?></td>
													<td data-label="<?php echo $tr->translate("Method");?>" align="center"><?php echo $rowLabel; ?></td>
													<td data-label="<?php echo $tr->translate("Note");?>"><span	class="noted text-truncate"><?php echo $rs['bankName'];echo !empty($rs['transactionNote'])?' ('.$rs['transactionNote'].')':''; ?></span></td>
													<td data-label="<?php echo $tr->translate("Teller");?>" ><?php echo $rs['byUserName'];?></td>
												</tr>
												
												<?php 
													if ($rs['isVoid']!=1){
													
														$totalPaidByMethod = $totalPaidByMethod + $paidAmount;
														$gTotalPaid = $gTotalPaid + $paidAmount;
													}
													
													$paymentMethod=$rs["pmtMethod"];
													$bankId=$rs["bankId"];
												?>
											<?php }
												$arryTotal = array(
													"methodTitle" =>$oldLabelMethod
													,"totalRecord" =>$i
													,"totalPaidAmt" =>$totalPaidByMethod
												);
												array_push($summaryInfoArray, $arryTotal);
											?>
												<tr class="style bg-grey-blues">
													<td colspan="7" align="right"><strong><?php echo $tr->translate("TOTAL")." ".$oldLabelMethod;?></strong></td>
													<td></td>
													<?php 
													$strGTotal="";
													if(!empty($parentCol)) foreach($parentCol AS $k =>$mainParent){ 
													$currTotalMethod = empty($mainParent["totalByMethod"]) ? "" : number_format($mainParent["totalByMethod"],2);
													$gTotal = empty($mainParent["gTotal"]) ? "" : number_format($mainParent["gTotal"],2);
													$strGTotal.= '<td align="right"><strong>'.$gTotal.'</strong></td>';
													?>
													<td align="right"><strong><?php echo $currTotalMethod;?></strong></td>
													<?php } ?>
													<td align="right"><strong><?php echo number_format($totalPaidByMethod,2);?></strong></td>
													<td></td>
													<td></td>
													<td></td>
												</tr>
												<tr class="style bg-head ">
													<td colspan="7" align="right"><strong><?php echo $tr->translate("GRAND_TOTAL");?></strong></td>
													<td></td>
													<?php echo $strGTotal;?>
													<td align="right"><strong><?php echo number_format($gTotalPaid,2);?></strong></td>
													<td></td>
													<td></td>
													<td></td>
												</tr>
										
										</tbody>
									</table>
									<div style="display: flex; text-align: right;align-content: end;flex-wrap: wrap;flex-direction: column;margin-top: 10px; margin-right:183px;">
										<table  class="content-data text-color-black text-h14px text-size-9px" style=" width:22%; text-align: center; margin: 0 auto; font-weight: bold; border: 0;">
											<tr>
												<td colspan="4" align="center" class="bg-head text-bold"><strong><?php echo $tr->translate("incomeSummary");?></strong></td>
											</tr>
											<tr>
												<td width="25%" align="right" style="white-space:nowrap;"><?php echo $tr->translate("GRAND_TOTAL");?></td>
												<td width="25%" align="right"><?php echo sprintf('%02d', count($this->rowStDailyPmt));?></td>
												<td width="25%" align="right">$</td>
												<td width="25%" align="right"><?php echo number_format($gTotalPaid,2);?></td>
											</tr>
											<?php if(!empty($summaryInfoArray)) foreach($summaryInfoArray as $sum){?>
											<tr>
												<td align="right"><?php echo $sum["methodTitle"];?></td>
												<td align="right"><?php echo sprintf('%02d', $sum["totalRecord"]);?></td>
												<td align="right">$</td>
												<td align="right"><?php echo number_format($sum["totalPaidAmt"],2);?></td>
											</tr>
											<?php } ?>
										</table>
									</div>
									<?php echo $this->rsfooteracc;?>
									<?php } ?>
								</td>
							</tr>
						</table>
					</div>	
				</div>	
			</div>	
		</div>	
	</div>
	<div class="right-panel-report" id="rightPanel">
		<div class="card-box">
			<div class="card-search-head col-sm-12 border-botom">
				<div class="col-sm-6 text-left pd-0">
					<h4 class="m-b-0">
						<?php echo $tr->translate("SEARCH");?> 
						<i class="fa fa-search "></i> 
					</h4>
				</div>
				<div class="col-sm-6 text-right pd-0">
					<button onclick="closeRightPanel()" title="<?php echo $tr->translate("CLOSED");?> " class="btn-close">
						<i class="fa-solid fa-xmark"></i>
					</button>
				</div>
			</div>	
			<form id='foundation_class' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
				<div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<input dojoType="dijit.form.TextBox" class="fullside" id="adv_search" name="adv_search" value="<?php echo $this->search['adv_search']?>"
							placeholder="<?php echo $tr->translate("SEARCH");?>" type="text">
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("branch_id");?>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm->getElement("degree");?>
					</div>
					<div class="col-md-6 col-sm-6 col-xs-12">
						<input id="grade_all" />
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm->getElement("start_date");?>
					</div>
					<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm->getElement("end_date");?>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("receipt_order");?>
					</div>
					<div class="form-group">
						<div class="col-md-12 col-sm-12 col-xs-12">
							<?php echo $frm->getElement("receiptStatus");?>
						</div>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<input id="userId" />
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<button class="button-class button-primary fullside"
							iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button"
							showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
				</div>
			</form>
		</div>	
	</div>	
</div>	
<script src="<?php echo $this->baseUrl();?>/js/help.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl();?>/admin/js/global.js" type="text/javascript"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore"); 
	dojo.require("dijit.form.CheckBox"); 
	
	dojo.ready(function(){
		new dijit.form.FilteringSelect({
			queryExpr: "*${0}*",
			autoComplete: false,                     
			required: false,                        
			id: "grade_all",
			name: "grade_all",  
			class: 'fullside',  
			placeHolder:"<?php echo $tr->translate("SELECT_GRADE");?>",          
			onChange: function() {  
			}
		}, "grade_all");
		
		new dijit.form.FilteringSelect({
			queryExpr: "*${0}*",
			autoComplete: false,                     
			required: false,                        
			id: "userId",
			name: "userId",  
			class: 'fullside',  
			placeHolder:"<?php echo $tr->translate("SELECT_USER");?>",          
			onChange: function() {  
			}
		}, "userId");

		var branch_id = dijit.byId('branch_id');
		branch_id.on('change', function(evt) {
			 getAllUser();
		});
		
		getallGrade();
		getAllUser();
		
		<?php if(!empty($this->search['receiptStatus'])){ ?>
		dijit.byId('receiptStatus').attr('value','<?php echo $this->search['receiptStatus']?>');
		<?php } ?>
		
		setTimeout(function() {
			setPrintOrientation('landscape');
		}, 500);
	});
	
	function getAllUser(){
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id=='' || branch_id==-1){
			$(".branchName").text("");
			dijit.byId('branch_id').focus();
			return false;
		}
		$(".branchName").text(dijit.byId("branch_id").attr('displayedValue'));
		let url_user = '<?php echo $this->url(array('module'=>'rsvacl','controller'=>'user','action'=>'get-user')); ?>';
		contentData = {
				'branchId':branch_id
			}
			selectedId = '';
			if('<?php echo $this->search['branch_id']?>'==branch_id){
				selectedId = '<?php echo $this->search['userId']?>';
			}
			getAllUserByBranch(url_user,contentData,selectedId);
	}
	
	var url_dept = '<?php echo $this->url(array('module'=>'global','controller'=>'grade','action'=>'get-grade')); ?>';
	function getallGrade(){
		dept_id = dijit.byId('degree').get('value');
		if(dept_id==''){return false;}
		dojo.xhrPost({
			url:url_dept,
			content:{
				'dept_id':dept_id,
				'noaddnew':1
				},
			handleAs:"json",
			load: function(data) {
				grade_store  = getDataStorefromJSON('id','name', data);
				dijit.byId('grade_all').set('store',grade_store);   
				dijit.byId('grade_all').attr('value','<?php echo $this->search['grade_all']?>');  
			},
			error: function(err) {
			}
		});
	}
	

	var row=0;
	var typereceipt=1;
	var url="";
	$(function(){
		$.contextMenu({
			selector: '.context-menu-one', 
			callback: function(key, options) {
				var m = "clicked: " + key;
				if(key=="receipt"){
					if(typereceipt==1){//Student Payment
						url='<?php echo $this->baseUrl()."/allreport/accounting/rptreceiptdetail/id/";?>';
					}else if(typereceipt==2){//Other Income
						url='<?php echo $this->baseUrl()."/allreport/accounting/reprint-other-income/id/";?>';
					}else if(typereceipt==3){//Other Expense
						url='<?php echo $this->baseUrl()."/allreport/accounting/rpt-expensedetail/id/";?>';
					}
				}
				gotoAction();
			},
			items:{
				"receipt": {name: "<?php echo $tr->translate("RECEIPT");?>", icon: "fa-money-bill", accesskey: "c"},
			}
		});
	});
	function setrowdata(index,type){
		row = index;
		typereceipt = type;
	}
	var recordid ='';
	function gotoAction(){
		 window.open(url+row, '_blank');
	}
</script>