<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('RATING')); 
	$baseurl = $this->baseUrl();
?>
<style>
.dijitTextArea[cols].dijitTextArea[cols]{
	width: 99%;
}
.image-box {
    text-align: center;
    width: 215px;
    height: 110px;
}
.image-box img {
    width: 120px;
    height: 120px;
}

.button_browse {
    position: relative;
    overflow: hidden;
    text-align: center;
    width: 101%;
    height: 42px;
    background: #fbf9f9;
    border: 1px solid #e8e8e8;
}
.button_browse span {
    line-height: 33px;
    font-weight: 600;
    cursor: pointer;
}
input.btn_borwse_image {
    position: absolute;
    width: 100%;
    height: 38px;
    top: 0;
    left: 0;
    z-index: 2;
    opacity: 0;
    cursor: pointer;
}
.account-image {
    border: solid 1px #eee;
    width: 200px;
    margin: 0 auto;
}
</style>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="glyphicon glyphicon-stats" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('RATING');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<form  method="post" dojoType="dijit.form.Form" enctype="multipart/form-data">
			<script type="dojo/method" event="onSubmit">   
  				 if(this.validate()) {
					loadingBlock();
    				dijit.byId("save_close").attr("disabled",true);
					dijit.byId("save_new").attr("disabled",true);
   					 return true;
   				}else {
    				return false;
   				}
			</script>
			<div class="card-box">
				<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-stats"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("RATING");?></p>
										</div> 
									</div>

									<div class="form-group">
									   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("INPUT_RATING");?> <span class="required">*</span>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<input dojoType="dijit.form.ValidationTextBox" required="1" class="fullside" id="rating" name="rating" type="text">
									   </div>
									</div>
									<div class="col-md-12 col-sm-12 col-xs-12">
										&nbsp;
									</div>
									<div class="form-group">
										<label class="control-label  col-md-4 col-sm-4 col-xs-12" ><?php echo $tr->translate("EMOJI");?> </label>
										<div class="col-md-6 col-sm-6 col-xs-12">
											<?php 
												$images = $this->baseUrl().'/images/noimage.jpg';
											?>
											<input name="old_photo"  value="" type="hidden" />
											<div class="account-image"  >
												<div class="image-box">
													<img id="profile_wiew" src="<?php echo $images;?>" alt=""  />
												</div>
												<div class="button_browse">
												<div id='preview'></div>	
													<span>Upload <span ><i class="fa fa-camera" aria-hidden="true"></i></span></span>
													<input class="btn_borwse_image" type="file" id="emoji" name="emoji" />
												</div>
											</div>
										 </div>
									  </div>
									</div>
									<div class="clearfix"></div>
									<div class="card-box mt-20">
										<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
											<input type="button" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-remove"  value="save_close" name="save_close" id="save_close" label="<?php echo $tr->translate('SAVE_CLOSE');?>" dojoType="dijit.form.Button" />
											<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" value="save_new" name="save_new" id="save_new" label="<?php echo $tr->translate('SAVE_NEW');?>" dojoType="dijit.form.Button" />
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
	            </div>
	         </div>
		</form>
	</div>
</div>

<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script type="text/javascript">

	function readURL(input) {
	    if (input.files && input.files[0]) {
	        var reader = new FileReader();
	        
	        reader.onload = function (e) {
	            $('#profile_wiew').attr('src', e.target.result);
	        }
	        reader.readAsDataURL(input.files[0]);
	    }
	}
	var maxSize = 0;
	$("#emoji").change(function(){
		var iSize = ($("#emoji")[0].files[0].size / 1024); 
		
	    if (iSize / 1024 > 1) 
	    { 
	       if (((iSize / 1024) / 1024) > 1) 
	       { 
	           iSize = (Math.round(((iSize / 1024) / 1024) * 100) / 100);
	           alert('<?php echo $tr->translate("Image size more than 5Mb can not upload");?>');
	     	   maxSize = 1;
	           return false;
	       }else{ 
	           iSize = (Math.round((iSize / 1024) * 100) / 100);
	           if(iSize>5){
	               alert('<?php echo $tr->translate("Image size more than 5Mb can not upload");?>');
	         	   maxSize = 1;
	               return false;
	           }
	       } 
	    } 
	    else 
	    {
	       iSize = (Math.round(iSize * 100) / 100);
	       maxSize = 0;
	    }
	    maxSize = 0;
	    readURL(this);
	});

</script>
