<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate("CRM Daily Contact")); 
	echo $this->headTitle(''); 
	$frm_items= $this->frm_crm;
	$dateFormat ="d/m/Y";
	$dateFormatExp ="d/M/Y";
	$dbCrm = new Home_Model_DbTable_DbCRM();
?>	
<style>
.hover:hover{ background:#ccc;}

</style>
<div class="layout-wrapper-report">
	<div id="mainContent" class="main-content-report">
		<div class="report-preview">
			<?php echo $this->controlReport?>
			<div id="main-viewer" class="main-viewer portrait">
				<div id="viewer" class="viewer portrait">
					<div id="divPrint" class="content">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style.css">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style-screen.css">
						<style>
							.hide{visibility: hidden;}
							@media print {
								<?php if(!empty($this->printFormat)){ echo $this->printFormat; } ?>
								.hide{visibility: visible; height: <?php echo $classHideHeight;?>;}
							}
							div.know_by {
								margin-top:10px;
							}
							ul.know_by {
								margin: 0;
								padding: 0;
								width: 100%;
							}
							.know_by, label {
								font-family: 'Times New Roman', 'Khmer OS Battambang';
								font-size: 11px;
							}
							.know_by li {
								line-height: 15px;
							}
							.know_byitem {
								display: inline-table;
								width: 33%;
							}
							span.count-value {
								line-height: 14px;
								padding-left: 10px;
								font-weight: 600;
							}
						</style>
						<table  style="margin: 0 auto; width: 100%; ">
							<tr>
								<td colspan="3"><?php echo $this->rsheader;?></td>
							</tr>
							<tr>
								<td width="20%" align="right">
								</td>
								<td width="60%" align="center">
									<span style="color:#000; font-size: 12px;font-family:'Times New Roman','Khmer OS Muol Light';"><?php echo $tr->translate("CRM Daily Contact");?></span><br/>
									<span style="color:#000; font-size: 12px;font-family:'Times New Roman','Khmer OS Battambang';"><?php if(!empty($this->search['start_date'])){?><?php echo date($dateFormat,strtotime($this->search['start_date']));?> <?php echo $tr->translate("TO");?> <?php echo date($dateFormat,strtotime($this->search['end_date']));}?> </span>
								</td>
								<td width="20%" align="right"></td>
							</tr>
							<tr>
								<td colspan="3">
									<div id="exportExcel">
										<table class="content-data text-color-black text-h16px text-size-11px bd-dark-grey"  cellpadding="4" border="1" >
											<thead>
												<tr class="style-head text-bold bd-black bd-w1px style-head bg-head text-center" >
													<td scope="col"><?php echo $tr->translate("NUM");?></td>
													<td scope="col"><?php echo $tr->translate("BRANCH");?></td>
													<td scope="col"><?php echo $tr->translate("STUDENT_NAMEKHMER");?></td>
													<td scope="col"><?php echo $tr->translate("NAME_ENGLISH");?></td>
													<td scope="col"><?php echo $tr->translate("GENDER");?></td>
													<td scope="col"><?php echo $tr->translate("PHONE");?></td>
													<td scope="col"><?php echo $tr->translate("CONTACT_DATE");?></td>
													<td scope="col"><?php echo $tr->translate("FEEDBACK_OPTION");?></td>
													<td scope="col"><?php echo $tr->translate("FEEDBACK");?></td>
													<td scope="col"><?php echo $tr->translate("STATUS");?></td>
													<td scope="col"><?php echo $tr->translate("CONTACT_BY");?></td>
													<td scope="col">&nbsp;</td>
												</tr>
											</thead>
											<?php 
											$i=0;
											$followup=[]; 
											$total_student = 0;
											if(!empty($this->row)){ foreach ($this->row AS $row) { $i++;?>
											<tr class="style hover" align="center">
												<td data-label="<?php echo $tr->translate("NUM");?>"><?php echo $i;?></td>
												<td data-label="<?php echo $tr->translate("BRANCH");?>" align="left">&nbsp;<?php echo $row['branch_name'];?></td>
												<td data-label="<?php echo $tr->translate("STUDENT_NAMEKHMER");?>" align="left" >&nbsp;<?php echo $row['kh_name'];?>&nbsp;</td>
												<td data-label="<?php echo $tr->translate("NAME_ENGLISH");?>" align="left">&nbsp;<?php echo $row['last_name']." ".$row['first_name'];?>&nbsp;</td>
												<td data-label="<?php echo $tr->translate("GENDER");?>" align="center">&nbsp;<?php echo $row['sexTitle']; ?>&nbsp;</td>
												<td data-label="<?php echo $tr->translate("PHONE");?>" ><?php echo $row['tel'];?></td>
												<td data-label="<?php echo $tr->translate("CONTACT_DATE");?>" align="center" class="hideExport">&nbsp;<?php echo date($dateFormat,strtotime($row['contact_date']));?>&nbsp;</td>
												<td data-label="<?php echo $tr->translate("CONTACT_DATE");?>" align="center" class="showExport" style="display:none;">&nbsp;<?php echo date($dateFormatExp,strtotime($row['contact_date']));?>&nbsp;</td>
												<td data-label="<?php echo $tr->translate("FEEDBACK_OPTION");?>">
												<?php 
													$total_student = $total_student+1;
													$pre = explode(",", $row['feedback_type']);
														$prevCon="";
														if (!empty($pre)) foreach ($pre as $a){
															if(empty($a)){continue;}
															$title = $dbCrm->getTitleViewKeyCode($a,34);
															if (empty($prevCon)){
																$prevCon = $title;
															}else {
																if (!empty($title)){
																	$prevCon = $prevCon." , ".$title;
																}
															}
														}
														echo $prevCon;
												?>
												</td>
												<td data-label="<?php echo $tr->translate("FEEDBACK");?>" align="left"><?php echo $row['feedback'];?></td>
												<td data-label="<?php echo $tr->translate("NUM");?>" ><?php echo $row['crm_status_title'];
												$followup[$row['proccess']]=@$followup[$row['proccess']]+1;
												?></td>	
												<td data-label="<?php echo $tr->translate("STATUS");?>">&nbsp;<?php echo $row['user_contact_name'];?>&nbsp;</td>
												<td data-label="<?php echo $tr->translate("CONTACT_BY");?>">
													<a target="_blank" style="text-decoration: none;color:#000;" href="<?php echo $this->baseUrl();?>/allreport/allstudent/rpt-crm-detail/id/<?php echo $row['crm_id'];?>">
													<?php echo $tr->translate("DETAIL");?>
													</a>
												</td>	
											</tr>
										<?php }}?>	
										</table>	
									</div>	
								</td>
							</tr>
							<tr>
							<td colspan="3">
								<div class='know_by'>&nbsp;</div>
								<ul class='know_by'>
								<?php if(!empty($this->followup))foreach($this->followup as $key=> $rs){?>
									<li class='know_byitem'>
										<?php echo $rs."&nbsp;";?>
										<span class="count-value"><?php echo empty($followup[$key])?'0':$followup[$key];echo " ".$tr->translate('STUDENT_UNIT'); ?></span>
										</li>
								<?php }?>
									<li style="border-top:1.5px #000 dashed;;list-style-type: none;padding-top:5px;"><strong><?php echo $tr->translate("TOTAL_STUDENT").'&nbsp;'.$total_student." ".$tr->translate('STUDENT_UNIT');?></strong></li>
								</ul>
							</td>
						</tr>
							<tr >
								<td colspan="3" width="100%">
									<?php echo $this->rsfooterFoundation;?>
								</td>
							</tr>
					</table>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="right-panel-report" id="rightPanel">
		<div class="card-box">
			<div class="card-search-head col-sm-12 border-botom">
				<div class="col-sm-6 text-left pd-0">
					<h4 class="m-b-0">
						<?php echo $tr->translate("SEARCH");?> 
						<i class="fa fa-search "></i> 
					</h4>
				</div>
				<div class="col-sm-6 text-right pd-0">
					<button onclick="closeRightPanel()" title="<?php echo $tr->translate("CLOSED");?> " class="btn-close">
						<i class="fa-solid fa-xmark"></i>
					</button>
				</div>
			</div>
			<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
				 <div class="form-group">
                   	<div class="col-md-12 col-sm-12 col-xs-12">
				 		<?php echo $frm_items->getElement("advance_search");?>
				 	</div>
				 	<div class="col-md-12 col-sm-12 col-xs-12">
				 		<?php echo $frm_items->getElement("branch_search");?>
				 	</div>
				 	<div class="col-md-12 col-sm-12 col-xs-12">
				 		<input id="crm_list" />
				 	</div>
				 	<div class="col-md-12 col-sm-12 col-xs-12">
				 		<?php echo $frm_items->getElement("ask_for_search");?>
				 	</div>
				 	<div class="col-md-12 col-sm-12 col-xs-12">
				 		<?php echo $frm_items->getElement('status_search');?>
				 	</div>
				 </div>
				 <div class="form-group">
				 	<div class="col-md-12 col-sm-12 col-xs-12">
	                	<input value="<?php echo $this->search['feedback_type'];?>" type="text" id="e15" name="feedback_type" style="width: 100%">
	                </div>
				</div>
				 <div class="form-group">
					<div class="col-md-6 col-sm-6 col-xs-12">
				 		<?php echo $frm_items->getElement("start_date");?>
				 	</div>
				 	<div class="col-md-6 col-sm-6 col-xs-12">
				 		<?php echo $frm_items->getElement("end_date");?>
				 	</div>
				</div>
				 <div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
				 		<button class="button-class button-primary fullside" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
				 	</div>
				 </div>
			</form>
		</div>
	</div>
</div>
 <link href="<?php echo $this->baseUrl()."/admin"?>/3.5.0/select2.css" rel="stylesheet">
<script src="<?php echo $this->baseUrl()."/admin"?>/3.5.0/select2.min.js"></script>
 <?php 
 $tags="";
 if (!empty($this->feedback_type)) foreach ($this->feedback_type as $rs){
 	if (empty($tags)){
 		$tags = '"'.$rs['name'].'"';
 	}else{
 		if (!empty($rs['name'])){
 			$tags=$tags.',"'.$rs['name'].'"';
 		}
 	}
 }
?>
<script type="text/javascript">
require(["dojo/ready"], function(ready){
	ready(function(){
		 $("#e15").select2({tags:[<?php echo $tags;?>],placeholder: "<?php echo $tr->translate("FEEDBACK_OPTION");?>",allowClear: true});
	});
});
</script>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");    
var crm_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
dojo.ready(function(){
	new dijit.form.FilteringSelect({
		store: crm_store,
		queryExpr: "*${0}*",
		autoComplete: false,                 
		required: false,
		id: "crm_list",
		name: "crm_list",           
		class: "fullside", 
		placeHolder:"<?php echo $tr->translate('STUDENTTEST');?>",          
		onChange: function() {  
		}
	}, "crm_list");

	 var branch_id = dijit.byId('branch_search');
	 branch_id.on('change', function(evt) {
		 getCRMByBranch();
    });
	 getCRMByBranch();
	 
	setTimeout(function() {
		setPrintOrientation('portrait');
	}, 500);
});

url_getacademic= '<?php echo $this->url(array('module'=>'home','controller'=>'crm','action'=>'getcrmbybranch'));?>';
var oldBranch = "<?php echo $this->search['branch_search']?>";
function getCRMByBranch(){
	dijit.byId('crm_list').reset();
	branch_id = dijit.byId('branch_search').get('value');
	if(branch_id=='' || branch_id==-1){
		var crm_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('crm_list').set('store',crm_store);  
		dijit.byId('branch_search').focus();
		return false;
	}
	dojo.xhrPost({
		url: url_getacademic,
		content:{
			'branch_id':branch_id
			},
		handleAs:"json",
		load: function(data) {
			crm_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('crm_list').set('store',crm_store);  
		    if(oldBranch==branch_id){
		    	dijit.byId('crm_list').set('value','<?php echo $this->search['crm_list']?>');  
		    }
		},
		error: function(err) {
		}
	});
}
</script>