<?php
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();

	$school_khname = $tr->translate('SCHOOL_NAME');
	$school_name = $tr->translate('CUSTOMER_BRANCH_EN');
		
	$branch_id=1;
	$db = new Application_Model_DbTable_DbGlobal();
	$rs = $db->getBranchInfo($branch_id);
	if(!empty($rs)){
		$school_khname = $rs['school_namekh'];
		$school_name = $rs['school_nameen'];
	}
	$this->headTitle($tr->translate("SCAN_SHOUT_OUT")." | ".$school_khname); 
	echo $this->headTitle();
?>
<!DOCTYPE html>
<html>
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta name="apple-mobile-web-app-capable" content="yes" />
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<!-- Meta, title, CSS, favicons, etc. -->
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<link rel="shortcut icon" href="<?php echo $base_url;?>images/icon.ico" type="image/x-icon"/>	
		<link href="<?php echo $base_url."/templates/";?>plugin/bootstrap-4.3.1/css/bootstrap.min.css" rel="stylesheet">
		<link href="<?php echo $base_url."/templates/";?>plugin/bootstrap-4.3.1/css/bootstrap.css" rel="stylesheet">
		<link href="<?php echo $base_url;?>admin/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
		<link href="<?php echo $base_url;?>admin/build/css/custom.min.css" rel="stylesheet">
		<link href="<?php echo $this->baseUrl()."/templates/";?>plugin/webcodecamjs/css/style.css" rel="stylesheet">
		<script src="<?php echo $this->baseUrl()."/templates/";?>plugin/1.11.3/jquery.min.js"></script>
		<style>
			.logo span {
				color: #030b69 !important;
			}
			.profile-block img#stuImageProfile {
				width: 120px;
				height: 150px;
			}
			
			.inputScanner {
				position: absolute;
				width: 100%;
				z-index: 2;
			}
			.inputScanner input.inputScannerValue {
				width: 100%;
				background: none;
				height: 100%;
				border: none;
				color: #eee0;
				font-size: 20px;
				
			}

			.inputScanner {
				position: absolute;
				width: 100%;
				z-index: 7;
				top: 0;
				height: 100%;
			}
			
			.entranceTitle {
				position: absolute;
				z-index: 3;
				color: #ffd400;
				width: 100%;
				padding: 15px;
				top: 0;
				display: flex;
				justify-content: space-between;
				align-content: center;
				flex-wrap: nowrap;
			}
			span.titleTop {
				display: block;
				width: 100%;
				font-size: 30px;
				font-weight: 600;
			}
			span.titleTop.titleTopEn {
				font-size: 18px;
			}
			.youTubeBlog{
				background-image: url("<?php echo $this->baseUrl()."/images/scan-cover.jpg";?>");
				BACKGROUND-SIZE: cover;
				position: absolute;
				width: 100%;
				height: 100%;
				z-index: -5;
			}
			.shadow-cover {
				background: #17334b1a;
				height: 100%;
				width: 100%;
				margin: 0 auto;
				box-shadow: inset 0px 0px 30px 25px #17334b75;
				    position: absolute;
			}
			.profile_details {
				left: 170px !important;
			}
			video.video-display {
				width: 100%;
				height: auto;
			}
		</style>
	</head>
	<body>
		<?php 
			$videoPlayList="";
			if(!empty($this->playListRs)){
				foreach($this->playListRs AS $rsV){
					if(!empty($rsV['youtubeLink'])){
						$youTubeLink=$rsV['youtubeLink'];
						$step1=explode('v=', $youTubeLink);
						$step2 =explode('&',$step1[1]);
						$vedio_id = $step2[0];
						
						if(empty($videoPlayList)){
							$videoPlayList=$vedio_id;
						}else{
							$videoPlayList=$videoPlayList.",".$vedio_id;
						}
					}
				}
			}else{
				$youTubeLink="https://www.youtube.com/watch?v=1H_S_0IWsRc";
				$step1=explode('v=', $youTubeLink);
				$step2 =explode('&',$step1[1]);
				$vedio_id = $step2[0];
				$videoPlayList=$vedio_id;
			}
			
		?>
		<div class="youTubeBlog" >
			<div class="shadow-cover"></div>
			<video id="vid" class="video-display" controls autoplay muted loop>
			  <source src="<?php echo $this->baseUrl()."/images/scan-utility/scanning-adv.mp4";?>" type="video/mp4">
			</video>
			<!--
			<iframe src="http://www.youtube.com/embed/<?php //echo $vedio_id;?>?rel=0&amp;autoplay=1&mute=1&loop=1&playlist=<?php echo $videoPlayList;?>" frameborder="0" style="position:absolute;width:100%;height:100%;left:0"  allowfullscreen></iframe>
			-->
		</div>
		<div class="body-key mainCotentBlog">
			<div class="main-content-scan"  >
				<div class="row">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<div class="profile_details" >
							<div class="" style="position:relative;display: flex;width: 100%;height: 100vh;align-content: center;justify-content: center;flex-wrap: nowrap;align-items: center;">
								<div class="resume-wrap text-center">
									<div class="card-student-info">
										<?php 
											echo $this->render('bloglogo.phtml');
										?>
										<div class="resume-content">
											<div class="profile-block text-center">
												<?php 
													$photo = $this->baseUrl()."/images/no-profile.png";
													//$photo = $this->baseUrl()."/images/profile_202012021606875720.jpg";
												?>
											  <img id="stuImageProfile" src="<?php echo $photo;?>" alt="" class="img-circle img-responsive">
											</div>
											<p class="m-0"><span id="stuNameCode">009872</span></p>
											<h2 id="stuNameKh" class="m-0">កែវ សំណាង</h2>
											<h2 id="stuNameEng" class="m-0">KEO Samnang</h2>
											  
											<p ></p>
											<p class="m-0"><span >20-Jan-2025 10:00 AM</span></p>
											
											<div class="success-animation">
												<svg class="checkmark" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 52 52"><circle class="checkmark__circle" cx="26" cy="26" r="25" fill="none" /><path class="checkmark__check" fill="none" d="M14.1 27.2l7.1 7.2 16.7-16.8" /></svg>
											</div>
										</div>
									</div>
									<div class="footCard"></div>
									<div class="clearfix"></div>
								</div>
							</div>
						</div>
					</div>
							  
				</div>
			</div>
		</div>
	</div>
		<div class="entranceTitle">
			<div>
				<span id="settingTitle" class="titleTop"><?php echo $this->setting['title'];?></span>
				<span id="settingTitleEn" class="titleTop titleTopEn"><?php echo $this->setting['titleEn'];?></span>
			</div>
			<div>
				<span class="titleTop"><?php echo $this->row['titleKh'];?></span>
				<span class="titleTop titleTopEn"><?php echo $this->row['titleEn'];?></span>
			</div>
			<input type="hidden" id="gate" name="gate" value="<?php echo $this->row['id'];?>">
			<input type="hidden" id="settingId" name="settingId" value="">
			<audio id="success-audio" src="<?php echo $this->baseUrl().'/audio/utility/success.mp3';?>" type="audio/ogg"></audio>
			<audio id="failed-audio" src="<?php echo $this->baseUrl().'/audio/utility/faield.mp3';?>" type="audio/ogg"></audio>
		</div>
		<div class="inputScanner">
			<input type="text" class="inputScannerValue" id="sanningValue" name="sanningValue" value="">
		</div>					
	<link href="<?php echo $this->baseUrl()."/templates/";?>plugin/webcodecamjs/css/style.css" rel="stylesheet">
	<script type="text/javascript" src="<?php echo $base_url."/templates/";?>plugin/bootstrap-4.3.1/js/bootstrap.js"></script>
	<script type="text/javascript" src="<?php echo $base_url."/templates/";?>plugin/bootstrap-4.3.1/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="<?php echo $base_url."/templates/";?>plugin/custom.js"></script>
	<script>
	$(document).ready(function() {
		$('#sanningValue').focus();
		$('#sanningValue').keypress(function (e) {
		  if (e.which == 13) {
			  var sanningValue = $("#sanningValue").val();
			   if( sanningValue !="" ) {
					scanDo(sanningValue);
					$("#sanningValue").val("");
					$('#sanningValue').focus();
					return false;
			   }
		  }
		});
		
		$(".youTubeBlog").css("display", "block");
		$(".mainCotentBlog").css("display", "none");
		
		$("#sanningValue").dblclick(function(){
		  window.history.back();
		});
		document.getElementById('vid').play();
	});

	function scanDo(keyword){
		var urlgo = '<?php echo $this->url(array('module'=>'','controller' => 'extscan','action' => 'scanningcard'));?>';
		var settingId = $("#settingId").val();
		$.ajax({
			url: urlgo,
			data: 
			{
				keyword: keyword,
				gate: $("#gate").val(),
				settingId: settingId,
			},
			type: "POST",
			dataType: "json",
			success:function(data){
				if(data.content!=""){
					if(data.status==1){
						
						if( data.scanned !=0 ){
							$('#failed-audio').get(0).play();							
						}else{
							$('#success-audio').get(0).play();
						}
						$(".resume-content").html(data.content);
						$(".mainCotentBlog").fadeIn(500);
						
						$(".checkmark").hide();
						setTimeout(function () {
							$(".checkmark").show();
						}, 100);
					
					}else{
						$('#failed-audio').get(0).play();
						$(".resume-content").html(data.content);
						$(".mainCotentBlog").fadeIn(500);
					}
				}
				
				$("#settingTitle").html(data.settingInfo.title);
				$("#settingTitleEn").html(data.settingInfo.titleEn);
				$("#settingId").val(data.setting);
				setTimeoutReload();
			},
			error: function (error) {
				alert('error; ' + error);
			}

		});
	}
	
	function setTimeoutReload(){
		setTimeout(function () {
			$(".mainCotentBlog").fadeOut(500);
	    }, 4200);
	}
	</script>
	</body>
</html>