<?php
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();

	$school_khname = $tr->translate('SCHOOL_NAME');
	$school_name = $tr->translate('CUSTOMER_BRANCH_EN');
		
	$branch_id=1;
	$db = new Application_Model_DbTable_DbGlobal();
	$rs = $db->getBranchInfo($branch_id);
	if(!empty($rs)){
		$school_khname = $rs['school_namekh'];
		$school_name = $rs['school_nameen'];
	}
	$this->headTitle($tr->translate("SCAN_SHOUT_OUT")." | ".$school_khname); 
	echo $this->headTitle();
?>
<!DOCTYPE html>
<html>
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta name="apple-mobile-web-app-capable" content="yes" />
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<!-- Meta, title, CSS, favicons, etc. -->
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<link rel="shortcut icon" href="<?php echo $base_url;?>images/icon.ico" type="image/x-icon"/>	
		<link href="<?php echo $base_url."/templates/";?>plugin/bootstrap-4.3.1/css/bootstrap.min.css" rel="stylesheet">
		<link href="<?php echo $base_url."/templates/";?>plugin/bootstrap-4.3.1/css/bootstrap.css" rel="stylesheet">
		<link href="<?php echo $base_url;?>admin/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
		<link href="<?php echo $base_url;?>admin/build/css/custom.min.css" rel="stylesheet">
		<link href="<?php echo $this->baseUrl()."/templates/";?>plugin/webcodecamjs/css/style.css" rel="stylesheet">
		<script src="<?php echo $this->baseUrl()."/templates/";?>plugin/1.11.3/jquery.min.js"></script>
		<style>
		
		.overlay-front { display:none; position: fixed;width: 100%;height: 100%;top: 0px;left: 0px;background: #FCFCFC;z-index: 1001;opacity: 1;}
		.overlay-load-front{
				margin: auto;
				top: 0px;
				bottom: 0px;
				position: absolute;
				left: 0px;
				right: 0px;
				text-align: center;
				   background: #fff url("<?php echo $this->baseUrl()?>/templates/plugin/webcodecamjs/css/gif/psisloading.gif");
				      background-repeat: no-repeat;
					width: 200px;
					height: 200px;
					background-size: 100%;
		}
		
		.inputScanner {
			position: absolute;
			width: 100%;
			z-index: 2;
		}
		.inputScanner input.inputScannerValue {
			width: 100%;
			background: none;
			height: 100%;
			border: none;
			color: #eee0;
			font-size: 20px;
			
		}

		.inputScanner {
			position: absolute;
			width: 100%;
			z-index: 7;
			top: 0;
			height: 100%;
		}
		
		.entranceTitle {
			position: absolute;
			z-index: 3;
			color: #ffd400;
			width: 100%;
			padding:15px;
			top: 0;
		}
		span.titleEntrance {
			display: block;
			width: 100%;
			font-size: 30px;
			font-weight: 600;
		}
		span.titleEntrance.titleEntranceEn {
			font-size: 18px;
		}
		ul.list-unstyled{
			display:inline-block;
			width:49%;
			vertical-align: top;
		}
		ul.convidInfo li {
			line-height: 45px;
		}
		ul.convidInfo li.status span.titleStatus{
			display:inline-block;
			 min-width: 195px;
		}
		span.cicleStatus i {
			width: 45px;
			height: 45px;
			border-radius: 100%;
			color: #fff;
			padding: 12px;
			font-size: 20px;
			text-align: center;
			vertical-align: middle;
		}
		span.cicleStatus i.checked {
			background: #00950b;
		}
		span.cicleStatus i.unchecked {
			background: #dd0c0c;
		}
		
		
		.music-container{
    width: 100%;
    min-height: 100vh;
    display: grid;
    place-items: center;
}

.music-body{
    box-shadow: 0 20px 50px #3d11839f;
    background: #fff;
    padding: 1.3rem;
    border-radius: 1.5rem;
    position: relative;
    overflow: hidden;
}

.btn{
    outline: none;
    border: 0;
    background: #eee6fc;
    font-size: 0.9rem;
    color: #7D30FA;
    height: 2.188rem;
    width: 2.188rem;
    border-radius: 50%;
    cursor: pointer;
}

.top-icons{
    display: flex;
    justify-content: space-between;
    align-items: center;
}

.volume{
    z-index: 5;
}

.layer{
    z-index: 4;
    position: absolute;
    background:#ffff;
    border: 2px solid #eee6fc;
    height: 2.188rem;
    width: 17.5rem;
    left: 0;
    right: 0;
    margin: auto;
    top: 1.3rem;
    border-radius: 1.5rem;
    display: grid;
    place-items: center;
    visibility: hidden;
}
.volume-slider,.progress-bar{
    position: relative;
    width: 100%;
    height: 0.2rem;
    background: #eee6fc;
}

.volume-slider{
    width: 80%;
}

.volume-slider {
    right: -15px;;
}

.volume-slider .bar,.progress-bar .progress-line{
	display: block;
	width: 0;
	height: inherit;
	background-color: #7D30FA;
}

.volume-slider .bar{
    width: 100%;
}

.volume-slider .volumerange, .progress-bar .progress{
   width: 100%;
  -webkit-appearance: none;
  height: inherit;
  background: transparent;
  outline: none;
  position: absolute;
  top: 0;
  left: 0;
}

.volume-slider .volumerange::-webkit-slider-thumb,  .progress-bar .progress::-webkit-slider-thumb{
	-webkit-appearance: none;
	height: 0.7rem;
    width: 0.7rem;
	background-color: #7D30FA;
    border-radius: 50%;
    cursor: pointer;
}

/* volume range slider design end */

.layer.hide{
    visibility: visible;
}

.music-img{
    margin-top: 1rem;
    width: 100%;
    height: 15rem;
    overflow: hidden;
    border-radius: 1.4hrem;
}

.music-img img{
    object-fit: cover;
    height: 100%;
    width: 100%;
}

.music-info{
    text-align: center;
}

.music-info h2{
    font-size: 1rem;
    margin-top: 1rem;
    letter-spacing: 0.02rem;
    color: rgb(117, 116, 116);
    color: #7D30FA;
}

.music-progress{
    margin-top: 1rem;
}

.music-progress .progress-bar{
    background: #ebdfff;
    height: 0.2rem;
    width: 100%;
    margin-bottom: 0.4rem;
    position: relative;
}

.progress-bar{
    cursor: pointer;
}

.progress{
    background: #7D30FA;
    width: 0;
    height: 100%;
    position: relative;
}

.progress::before{
    content: "";
    position: absolute;
    height: 0.7rem;
    width: 0.7rem;
    border-radius: 50%;
    top: 50%;
    right: -5px;
    z-index: 2;
    transform: translateY(-50%);
    background: inherit;
    transition: all 0.1s ease;
}

.duration{
    display: flex;
    color: #7D30FA;
    justify-content: space-between;
}

.duration span{
    font-size: 0.7rem;
}

.music-controls{
    display: flex;
    justify-content: space-between;
    align-items: center;
}

.prevbtn, .nextbtn, .playpause{
    border: 0;
    outline: 0;
    font-size: 2rem;
    background: #fff;
    color: #7D30FA;
    cursor: pointer;
}

.prevbtn:hover, .nextbtn:hover{
    color: #5717be;
}


.playpause{
    font-size: 1.7rem;
    /* position: absolute; */
    background: #7D30FA;
    height: 4.5rem;
    width: 4.5rem;
    color: #fff;
    border-radius: 50%;
    display: grid;
    place-items: center;
}

.fa-play{
    position: relative; 
    display: inline-block;
    left: 0.1rem;
}



.main-controls{
    position: relative;
    /* border: 1px solid #b88ffa; */
    border-radius: 2rem;
    padding: 0.5rem 1rem;
    display: flex;
    justify-content: space-between;
    gap: 1.3rem;
}

.color{
    color: #fc00b0;
}

/* music list */

.list-close{
    background: none;
    font-size: 1.1rem;
    color: #ff1b1bf3;
    position: absolute;
    top: 0.4rem;
    right: 0.4rem;
}

.songs-list{
    position: absolute;
    width: 100%;
    height: 100%;
    background: #fff;
    top: 0;
    left: 0;
    z-index: 10;
    visibility: hidden;
}
.showlist{
    visibility: visible;
}

		</style>
	</head>
	<body>
		<div class="overlay-front">
			<div class="overlay-load-front">
			</div>
		</div>
		<?php 
			$videoPlayList="";
			if(!empty($this->playListRs)){
				foreach($this->playListRs AS $rsV){
					if(!empty($rsV['youtubeLink'])){
						$youTubeLink=$rsV['youtubeLink'];
						$step1=explode('v=', $youTubeLink);
						$step2 =explode('&',$step1[1]);
						$vedio_id = $step2[0];
						
						if(empty($videoPlayList)){
							$videoPlayList=$vedio_id;
						}else{
							$videoPlayList=$videoPlayList.",".$vedio_id;
						}
					}
				}
			}else{
				$youTubeLink="https://www.youtube.com/watch?v=1H_S_0IWsRc";
				$step1=explode('v=', $youTubeLink);
				$step2 =explode('&',$step1[1]);
				$vedio_id = $step2[0];
				$videoPlayList=$vedio_id;
			}
			
		?>
		<div class="youTubeBlog" >
			<!--<iframe src="http://www.youtube.com/embed/<?php echo $vedio_id;?>?rel=0&amp;autoplay=1&mute=1&loop=1&playlist=<?php echo $videoPlayList;?>" frameborder="0" style="position:absolute;width:100%;height:100%;left:0"  allowfullscreen></iframe>-->
		</div>
		<div class="container body-key mainCotentBlog">
			<div class="main_container">
				<?php 
					echo $this->render('bloglogo.phtml');
				?>
				<div class="main-content-scan"  >
					<div class="row">
							<div class="col-md-12 col-sm-12 col-xs-12">
								<div class="profile_details" >
									<div class="col-md-4 col-sm-4 col-xs-12 text-center">
										<?php 
											$photo = $this->baseUrl()."/images/no-profile.png";
											//$photo = $this->baseUrl()."/images/profile_202012021606875720.jpg";
										?>
									  <img id="stuImageProfile" src="<?php echo $photo;?>" alt="" class="img-circle img-responsive">
									  <div class="backImage">&nbsp;</div>
									</div>
									<div class="col-md-8 col-sm-8 col-xs-12" style="position:relative;">
										<div class="bg-style-drop" style="background: url(/camappgit/psst/public/images/logo.png);   background-repeat: no-repeat; background-size: 100%;"></div>
										<div class="resume-wrap">
											<div class="w-100">
												<div class="icon"><i class="fa fa-graduation-cap" aria-hidden="true"></i></div>
											</div>
											  <h2 id="stuNameKh"></h2>
											  <h2 id="stuNameEng"></h2>
											  <p><strong><?php echo $tr->translate("STUDENT_CODE")?>: </strong> <span id="stuNameCode"></span></p>
											  <ul class="list-unstyled">
												<li><i class="fa fa-graduation-cap"></i> <?php echo $tr->translate("ACADEMIC_YEAR")?>: <span id="academicYear"></span></li>
												<li><i class="fa fa-magic"></i> <?php echo $tr->translate("DEGREE")?>: <span id="stuDegree"></span></li>
												<li><i class="fa fa-building"></i> <?php echo $tr->translate("GRADE")?>: <span id="stuGrade"></span></li>
												<li><i class="fa fa-phone"></i> <?php echo $tr->translate("PHONE")?>: <span id="primaryPhone"></span></li>
											  </ul>
											  <ul class="convidInfo list-unstyled ">
												<li class="status"><span class="titleStatus"><?php echo $tr->translate("ការចាក់វ៉ាក់សាំង")?></span>: <span id="vaccineStatus" class="cicleStatus"><i class="fa fa-check checked"></i></span></li>
												<li class="status"><span class="titleStatus"><?php echo $tr->translate("ការធ្វើតេស្ដ Covid-19")?></span>: <span id="covidTestStatus" class="cicleStatus"><i class="fa fa-times unchecked"></i></span></li>
											  </ul>
											  <div class="clearfix"></div>
										</div>
									</div>
								</div>
							</div>
						   <div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="entranceTitle">
			<span class="titleEntrance titleEntrance"><?php echo $this->row['titleKh'];?></span>
			<span class="titleEntrance titleEntranceEn"><?php echo $this->row['titleEn'];?></span>
			<input type="hidden" id="entrance_id" name="entrance_id" value="<?php echo $this->row['id'];?>">
			<?php 
				$defaultAudio = $this->baseUrl()."/images/frontFile/audio/audio_202110221634878502.mp3";
				$welcomeAudio = $defaultAudio;
				$successAudio = $defaultAudio;
				$gradeAudio = $defaultAudio;
				$entranceAudioKh = $defaultAudio;
				$entranceAudioEn = $defaultAudio;
				$confirmedAudio=$defaultAudio;
				$denydAudio=$defaultAudio;
				
				if(!empty($this->row['soundFileKh'])){
					if (file_exists(PUBLIC_PATH."/images/frontFile/audio/".$this->row['soundFileKh'])){
						$entranceAudioKh = $this->baseUrl().'/images/frontFile/audio/'.$this->row['soundFileKh'];
					}
				}
				if(!empty($this->row['soundFile'])){
					if (file_exists(PUBLIC_PATH."/images/frontFile/audio/".$this->row['soundFile'])){
						$entranceAudioEn = $this->baseUrl().'/images/frontFile/audio/'.$this->row['soundFile'];
					}
				}
				
				if(!empty($this->data['confirmGetInAudio'])){
					if (file_exists(PUBLIC_PATH."/images/frontFile/audio/".$this->data['confirmGetInAudio'])){
						$confirmedAudio = $this->baseUrl().'/images/frontFile/audio/'.$this->data['confirmGetInAudio'];
					}
				}
				
				if(!empty($this->data['denyGetInAudio'])){
					if (file_exists(PUBLIC_PATH."/images/frontFile/audio/".$this->data['denyGetInAudio'])){
						$denydAudio = $this->baseUrl().'/images/frontFile/audio/'.$this->data['denyGetInAudio'];
					}
				}
			?>
			<audio id="welcomeAudio" src="<?php echo $welcomeAudio;?>" type="audio/ogg"></audio>
			<audio id="successAudio" src="<?php echo $successAudio;?>" type="audio/ogg"></audio>
			<audio id="confirmGetInAudio" src="<?php echo $confirmedAudio;?>" type="audio/ogg"></audio>
			<audio id="denydAudio" src="<?php echo $denydAudio;?>" type="audio/ogg"></audio>
		</div>
		<div class="inputScanner">
			<input type="text" class="inputScannerValue" id="SanningValue" name="SanningValue" value="">
		</div>

	 <div class="music-container">
			<div class="music-body">
				<div class="layer">
					<div class="volume-slider">
					<span class="bar"></span>
					<input type='range' min='0.01' max='1' value='1' step='0.01' class="volumerange"/>
					</div>
				</div>
				<div class="top-icons">
					<button class="volume btn" id="volume">
						<i id="volumeicon" class="fa fa-volume-up"></i>
					</button>
					<button class="list btn" id="list">
						<i class="fa fa-list"></i>
					</button>
				</div>
				<div class="music-img">
					<img src="<?php echo $this->baseUrl().'/images/frontFile/audio/audio_icon.png'; ?>" alt="song-images" id="img">
				</div>
				<div class="music-info">
					<h2 id="title">Welcome</h2>
				</div>
				<audio src="<?php echo $welcomeAudio;?>" id="audio"></audio>
				<div class="music-progress">
					<div class="progress-bar">
						<span class="progress-line"></span>
						<input type='range' min='0' max='100' value='0' class="progress" id="progress"/>
					</div>
					<div class="duration">
						<span class="current-time">00:00</span>
						<span class="duration-time">00:00</span>
					</div>
				</div>
				<div class="music-controls">
					<button class="repeat btn" id="repeat">
						<i class="fa fa-repeat"></i>
					</button>
					<div class="main-controls">
						<button class="prevbtn" id="prevbtn">
							<i class="fa fa-backward"></i>
						</button>
						<button class="playpause" id="playpause">
							<i id="playpause-btn"class="fa fa-play"></i>
						</button>
						<button class="nextbtn" id="nextbtn">
							<i class="fa fa-forward"></i>
						</button>
					</div>
					<button class="like btn" id="like">
						<i id="likeicon" class="fa fa-heart"></i>
					</button>
				</div>
				<div class="songs-list" id="songs-list">
					<button class="list-close btn" id="listclose">
						<i class="fa fa-times"></i>
					</button>
				</div>
			</div>
		</div>
	
	<link href="<?php echo $this->baseUrl()."/templates/";?>plugin/webcodecamjs/css/style.css" rel="stylesheet">
	<script type="text/javascript" src="<?php echo $base_url."/templates/";?>plugin/bootstrap-4.3.1/js/bootstrap.js"></script>
	<script type="text/javascript" src="<?php echo $base_url."/templates/";?>plugin/bootstrap-4.3.1/js/bootstrap.min.js"></script>
	<script>
	var urlpart = "<?php echo $this->baseUrl();?>";
	var urlgo = '<?php echo $this->url(array('module'=>'','controller' => 'index','action' => 'scanningcode'));?>';
	$(document).ready(function() {
		$('#SanningValue').focus();
		$('#SanningValue').keypress(function (e) {
		  if (e.which == 13) {
			  var sanningValue = $("#SanningValue").val();
			   if( sanningValue !="" ) {
					scanDo(sanningValue);
					$("#SanningValue").val("");
					$('#SanningValue').focus();
					return false;
			   }
		  }
		});
		$(".youTubeBlog").css("display", "none");
		$(".mainCotentBlog").css("display", "none");
		
		
		
	});

	function scanDo(keyword){
		loadSong(songs[songIndex]);
		setTimeout(function () {
	       playSong();
	    }, 700);
		return false;
		var entrance_id = $("#entrance_id").val();
		$.ajax({
			url: urlgo,
			data: {keyword: keyword,scantype: 1,entrance_id: entrance_id},
			type: "POST",
			dataType: "json",
			success:function(data){
				if(data.statusReturn==1){
					sourceUrl = data.fullUrlAudio;
					$("#successAudio").attr("src", sourceUrl);
					
					sourceGradeAudioUrl = data.fullUrlGradeAudio;
					$("#gradeAudio").attr("src", sourceGradeAudioUrl);
					
					sourceImgUrl = data.fullUrlProfile;
					$("#stuImageProfile").attr("src", sourceImgUrl);
					
					$( "#stuNameKh" ).html(data.stu_khname);
					$( "#stuNameEng" ).html(data.fullNameEng);
					$( "#stuNameCode" ).html(data.stu_code);
					$( "#academicYear" ).html(data.academic_year);
					$( "#stuDegree" ).html(data.degree);
					$( "#stuGrade" ).html(data.grade);
					$( "#primaryPhone" ).html(data.tel);
					
					$(".youTubeBlog").css("display", "none");
					$(".mainCotentBlog").css("display", "block");
					
					
					var stringCheck='<i class="fa fa-check checked"></i>';
					var stringUncheck='<i class="fa fa-times unchecked"></i>';
					
					$( "#vaccineStatus" ).html(stringUncheck);
					$( "#covidTestStatus" ).html(stringUncheck);
					
					if(data.is_vaccined==1){
						$( "#vaccineStatus" ).html(stringCheck);
					}
					if(data.is_covidTested==1){
						$( "#covidTestStatus" ).html(stringCheck);
					}
					
					if(data.is_vaccined==1 && data.is_covidTested==1){
						$('#confirmGetInAudio').get(0).play();
					}
					allowIn = false;
					if(data.is_vaccined==0 || data.is_covidTested==0){
						$('#denydAudio').get(0).play();
					}
					setTimeoutReload();
				}else{
					$(".youTubeBlog").css("display", "block");
					$(".mainCotentBlog").css("display", "none");
					
					sourceUrl = urlpart+'/images/frontFile/audio/no_sound.mp3';
					$("#successAudio").attr("src", sourceUrl);
					$('#successAudio').get(0).play();
				}
				hideloadingFront();
			}

		});
	}
	function loadingFront(){
		$(".overlay-front").css("display", "block");
	}
	function hideloadingFront(){
		setTimeout(function () {
	        $(".overlay-front").css("display", "none");
	    }, 700);
	}
	function setTimeoutReload(){
		setTimeout(function () {
			loadingFront();
	       $(".youTubeBlog").css("display", "block");
			$(".mainCotentBlog").css("display", "none");
			hideloadingFront();
	    }, 35000);
	}
	
	
	const img = document.querySelector("#img");
	const playPause = document.querySelector("#playpause");
	const playPauseBtn = document.querySelector("#playpause-btn");
	const audio = document.querySelector("#audio");
	const title = document.querySelector("#title");
	const prevBtn = document.querySelector("#prevbtn");
	const nextBtn = document.querySelector("#nextbtn");
	const progress = document.querySelector("#progress");
	const progressBar = document.querySelector(".progress-bar");
	const currTime = document.querySelector(".current-time");
	const totalDuration = document.querySelector(".duration-time");
	const volume = document.querySelector("#volume");
	const layer = document.querySelector(".layer");
	const volBar = document.querySelector(".bar");
	const progressLine = document.querySelector(".progress-line");
	const volumeRange = document.querySelector(".volumerange");
	const repeatBtn = document.querySelector("#repeat");
	const likeBtn = document.querySelector("#like");
	const likeIcon = document.querySelector("#likeicon");
	const songListBtn = document.querySelector("#list");
	const songList = document.querySelector("#songs-list");
	const listCloseBtn = document.querySelector("#listclose");
	// songs array

	let songs = [
	  {
		path: '<?php echo $welcomeAudio;?>',
		displayName: 'Welcome',
		artist: 'N/A',
		cover: "<?php echo $this->baseUrl().'/images/frontFile/audio/audio_icon.png'; ?>",
	  },
	  {
		path: '<?php echo $this->baseUrl().'/images/frontFile/audio/grade4Audio_202110221634878339.mp3'; ?>',
		displayName: 'Success',
		artist: 'N/A',
		cover: "<?php echo $this->baseUrl().'/images/frontFile/audio/audio_icon.png'; ?>",
	  },
	];

	// deafult song index 

	let songIndex = 0;

	// song default state

	let isPlaying = false;

	// song pause function

	function playSong(){
		
	  isPlaying = true;
	  playPauseBtn.classList.replace("fa-play","fa-pause");
	  audio.play();
	}

	// song play function

	function pauseSong(){
	  isPlaying = false;
	  playPauseBtn.classList.replace("fa-pause","fa-play");
	  audio.pause();
	}

	// loading songs

	function loadSong(song){
		img.src = song.cover;
		title.textContent = song.displayName;
		audio.src = song.path;
	};

	// previous song 

	function prevSong(){
	  songIndex--;
	  if(songIndex < 0){
		songIndex = songs.length - 1;
	  }
	  loadSong(songs[songIndex]);
	  playSong();
	}

	// next song

	function nextSong(){
	  songIndex++;
	  if(songIndex > songs.length-1){
		songIndex = 0;
	  }
	  loadSong(songs[songIndex]);
	  playSong();
	}

	function updateProgress(e){
	  if (isPlaying) {
		  console.log((songIndex+1)+"==="+songs.length);
		 
		
		const { duration, currentTime } = e.target;
		// Update progress bar width
		const progressPercent = (currentTime / duration) * 100;
		progress.value = progressPercent;
		progressLine.style.width = `${progressPercent}%`;
		if(progressPercent==100){
		  return nextSong();
		}
		// Calculate display for duration
		const durationMinutes = Math.floor(duration / 60);
		let durationSeconds = Math.floor(duration % 60);
		if (durationSeconds < 10) {
		  durationSeconds = `0${durationSeconds}`;
		}
		// Delay switching duration Element to avoid NaN
		if (durationSeconds) {
		  totalDuration.textContent = `${durationMinutes}:${durationSeconds}`;
		}
		// Calculate display for currentTime
		let currentMinutes = Math.floor(currentTime / 60);
		let currentSeconds = Math.floor(currentTime % 60);
		if (currentSeconds < 10) {
		  currentSeconds = `0${currentSeconds}`;
		}
		currTime.textContent = `${currentMinutes}:${currentSeconds}`;
		
		if( (songIndex+1) >= songs.length){
			if(currTime.textContent == totalDuration.textContent){
				pauseSong();
				songIndex=0;
				return false;
			}
		}
		
	  }
	}

	function progressSlide(e){
	  const { value } = e.target;
	  const progressTime = Math.ceil((audio.duration / 100) * value);
	  audio.currentTime = progressTime;
	  console.log(progressTime);
		if(!isPlaying) {
		  progressLine.style.width = `${value}%`;    
	   }
	}

	function volumeBar(){
	  layer.classList.toggle('hide');
	  setTimeout(()=>{
		if(layer.classList.contains("hide")){
		  layer.classList.remove("hide");
		}
	  }, 5000);
	}

	function setVolume(){
	  audio.volume = volumeRange.value;
	  const barWidth = (volumeRange.value/1)*100;
	  volBar.style.width = `${barWidth}%`;
	}

	function repeat(){
	  repeatBtn.classList.toggle('color');
	  const repeatBtnState = repeatBtn.classList.contains("color");
	  if(repeatBtnState){
		audio.loop = true;
		loadSong();
	  }else{
		audio.loop = false;
		loadSong();
	  }
	  
	}

	// function like(){
	//   likeBtn.classList.toggle('color');
	//   if(likeBtn.classList.contains("color")){
	//   likeIcon.classList.replace("far","fas");
	// }else{
	//   likeIcon.classList.replace("fas","far");
	// }}

	function like() {
	  if (likeBtn.classList.toggle('color')) {
		likeIcon.classList.replace('far', 'fas');
	  } else {
		likeIcon.classList.replace('fas', 'far');
	  }
	}

	function musicList(){
	  songList.classList.toggle("showlist");
	  listCloseBtn.addEventListener("click",()=>{
		songList.classList.remove("showlist");
	  })
	}


	playPause.addEventListener("click", () => (isPlaying ? pauseSong() : playSong())); 
	prevBtn.addEventListener("click",prevSong);
	nextBtn.addEventListener("click",nextSong);
	audio.addEventListener("timeupdate", updateProgress);
	progress.addEventListener("input", progressSlide);
	volume.addEventListener("click", volumeBar);
	volumeRange.addEventListener("input",setVolume);
	repeatBtn.addEventListener("click", repeat);
	likeBtn.addEventListener("click", like);
	songListBtn.addEventListener("click",musicList);
	</script>
	</body>
</html>