<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	
	$teacherInfo = $this->teacherInfo;
	$detail = json_decode($teacherInfo['jsonData'], TRUE);
	$teacherName = $teacherInfo['teacherNameKh'];
	$teacherNameEn = $teacherInfo['teacherNameEn'];
	$teacherNameKh = $teacherName;
	$teacherName = empty($teacherName) ? $teacherNameEn : $teacherName;
	
	echo $this->headTitle($tr->translate('TEACHER_INFO')." ".$teacherName);
	
	$dbGb = new Application_Model_DbTable_DbGlobal();
	$photo = $this->baseUrl() . "/images/user.png";
	if (!empty($rs['photo'])) {
		if (file_exists(PUBLIC_PATH . "/images/photo/" . $rs['photo'])) {
			$photo = $this->baseUrl() . '/images/photo/' . $rs['photo'];
		}
	}
?>
 <div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
			<div class="col-sm-12 border-botom">
				<div class="col-sm-8 pd-0">
					<h4 class="m-b-0"><i class="fa fa-suitcase" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('TEACHER_INFO');?> <strong><?php echo $teacherName;?></strong></h4>
				</div>
				<div class="col-sm-4 text-right pd-0">
					<span style="display: inline-block;">
						<a class="add-link addsign" href="<?php echo $this->baseUrl()?>/home/searchteacher">
						<i class="fa fa-arrow-circle-left" aria-hidden="true"></i>&nbsp;<?php echo $tr->translate("GO_BACK")?></a>
					</span>
				</div>
			</div>
		</div>
		<div class="card-box" style="padding: 0 10px;">
			<div class="row g-3">
				<div class="col-lg-2 col-md-2 col-sm-2 col-xs-12 ">
					<ul class="nav verticle-tab md-pills pills-primary nav-tab" role="tablist">
						<li class="nav-item active">
							<a class="nav-link " data-toggle="tab" href="#teacherProfile" role="tab" title="<?php echo $tr->translate("TEACHER_PROFILE");?>">
								<i class="fa fa-graduation-cap"></i> <?php echo $tr->translate("TEACHER_PROFILE");?>
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" data-toggle="tab" href="#appoinmentLetter" role="tab" title="<?php echo $tr->translate("APPOINTMENT_LETTER");?>">
							<i class="fa fa-newspaper-o ml-2"></i> <?php echo $tr->translate("APPOINTMENT_LETTER");?></a>
						</li>
					</ul>
				</div>
				<div class="col-lg-10 col-md-10 col-sm-10 col-xs-12 ">
					<div class="tab-content">
						<div role="tabpanel" class="tab-pane fade active in" id="teacherProfile" aria-labelledby="profile-tab">
							<div class="text-right">
								<a class="qButton print" href="#" title="<?php echo $tr->translate("PRINT");?>" onclick="doPrintProfle('divPrintProfile');" ><i class="fa fa-print" ></i></a>
								<a class="qButton print" href="#" title="<?php echo $tr->translate("PRINT");?>" onclick="downloadImage('divPrintProfile');" ><i class="fa fa-download" ></i></a>
							</div>
							<div class="card-box " id="divPrintProfile">
								<style>
									
									#divPrintProfile {
										width: 242mm;
										min-height: 296mm;
										font-family: 'Times New Roman', 'Khmer OS Battambang';
										margin: 0 auto;
									}
									.report-frame h2,
									.report-frame h3,
									.report-frame h4,
									.report-frame h5{
										margin:0 !important;
										padding:0 !important;
										color: #0c2276;
									}
									.report-frame {
										background-image: url('<?php echo $this->baseUrl()."/images/background/profile-bg.jpg";?>');
										background-position: center;
										background-repeat: no-repeat;
										background-size: cover;
										position: relative;
										display: inline-block;
										line-height: 24px;
										top: -37px;
										left: -4px;
										color: #0c2276;
										width: 210mm;
										min-height: 296mm;
										height: 296mm;
										font-family: 'Times New Roman', 'Khmer OS Battambang';
										margin: 0 auto;
										border: 1px solid #ccc;
									}
									table.content-data-profile td {
										padding: 10px;
										color: #0c2276;
									}
									img.d-block.profile-card {
										width: 148px;
										height: 150px;
										border-radius: 5px;
									}
									.teacherName{
										font-family: 'Times New Roman','Khmer OS Battambang';
										font-size:18px;
										font-weight:bold;
										line-height: 26px;
									}
									.teacherName.teacherNameKh{
										font-family: 'Times New Roman','Khmer OS Muol Light';
										font-size:18px;
										font-weight:normal;
										line-height: 26px;
									}
									.divided {
										width: 100%;
										height: 4px;
										background: #143b7c;
										margin: 20px 0;
										border-radius: 10px;
									}
									h3.section {
										font-size: 16px;
										line-height: 28px;
										margin-bottom: 5px !important;
										display: block;
										font-weight: bold;
									}
									h5.row-info {
										font-size: 14px;
										line-height: 22px;
										margin-bottom: 4px !important;
									}
									
									table.table-teaching {
										width: 100%;
										border-collapse: collapse;
										border: 2px #143b7c solid;
										margin-top: 15px;
										color: #0c2276;
									}
									table.table-teaching tr.headrow {
										background: #315796;
										color: #ffffff;
										text-align: center;
										
									}
									table.table-teaching tr.headrow td {
										color: #ffffff;
										text-align: center;
									}
									table.table-teaching td {
										padding: 3px;
										line-height: 18px;
										border: 1px #143b7c dashed;
									}
									
									@media print{
										@page{
											page: A4;
											margin:0;
											padding:0;
										}
										body {
											-webkit-print-color-adjust: exact; /* Ensures colors and backgrounds are printed */
											print-color-adjust: exact; /* Standard version for color printing */
										}
										.report-frame {
											background-image: url('<?php echo $this->baseUrl()."/images/background/profile-bg.jpg";?>');
											background-position: center;
											background-repeat: no-repeat;
											background-size: cover;
											position: relative;
											display: inline-block;
											line-height: 24px;
											top: -2px;
											left: -4px;
											color: #0c2276;
											width: 210mm;
											min-height: 296mm;
											font-family: 'Times New Roman', 'Khmer OS Battambang';
											margin: 0 auto;
										}
									}
									.padding-10{padding:20px 0px;}
									.semi-divided{
										border-bottom: 1px dashed #0c2276;
										margin: 20px 0;
									}
								</style>
								<div class="report-frame html-content-holder" style="margin: 0 auto; min-height: 296mm; padding: 0.5cm; width: 210mm;">
									
									<table class="content-data-profile" width="100%" > 
										<tr>
											<td rowspan="2" width="30%" align="center">
												<img src="<?php echo $photo; ?>" alt="user image" class="d-block profile-card">
											</td>
											<td align="right">
												<h5><?php echo $teacherInfo["teacherDeptTitle"]; ?></h5>
											</td>
										</tr>
										<tr>
											<td>
												<h3 class="teacherName teacherNameKh"><?php echo $teacherNameKh; ?> </h3>
												<h3 class="teacherName"><?php echo $teacherNameEn; ?></h3>
												<h5><?php echo $teacherInfo["teacherCode"]; ?></h5>
												<div class="divided"></div>
											</td>
										</tr>
										<tr>
											<td valign="top">
												<?php 
												$dobDate = new DateTime($teacherInfo["dob"]);
												$dobM =  $dobDate->format("m");
												$dobY =  $dobDate->format("Y");
												$dobD =  $dobDate->format("d");
			
												$monthDob = $dbGb->getMonthInkhmer($dobM);
												?>
												<h3 class="section"><?php echo $tr->translate("INFORMATION_TEACHER");?></h3>
												<h5 class="row-info"><?php echo $tr->translate("SEX");?> : <?php echo $teacherInfo["sexTitle"]; ?></h5>
												<h5 class="row-info"><?php echo $tr->translate("DOB");?> : <?php echo $dobD."-".$monthDob."-".$dobY; ?></h5>
												<h5 class="row-info"><?php echo $tr->translate("POB");?> : <?php echo $teacherInfo["pob"]; ?></h5>
												<h5 class="row-info"><?php echo $tr->translate("NATION");?> : <?php echo $teacherInfo["nation"]; ?></h5>
												<h5 class="row-info"><?php echo $tr->translate("NATIONALITY");?> : <?php echo $teacherInfo["nationality"]; ?></h5>

												<div class="semi-divided"></div>

												<h3 class="section"><?php echo $tr->translate("CONTACT");?></h3>
												<h5 class="row-info">&#9990; <?php echo $teacherInfo["tel"]; ?></h5>
												<h5 class="row-info">&#9993; <?php echo $teacherInfo["email"]; ?></h5>
												<h5 class="row-info">&#127968; <?php 
													if(!empty($teacherInfo["houserNo"])){ echo $tr->translate("NUMBER_HOME")." ".$teacherInfo["houserNo"];}
													if(!empty($teacherInfo["streetNo"])){ echo " ".$tr->translate("STREET")." ".$teacherInfo["streetNo"];}
													if(!empty($teacherInfo["villageName"])){ echo " ".$tr->translate("VILLAGE")." ".$teacherInfo["villageName"];}
													if(!empty($teacherInfo["communeName"])){ echo " ".$tr->translate("COMMUNE")." ".$teacherInfo["communeName"];}
													if(!empty($teacherInfo["districtName"])){ echo " ".$tr->translate("DISTRICT")." ".$teacherInfo["districtName"];}
													if(!empty($teacherInfo["provinceName"])){ echo " ".$tr->translate("PROVINCE")." ".$teacherInfo["provinceName"];}
													 ?>
												</h5>
												
												<div class="padding-10"></div>
												
												<h3 class="section"><?php echo $tr->translate("CONTACT_INFO_EXPER");?></h3>
												<h5 class="row-info"><?php echo $tr->translate("SKILL");?> : <?php echo $teacherInfo["skill"]; ?></h5>
												<h5 class="row-info"><?php echo $tr->translate("POSITION");?> : <?php echo $teacherInfo["position"]; ?></h5>
												
												<h3 class="section"><?php echo $tr->translate("CULTURE_LEVEL");?></h3>
												<h5><?php echo $teacherInfo["educationTitle"]; ?></h5>
											</td>
											<td valign="top">
												
												<h3 class="section"><?php echo $tr->translate("TEACHING_INFO");?> <?php echo $teacherInfo["academicYearTtitle"];?></h3>
												<table class="table-teaching">
													<tr class="headrow">
														<td width="50px"><?php echo $tr->translate("NUM");?></td>
														<td><?php echo $tr->translate("SUBJECT");?></td>
														<td><?php echo $tr->translate("CLASS");?></td>
													</tr>
												<?php if(!empty($detail)) foreach($detail as $k => $row){?>
													<tr>
														<td align="center"><?php echo $k+1;?></td>
														<td><?php echo "<strong>".$row["subj"]."</strong> ".$row["subjSho"]; ?></td>
														<td><?php echo $row["class"]; ?></td>
													</tr>
												<?php } ?>
												</table>
											</td>
										</tr>
									</table>
									<input type="hidden" id="title-0" name="title-0" value="<?php echo $teacherInfo["teacherCode"]; ?>">
								</div>
							</div>
						</div>
						<div class="tab-pane fade" id="appoinmentLetter" role="tabpanel">
							<iframe scrolling="auto" frameborder="0" src="<?php echo $this->baseUrl() . "/allreport/allstaff/appointment-letter?id=". $teacherInfo['teacherId']."&appointment_date=". date("d-m-Y")."&year_id=". $teacherInfo['academicYear']."&year_value=". $teacherInfo['academicYearTtitle']."&inFrame=true"; ?>" style="width:100%;height:100%;"></iframe>
						</div>
					</div>
				</div>
			</div>
		</div>
		
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/admin/js/extra-plug.js"></script>
<script type="text/javascript">
dojo.require("dijit.form.CheckBox"); 
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.DateTextBox");
	
	function doPrintProfle(keyid) {
		window.frames["print_frame"].document.body.innerHTML=dojo.byId(keyid).innerHTML;
	    window.frames["print_frame"].window.focus();
	    window.frames["print_frame"].window.print();
	}
	
	function downloadImage(keyid){
		loadingBlock();
		createAbsoluteHidden();
		
		var data = dojo.byId(keyid).innerHTML
		//$("#cam-app-absolute").html(data);
		setTimeout(function() {
			let pages = document.querySelectorAll('.html-content-holder');
			var index=0;
			for (let node of pages) { 
				captureAndDownloadImage(node,index,"teacher-profile");
				index++;
			}
		}, 500);
					
		setTimeout(function() {
			HideloadingBlock();
		}, 700);
		
	}
</script> 