<?php
	$request = Zend_Controller_Front::getInstance ()->getRequest ();
	
	$tr = Application_Form_FrmLanguages::getCurrentlanguage ();
	echo $this->headTitle($tr->translate('CUTSTOCK'));
	$frm = $this->frm_payment;
	$urlEdit = $this->baseUrl()."/stock/cutstock/edit/id/";
	$urlVoid = $this->baseUrl()."/stock/cutstock/void/id/";
	$urlreceipt = $this->baseUrl()."/stock/cutstock/receipt/id/";
?>
<meta charset="utf-8">
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa-solid fa-boxes-stacked" ></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('CUTSTOCK');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<div class="card-box">
			<form action="" dojoType="dijit.form.Form" method="post">
				<script type="dojo/method" event="onSubmit">			
					if(this.validate()) {
							start_date = dijit.byId('start_date').get('value');
							if(start_date==null){
								alert("<?php echo $tr->translate("PLEASE_SELECT_START_DATE");?>");
								dijit.byId("start_date").focus();
								return false;
							}
							loadingBlock();
							return true;
					} else {
						return false;
					}
				</script>

				<div class="form-group">
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("adv_search");?>
                   </div>
				   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("branch_id");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<input id="student_id" />
                   </div>
				   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("cut_stock_type");?>
                   </div>
                	<div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("start_date");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("end_date");?>
                   </div>
                </div>
				<div class="form-group">
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<button 
							class="button-class button-primary" 
							iconClass="glyphicon glyphicon-search" 
							dojoType="dijit.form.Button"
							showLabel="true" type="submit">
							<?php echo $tr->translate("SEARCH");?>
						</button>
                   </div>
                </div>
			</form>
		</div>
		<div class="card-box">
		<?php echo $this->list;?>
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dojo.NodeList-manipulate");
	dojo.require("dijit.form.Textarea");
	dojo.require("dijit.form.DateTextBox");
	
	dojo.ready(function(){
		new dijit.form.FilteringSelect({
			autoComplete: false,
			queryExpr: "*${0}*",                     
			id: "student_id",
			name: "student_id",   
			value:"<?php echo $this->search['student_id'];?>",
			required:false,        
			class: 'fullside', 
			placeHolder:"<?php echo $tr->translate("SELECT_STUDENT_NAME");?>",          
		}, "student_id");
		getallstudentname();
		 var branch_id = dijit.byId('branch_id');
		 	branch_id.on('change', function(evt) {
				getallstudentname();
		    });
	});
	function getallstudentname(){//
		var url_data = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'getliststudenturl')); ?>';
		branch_id = dijit.byId("branch_id").attr("value");
		if(branch_id==''){
			dijit.byId("branch_id").focus();
			return false;
		}
		dojo.xhrPost({
			url:url_data,
			content:{
				'student_name':1,
				'branchId':branch_id,
				'customerType':1,
			},
			handleAs:"json",
			load: function(data) {
				student_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('student_id').set('store',student_store);  
			    <?php if (!empty($this->search['student_id'])){?>
			    dijit.byId('student_id').set('value','<?php echo $this->search['student_id'];?>'); 
			   
			    <?php }?>
			},
			error: function(err){
			}
		});
	}
	
	var row=0;
	var url="";
	$(function(){
		$.contextMenu({
			selector: '.context-menu-one', 
			callback: function(key, options) {
			
				var m = "clicked: " + key;
				if(key=="void"){
					url='<?php echo $urlVoid;?>';
				}else if(key=="receipt"){
					url='<?php echo $urlreceipt;?>';
				}else if(key=="edit"){
					url='<?php echo $urlEdit;?>';
				}
				gotoAction();
			},
			items: {
				"edit": {name: "<?php echo $tr->translate("EDIT");?>", icon: "fa-edit"},
				"receipt": {name: "<?php echo $tr->translate("RECIEVED_NOTED");?>", icon: "fa-print"},
				"void": {name: "<?php echo $tr->translate("VOID");?>", icon: "fa-times", accesskey: "e"},
			}
		});
	});
	function setrowdata(index){
		row = index;
	}
	var recordid ='';
	function gotoAction(){
		window.open(url+row);
	}
</script> 


 