<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('EDIT_SCHOOLL')); 
	
	$frm_items= $this->frm_items;
?>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0">
						<i class="fa fa-edit" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT_SCHOOLL');?>
					</h4>
					<span id="message"></span>
    			</div>
    			<div class="col-sm-4 text-right"></div>
    		</div>
    	</div>
		<form id='add_occupation' action="" method="post" dojoType="dijit.form.Form" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">				
				if(this.validate()) {
					if(isDuplicate==1){
						alert("<?php echo $tr->translate("ALREADY_EXISTING_RECORD");?>");
						dijit.byId("schoolName").focus();
						return false;
					}
					loadingBlock();
					return true;
				}else {
					return false;
				}
			</script>
			<div class="card-box">
				<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="fa-solid fa-school"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("SCHOOL");?></p>
										</div> 
									</div>
									<div class="form-group">
									   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("SCHOOL_TITLE");?> <span class="required">*</span>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm_items->getElement("schoolName"); ?>
											<?php echo $frm_items->getElement("id"); ?>
											<input class="fullside" name="inFrame" id="inFrame" value="<?php echo $this->inFrame;?>" type="hidden" dojoType="dijit.form.TextBox"  >
									   </div>
									</div>
									<div class="form-group">
										<label class="control-label custom-switch float-end "> 
											<a href="javascript:void(0);" class="switchButton status"><?php echo $tr->translate("STATUS");?></a> 
											<input type="checkbox" id="status" name="status" class="custom-switch-input" <?php if(!empty($this->rs['status'])){ echo "checked";} ?> > 
											<span class="custom-switch-indicator custom-radius switch-status"></span> 
										</label>
									</div>
									<div class="card-box mt-20">
										<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
											<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" value="save_new" name="save_new" id="save_new" label="<?php echo $tr->translate('SAVE');?>" dojoType="dijit.form.Button" />
										</div>
								    </div>
								</div>
							</div>
						</div>
					</div>
					
	            </div>
	         </div>
		</form>
	</div>
</div>
<script>

var isDuplicate = 0;
var url_duplicate = '<?php echo $this->url(array("module"=>"global","controller"=>"prevschool","action"=>"checkduplicate"));?>';										
function checkDuplicateRecord(){
	let schoolName = dijit.byId('schoolName').get('value');
	if(schoolName==''){
		dijit.byId('schoolName').focus();
		return false;
	}
	dojo.xhrPost({
		url: url_duplicate,
		content:{
			'schoolName':schoolName,
			'id':'<?php echo $this->rs['id']; ?>',
			},
		handleAs:"json",
		load: function(data) {
			if(data==1){
				isDuplicate = 1;
				alert("<?php echo $tr->translate("ALREADY_EXISTING_RECORD");?>");
				$("#message").html('<?php echo '<i class="fa fa-exclamation-triangle" aria-hidden="true"></i> '.$tr->translate("ALREADY_EXISTING_RECORD");?> !');
				dijit.byId('schoolName').focus();
			}else{
				isDuplicate=0;
				$("#message").html('');
			}
			HideloadingBlock();
		},
		error: function(err) {
			HideloadingBlock();
		}
	});
}
</script>