<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage ();
	echo $this->headTitle($tr->translate('REQUEST_STOCK'));
	$frm = $this->form_search;
	$urlReceipt = $this->baseUrl()."/allreport/stock/rpt-request-productdetail/id/";
	$urlEdit = $this->baseUrl()."/stock/requestproduct/edit/id/";
	$urlReturn = $this->baseUrl()."/stock/requestproduct/return/id/";
?>
<meta charset="utf-8">
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-cubes " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('REQUEST_STOCK');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<div class="card-box">
			<form action="<?php echo $this->url(array('module'=>'stock','controller'=>'requestproduct','action'=>'index')); ?>"
				dojoType="dijit.form.Form" method="post">
				<div class="form-group">
					<div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("adv_search");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("branch_id");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("request_for");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("for_section");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("request_status");?>
                   </div>
                </div>
                <div class="form-group">
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("start_date");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("end_date");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<button class="button-class button-primary" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button"
							showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
                   </div>
                </div>
			</form>
		</div>
		<div class="card-box">
			<?php  echo $this->list;?>
		</div>
	</div>
</div>
<script>
	dojo.require('dijit.form.Button');
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.TextBox");
	var row=0;
	var url="";
	$(function(){
		$.contextMenu({
			selector: '.context-menu-one', 
			callback: function(key, options) {
				var m = "clicked: " + key;
				if(key=="receipt"){
					url='<?php echo $urlReceipt;?>';
				}else if(key=='edit'){
					url='<?php echo $urlEdit;?>';
				}else if(key=='return'){
					url='<?php echo $urlReturn;?>';
				}
				gotoAction();
			},
			items: {
				"edit": {name: "<?php echo $tr->translate("EDIT");?>", icon: "fa-edit", accesskey: "c"},
				"return": {name: "<?php echo $tr->translate("RETURN_STOCK");?>", icon: "fa-undo", accesskey: "c"},
				"receipt": {name: "<?php echo $tr->translate("REQUEST_STOCK_VOUCHER");?>", icon: "fa-print", accesskey: "c"},
			}
		});
	});
	function setrowdata(index){
		row = index;
	}
	var recordid ='';
	function gotoAction(){
		window.open(url+row, '_blank');
	}

</script>