 <?php
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$db = new Allreport_Model_DbTable_DbRptAllStudent();
      $rsamountstudent =$db->getAmountStudent();
      $rsnewstudent = $db->getAmountNewStudent();
      $rsdropstudent = 0;//$db->getAmountDropStudent();
      $rsteststudent = 0;//$db->getAmountStudentTest();
      $rsteststuregistered = 0;//$db->getAmountStudentTestRegistered();
      $rsupdateresult = 0;//$db->getAmountStudentUpdateresult();
      
      
	  $date = new DateTime();
	$currentDate =  $date->format("Y-m-d");
		
	$search = array(
				'currentDate' =>$currentDate,
				'academic_year' =>'',
				'degree'=>'',
				'grade'=>'',
				'branch_id'=>0,
		);
	$dbGb = new Application_Model_DbTable_DbGlobal();
	
   
	$dbDash = new Home_Model_DbTable_DbDashboard();
	$countingSummary = $dbDash->getCountingCrmSummary($search);
	$totalTesting = empty($countingSummary["totalTesting"]) ? 0  : $countingSummary["totalTesting"];
	$completed = empty($countingSummary["totalRegistered"]) ? 0  : $countingSummary["totalRegistered"];
	$totalDropedCrm = empty($countingSummary["totalDropedCrm"]) ? 0  : $countingSummary["totalDropedCrm"];
	$totalRecord = empty($countingSummary["totalRecord"]) ? 0  : $countingSummary["totalRecord"];
	$proccessing = empty($countingSummary["totalProcessingCrm"]) ? 0  : $countingSummary["totalProcessingCrm"];
	
	$attendanceSummary = array(
		array("label"=>$tr->translate("Completed"),"value"=>$completed,"color"=>"#02217c"),
		array("label"=>$tr->translate("Dropped"),"value"=>$totalDropedCrm,"color"=>"#d39082"),
		array("label"=>$tr->translate("In Progress"),"value"=>$proccessing,"color"=>"#347bb5"),
	);
	
	$limitRecord = 20;
	$dbNotification = new Application_Model_DbTable_DbNotification();
	$arrCon = array(
		"limitRecord" =>$limitRecord,
		"currentDate" =>date("d-m-Y"),
		
	);
	$crmNotif = $dbNotification->getCrmNextContactNoti($arrCon);
	
	$arrFilter = array(
		"limitRecord" =>10,
		
	);
	$amtCus = $dbDash->getAmtCustomerByMonth($arrFilter);
	 
?>
<link rel="stylesheet" href="<?php echo $this->baseUrl()."/"?>dashboard/plugins/morris/morris.css">
<!-- Icons CSS -->
<link href="<?php echo $this->baseUrl()."/"?>dashboard/css/icons.css" rel="stylesheet">
<!-- Custom styles for this template -->
<link href="<?php echo $this->baseUrl()."/"?>dashboard/css/style.css" rel="stylesheet">
<style>
ul.list-att-status {
    list-style: none;
    margin: 0;
    padding: 0;
    width: 100%;
}

ul.list-att-status li {
    margin-bottom: 5px;
	text-align: left;
}
ul.list-att-status li span, ul.list-att-status li div {
    font-size: 16px;
}
.latest-record {
    min-height: 265px;
    max-height: 265px;
    padding: 10px;
    overflow-y: auto;
    margin-bottom: 10px;
    margin-top: 5px;
}
svg text {
    font-family: 'Khmer Os Battambang' !important;
}

.title-list-record {
    display: flex;
    flex-wrap: nowrap;
    align-content: center;
    justify-content: space-between;
}
.detail-row {
    display: block;
    color: #918e8e;
}
</style>
<div id="page-wrapper">
	<!-- Page content start -->
	<div class="page-contentbar">
		<!-- START PAGE CONTENT -->
		<div id="page-right-content">
			<div class="container">
				<div class="row" style="margin-top: 15px;">
					<div class="col-lg-12">
						<div class="row top_tiles">
							<div  class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
								<div class="tile-stats">
								  <div class="icon"><i class="fa fa-user"></i></div>
								  <div class="count"><?php echo sprintf('%02d',$totalRecord); ?></div>
								  <h3><?php echo $tr->translate("totalCrm");?></h3>
								</div>
							</div>
							<div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
								<div class="tile-stats">
								  <div class="icon"><i class="glyphicon glyphicon-education"></i></div>
								  <div class="count"><?php echo sprintf('%02d',$completed); ?></div>
								  <h3><?php echo $tr->translate("totalRegtered");?></h3>
								</div>
							</div>
							<div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
								<div class="tile-stats">
								  <div class="icon"><i class="glyphicon glyphicon-blackboard"></i></div>
								  <div class="count"><?php echo sprintf('%02d',$totalTesting); ?></div>
								  <h3><?php echo $tr->translate("totalTesting");?></h3>
								</div>
							</div>
							<div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
								<a style=" color: #17418e;" title="<?php echo $tr->translate("FINDING_ALL_STUDENT_INFORMATION")?>" href="<?php echo $this->url(array('module'=>'home','controller'=>'searchstudentinfo','action'=>'index'), null, true);?>">
									<div class="tile-stats">
									  <div class="icon"><i class="glyphicon glyphicon-search"></i></div>
									  <div class="count"><i class="glyphicon glyphicon-search"></i></div>
									  <h3><?php echo $tr->translate("FINDING_ALL_STUDENT_INFORMATION");?></h3>
									</div>
								</a>
							</div>
						</div>
					</div>
				</div>
						
				<div class="row" style="margin-top: 15px;">
					<div class="col-lg-9">
						<div class="card-box" style="  margin: 0;">
							<div class="row">
								<div class="col-md-6 col-sm-6 col-xs-12 text-center">
									<div class="x_panel">
										<div class="card-box" style="padding: 0;  margin: 0;">
											<div class="row">
												<div class="col-md-6 col-sm-6 col-xs-12">
													<span style=" color: #17418e;">
														<span data-bind="text: txnRecorded"><h3><?php echo $tr->translate("Overall Progress")?></h3></span>
														<p>&nbsp;</p>
													</span>
													<div id="donutStudent" class="morris-donut-inverse" style="width:100%; height:240px;"></div>
												</div>
												<div class="col-md-6 col-sm-6 col-xs-12" style="height:150px;display: flex;justify-content: center;align-items: center;align-content: center;">
													<ul class="list-att-status">
														
													<?php if(!empty($attendanceSummary)) foreach($attendanceSummary as $attSum ){ ?>
														<li>
															<div class="row">
																<div class="col-md-8 col-sm-8 col-xs-12"> 
																	<i class="fa fa-square " style="color:<?php echo empty($attSum["color"]) ? "blue" : $attSum["color"]; ?>;"></i> <?php echo $attSum["label"];?> 
																</div>
																<div class="col-md-4 col-sm-4 col-xs-12">
																<?php echo empty($attSum["value"]) ? "00" : sprintf('%02d',$attSum["value"])?>
																</div>
															</div>
														</li>
													<?php } ?>
													</ul>
												</div>
											</div>
										</div>
									</div>
								</div>
								<div class="col-md-6 col-sm-6 col-xs-12 text-center">
									<div class="x_panel">
										<div class="card-box" style="padding: 0;  margin: 0;">
											<div class="row">
												<div class="col-md-12 col-sm-12 col-xs-12">
													<span style=" color: #17418e;" >
														<span data-bind="text: txnRecorded"><h3><?php echo $tr->translate("Customer")?></h3></span>
														<p class="month" style="text-align: center; margin: 0 auto;" data-bind="text: lang.lang.transactions_recorded"><?php echo $tr->translate("statistic")?></p>
													</span>
													<div id="customer-statistic" class="morris-donut-inverse" style="width:100%; height:240px;"></div>
												
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
							
						</div>
					</div> <!-- end col -->	  
					<div class="col-lg-3">
					 	<div class="card-box" style="padding: 0;  margin: 0;">
							<ul class="list-inline count2" style=" color: #17418e; font-weight: bold;">
                                <li style="width:100%;">
                                  <h3 style=" color: #17418e; font-weight: bold;"><i class="fa fa-laptop"></i> <?php echo $tr->translate("Today Task");?></h3>
                                  <span></span>
                                </li>
							</ul>
							<span class="title-list-record" data-bind="text: lang.lang.performance">
								<span><i class="fa fa-laptop" ></i> <?php echo $tr->translate("customerForContact");?></span>
								<a title="<?php echo $tr->translate("SHOW_ALL");?>" href="<?php echo $this->baseUrl()."/allreport/allstudent/rpt-crm-daily-contact"; ?>"><small><?php echo $tr->translate("SHOW_ALL");?></small></a>
							</span>
							<div class="latest-record">
								<?php if(!empty($crmNotif) ){?>
								<ul class="top_profiles list-inline widget_tally">
									<?php foreach($crmNotif AS $reqRow){
										$class="label-primary";
										$proccess = $reqRow["proccess"];
										if($proccess==2){
											$class="label-warning";
										}
										?>
									<li>
									  <p>
										<span class="month">
											<span class="text-muted"><i class="fa fa-university" ></i> <?php echo $reqRow['branch_name']; ?> <?PHP echo $reqRow["nameKh"]; ?></span>
											<small class="detail-row">
												<?PHP echo $reqRow["nameEng"]; ?>
											</small>
											<small class="detail-row">
												<i><i class="fa fa-commenting-o" ></i> <?PHP echo $reqRow["feedback"]; ?></i>
											</small>
											
										</span>
										<span class="count">
											<span class="label <?php echo $class; ?>"><?PHP echo $reqRow["proccessTitle"]; ?></span>
											<small class="detail-row">
												<i><?php echo date("d-m-Y",strtotime($reqRow["next_contact"])); ?></i>
											</small>
										</span>
									  </p>
									</li>
									<?php } ?>
									
								</ul>
								<?php } ?>
							</div>
						</div>
						<div class="clearfix"></div>
						
						
						
						
					</div> <!-- end col -->	  
				</div> <!-- end row -->
				     
			</div>
		</div>
		<!-- END PAGE CONTENT -->
	</div>
	<div class="row-fluid">
					<div style="margin-top: 10px; margin-left: 0;" align="center">
						<p>© 2018<span data-bind="text: lang.lang.all_rights_reserved"><a href="http://www.cam-app.com" target="_blank" > Cam App Teachnology</a>. All rights reserved.</span></p>
					</div>	
				</div>  
</div>


<script src="<?php echo $this->baseUrl()."/"?>dashboard/plugins/morris/morris.min.js"></script>
<script src="<?php echo $this->baseUrl()."/"?>dashboard/plugins/raphael/raphael-min.js"></script>
<?php 
$date = date("Y-m-d");
$lenghtLine = 5;
$arrLine = [];
					
for ($x = 0; $x <= $lenghtLine; $x++) {
	
	$dateMY = date("Y-m",strtotime("-$x month"));
	$strFilter =  (string) $dateMY;
	$rsRecord = array_filter($amtCus, function ($item) use ($strFilter) {
		if ($item['year'] == $strFilter) {
			return $item;
		}
		return;
	});
	if(!empty($rsRecord)){
		
		$arrVal = array_values($rsRecord)[0];
		array_push($arrLine,$arrVal);
	}else{
		$arrNew =[
			"year" => $strFilter, 
			"customer" => "0" 
		]; 
		array_push($arrLine,$arrNew);
	}
}
?>
<script>
var colorDanger = "#FF1744";
Morris.Donut({
  element: 'donutStudent',
  resize: true,
  data: <?php  echo Zend_Json::encode($attendanceSummary);?>
});

Morris.Area({
  element: 'customer-statistic',
  data: <?php  echo Zend_Json::encode($arrLine);?>,
  xkey: 'year',
  ykeys: ['customer'],
  labels: ['<?php echo $tr->translate("Customer");?>']
});
</script>