<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$reportTitle = $tr->translate('REPORT_LIST_STUDENTS');
	$this->headTitle($reportTitle); 
	echo $this->headTitle(''); 
	$frm =  $this->form_search;
	
	$dateFormat ="d/m/Y";
	$dateFormatExport ="d/M/Y";
	$qrReport = empty($this->search['qrReport'])?0:$this->search['qrReport'];
?>
<style>
.hover:hover{ background:#ccc;}
.line-height{line-height:20px !important;}
.table-width{width:40% !important}
.hover:hover{ background:#ccc;}
table.content-data tr.style-head,
table.content-data-main tr.style-head,
table.tb-footer tr.style-head {
   font-weight: bold !important;
}
</style>
<div class="layout-wrapper-report">
	<div id="mainContent" class="main-content-report">
		<div class="report-preview">
			<?php echo $this->controlReport?>
			<div id="main-viewer" class="main-viewer portrait">
				<div id="viewer" class="viewer portrait">
					<div id="divPrint" class="content">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style.css">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style-screen.css">
						<style>
							@media print {
								<?php if(!empty($this->printFormat)){ echo $this->printFormat; } ?>
							}
							ul.title-report {
								list-style: none;
								margin: 0;
								padding: 0;
							}
							table{ border-collapse:collapse; margin:0 auto; border-color:#4839bd; }
							.padding{ padding: 0 1px !important;}
							.divBreak{
								page-break-inside:always;
								page-break-after:always;
							}
							.content-data-main{ page-break-inside:auto; font-family:'Times New Roman','Khmer OS Battambang'; }
							.content-data-main tr{ page-break-inside:avoid; page-break-after:auto }
							
							
							table.tableFooterTotal tr td {
								border: none !important;
							}
							#BrowserPrintDefaults{display:none}
							
							.imageQr {
								display: inline-block;
								width: 135px;
								margin-right: 25px;
								margin-bottom: 10px;
							}
							.imageQr span {
								text-align: center;
								display: block;
								line-height: 18px;
								font-family: 'Times New Roman', 'Khmer OS Battambang';
								white-space: nowrap;
								overflow: hidden;
							}
						</style>
						<?php if($qrReport==1){ ?>
									
								<?php 
								$i=0; 
								if(!empty($this->rs)){
									foreach ($this->rs AS $row) { 
										$i++;

										$QrCodeValue =URL_STUDENT_PROFILE.'/public/info/studentinfo/token/'.$row['studentToken'];
				
										$url = $this->url(array("module"=>"default","controller"=>"index","action"=>"generate-qr"),null,true);
										$url.='?codeReader='.$QrCodeValue;
									
							 ?>
								<div class="imageQr">
									<img  src="<?php echo $url;?>" alt="qr-student" >
									<span><?php echo empty($row['groupCode']) ? $row['grade'] : $row['groupCode'];?></span>
									<span><?php echo $row['stu_code'];?></span>
									<span><?php echo $row['stu_khname'];?></span>
								</div>
							 <?php }
								} ?>
						<?php }else{ ?>
							<div class="text-h12px text-size-12px" style="width:100%;text-align: center;">
								<span class="text-h12px text-size-12px text-bold" style="font-family: 'Times New Roman','Khmer OS Battambang'; "><?php echo $reportTitle; ?></span><br />
								<div id="lblBranchId"></div>
								<span class="text-h12px text-size-12px" style="font-family: 'Times New Roman','Khmer OS Battambang'; "><?php if(!empty($this->search['start_date'])){?><?php echo date($dateFormat,strtotime($this->search['start_date']));?> <?php echo $tr->translate("TO");?> <?php echo date($dateFormat,strtotime($this->search['end_date']));}?> </span>
							</div>
							<table width="100%" style="background:#fff; margin: 0 auto;">
								
								<tr>
									<td colspan="3">
									<div id="exportExcel">
										<table width="100%" class="content-data-main text-color-black text-h12px text-size-9px bd-dark-grey" cellpadding="2" border="1" >
											<thead>
												<tr style="white-space:nowrap;" class="style-head bd-black bd-w1px style-head bg-head hpx-25" align="center" >
													<th class="text-center w-px-30" rowspan="2"><?php echo $tr->translate("NUM");?></th>
													<th class="text-center" rowspan="2"><?php echo $tr->translate("BRANCH_NAME");?></th>
													<th class="text-center" colspan="6"><?php echo $tr->translate("STUDENT_INFO");?></th>

													<th class="text-center" colspan="3"><?php echo $tr->translate("STUDY_INFO");?></th>
													<th class="text-center" colspan="6"><?php echo $tr->translate("PARENT_INFO");?></th>
													<th class="text-center w-px-80" rowspan="2"><?php echo $tr->translate("CURRENT_ADDRESS");?></th>	
													<th class="text-center w-px-60" rowspan="2" ><?php echo $tr->translate("CONTACT_NO");?></th>				
													<th class="text-center" rowspan="2"><?php echo $tr->translate("STATUS");?></th>
												</tr>
												<tr style="white-space:nowrap;" class="style-head bd-black bd-w1px style-head bg-head hpx-25 " align="center" >

													<th class="text-center" ><?php echo $tr->translate("STUDENT_ID");?></th>
													<th class="text-center" ><?php echo $tr->translate("STUDENT_NAMEKHMER");?></th>
													<th class="text-center" ><?php echo $tr->translate("NAME_ENGLISH");?></th>
													<th class="text-center" ><?php echo $tr->translate("SEX");?></th>
													<th class="text-center" ><?php echo $tr->translate("NATIONALITY");?></th>
													<th class="text-center" ><?php echo $tr->translate("DATE_OF_BIRTH");?></th>

													<th class="text-center"><?php echo $tr->translate("DEGREE");?></th>
													<th class="text-center w-px-70"><?php echo $tr->translate("GRADE");?></th>
													<th class="text-center"><?php echo $tr->translate("SESSION");?></th>

													<th class="text-center w-px-70"><?php echo $tr->translate("FATHER_NAME");?></th>
													<th class="text-center w-px-60"><?php echo $tr->translate("OCCUPATION");?></th>
													<th class="text-center w-px-60"><?php echo $tr->translate("CONTACT_NO");?></th>											
													<th class="text-center w-px-70"><?php echo $tr->translate("MOTHER_NAME");?></th>
													<th class="text-center w-px-60"><?php echo $tr->translate("OCCUPATION");?></th>
													<th class="text-center w-px-60"><?php echo $tr->translate("CONTACT_NO");?></th>	
												</tr>											
											</thead>
										<?php $i=0; foreach ($this->rs AS $row) { 
											$i++;

												$stuDob="";
												if(!empty($row['dob'])){
													$stuDob = date($dateFormat,strtotime($row['dob']));
												}
											
											?>
											<tr class="style-rowdata hover" align="center" >
												<td ><?php echo $i;?></td>
												<td ><?php echo $row['branch_name'];?></td>

												<td style="white-space:nowrap;"><?php echo $row['stu_code'];?></td>
												<td align="left"><?php echo $row['stu_khname'];?></td>
												<td align="left"><?php echo $row['stuNameLatin'];?></td>
												<td ><?php echo $row['sex'];?></td>	
												<td ><?php echo $row['nationality'];?></td>
												<td class="text-center">
													<?php echo $stuDob; ?>
												</td>

												<td ><?php echo $row['degree'];?></td>
												<td align="left"><?php echo empty($row['groupCode']) ? $row['grade'] : $row['groupCode'];?></td>
												<td ><?php echo $row['session'];?></td>	

												<td align="left"><?php echo empty($row['father_enname']) ? $row['father_khname'] : $row['father_enname'];?></td>
												<td align="left"><?php echo $row['father_job'];?></td>
												<td ><?php echo $row['father_phone'];?></td>													
												<td align="left"><?php echo empty($row['mother_enname']) ? $row['mother_khname'] : $row['mother_enname'];?></td>
												<td align="left"><?php echo $row['mother_job'];?></td>
												<td ><?php echo $row['mother_phone'];?></td>
												
												<td align="left" class="wrap-cell">
													<?php if (!empty($row['home_num'])){ echo $tr->translate("NUMBER_HOME")." ".$row['home_num']." ";}?>
													<?php if (!empty($row['street_num'])){ echo $tr->translate("STREET")." ".$row['street_num']." ";}?>
													<?php if (!empty($row['village_name'])){ echo $tr->translate("VILLAGE")." ".str_replace('ភូមិ', '', $row['village_name'])." ";}?>
													<?php if (!empty($row['commune_name'])){ echo $tr->translate("COMMUNE")." ".$row['commune_name']." ";}?>
													<?php if (!empty($row['district_name'])){ echo $tr->translate("DISTRICT")." ".$row['district_name']." ";}?>
													<?php if (!empty($row['province'])){ echo $tr->translate("CITY_PROVINCE")." ".$row['province']." ";}?>
												</td>
												<td align="left"><?php echo $row['tel'];?></td>														
												<td ><?php echo $row['statusStudent'];?></td>
											</tr>
										<?php }?>	
										</table>
									</div>										
									</td>
								</tr>
								<tr>
									<td colspan="3">
										<?php echo $this->rsfooteracc;?>
									</td>
								</tr>
							</table>
						<?php }?>	
					</div>	
				</div>	
			</div>	
		</div>	
	</div>
	<div class="right-panel-report" id="rightPanel">
		<div class="card-box">
			<div class="card-search-head col-sm-12 border-botom">
				<div class="col-sm-6 text-left pd-0">
					<h4 class="m-b-0">
						<?php echo $tr->translate("SEARCH");?> 
						<i class="fa fa-search "></i> 
					</h4>
				</div>
				<div class="col-sm-6 text-right pd-0">
					<button onclick="closeRightPanel()" title="<?php echo $tr->translate("CLOSED");?> " class="btn-close">
						<i class="fa-solid fa-xmark"></i>
					</button>
				</div>
			</div>
			<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'allstudent','action'=>'rpt-student')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
				<div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("title");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("branch_id");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<input id="study_year" />
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
							<input id="group" />
						</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("degree");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<input id="grade" />
						<?php //echo $frm->getElement("grade");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<input id="session" />
						<?php //echo $frm->getElement("session");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("academicYearEnroll");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("study_type");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
					
						<select class="fullside" dojoType="dijit.form.FilteringSelect" id="qrReport" name="qrReport">
							<option value="0" <?php if($qrReport==0){echo "selected";}?> ><?php echo $tr->translate("GENERAL");?></option>
							<option value="1" <?php if($qrReport==1){echo "selected";}?>><?php echo $tr->translate("QR");?></option>
						</select>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm->getElement("start_date");?>
					</div>
					<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm->getElement("end_date");?>
					</div>
				</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<button class="button-class button-primary fullside" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
				</div>
			</form>
		</div>	
	</div>	
</div>	

<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script src="<?php echo $this->baseUrl();?>/admin/js/global.js"  type="text/javascript"></script>
<script type="text/javascript">

dojo.require("dojo.data.ItemFileWriteStore"); 

var academic_store= getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
dojo.ready(function(){
	new dijit.form.FilteringSelect({
		queryExpr: "*${0}*",
		autoComplete: false,                     
		required: false,                        
		id: "grade",
		name: "grade",  
		class: 'fullside',  
		placeHolder:"<?php echo $tr->translate("SELECT_GRADE");?>",          
		onChange: function() {  

		}
	}, "grade");
	
	new dijit.form.FilteringSelect({
		queryExpr: "*${0}*",
		autoComplete: false,                     
		required: false,                        
		id: "session",
		name: "session",  
		class: 'fullside',  
		placeHolder:"<?php echo $tr->translate("SELECT_SESSION");?>",          
		onChange: function() {  

		}
	}, "session");
	
	new dijit.form.FilteringSelect({
		store: academic_store,
		queryExpr: "*${0}*",
		autoComplete: false,                     
		required: false,                     
		id: "study_year",
		name: "study_year",
		class: "fullside", 		
		placeHolder:"<?php echo $tr->translate("SELECT_ACADEMIC_YEAR");?>",          
		onChange: function() {  
			academic_year = dijit.byId('study_year').get('value');
		}
	}, "study_year");
	new dijit.form.FilteringSelect({
		store: group_store,
	    queryExpr: "*${0}*",
		autoComplete: false,                     
		required: true,                      
	    id: "group",
	    name: "group",  
	    class: 'fullside', 
	    readonly:false,
	    required:false,
	    placeHolder:"<?php echo $tr->translate("SELECT_GROUP");?>",          
	    onChange: function() {  
		    
	    }
	}, "group");
	
	 var branch_id = dijit.byId('branch_id');
	 branch_id.on('change', function(evt) {
		 getAllAcademicByBranch();
		 getAllGroupByBranch();
    });
	
	var degree = dijit.byId('degree');
	degree.on('change', function(evt) {
		getAllSession();
  	});
	
	 getAllAcademicByBranch();
	 getAllGroupByBranch();
	 getallGrade();
	 getAllSession();
	 
	 setTimeout(function() {
		setPrintOrientation('landscape');
		let branchId = dijit.byId("branch_id").get('value');
		if(branchId!=""){
			
			let branchLable = dijit.byId("branch_id").attr('displayedValue');
			$('#lblBranchId').html(branchLable);
		}
	}, 500);
});
var url_dept = '<?php echo $this->url(array('module'=>'global','controller'=>'grade','action'=>'get-grade')); ?>';
function getallGrade(){
	getAllGroupByBranch();  
	dept_id = dijit.byId('degree').get('value');
	if(dept_id=='' || dept_id==-1){return false;}
		dojo.xhrPost({
			url:url_dept,
			content:{
				'dept_id':dept_id,
				'noaddnew':1
				},
			handleAs:"json",
			load: function(data) {
				dijit.byId('grade').attr('value','');
				grade_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('grade').set('store',grade_store); 
			    dijit.byId('grade').attr('value','<?php echo $this->search['grade']?>');  
			},
			error: function(err) {
			}
	});
}
var url_getSession = '<?php echo $this->url(array('module'=>'global','controller'=>'parttimelist','action'=>'get-parttime')); ?>';
function getAllSession(){
	dijit.byId('session').set('value',''); 
	degree = dijit.byId('degree').get('value');
	if(degree==''){
		sessionStore  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('session').set('store',sessionStore);  
		return false;
	}
	dojo.xhrPost({
		url:url_getSession,
		content:{
			'degree':degree,
		},
		handleAs:"json",
		load: function(data) {
			sessionStore  = getDataStorefromJSON('id','name', data);
			dijit.byId('session').set('store',sessionStore);  
			<?php if(!empty($this->search['session'])){ ?>
			dijit.byId('session').set('store','<?php echo $this->search['session']?>');  
			<?php } ?>
		},
		error: function(err) {
		}
	});
}


url_getacademic= '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'get-academicyear'));?>';
var oldBranch = "<?php echo $this->search['branch_id']?>";
function getAllAcademicByBranch(){
	dijit.byId('study_year').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var academic_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('study_year').set('store',academic_store);  
		dijit.byId('branch_id').focus();
		return false;
	}
	
	contentData = {
		'branch_id':branch_id
	}
	selectedId = '';
	if(oldBranch==branch_id){
		selectedId = '<?php echo $this->search['study_year']?>';
	}
	getAllYear(url_getacademic,contentData,selectedId,'study_year');

}
url_getgroup = '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'getallgroup'));?>';
function getAllGroupByBranch(){
	dijit.byId('group').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('group').set('store',group_store);  
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url: url_getgroup,
		content:{
			'branch_id':branch_id,
			'noaddnew':1
			},
		handleAs:"json",
		load: function(data) {
		    group_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('group').set('store',group_store);   
		    if(oldBranch==branch_id){
		    	dijit.byId('group').set('value','<?php echo $this->search['group']?>');  
		    }
		},
		error: function(err) {
			alert(err);
		}
	});
}
	function doPrintQr(){
		loadingBlock();
	  	 var contents = document.getElementById("divPrint").innerHTML;
	 	  var frame1 = document.createElement('iframe');
	    frame1.name = "frame1";
	    frame1.style.position = "absolute";
	    frame1.style.top = "-1000000px";
	    document.body.appendChild(frame1);
	    var frameDoc = (frame1.contentWindow) ? frame1.contentWindow : (frame1.contentDocument.document) ? frame1.contentDocument.document : frame1.contentDocument; frameDoc.document.open();
	    frameDoc.document.write('<html><head><title>Employee ID</title>');
	    frameDoc.document.write('</head><body>');
	    frameDoc.document.write(contents);
	    frameDoc.document.write('</body></html>');
	    frameDoc.document.close();
	    setTimeout(function () {
	        window.frames["frame1"].focus();
	        window.frames["frame1"].print();
	        document.body.removeChild(frame1);
	        HideloadingBlock();
	    }, 10000);
	   return false;
	}
</script>