<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate("CRM_REPORT")); 
	echo $this->headTitle(''); 
	$frm_items= $this->frm_crm;
	$dateFormat ="d/m/Y";
	
	$classHideHeight=classHideHeight;
?>
<div class="layout-wrapper-report white">
	<div id="mainContent" class="main-content-report">
		<div class="report-preview">
			<?php echo $this->controlReport?>
			<div id="main-viewer" class="main-viewer portrait">
				<div id="viewer" class="viewer portrait">
					<div id="divPrint" class="content">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style.css">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style-screen.css">
						<style>
							.hide{visibility: hidden;}
							@media print {
								<?php if(!empty($this->printFormat)){ echo $this->printFormat; } ?>
								.hide{visibility: visible; height: <?php echo $classHideHeight;?>;}
							}
							
							div.know_by {
								margin-top:10px;
							}
							ul.know_by {
								margin: 0;
								padding: 0;
								width: 100%;
							}
							.know_by, label {
								font-family: 'Times New Roman', 'Khmer OS Battambang';
								font-size: 11px;
							}
							.know_by li {
								line-height: 15px;
							}
							.know_byitem {
								display: inline-table;
								width: 33%;
							}
							span.count-value {
								line-height: 14px;
								padding-left: 10px;
								font-weight: 600;
							}
						</style>
						<table  style="margin: 0 auto; width: 100%; ">
						<tr>
							<td colspan="3"><?php echo $this->rsheader;?></td>
						</tr>
						<tr>
							<td width="20%" align="right">
							</td>
							<td width="60%" align="center">
								<span style="color:#000; font-size: 11px;font-family:Times New Roman,'Khmer OS Muol Light';"><?php echo $tr->translate("CRM_REPORT");?></span><br/>
								<span style="color:#000; font-size: 11px;font-family:Times New Roman,'Khmer OS Battambang';"><?php if(!empty($this->search['start_date'])){?><?php echo date($dateFormat,strtotime($this->search['start_date']));?> <?php echo $tr->translate("TO");?> <?php echo date($dateFormat,strtotime($this->search['end_date']));}?> </span>
							</td>
							<td width="20%" align="right"><label id='lbl_branch'></label></td>
						</tr>
							<tr>
								<td colspan="3">
									<div id="exportExcel">
										<table class="content-data text-color-black text-h16px text-size-10px bd-dark-grey" cellpadding="4" border="1" >
											<thead>
												<tr class="style-head text-bold text-center" >
													<td rowspan="2" class="w-px-30"><?php echo $tr->translate("NUM");?></td>
													<td rowspan="2" class="w-px-50"><?php echo $tr->translate("BRANCH");?></td>
													<td colspan="3"><?php echo $tr->translate("CUSTOMER_INFO");?></td>
													<td rowspan="2"><?php echo $tr->translate("ASK_FOR");?></td>
													<td class="w-px-90" rowspan="2"><?php echo $tr->translate("Previous Concern");?></td>
													<td rowspan="2"><?php echo $tr->translate("KNOW_BY");?></td>
													<td	rowspan="2"><?php echo $tr->translate("Amount Contacted");?></td>
													<td colspan="2"><?php echo $tr->translate("STUDENT_INFO");?></td>
													<td rowspan="2"><?php echo $tr->translate("TYPE");?></td>
													<td rowspan="2"><?php echo $tr->translate("CREATE_DATE");?></td>
													<td rowspan="2"><?php echo $tr->translate("BY_USER");?></td>
													<td rowspan="2"><?php echo $tr->translate("STATUS");?></td>
													<td rowspan="2"><?php echo $tr->translate("FOLLOWU_STATUS");?></td>
												</tr>
												<tr class="style-head text-bold text-center" >
													<td class=" w-px-100"><?php echo $tr->translate("NAME");?></td>
													<td class=" w-px-30"><?php echo $tr->translate("GENDER");?></td>
													<td class=" w-px-100"><?php echo $tr->translate("PHONE");?></td>
													<!--
													<td class=" w-px-90"><?php //echo $tr->translate("CURRENT_ADDRESS");?></td>
													-->
													<td class=""><?php echo $tr->translate("STUDENT_NAME"); ?></td>
													<td class=""><?php echo $tr->translate("GRADE"); ?></td>
												</tr>
											</thead>
											<?php $i=0;
											$total_student=0; 
											$know_by = array();
											if(!empty($this->row)){ foreach ($this->row AS $key=> $row) { 
												$i++;
											?>
											<tr class="style hover context-menu-one <?php if($key%2==0){echo'oddRecord';}?>" align="center" onClick="generateTab('<?=$row['id']?>','<?=$row['kh_name']?>')"  >
												<td><?php echo $i;?></td>
												<td  align="left"><?php echo $row['branch_name'];?></td>
												<td align="left">
													<span class="d-block w-px-90 text-truncate">
													<?php echo $row['kh_name'];?>
													</span>
												</td>
												<td align="center"><?php echo $row['sexTitle']; ?></td>
												<td align="left" >
													<span class="d-block breakword text-size-9px w-px-100">
													<?php echo $row['tel'];?>
													</span>
												</td>
												<!--
												<td align="left" >
													<span class="d-block breakword text-size-9px w-px-90">
													<?php //echo $row['current_address'];?>
													</span>
												</td>
												-->
												<td class=" breakword text-size-9px" align="left">
													<span class="d-block breakword text-size-9px w-px-90">
													<?php echo $row['ask_for_title'];?>
													</span>
												</td>
												<?php 
													$total_student = $total_student+1;
													$know_by[$row['know_by']]=@$know_by[$row['know_by']]+1;
													
													$prevCon=$row['prevConcernTitle'];
													
												?>
												<td>
													<span class="d-block breakword text-size-9px w-px-90">
													<?php echo $prevCon;?>
													</span>
												</td>
												<td>
													<span class="d-block breakword text-size-9px w-px-60">
													<?php echo $row['know_by_title'];?>
													</span>
												</td>
												<td align="center"><?php echo $row['amountContact'];?> <?php echo $tr->translate("Times");?></td>
												<td align="left">
													<span class="d-block w-px-90 text-truncate">
													<?php echo $row['stuNameKh'];?>
													</span>
												</td>	
												<td class="normal_wrap" align="left"><?php echo empty($row['grade'])?$row['degree']:$row['grade'];?></td>	
												<td class="text-size-9px"><?php echo $row['customer_type'];?></td>	
												<td>
												<?php
													$format = $dateFormat;
													$dateString = $row["create_date"];
													$date = new DateTime($dateString);
													$create_date = $date->format($format);
													echo $create_date;
												 ?>
												 </td>	
												<td><?php echo $row['userby'];?></td>	
												<td class="text-size-9px"><?php echo $row['crm_status_title'];?></td>	
												<td class="text-size-9px"><?php echo $row['followup_status'];?></td>	
											</tr>
										<?php }}?>	
										</table>	
									</div>	
								</td>
							</tr>
							<tr>
								<td colspan="3" align="left">
									<div class='know_by'><strong><?php echo $tr->translate("KNOW_BY");?></strong></div>
									<ul class='know_by'>
									<?php if(!empty($this->rsknowBy)){ foreach($this->rsknowBy as $rsknow){?>
										<li class='know_byitem'>
										<?php echo $rsknow['name'].""; ?>
										<span class="count-value"><?php echo empty($know_by[$rsknow['id']])?'0':$know_by[$rsknow['id']];echo " ".$tr->translate('STUDENT_UNIT'); ?></span>
										</li>
									<?php }}?>
										<li style="border-top:1.5px #000 dashed;;list-style-type: none;padding-top:5px;"><strong><?php echo $tr->translate("TOTAL_STUDENT").''.$total_student." ".$tr->translate('STUDENT_UNIT');?></strong></li>
									</ul>
								</td>
							</tr>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="right-panel-report" id="rightPanel">
		<div class="card-box">
			<div class="card-search-head col-sm-12 border-botom">
				<div class="col-sm-6 text-left pd-0">
					<h4 class="m-b-0">
						<?php echo $tr->translate("SEARCH");?> 
						<i class="fa fa-search "></i> 
					</h4>
				</div>
				<div class="col-sm-6 text-right pd-0">
					<button onclick="closeRightPanel()" title="<?php echo $tr->translate("CLOSED");?> " class="btn-close">
						<i class="fa-solid fa-xmark"></i>
					</button>
				</div>
			</div>
			<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
				 <div class="form-group">
                   	<div class="col-md-12 col-sm-12 col-xs-12">
				 		<?php echo $frm_items->getElement("advance_search");?>
				 	</div>
				 	<div class="col-md-12 col-sm-12 col-xs-12">
				 		<?php echo $frm_items->getElement("branch_search");?>
				 	</div>
				 	<div class="col-md-12 col-sm-12 col-xs-12">
				 		<?php echo $frm_items->getElement("ask_for_search");?>
				 	</div>
				 	<div class="col-md-12 col-sm-12 col-xs-12">
				 		<?php echo $frm_items->getElement("know_by_search");?>
				 	</div>
				 	<div class="col-md-12 col-sm-12 col-xs-12">
				 		<?php echo $frm_items->getElement('status_search');?>
				 	</div>
				 </div>
				 <div class="form-group">
	                <div class="col-md-12 col-sm-12 col-xs-12">
				 		<?php echo $frm_items->getElement("crm_process");?>
				 	</div>
				 	<div class="col-md-12 col-sm-12 col-xs-12">
				 		<?php echo $frm_items->getElement("followup_status");?>
				 	</div>
				 	<div class="col-md-12 col-sm-12 col-xs-12">
	                	<input value="<?php echo $this->search['prev_concern'];?>" type="text" id="e15" name="prev_concern" style="width: 100%">
	                </div>
				</div>
				 <div class="form-group">
					 <div class="col-md-12 col-sm-12 col-xs-12">
				 		<?php echo $frm_items->getElement("school_option");?>
				 	</div>
				</div>
				<div class="form-group">
	                <div class="col-md-6 col-sm-6 col-xs-12">
				 		<?php echo $frm_items->getElement("degree");?>
				 	</div>
				 	<div class="col-md-6 col-sm-6 col-xs-12">
				 		<input id="grade" />
				 	</div>
				 </div>
				 <div class="form-group">
	                <div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm_items->getElement("start_date");?>
					</div>
					<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm_items->getElement("end_date");?>
					</div>
				 </div>
				 <div class="form-group">
				 	<div class="col-md-12 col-sm-12 col-xs-12">
				 		<button class="button-class button-primary fullside" iconClass="glyphicon glyphicon-search"  dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
				 	</div>
				 </div>
			</form>
		</div>
	</div>
</div>
<link href="<?php echo $this->baseUrl()."/admin"?>/3.5.0/select2.css" rel="stylesheet">
<script src="<?php echo $this->baseUrl()."/admin"?>/3.5.0/select2.min.js"></script>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>

<?php 
 $tags="";
 if (!empty($this->prev_concern)) foreach ($this->prev_concern as $rs){
 	if (empty($tags)){
 		$tags = '"'.$rs['name'].'"';
 	}else{
 		if (!empty($rs['name'])){
 		$tags=$tags.',"'.$rs['name'].'"';
 		}
 	}
 }
?>
<script type="text/javascript">
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dojo.data.ItemFileWriteStore"); 
	var grade_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	
require(["dojo/ready"], function(ready){
	ready(function(){
		 $("#e15").select2({tags:[<?php echo $tags;?>],placeholder: "<?php echo $tr->translate("Previous Concern");?>",allowClear: true});
	
		new dijit.form.FilteringSelect({
			queryExpr: "*${0}*",
			autoComplete: false,                     
			required: false,                        
			id: "grade",
			name: "grade",  
			class: 'fullside',  
			placeHolder:"<?php echo $tr->translate("SELECT_GRADE");?>",          
			onChange: function() {  

			}
		}, "grade");
		<?php if(!empty($this->search['degree'])){?>
		dijit.byId('degree').attr('value','<?php echo $this->search['degree']?>'); 
		<?php }?>
		getAllGrade();
		branch_id = dijit.byId("branch_search").attr('value');
		if(branch_id!=''){
			branch_label = dijit.byId("branch_search").attr('displayedValue');
			$( "#lbl_branch" ).html(branch_label);
		}
		
	});
});

function generateTab(recordId,Title){
	let tabTitle = '<?= $tr->translate('CRM_SUMMARY') ?> ' + Title;
    let url = '<?= $this->baseUrl() ?>/allreport/allstudent/rpt-crm-detail/id/' + encodeURIComponent(recordId) + '?inFrame=true';
    addTab(tabTitle, url);
}

var url_dept = '<?php echo $this->url(array('module'=>'global','controller'=>'grade','action'=>'get-grade')); ?>';
function getAllGrade(){
	dept_id = dijit.byId('degree').get('value');
	if(dept_id==''){return false;}
	dojo.xhrPost({
		url:url_dept,
		content:{
			'dept_id':dept_id,
			'noaddnew':1
			},
		handleAs:"json",
		load: function(data) {
			grade_store  = getDataStorefromJSON('id','name', data);
			dijit.byId('grade').set('store',grade_store);   
			dijit.byId('grade').attr('value','<?php echo $this->search['grade']?>');  
		},
		error: function(err) {
		}
	});
}
</script>