<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$pageTitle = $tr->translate("RPT_STU_CHANGE_BRANCH");
	echo $this->headTitle($pageTitle); 
	$frm =  $this->form_search;
	$dateFormat ="d/m/y";
?>
<div class="layout-wrapper-report">
	<div id="mainContent" class="main-content-report">
		<div class="report-preview">
			<?php echo $this->controlReport?>
			<div id="main-viewer" class="main-viewer portrait">
				<div id="viewer" class="viewer portrait">
					<div id="divPrint" class="content">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style.css">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style-screen.css">
						<style>
							@media print {
								<?php if(!empty($this->printFormat)){ echo $this->printFormat; } ?>
							}
							.note{
								font-size: 80%;
								line-height: 12px;
								text-align: left;
								white-space: normal;
								overflow-wrap: break-word;
								
							}
						</style>
						<table border="0" style="background:#fff; margin: 0 auto; width: 100%; ">
							<tr>
								<td colspan="3"><?php echo $this->rsheader;?></td>
							</tr>
							<tr>
								<td width="15%" align="center"></td>
								<td width="70%"  align="center">
									<span class="text-color-black text-size-14px" style=" font-family:'Times New Roman','Khmer OS Muol Light';"><?php echo $pageTitle;?></span><br />
									<?php if(!empty($this->search["start_date"])){?>
									<span class="text-color-black text-size-12px" style=" font-family:'Times New Roman','Khmer OS Muol Light';"><?php echo date($dateFormat,strtotime($this->search["start_date"]))?> to <?php echo date($dateFormat,strtotime($this->search["end_date"]));?></span>
									<?php } ?>
								</td>
								<td width="15%" align="center"></td>
							</tr>
							<tr>
								<td id="exportExcel" colspan="3" valign="top">
									<table class="content-data bd-dark-grey bd-w1px text-color-black text-h16px text-size-12px" border="1" cellpadding="1"  >
										<thead>
											<tr class="bg-head style-head bd-black bd-w1px text-h16px hpx-25 text-bold">
												<td class="widthCol-px-30" rowspan="2">
													<?php echo $tr->translate("NUM") ?>
												</td>
												<td  rowspan="2"><?php echo $tr->translate("BRANCH") ?></td>
												<td  colspan="3" ><?php echo $tr->translate("STUDENT_INFO") ?></td>
												<td  colspan="2" ><?php echo $tr->translate("STUDY_INFO") ?></td>
												<td  rowspan="2"><?php echo $tr->translate("BRANCH") ?></td>
												<td  colspan="4" ><?php echo $tr->translate("NEW_STUDY_INFO") ?></td>
												<td class="wpx-120"  rowspan="2"><?php echo $tr->translate("REASON") ?></td>
												<td  rowspan="2"><?php echo $tr->translate("BY") ?></td>
											</tr>
											<tr class="bg-head style-head bd-black bd-w1px text-h16px hpx-25 text-bold">
												<td><?php echo $tr->translate("STUDENT_ID") ?></td>
												<td><?php echo $tr->translate("STUDENT_NAME") ?></td>
												<td><?php echo $tr->translate("GENDER") ?></td>
												
												<td ><?php echo $tr->translate("ACADEMIC_YEAR") ?></td>
												<td><?php echo $tr->translate("GROUP") ?></td>
												
												<td><?php echo $tr->translate("MOVING_DATE") ?></td>
												<td><?php echo $tr->translate("ACADEMIC_YEAR") ?></td>
												<td><?php echo $tr->translate("DEGREE") ?></td>
												<td><?php echo $tr->translate("GRADE") ?></td>
											</tr>
										</thead>
										<?php 
										$i=0;
										if(!empty($this->rs)) foreach($this->rs AS $row){?>
											<tr class="hover text-size-12px">
												<td align="center"><?php echo $i; ?></td>
												<td align="center"><?php echo $row["branchName"]?></td>
												<td align="center"><?php echo $row["stuCode"]?></td>
												<td align="left"><?php echo $row["stuNameKh"]?></td>
												<td align="center"><?php echo $row["sex"]?></td>	
												<td align="center"><?php echo $row["academicYearTitle"]?></td>	
												<td align="left"><?php echo $row["groupCode"]?></td>

												<td align="center"><?php echo $row["toBranchName"]?></td>									
												<td align="center"><?php echo date($dateFormat,strtotime($row["moving_date"]));?></td>									
												<td align="center"><?php echo $row["toAcademicYearTitle"]?></td>	
												<td align="left"><?php echo $row["toDegreeTitle"]?></td>
												<td align="left"><?php echo $row["toGradeTitle"]?></td>
												<td align="left" class="note"><?php echo $row["reason"]?></td>
												<td align="left"><?php echo $row["userName"]?></td>
											</tr>
										<?php } ?>
												
									</table>
									
								</td>
							</tr>
							<tr>
								<td colspan="3"><?php echo $this->rsfooter;?></td>
							</tr>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="right-panel-report" id="rightPanel">
		<div class="card-box">
			<div class="card-search-head col-sm-12 border-botom">
				<div class="col-sm-6 text-left pd-0">
					<h4 class="m-b-0">
						<?php echo $tr->translate("SEARCH");?> 
						<i class="fa fa-search "></i> 
					</h4>
				</div>
				<div class="col-sm-6 text-right pd-0">
					<button onclick="closeRightPanel()" title="<?php echo $tr->translate("CLOSED");?> " class="btn-close">
						<i class="fa-solid fa-xmark"></i>
					</button>
				</div>
			</div>
			<form  action="" dojoType="dijit.form.Form" method="post">
				<div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("adv_search");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("branch_id");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("academic_year");?>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm->getElement("degree");?>
					</div>
					<div class="col-md-6 col-sm-6 col-xs-12">
						<input id="grade" />
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm->getElement("start_date");?>
					</div>
					<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm->getElement("end_date");?>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<button class="button-class button-primary" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl(); ?>/js/help.js"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");
	
	dojo.ready(function () {
		new dijit.form.FilteringSelect({
			queryExpr: "*${0}*",
			autoComplete: false,
			required: false,
			id: "grade",
			name: "grade",
			class: 'fullside',
			placeHolder: "<?php echo $tr->translate("SELECT_GRADE"); ?>",
			onChange: function () {
			}
		}, "grade");

		var degree = dijit.byId('degree');
		degree.on('change', function (evt) {
			getallGrade();
		});
		getallGrade();
		setTimeout(function() {
			setPrintOrientation('landscape');
		}, 500);
	});
	
	var url_dept = '<?php echo $this->url(array('module' => 'global', 'controller' => 'grade', 'action' => 'get-grade')); ?>';
	function getallGrade() {
		dept_id = dijit.byId('degree').get('value');
		if (dept_id == '' || dept_id == -1) { return false; }
		dojo.xhrPost({
			url: url_dept,
			content: {
				'dept_id': dept_id,
				'noaddnew': 1
			},
			handleAs: "json",
			load: function (data) {
				dijit.byId('grade').attr('value', '');
				grade_store = getDataStorefromJSON('id', 'name', data);
				dijit.byId('grade').set('store', grade_store);
				dijit.byId('grade').attr('value', '<?php echo $this->search['grade'] ?>');
			},
			error: function (err) {
			}
		});
	}
</script>