<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("RPT_STUDENT_TEST"));
	$frm =  $this->form_search;
	$classHideHeight=classHideHeight;
	$dateFormat ="d/m/Y";
?>	
<style>
.hover:hover{ background:#ccc;}
table.content-data tr.style-head,
table.tb-footer tr.style-head {
   font-weight: bold !important;
}
</style>
<div class="layout-wrapper-report">
	<div id="mainContent" class="main-content-report">
		<div class="report-preview">
			<?php echo $this->controlReport?>
			<div id="main-viewer" class="main-viewer portrait">
				<div id="viewer" class="viewer portrait">
					<div id="divPrint" class="content">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style.css">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style-screen.css">
						<style>
							.hide{visibility: hidden;}
							@media print {
								<?php if(!empty($this->printFormat)){ echo $this->printFormat; } ?>
								.hide{visibility: visible; height: <?php echo $classHideHeight;?>;}
							}
							
							.normal-wrap {
								white-space: pre-line !important;
								line-height: 16px;
								text-align: left;
								width: 120px;
							}
							span.note{
								font-size:10px !important;
								line-height:12px !important;
								max-width: 150px; display: block; 
								width: 150px; display: block; 
								white-space: pre-line; 
								overflow-wrap: break-word;
								padding: 0 1px;
							}
						</style>
						<table  style="background:#fff; margin: 0 auto; width: 100%; ">
							<tr>
								<td colspan="3"><?php echo $this->rsheader;?></td>
							</tr>
							<tr>
								<td width="20%" align="right">
								</td>
								<td width="60%" align="center">
									<span style="color:#000; font-size: 12px;font-family:Times New Roman,'Khmer OS Muol Light';"><?php echo $tr->translate("RPT_STUDENT_TEST");?></span><br/>
									<span style="color:#000; font-size: 12px;font-family:Times New Roman,'Khmer OS Battambang';"><?php if(!empty($this->search['start_date'])){?><?php echo date($dateFormat,strtotime($this->search['start_date']));?> <?php echo $tr->translate("TO");?> <?php echo date($dateFormat,strtotime($this->search['end_date']));}?> </span>
								</td>
								<td width="20%" align="right"></td>
							</tr>
							<tr>
								<td colspan="3">
									<div id="exportExcel">
										<table class="content-data  text-color-black text-h14px text-size-11px bd-dark-grey" cellpadding="4" border="1" >
											<thead>
												<tr class="style-head bd-black bd-w1px style-head bg-head" align="center" >
													<td scope="col" rowspan="2"><?php echo $tr->translate("N_O"); ?></td>
													<td scope="col" rowspan="2"><?php echo $tr->translate("BRANCH"); ?></td>
													<td scope="col" colspan="4"><?php echo $tr->translate("STUDENT_INFO"); ?></td>
													<td scope="col" colspan="2"><?php echo $tr->translate("STUDY_INFO"); ?></td>
													<td scope="col" colspan="4"><?php echo $tr->translate("RESULT"); ?></td>
													
													
													<td scope="col" colspan="4"><?php echo $tr->translate("OTHER"); ?></td>
												</tr>
												<tr class="style-head bd-black bd-w1px style-head bg-head" align="center" >
													<td scope="col" class="w-px-90 breakword text-h14px"  >
													<?php echo $tr->translate("SERIAL"); ?>/<?php echo $tr->translate("STUDENT_ID"); ?></td>
													<td scope="col" class="w-px-120 breakword text-h14px" ><?php echo $tr->translate("STUDENT_NAME"); ?>&nbsp;</td>
													<td scope="col" class="w-px-30"><?php echo $tr->translate("SEX"); ?></td>
													<td scope="col" class="w-px-90"><?php echo $tr->translate("PHONE"); ?></td>
													<td scope="col" ><?php echo $tr->translate("ACADEMIC_YEAR"); ?></td>
													<td scope="col" ><?php echo $tr->translate("TEST_DATE"); ?>/<?php echo $tr->translate("TEST_TERM");?></td>
													<td scope="col" class="w-px-120 breakword text-h14px"><?php echo $tr->translate("DEGREE"); ?> <?php echo $tr->translate("GRADE"); ?></td>
													<td scope="col"><?php echo $tr->translate("RESULT_DATE"); ?></td>
													<td scope="col" style="line-height: 18px; padding: 2px;"><?php echo $tr->translate("RESULT_BY"); ?></td>
													<td scope="col" ><?php echo $tr->translate("NOTE"); ?></td>
													<td scope="col" ><?php echo $tr->translate("USER"); ?></td>
													<td scope="col" ><?php echo $tr->translate("STATUS"); ?></td>
													<td scope="col" ><?php echo $tr->translate("RESULT"); ?></td>
													<td scope="col" ><?php echo $tr->translate("PROCESS_TYPE"); ?></td>
												 </tr>
												
											</thead>
											<?php 
											$updated_result=0;
											$total_register=0;
											 $i=0;
											
											if(!empty($this->row)){ foreach($this->row as $rs){ $i++;?>
												  <tr class="style hover context-menu-one" oncontextmenu="setrowdata(<?php echo $rs['stu_id'];?>);return false;" align="center"  >
														<td data-label="<?php echo $tr->translate("N_O");?>" align="center"><?php echo $i;?></td>
														<td data-label="<?php echo $tr->translate("BRANCH");?>"><?php echo $rs['branchName']; ?></td>
														<td data-label="<?php echo $tr->translate("STUDENT_ID");?>"><?php echo $rs['serial']; ?><br /><?php echo $rs['stu_code']; ?></td>
														<td data-label="<?php echo $tr->translate("STUDENT_NAMEKHMER");?>" align="left"  >
														<?php echo $rs['stu_khname']; ?>
														<br />
														<?php echo $rs['last_name']." ".$rs['stu_enname']; ?>
														</td>
														<td data-label="<?php echo $tr->translate("SEX");?>" align="center" valign="center"><?php echo $rs['sex']; ?></td>
														<td class="normal-wrap" data-label="<?php echo $tr->translate("PHONE");?>"><?php echo $rs['tel']; ?></td>
														<td data-label="<?php echo $tr->translate("ACADEMIC_YEAR");?>"><?php echo $rs['academic']; ?></td>
														<td data-label="<?php echo $tr->translate("TEST_DATE");?>" style="padding: 2px;"><?php echo date($dateFormat, strtotime($rs['create_date_exam'])); ?><br /><?php echo $rs['study_term'];?></td>
														<td data-label="<?php echo $tr->translate("DEGREE");?>" ><?php if ($rs['updated_result_de']==1){ echo $rs['degree_result_title']; }?>
														
														<?php if ($rs['updated_result_de']==1){ echo "<br /><strong>".$rs['grade_result_title']."</strong>"; }?>
														<?php if (!empty($rs['partTimeTitle'])){ echo "<br />".$rs['partTimeTitle']; }?>
														
														</td>
														<td data-label="<?php echo $tr->translate("RESULT_DATE");?>" style="padding: 2px;"><?php if ($rs['updated_result_de']==1){ echo date($dateFormat, strtotime($rs['result_date'])); }?></td>
														<td data-label="<?php echo $tr->translate("RESULT_BY");?>" ><?php echo $rs['result_by'];?></td>	
														<td  data-label="<?php echo $tr->translate("NOTE");?>" align="left" ><span class="note" style="" ><?php echo $rs['note_result']; ?></span></td>
														<td data-label="<?php echo $tr->translate("USER");?>" valign="center"><?php echo $rs['user_id'];?></td>								    
														<td data-label="<?php echo $tr->translate("USER");?>" valign="center"><?php echo $rs['resultStatusTitle'];?></td>								    
														<td data-label="<?php echo $tr->translate("RESULT");?>" style=" <?php if($rs['updated_result_de']==0){echo " color:red;";}?>" ><?php echo $rs['result_status']; ?></td>
														<td data-label="<?php echo $tr->translate("STATUS");?>" style=" <?php if($rs['is_registered']==0){echo " color:red;";}?>"><?php if ($rs['is_registered']==1){ echo $tr->translate("REGISTERED");}else{ echo $tr->translate("PENDING");}?></td>							    
												  </tr>

												  <?php 
													if($rs['updated_result_de']==1){
														$updated_result = $updated_result + 1;
													}
													if($rs['is_registered']==1){
														$total_register = $total_register + 1;
													}
												  ?>
											  <?php }
											  }?>
										</table>	
										<?php if (!empty($this->row)){?>
										<table width="40%"  align="right" style="white-space: nowrap;font-family: 'Times New Roman','Khmer OS Battambang'; margin-top: 10px;">
											<tr align="right">
												<td>
													<ul style=" list-style: none; padding: 0;font-size: 12px;">
														<li>
															<?php echo $tr->translate("STUDENT_TOTAL");?> : <?php echo $i;?> <?php echo $tr->translate("STUDENT_UNIT");?>
														</li>
														<li>
															<?php echo $tr->translate("TOTAL_GET_RESULT");?> : <?php echo $updated_result;?> <?php echo $tr->translate("STUDENT_UNIT");?>
														</li>
														<li>
															<?php echo $tr->translate("TOTAL_NO_RESULT");?> : <?php echo ($i-$updated_result);?> <?php echo $tr->translate("STUDENT_UNIT");?>
														</li>
														<li>
															<?php echo $tr->translate("TOTAL_REGISTER_STUDENT");?> : <?php echo $total_register;?> <?php echo $tr->translate("STUDENT_UNIT");?>
														</li>
														<li>
															<?php echo $tr->translate("TOTAL_NOT_YET_REGISTER_STUDENT");?> : <?php  echo ($i-$total_register);?> <?php echo $tr->translate("STUDENT_UNIT");?>
														</li>
													</ul>
												</td>
											</tr>
										</table>
										<?php }?>
									</div>	
								</td>
							</tr>
							<tr>
								<td colspan="3">
									<?php echo $this->rsfooterFoundation;?>
								</td>
							</tr>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="right-panel-report" id="rightPanel">
		<div class="card-box">
			<div class="card-search-head col-sm-12 border-botom">
				<div class="col-sm-6 text-left pd-0">
					<h4 class="m-b-0">
						<?php echo $tr->translate("SEARCH");?> 
						<i class="fa fa-search "></i> 
					</h4>
				</div>
				<div class="col-sm-6 text-right pd-0">
					<button onclick="closeRightPanel()" title="<?php echo $tr->translate("CLOSED");?> " class="btn-close">
						<i class="fa-solid fa-xmark"></i>
					</button>
				</div>
			</div>
			<form  id='foundation_class' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
				<div class="form-group">
                   <div class="col-md-12 col-sm-12 col-xs-12">
                   		<?php echo $frm->getElement("adv_search");?>
                   </div>
                  <div class="col-md-12 col-sm-12 col-xs-12">
                   		<?php echo $frm->getElement("branch_id");?>
                   </div>
                    <div class="col-md-12 col-sm-12 col-xs-12">
                   		<?php echo $frm->getElement("academic_year");?>
                   </div>
                   <div class="col-md-12 col-sm-12 col-xs-12">
    	               	<input id="term_test" />
                   </div>
                   <div class="col-md-12 col-sm-12 col-xs-12">
                   		<?php echo $frm->getElement("degree");?>
                   </div>
				   <div class="col-md-12 col-sm-12 col-xs-12">
						<input id="partTimeList" />
                   </div>
                  
                </div>
                <div class="form-group">
					
					<div class="col-md-12 col-sm-12 col-xs-12">
    	               	<?php echo $frm->getElement("student_option_search");?>
                   </div>
				   <div class="col-md-12 col-sm-12 col-xs-12">
    	               	<?php echo $frm->getElement("province_search");?>
                   </div>
			   </div>
			   <div class="form-group">
					<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm->getElement("type_exam");?>
                   </div>
					<div class="col-md-6 col-sm-6 col-xs-12">
    	               	<?php echo $frm->getElement("resultStatus");?>
                   </div>
				</div>
			    <div class="form-group">
					<div class="col-md-6 col-sm-6 col-xs-12">
    	               	<?php echo $frm->getElement("result_status");?>
                   </div>
				   <div class="col-md-6 col-sm-6 col-xs-12">
    	               	<?php echo $frm->getElement("register_status");?>
                   </div>
                </div>
				<div class="form-group">
					<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm->getElement("start_date");?>
                   </div>
                   <div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm->getElement("end_date");?>
                   </div>
			   </div>
			    <div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
                   		<button class="button-class button-primary fullside" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
                   </div>
                   
                </div>
			</form>
		</div>
	</div>
</div>


<?php 
	$urlStudentProfile = $this->baseUrl()."/test/index/profile/id/";
?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore");  
var academic_store= getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
dojo.ready(function(){
	getAllTermStudy();
	new dijit.form.FilteringSelect({
		placeHolder:"<?php echo $tr->translate("SELECT_TERM");?>",   
		queryExpr: "*${0}*",
		autoComplete: false,                     
		required: false,                     
		id: "term_test",
		name: "term_test",
		class: "fullside", 		
		onChange: function() {  
		}
	}, "term_test");
	
	new dijit.form.FilteringSelect({
		autoComplete: false,
		queryExpr:'*${0}*',                        
		required: false,
		id: "partTimeList",
		name: "partTimeList",           
		class: "fullside", 
		placeHolder:"<?php echo $tr->translate('PART_TIME_LIST');?>",          
		onChange: function() {  
		}
	}, "partTimeList");
		
	 var branch_id = dijit.byId('branch_id');
	 branch_id.on('change', function(evt) {
		 getAllTermStudy();
    });
	var degree = dijit.byId('degree');
	 degree.on('change', function(evt) {
		 getPartTimeListByDregree();
    });

	getPartTimeListByDregree();
	
	setTimeout(function() {
		setPrintOrientation('landscape');
	}, 500);
});

var url_term_study = '<?php echo $this->url(array('module'=>'test','controller'=>'index','action'=>'gettermstudy'));?>';

function getAllTermStudy(){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		return false;
	}

	dojo.xhrPost({
		url: url_term_study,
		content:{
			'branch_id':branch_id,
			'option':0
		},
		handleAs:"json",
		load: function(data){
			term_store  = getDataStorefromJSON('id','name', data);
			dijit.byId('term_test').set('store',term_store); 
			<?php if (!empty($this->search['term_test'])){?>
				dijit.byId('term_test').attr('value','<?php echo $this->search['term_test']?>');  
			<?php }?>
		},
		error: function(err) {
			alert(err);
		}
	});
}

var urlGetParttime = '<?php echo $this->url(array('module'=>'global','controller'=>'parttimelist','action'=>'get-parttime')); ?>';
function getPartTimeListByDregree(){
	degree = dijit.byId('degree').get('value');
	branchId = dijit.byId('branch_id').get('value');
	if(degree==''){
		return false;
	}
	dojo.xhrPost({
		url: urlGetParttime,
		content:{
			'degree':degree,
			'branchId':branchId,
			},
		handleAs:"json",
		load: function(data) {
			partTimeListStore  = getDataStorefromJSON('id','name', data);
			dijit.byId('partTimeList').set('store',partTimeListStore);  
			<?php if (!empty($this->search['partTimeList'])){?>
				dijit.byId('partTimeList').set('value',<?php echo $this->search['partTimeList'];?>);
			<?php }?>
		},
		error: function(err) {
		}
	});
}
function getallGrade(){
}

var row=0;
var url="";
$(function(){
	$.contextMenu({
		selector: '.context-menu-one', 
		callback: function(key, options) {
			var m = "clicked: " + key;
			if(key=="profile"){
				url='<?php echo $urlStudentProfile;?>';
			}
			gotoAction();
		},
		items: {
			"profile": {name: "<?php echo $tr->translate("STUDENT_INFO");?>", icon: "fa-solid fa-address-card",},
		}
	});
});
function setrowdata(index){
	row = index;
}
var recordid ='';
function gotoAction(){
	window.open(url+row);
}
</script>


