<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('STUDENT_NOT_YET_REPORT')); 
	echo $this->headTitle(''); 
	$frm =  $this->form_search;
	$classHideHeight="110px";

?>	
<style>
	.hover:hover{ background:#ccc;}
	.hidden{visibility: visible !important;
	display: table-cell !important;
}
</style>
<div class="layout-wrapper-report">
	<div id="mainContent" class="main-content-report">
		<div class="report-preview">
			<?php echo $this->controlReport?>
			<div id="main-viewer" class="main-viewer portrait">
				<div id="viewer" class="viewer portrait">
					<div id="divPrint" class="content">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style.css">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style-screen.css">
						<style>
							.hide{visibility: hidden;}
							@media print {
								<?php if(!empty($this->printFormat)){ echo $this->printFormat; } ?>
								.hide{visibility: visible; height: <?php echo $classHideHeight;?>;}
							}
						</style>
						
						<table border="0" style="margin: 0 auto; width: 100%; ">
							<tr>
								<td colspan="3"><?php echo $this->rsheader;?></td>
							</tr>
							<tr>
								<td width="15%" align="center">
								</td>
								<td width="70%"  align="center">
									<strong class="text-size-14px text-h16px text-normal " style="font-family: Arial Black;font-family:'Khmer OS Muol Light';"><?php echo $tr->translate("STUDENT_NOT_YET_REPORT");?></strong><br />
									<strong class="text-size-12px text-h14px text-normal" style="font-family: Arial Black;font-family:'Khmer OS Muol Light';"><?php if(!empty($this->search['start_date'])){?><?php echo date('d-M-Y',strtotime($this->search['start_date']));?> <?php echo $tr->translate("TO");?> <?php echo date('d-M-Y',strtotime($this->search['end_date']));}?> </strong>
								</td>
								<td width="15%" align="center">
								</td>
							</tr>
							<tr>
								<td colspan="3">
								<div id="exportExcel">
									<table class="content-data text-color-black text-size-11px  text-h14px bd-dark-grey" cellpadding="4"  border="1" >
										<thead>
											<tr class="style-head bd-black bd-w1px style-head bg-head text-center" align="center" >
												<th scope="col"  rowspan="2" class="w-px-30"><?php echo $tr->translate("NUM");?></th>
												<th scope="col" rowspan="2" class="w-px-50"><?php echo $tr->translate("BRANCH");?></th>
												<th scope="col" colspan="5"><?php echo $tr->translate("STUDENT_INFO");?></th>
												<th scope="col" colspan="2"><?php echo $tr->translate("CONTACT_INFO");?></th>
												<th scope="col" colspan="4"><?php echo $tr->translate("STUDY_INFO");?></th>
												<th scope="col"  rowspan="2"><?php echo $tr->translate("STATUS");?></th>
											</tr>
											<tr class="style-head bd-black bd-w1px style-head bg-head text-center" align="center" >
												<th scope="col" class="w-px-90"><?php echo $tr->translate("STUDENT_CODE");?></th>
												<th scope="col" class="w-px-120"><?php echo $tr->translate("STUDENT_NAMEKHMER");?></th>
												<th scope="col" class="w-px-120"><?php echo $tr->translate("NAME_ENGLISH");?></th>
												<th scope="col" class="w-px-30"><?php echo $tr->translate("SEX");?></th>
												<th scope="col" class="w-px-50"><?php echo $tr->translate("NATIONALITY");?></th>
												<th scope="col" class="w-px-120"><?php echo $tr->translate("PHONE");?></th>
												<th scope="col" class="w-px-120"><?php echo $tr->translate("EMAIL");?></th>
												<th scope="col" class="w-px-80"><?php echo $tr->translate("ACADEMIC_YEAR");?></th>
												<th scope="col" class="w-px-80"><?php echo $tr->translate("DEGREE");?></th>
												<th scope="col" class="w-px-80"><?php echo $tr->translate("GRADE");?></th>
												<th scope="col" class="w-px-100"><?php echo $tr->translate("GROUP");?></th>
											</tr>
										</thead>
									<?php $i=0;$degree=0;foreach ($this->rs AS $row) { $i++;$degree=$row['degree'];?>
										<tr  align="center" class="hover style" >
											<td  data-label="<?php echo $tr->translate("NUM");?>"><?php echo $i;?></td>
											<td  data-label="<?php echo $tr->translate("BRANCH");?>" ><?php echo $row['branch_name'];?></td>
											<td data-label="<?php echo $tr->translate("STUDENT_CODE");?>"  ><?php echo $row['stu_code'];?></td>
											<td data-label="<?php echo $tr->translate("STUDENT_NAMEKHMER");?>"  align="left"><?php echo $row['stu_khname'];?></td>
											<td data-label="<?php echo $tr->translate("NAME_ENGLISH");?>"  align="left"><?php echo $row['last_name']." ".$row['stu_enname'];?></td>
											<td data-label="<?php echo $tr->translate("SEX");?>"  ><?php echo $row['sextitle'];?></td>	
											<td data-label="<?php echo $tr->translate("NATIONALITY");?>"  ><?php echo $row['nationality'];?></td>
											<td data-label="<?php echo $tr->translate("PHONE");?>" align="left" ><?php echo $row['tel'];?></td>
											<td data-label="<?php echo $tr->translate("EMAIL");?>"  align="left"><?php echo $row['email'];?></td>
											<td data-label="<?php echo $tr->translate("ACADEMIC_YEAR");?>"  ><?php echo $row['academic_year'];?></td>
											<td data-label="<?php echo $tr->translate("DEGREE");?>" align="left" ><?php echo $row['degree'];?></td>
											<td data-label="<?php echo $tr->translate("GRADE");?>"  align="left"><?php echo $row['grade'];?></td>
											<td data-label="<?php echo $tr->translate("GROUP");?>"  align="left"><?php echo $row['group_name'];?></td>
											<td data-label="<?php echo $tr->translate("SEX");?>"  ><?php if($row['is_setgroup']==1){ echo $tr->translate("IS_GROUP");}else { echo $tr->translate("NOT_YET_GROUP");}?></td>	
										</tr>
									<?php }?>	
									</table>	
								</div>	
								</td>
							</tr>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="right-panel-report" id="rightPanel">
		<div class="card-box">
			<div class="card-search-head col-sm-12 border-botom">
				<div class="col-sm-6 text-left pd-0">
					<h4 class="m-b-0">
						<?php echo $tr->translate("SEARCH");?> 
						<i class="fa fa-search "></i> 
					</h4>
				</div>
				<div class="col-sm-6 text-right pd-0">
					<button onclick="closeRightPanel()" title="<?php echo $tr->translate("CLOSED");?> " class="btn-close">
						<i class="fa-solid fa-xmark"></i>
					</button>
				</div>
			</div>
			<form  id='foundation_class' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
				<div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("adv_search");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("branch_id");?>
					</div>
					
				</div>
				<div class="form-group">
					<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm->getElement("degree");?>
				    </div>
				   <div class="col-md-6 col-sm-6 col-xs-12">
						<input id="grade" />
				   </div>
				</div>
				<div class="form-group">
					<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm->getElement("academic_year");?>
					</div>
					<div class="col-md-6 col-sm-6 col-xs-12">
						<input id="group" />
				   </div>
				</div>
				<div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("student_group_status");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<button class="button-class button-primary fullside" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
				   </div>
				</div>
			</form>
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore"); 
var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
dojo.ready(function(){
	new dijit.form.FilteringSelect({
		queryExpr: "*${0}*",
		autoComplete: false, 
		required: false,
		id: "grade",
		name: "grade",           
		class: 'fullside',  
		placeHolder:"<?php echo $tr->translate("SELECT_GRADE");?>",          
		onChange: function() {  
		}
	}, "grade");

	new dijit.form.FilteringSelect({
		store : group_store,
		queryExpr: "*${0}*",
		autoComplete: false, 
		required: false,
		id: "group",
		name: "group",           
		class: 'fullside',  
		placeHolder:"<?php echo $tr->translate("SELECT_GROUP");?>",          
		onChange: function() {  
		}
	}, "group");

	var branch_id = dijit.byId('branch_id');
	 branch_id.on('change', function(evt) {
		getAllGroupByBranch();
	  });
	getallGrade();
	getAllGroupByBranch();
	<?php if($this->search['student_group_status']>-1){?>
	 dijit.byId('student_group_status').attr('value','<?php echo $this->search['student_group_status']?>'); 
	<?php } ?>	 
	setTimeout(function() {
		setPrintOrientation('landscape');
	}, 500);
});

var url_dept = '<?php echo $this->url(array('module'=>'global','controller'=>'grade','action'=>'get-grade')); ?>';
function getallGrade(){
	getAllGroupByBranch();
	dept_id = dijit.byId('degree').get('value');
	if(dept_id=='' || dept_id==-1){return false;}
		dojo.xhrPost({
			url:url_dept,
			content:{
				'dept_id':dept_id,
				'noaddnew':1
				},
			handleAs:"json",
			load: function(data) {
				dijit.byId('grade').attr('value','');
				grade_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('grade').set('store',grade_store); 
			    dijit.byId('grade').attr('value','<?php echo $this->search['grade']?>');    
			},
			error: function(err) {
			}
		});
}
var url_getgroup = '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'getallgroup'));?>';
function getAllGroupByBranch(){
	dijit.byId('group').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('group').set('store',group_store);  
		dijit.byId('branch_id').focus();
		return false;
	}
	degree = dijit.byId('degree').get('value');
	if(degree=='' || degree==-1){degree ="";}
	grade = dijit.byId('grade').get('value');
	if(grade=='' || grade==-1){grade ="";}
	academic_year = dijit.byId('academic_year').get('value');
	if(academic_year=='' || academic_year==-1){academic_year ="";}
	
	dojo.xhrPost({
		url: url_getgroup,
		content:{
			'branch_id':branch_id,
			'degree':degree,
			'grade':grade,
			'academic_year':academic_year,
			'noaddnew':1,
			'forfilter':1
			},
		handleAs:"json",
		load: function(data) {
		    group_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('group').set('store',group_store);   
			dijit.byId('group').attr('value','<?php echo $this->search['group']?>');  
		  
		},
		error: function(err) {
		}
	});
	
}
</script>