<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_KNOW_BY')); 
?>	
<?php  $classname= $this->frm_classname;?>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
						<h4 class="m-b-0">
						<i class="glyphicon glyphicon-blackboard" aria-hidden="true"></i>
						&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_KNOW_BY');?>
						<small id="msg_deplicate" class="red italic"></small>
						</h4>
					</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<form  id='frmAddData' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				title=dijit.byId("title").get('value');
				if(title=='' || title==null){
					dijit.byId("title").focus();
					return false;
				}
				if (isDuplicate == 1) {
					alert("<?php echo $tr->translate("DUPLICATED_RECORD"); ?>");
					$("#msg_deplicate").html("<?php echo $tr->translate("DUPLICATED_RECORD"); ?>");
					dijit.byId("title").focus();
					return false;
				}
				loadingBlock();	
                dijit.byId("save_close").attr("disabled",true);
				dijit.byId("save_new").attr("disabled",true);
				return true;
			}else {
				return false;
			}
			</script>
			<div class="card-box">			 
				<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-blackboard"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("KNOW_BY");?></p>
										</div> 
									</div>
									<div class="form-group">
									   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("TITLE");?> <span class="required">*</span>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php  echo $classname->getElement('title');?>
									   </div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="clearfix"></div>
				 <div class="card-box mt-20">
					<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
						<input type="button" class="button-class button-danger"  iconClass="glyphicon glyphicon-repeat" onClick="submitDataClose()" value="save_close" name="save_close" id="save_close" label="<?php echo $tr->translate('SAVE_CLOSE');?>" dojoType="dijit.form.Button"  />
						<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" value="save_new" name="save_new" id="save_new" label="<?php echo $tr->translate('SAVE_NEW');?>" dojoType="dijit.form.Button" />
					</div>
				 </div>
           </div>
         </div>
		</form>
	</div>
</div>


<script type="text/javascript">

dojo.ready(function(){
	 	var title = dijit.byId('title');
		 title.on('keyUp', function(evt) {
			checkingDuplicate();
	    });
});
var isDuplicate = 0;
var urlCheckDuplicate = '<?php echo $this->url(array('module'=>'global','controller'=>'knowby','action'=>'checkduplicate')); ?>';
function checkingDuplicate(){
	title = dijit.byId('title').get('value');
	dojo.xhrPost({
		url: urlCheckDuplicate,
		content:{
			'title':title
			},
		handleAs:"json",
		load: function(data) {
			isDuplicate = 0;
			if(data>0){
				isDuplicate = 1;
				alert("<?php echo $tr->translate("DUPLICATED_RECORD"); ?>");
				$("#msg_deplicate").html("<?php echo $tr->translate("DUPLICATED_RECORD"); ?>");
				dijit.byId("title").focus();
			}else{
				$("#msg_deplicate").html("");
			}
		},
		error: function(err) {
		}
	});
}
function submitDataClose(){
	if(dijit.byId('frmAddData').validate()) {
		title=dijit.byId("title").get('value');
		if(title=='' || title==null){
			dijit.byId("title").focus();
			return false;
		}
		dijit.byId('save_close').set('disabled',true);
		dijit.byId('save_new').set('disabled',true);
		var url_submit = '<?php echo $this->url(array('module'=>'global','controller'=>'knowby','action'=>'add')); ?>';
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("frmAddData"),		    
			load: function(data){
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				window.location.href ="<?php echo $this->baseUrl();?>/global/knowby";
			},			
			error: function(e) {
			}
		});
	}
}
</script>