<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();

$defaultmockupAppImage = $this->baseUrl()."/images/slide/app-utility/mockupAppImage.png";
if(!empty($this->row['mockupAppImage']['keyValue'])){
	if (file_exists(PUBLIC_PATH."/images/slide/app-utility/".$this->row['mockupAppImage']['keyValue'])){
		$defaultmockupAppImage = $this->baseUrl().'/images/slide/app-utility/'.$this->row['mockupAppImage']['keyValue'];
	}
}


$defaultqrImage = $this->baseUrl()."/images/slide/app-utility/qrcodeAppLink.png";
if(!empty($this->row['qrcodeAppLink']['keyValue'])){
	if (file_exists(PUBLIC_PATH."/images/slide/app-utility/".$this->row['qrcodeAppLink']['keyValue'])){
		$defaultqrImage = $this->baseUrl().'/images/slide/app-utility/'.$this->row['qrcodeAppLink']['keyValue'];
	}
}


?>
<style>
   
   img.image_view{
      height: 150px;
   }
   img.image_qrcode{
      height: 150px;
   }
   div.button_browse{
      width: 150px;
   }
   div.bt{
      width: 200px;
   }
  
   
</style>

<title><?php echo $tr->translate("MOBILE_SETTING");?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
        	<div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-cogs" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('MOBILE_SETTING');?></h4>
	    		</div>
	    		<div class="col-sm-4 text-right">
	    		</div>
    		</div>
    	</div>
    	<form action="" method="post" dojoType="dijit.form.Form"  enctype="multipart/form-data" >
    		<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
					loadingBlock();
					return true;
				}else{
					return false;
				}
			</script>
			<div class="card-box">
				<div class="col-md-3 col-sm-3 col-xs-12">
					<ul class="nav verticle-tab md-pills pills-primary nav-tab" role="tablist">
						
						<li class="nav-item active">
							<a class="nav-link" data-toggle="tab" href="#panelSettingStudent" role="tab">
							<i class="fa fa-graduation-cap ml-2"></i> <?php echo $tr->translate("STUDENT");?>
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" data-toggle="tab" href="#panelSettingTeacher" role="tab">
							<i class="fa fa-briefcase ml-2"></i> <?php echo $tr->translate("TEACHER");?>
							</a>
						</li>
					</ul>
				</div>
				<div class="col-md-9 col-sm-9 col-xs-12">
					<!-- Tab panels -->
					<div class="tab-content vertical">
						<!--Panel 1-->
						<div class="tab-pane fade in active" id="panelSettingStudent" role="tabpanel">
							<div class="col-md-12 col-sm-12 col-xs-12">
								<div class="card-blogform">
									<div class="card-body"> 
										<div class="row"> 
											<div class="col-md-12 col-sm-12 col-xs-12"> 
												<div class="d-flex"> 
													<div class="settings-main-icon ">
														<i class="fa fa-university" aria-hidden="true"></i>
													</div> 
													<div class="col-md-10 col-sm-10 col-xs-12"> 
														<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("STUDENT");?></p>
													</div> 
												</div>
											</div>
										</div>
										<div class="form-group">
											<label class="control-label col-md-4 col-sm-4 col-xs-12">
												<?php echo $tr->translate("maxAmountDayRequestPermission");?> :
											</label>
										    <div class="col-md-8 col-sm-8 col-xs-12">
												<input type="text" placeholder="<?php echo $tr->translate("maxAmountDayRequestPermission");?>" value="<?php echo $this->row['amountRequestPermission']['keyValue']?>"  name="amountRequestPermission" id="amountRequestPermission" dojoType="dijit.form.NumberTextBox" class="fullside"  />
										   </div>
										</div>
										<div class="form-group">
											<label class="custom-switch  "> 
												<input type="checkbox" <?php if(!empty($this->row['displayPmtValidate']['keyValue'])) { echo "checked"; }else{ echo ""; }?>  id="displayPmtValidate" name="displayPmtValidate"  class="custom-switch-input" > 
												<span class="custom-switch-indicator custom-radius"></span> 
												<a href="javascript:void(0);" class="tx-14 mb-0 me-2"><?php echo $tr->translate('displayPmtValidate')?></a> 
											</label>
										</div>
										<?php
											$spIdetity="";
											if(!empty($this->stuFeature)){?>
											<br />
											<br />
											<div class="row"> 
												<div class="col-md-12 col-sm-12 col-xs-12"> 
													<div class="d-flex"> 
														<div class="settings-main-icon ">
															<i class="fa fa-tasks" aria-hidden="true"></i>
														</div> 
														<div class="col-md-10 col-sm-10 col-xs-12"> 
															<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("FEATURE");?></p>
														</div> 
													</div>
												</div>
											</div>
											<?php foreach($this->stuFeature as $sFt){ 
												if(empty($spIdetity)){
													$spIdetity=$sFt['id'];
												}else{
													$spIdetity=$spIdetity.",".$sFt['id'];
												}
											
											?>
											<div class="form-group">
												<label class="control-label col-md-8 col-sm-8 col-xs-12">
													<?php echo $tr->translate($sFt["title"]);?>
													<small><?php echo $sFt['description'];?></small>
												</label>
												<div class="col-md-4 col-sm-4 col-xs-12">
													<label class="custom-switch  "> 
														<input type="checkbox" <?php if(!empty($sFt['status'])) { echo "checked"; }else{ echo ""; }?>  id="sFt<?php echo $sFt['id'];?>" name="sFt<?php echo $sFt['id'];?>"  class="custom-switch-input" > 
														<span class="custom-switch-indicator custom-radius"></span> 
														<a href="javascript:void(0);" class="tx-14 mb-0 me-2"></a> 
													</label> 
												</div>
											</div>
											<?php } ?>
											<input type="hidden" value="<?php echo $spIdetity;?>"  name="spIdetity" id="spIdetity" dojoType="dijit.form.TextBox" class="fullside"  />
										<?php } ?>
										
									</div>
								</div>
							</div>
						</div>
						<!--Panel 1-->
						<div class="tab-pane fade " id="panelSettingTeacher" role="tabpanel">
							<div class="col-md-12 col-sm-12 col-xs-12">
								<div class="card-blogform">
									<div class="card-body"> 
										<div class="row"> 
											<div class="col-md-12 col-sm-12 col-xs-12"> 
												<div class="d-flex"> 
													<div class="settings-main-icon ">
														<i class="fa fa-briefcase" aria-hidden="true"></i>
													</div> 
													<div class="col-md-10 col-sm-10 col-xs-12"> 
														<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("TEACHER");?></p>
													</div> 
												</div>
											</div>
										</div>
										<div class="form-group">
											<label class="control-label col-md-4 col-sm-4 col-xs-12">
												<?php echo $tr->translate("intervalMinAtt");?> :
											</label>
										    <div class="col-md-8 col-sm-8 col-xs-12">
												<input type="text" placeholder="<?php echo $tr->translate("intervalMin");?>" value="<?php echo empty($this->row['intervalMinAtt']['keyValue']) ? 0 : $this->row['intervalMinAtt']['keyValue'];?>"  name="intervalMinAtt" id="intervalMinAtt" dojoType="dijit.form.NumberTextBox" class="fullside"  />
										   </div>
										</div>
										<div class="form-group">
											<label class="control-label col-md-4 col-sm-4 col-xs-12">
												<?php 
												echo $tr->translate("settingEvaluation"); 
												$settingEvaluation = empty($this->row['settingEvaluation']['keyValue']) ? 0 : $this->row['settingEvaluation']['keyValue'];
												?> :
											</label>
										    <div class="col-md-8 col-sm-8 col-xs-12">
												<select  class="fullside" name="settingEvaluation" id="settingEvaluation" placeholder="<?php echo $tr->translate("settingEvaluation");?>" class="fullside"  dojoType="dijit.form.FilteringSelect" >
													<option value="0" <?php if ($settingEvaluation==0){ echo 'selected="selected"';} ?>><?php echo $tr->translate("ALL");?></option>
													<option value="1" <?php if ($settingEvaluation==1){ echo 'selected="selected"';} ?>><?php echo $tr->translate("ONLY_MONTHLY");?></option>
												</select>
											</div>
										</div>
										
										<?php
											$tIdetity="";
											if(!empty($this->tFeature)){?>
											<br />
											<br />
											<div class="row"> 
												<div class="col-md-12 col-sm-12 col-xs-12"> 
													<div class="d-flex"> 
														<div class="settings-main-icon ">
															<i class="fa fa-tasks" aria-hidden="true"></i>
														</div> 
														<div class="col-md-10 col-sm-10 col-xs-12"> 
															<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("FEATURE");?></p>
														</div> 
													</div>
												</div>
											</div>
											<?php foreach($this->tFeature as $tFt){ 
												if(empty($tIdetity)){
													$tIdetity=$tFt['id'];
												}else{
													$tIdetity=$tIdetity.",".$tFt['id'];
												}
											
											?>
											<div class="form-group">
												<label class="control-label col-md-8 col-sm-8 col-xs-12">
													<?php echo $tr->translate($tFt["title"]);?>
													<small><?php echo $tFt['description'];?></small>
												</label>
												<div class="col-md-4 col-sm-4 col-xs-12">
													<label class="custom-switch  "> 
														<input type="checkbox" <?php if(!empty($tFt['status'])) { echo "checked"; }else{ echo ""; }?>  id="tFt<?php echo $tFt['id'];?>" name="tFt<?php echo $tFt['id'];?>"  class="custom-switch-input" > 
														<span class="custom-switch-indicator custom-radius"></span> 
														<a href="javascript:void(0);" class="tx-14 mb-0 me-2"></a> 
													</label> 
												</div>
											</div>
											<?php } ?>
											<input type="hidden" value="<?php echo $tIdetity;?>"  name="tIdetity" id="tIdetity" dojoType="dijit.form.TextBox" class="fullside"  />
										<?php } ?>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="clearfix"></div>
		    <div class="card-box">
               	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
               		 <input type="hidden" name="id" value="<?php echo $this->rs['code'];?>"  />
		  			 <input class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" type="submit" value="រក្សាទុក" label="<?php echo $tr->translate("SAVE");?>" dojoType="dijit.form.Button"  /> 
	    		</div>
	    	</div>
		</form>
	</div>
</div>

<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script>
dojo.require('dijit.form.NumberTextBox');
   function loadImage(){
	 var output = document.getElementById('image_view');
    output.src = URL.createObjectURL(event.target.files[0]);
}

function loadqrImage(){
	 var output = document.getElementById('image_qrcode');
    output.src = URL.createObjectURL(event.target.files[0]);
}

</script>