<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
	echo $this->headTitle("កាលវិភាគបណ្ដោះអាសន្ន"); 
	
	$subjectCounting =  $this->rsCouning;
	$db_global = new Application_Model_DbTable_DbGlobal();
	$lang_id  = $db_global->currentlang();
?>
<div style="min-height:15cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">	
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file-text " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo "កាលវិភាគបណ្ដោះអាសន្ន";?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
				<a class="qButton print" href="#" title="បោះពុម្ព" onclick="doPrintProfle('divPrint');"><i class="fa fa-print" aria-hidden="true"></i></a>
											
    		</div>
    	</div>
    </div>
	<div id="divPrint">
		<style>
			table.main_table tr td{
			line-height:16px !important;
			border: 1px solid #000;
			border-collapse: collapse;
			font-size:12px !important;
			padding:4px 0px;}
			table.main_table tr ul li{font-size:12px !important;}
		</style>
		<table width="100%" style="background:#fff;margin: 0 auto;width: 100%; font-family: 'Times New Roman','Kh Battambang','Khmer Battambang';">
			<style>
			.principalStamp {
					position:relative;
					width: 300px;
   					height: 140px;
					margin:0 auto;
					margin-top:-5px;
				}
				.principalStamp .stamp {
					width:140px;
					height:140px;
					position:absolute;
					transform: translate(-81%);
					left:50%;
				}
				.principalStamp .signature {
					left: 40px;
					bottom: 32px;
					height: 100px;
					width:150px;
					position: absolute;
				}
				.principalStamp .principalName{
					left: 130px;
				    top: 113px;
				    height: 100px;
				    width: 100px;
				    position: absolute;
				}
				.seenApproved{
					position: relative;
				}
				.seenApproved .interimPrincipal{
					position: absolute;
					left: 50%;
				    top: 20px;
				    transform: translate(-50%);
				    z-index: 1;
				}
				
				.hover:hover{background: #ccc;}
				table { page-break-inside:auto }
				  tr{ page-break-inside:avoid; page-break-after:auto; }
				#header {
				  display: table-header-group;
				  page-break-inside:avoid; page-break-after:auto;
				}
				tr.head_schedule th {
				    text-align: center;
				}
				tr.head_schedule {
				    background-color: #ffdbdb;
				}
				tr.head_schedule_blue th {
				    text-align: center;
				}
				tr.head_schedule_blue {
				    color:blue;
				}
				
				ul.subject {
				    list-style: none;
				    padding: 0;
				    line-height: 20px;
				    margin: 0;
				}
				tr.line td{ border-bottom: 1px solid #000;}
				.padding-top{padding-top:20px;}

				.headerKhmer {
					font-size: 13px;
					line-height: 12px;
					font-weight: initial;
					font-family: 'Times New Roman','Khmer OS Muol Light', serif;
				}
				.headerLabel {
				font-size: 14px;
				line-height: 12px;
				font-weight: initial;
				font-family: 'Times New Roman','Khmer OS Muol Light';
				}
				span.valueLabel.khmerLabel {
				font-size: 12px;
				font-weight: normal !important;
				font-family: 'Times New Roman', 'Khmer OS Muol Light';
				line-height: 12px;
				}
				@media print {
					@page {
						page:A4;
						margin:0.8cm 0.8cm 0cm 0.8cm;
					}
				}
				.pages-break {
					page-break-inside: always;
					page-break-before: always;
				}
				.blue{
					color: blue;
				}
				.red{
					color: red;
				}
			</style>
				<?php $title=0; $titles=0; $year='';$group='';$hour=''; if(!empty($this->rs)) 
					foreach ($this->rs As $rs){
						$title=0; $titles=0;
						
						$day = json_decode($rs['jsonDay'], TRUE);
						
						$jsonSubject = json_decode($rs['jsonSubject'], TRUE);
						$amt_day = count($day);
						$break_page = "pages-break";

						$logo = $this->baseUrl() . '/images/logo/logo.png';
						if (!empty($rs['branch_logo'])) {
							$logo = $this->baseUrl() . '/images/logo/' .$rs['branch_logo'];
						}
						$class_head_schedule="head_schedule";
						$color_time="";
						$color_teacher="red";
						$blue="";
						if($rs['degree']==1){
							$class_head_schedule="head_schedule_blue";
							$color_time="red";
							$color_teacher="blue";
							$blue="blue";
						}
						
						
						$arrayTime=array();
						$stringDaySubject='';
						$stringDayHead='<tr class="'.$class_head_schedule.'" style="font-size:10px;line-height:16px;" align="center" >';
							$stringDayHead.='<td rowspan="2" >'.$tr->translate("TIME").'</td>';
							$stringDayHead.='<td colspan="'.$amt_day.'" >'.$tr->translate("DAYS").'</td>';
						$stringDayHead.='</tr>';
						if(!empty($day)){
							$stringDayHead.='<tr class="'.$class_head_schedule.'" style="font-size:11px;line-height:16px;" align="center" >';	
							foreach ($day as $key => $days){
								
								$strFilter =  (string) $days['dayId'];
								$resultOfSubject = array_filter($jsonSubject, function ($item) use ($strFilter) {
									if ($item['dayId'] == $strFilter) {
										return $item;
									}
									return;
								});
								
								$subjectCol="";
								if(!empty($resultOfSubject)){
									foreach($resultOfSubject as $sub){
										$keyTime = $sub["frTimeT"]."-".$sub["toTimeT"];
										$subject = $sub["sTitleEn"];
										if($sub["sLang"]==1){
											$subject = $sub["sTitleKh"];
										}
										$arrayItem = array(
											'subject'=>$subject,
											'tNameEn'=>$sub["tNameEn"],
											'tNameKh'=>$sub["tNameKh"],
											'tTel'=>$sub["tTel"],
										);
										
										if (array_key_exists($keyTime, $arrayTime)) {
											array_push($arrayTime[$keyTime]["subjectList"], $arrayItem);
										}else{
											$arrayTime[$keyTime] = array(
												'frTime'=>$sub["frTime"],
												'toTime'=>$sub["toTime"],
												'subjectList'=>array(),
											);
											array_push($arrayTime[$keyTime]["subjectList"], $arrayItem);
											
										}
									}
									
								}
											
								$stringDayHead.='<td>'.$days['dTitle'].'</td>';
							}
							$stringDayHead.='</tr>';
						}
				?>

				<?php if($rs['degree']==1) {?>
					<tr class="<?php echo $break_page; ?> ">
						<td colspan="3" valign="top" style="margin-top:20px;">
							<table width="100%">
								<tr>
									<td align="center" valign="top"  width="30%">
										<img style="max-height:100px; margin-top: -8px;" src="<?php echo $logo; ?>">
									</td>
									<td  align="center" width="40%" valign="top" >
										<h2 class="headerKhmer blue ">
											<?php echo $rs['school_namekh']?>
										</h2>
										<h2 class="headerKhmer red ">
											<?php echo $rs['school_nameen']?>
										</h2>
										<h2 class="headerKhmer blue ">
											កាលវិភាគបណ្ដោះអាសន្ន
											<?php echo $db_global->getNumberInkhmer(date($rs['academicYear'])); ?>
										</h2>
										<h2 class="headerKhmer blue " valign="top" >
											PRE-SCHEDULE FOR ACADEMIC YEAR 
											<?php echo $rs['academicYear']; ?>
										</h2>
									</td>
									<td align="center" width="30%">
									</td>
								</tr>
							</table>
						</td>
					</tr>
				<?php }else{ ?>
					<tr class="<?php echo $break_page; ?> ">
						<td colspan="2" valign="bottom">
							
						</td>
						<td align="center" valign="top" width="35%">
						</td>
					</tr>

					<tr >
						<td colspan="3" align="center">
							<?php // echo $this->rsheader;?>
							<span style=" font-size:12px;font-weight: initial;font-family:'Times New Roman','Khmer OS Muol Light';">កាលវិភាគបណ្ដោះអាសន្ន</span></br>
							<span style=" font-size:12px;font-weight: initial;font-family:'Times New Roman','Khmer OS Muol Light';"><?php echo $tr->translate("ACADEMIC_YEAR");?>:
							<?php
									if ($lang_id == 1) { ?>
										<?php echo $db_global->getNumberInkhmer(date($rs['academicYear'])); ?>
									<?php }else{ ?>
										<?php echo $rs['academicYear']; ?>
									<?php } ?>
							</span>
							
						</td>
					</tr>

				<?php } ?>
				<tr>
					<td colspan="3">
						<table class="main_table"  width="100%" cellpadding="0"​  cellspacing="0"​ style="color: #000; margin:0 auto;width:100%;white-space: normal;" >
							<thead>
								<tr>
									<td align="left" colspan="<?php echo $amt_day+1?>" style="font-size:10px;border:1px solid #fff;border-bottom:1px solid #000;">
									<?php if($rs['degree']==1) {?>
										<table width="100%" border="0">
											<tr>
												<td align="left" style="font-size:10px;border:1px solid #fff;" width="30%">
													<ul class="subject">
														<li><span class="blue"><?php echo $tr->translate("GROUP");?> : </span><span class="red"><?php echo $rs['group_code']?></span></li>
														<li><span class="blue"><?php echo $tr->translate("ROOM");?> : </span><span class="red"><?php echo $rs['room_name']?></span></li>		
													</ul>
												</td>
												<td align="center" style="font-size:10px;border:1px solid #fff;" width="40%">
													
												</td>
												<td align="right" style="font-size:10px;border:1px solid #fff;" width="30%">
													
												</td>
											</tr>
										</table>
									<?php }else{ ?>
										<table width="100%" border="0">
											<tr>
												<td align="left" style="font-size:12px;border:1px solid #fff;" >
													<ul class="subject">
														<li><?php echo $tr->translate("GROUP");?>:&nbsp;<?php echo $rs['group_code']?></li>	
														<li><?php echo $tr->translate("ROOM");?>:&nbsp;<?php echo $rs['room_name']?></li>
													</ul>
												</td>
												<td align="right" style="font-size:12px;border:1px solid #fff;">
													
												</td>
											</tr>
										</table>
									<?php } ?>
										
									</td>
								</tr>
								<?php echo $stringDayHead;?>
							</thead>
							<?php $session=''; foreach($arrayTime As $key => $time){ ?>
								<?php if($time['frTime']<=12){
										if($title==0){?>
										<tr  align="center" >
											<td  align="center"  colspan="<?php echo $amt_day+1?>" style="font-size:10px;padding: 5px 2px;text-decoration: underline; color:blue;"><?php echo  $tr->translate("MORNING");?></td>
										</tr>
								<?php $title=1;}
									}else{
										if($titles==0){
								?>
										<tr  align="center" >
											<td  align="center" colspan="<?php echo $amt_day+1?>" style="text-decoration: underline; color:blue;"><?php echo  $tr->translate("AFTERNOON");?></td>
										</tr>
								<?php $titles=1;} ?>
							<?php } ?>
							
							<tr class="hover" align="center" >
								<td width="10%" align="center" class="<?php echo $color_time; ?>" ><strong><?php echo $key;?></strong></td>
								<?php $countCol = count($time["subjectList"]); if(!empty($time["subjectList"])){ foreach($time["subjectList"] as $subj){?>
									<td width="<?php echo 90/$amt_day.'%';?>" align="center">
										<span class= "blue"><strong> <?php echo $subj['subject']; ?> </strong></span><br>
										<span class= "<?php echo $color_teacher; ?>"><?php 	if (!empty($subj['tNameKh'])){echo "".$subj['tNameKh'];} ?> </span><br>
										<span class= "<?php echo $color_teacher; ?>"><?php 	if (!empty($subj['tTel'])){echo "".$subj['tTel'];} ?> </span>
									</td>
								<?php }} ?>
								
								<?php if($countCol<$amt_day){ 
									for ($x = $countCol; $x < $amt_day; $x++) {
										echo '<td width="'.(90/$amt_day).'%" align="center"></td>';
									}
								}
								?>
								
							</tr>
							<?php } ?>
							
							<?php 
								$strFilterGroup =  (string) $rs['groupId'];
								$groupSubject = array_filter($subjectCounting, function ($item) use ($strFilterGroup) {
									if ($item['groupId'] == $strFilterGroup) {
										return $item;
									}
									return;
								});
							?>
							<tr>	
								<td colspan="<?php echo $amt_day+1?>" style=" border:1px solid #fff;">	
									<ul style="display: inline-table;font-size: 10px;">	
										<?php 
										$num =0;
										if(!empty($groupSubject)) foreach($groupSubject as $rowSubj){
											$num++;
											$subjectName = $rowSubj['subjectName'];
											$totalTime = $rowSubj['totalHour'];
											if($totalTime>1){
												$h_label='hrs';
											}else{
												$h_label='hr';
											}
											$totalTime = $totalTime." ".$h_label;
											?>
											<li class="<?php echo $blue; ?>" style="width: 25%;float: left;list-style-type: none;line-height:18px;"><?php echo $num;?>.&nbsp;<?php echo $subjectName;?>:&nbsp;<?php echo $totalTime;?></li>
										<?php } ?>
									</ul>	
								</td>	
							</tr>	
						</table>											
					</td>
				</tr>
			<?php  }?>
		</table>
	</div>		
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script type="text/javascript">
function doPrintProfle(keyid) {
	window.frames["print_frame"].document.body.innerHTML=dojo.byId(keyid).innerHTML;
	window.frames["print_frame"].window.focus();
	window.frames["print_frame"].window.print();
}

</script>