 <?php
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$dbGb = new Application_Model_DbTable_DbGlobal();
	$db = new Allreport_Model_DbTable_DbRptAllStudent();
      $rsamountstudent =$db->getAmountStudent();
      $rsnewstudent = $db->getAmountNewStudent();
      $rsdropstudent = 0;//$db->getAmountDropStudent();
      $rsteststudent = 0;//$db->getAmountStudentTest();
      $rsteststuregistered = 0;//$db->getAmountStudentTestRegistered();
      $rsupdateresult = 0;//$db->getAmountStudentUpdateresult();
      
    
	
	$date = new DateTime();
	$currentDate =  $date->format("Y-m-d");
	$search = array(
				'currentDate' =>$currentDate,
				'academic_year' =>'',
				'degree'=>'',
				'grade'=>'',
				'branch_id'=>0,
		);
	
	$last = $dbGb->getLatestAcadmicYear();
	if(!empty($last)){
		$search["academic_year"] = empty($last["id"]) ? 0 : $last["id"];
	}
	$db = new Allreport_Model_DbTable_DbAttendanceReport();
	$allClass = $db->getCountingAllClass($search);
	$allClass = empty($allClass) ? 0  : $allClass;  
	
   
	$dbDash = new Home_Model_DbTable_DbDashboard();
	
	$arrLine = [];
	$operateLineColors = array(
		"#153c7f",
		"#e23536",
	);
	$totdayOperation = array();
	$amtDay=7;
	$date = new DateTime();
	for($i = 0; $i < $amtDay; $i++){
		$day = 1;
		if($i==0){
			$day = 0;
		}
		$date->modify("-$day day");
		$search["currentDate"] = $date->format('Y-m-d');
		$recordDate = $date->format('Y-m-d');
		$result = $dbDash->getDailyIncomeExpense($search);
		if($i==0){
			$totdayOperation =$result;
		}
		$arrNew =[
			"year" => $recordDate, 
			"income" => empty($result["totalIncome"]) ? "0" : $result["totalIncome"],
			"expense" => empty($result["totalExpense"]) ? "0" : $result["totalExpense"],
		]; 
		array_push($arrLine,$arrNew);	
	}
	sort($arrLine);
?>
<link rel="stylesheet" href="<?php echo $this->baseUrl()."/"?>dashboard/plugins/morris/morris.css">
<!-- Icons CSS -->
<link href="<?php echo $this->baseUrl()."/"?>dashboard/css/icons.css" rel="stylesheet">
<!-- Custom styles for this template -->
<link href="<?php echo $this->baseUrl()."/"?>dashboard/css/style.css" rel="stylesheet">
<style>
ul.list-att-status {
    list-style: none;
    margin: 0;
    padding: 0;
    width: 100%;
}

ul.list-att-status li {
    margin-bottom: 5px;
	text-align: left;
}
ul.list-att-status li span, ul.list-att-status li div {
    font-size: 16px;
}
.latest-record {
    min-height: 265px;
    max-height: 265px;
    padding: 10px;
    overflow-y: auto;
    margin-bottom: 10px;
    margin-top: 5px;
}
svg text {
    font-family: 'Khmer Os Battambang' !important;
}

.title-list-record {
    display: flex;
    flex-wrap: nowrap;
    align-content: center;
    justify-content: space-between;
}
.detail-row {
    display: block;
    color: #918e8e;
}
</style>
<div id="page-wrapper">
	<!-- Page content start -->
	<div class="page-contentbar">
		<!-- START PAGE CONTENT -->
		<div id="page-right-content">
			<div class="container">
				<h3 class="fw-normal" style=" color: #17418e;"><i class="glyphicon glyphicon-education"></i> <?php  echo empty($last["academicYear"]) ? "" : $last["academicYear"];?></h3>
				
				<div class="row" style="margin-top: 15px;">
					<div class="col-lg-12">
						<div class="row top_tiles">
							<div  class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
								<div class="tile-stats">
								  <div class="icon"><i class="fa fa-user"></i></div>
								  <div class="count"><?php echo sprintf('%02d',$rsamountstudent); ?></div>
								  <h3><?php echo $tr->translate("STUDENT_TOTAL");?></h3>
								</div>
							</div>
							<div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
								<div class="tile-stats">
								  <div class="icon"><i class="glyphicon glyphicon-education"></i></div>
								  <div class="count"><?php echo sprintf('%02d',$rsnewstudent); ?></div>
								  <h3><?php echo $tr->translate("NEW_STUDENT");?></h3>
								</div>
							</div>
							<div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
								<div class="tile-stats">
								  <div class="icon"><i class="glyphicon glyphicon-blackboard"></i></div>
								  <div class="count"><?php echo sprintf('%02d',$allClass); ?></div>
								  <h3><?php echo $tr->translate("Total Class");?></h3>
								</div>
							</div>
							<div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
								<a style=" color: #17418e;" title="<?php echo $tr->translate("FINDING_ALL_STUDENT_INFORMATION")?>" href="<?php echo $this->url(array('module'=>'home','controller'=>'searchstudentinfo','action'=>'index'), null, true);?>">
									<div class="tile-stats">
									  <div class="icon"><i class="glyphicon glyphicon-search"></i></div>
									  <div class="count"><i class="glyphicon glyphicon-search"></i></div>
									  <h3><?php echo $tr->translate("FINDING_ALL_STUDENT_INFORMATION");?></h3>
									</div>
								</a>
							</div>
						</div>
					</div>
				</div>
						
				<div class="row" style="margin-top: 15px;">
					<div class="col-lg-9">
						<div class="card-box" style="  margin: 0;">
							<div class="row">
								<div class="col-md-12 col-sm-12 col-xs-12 ">
									<div class="x_panel">
										<div class="card-box" style="padding: 0;  margin: 0;">
											<div class="row">
												<div class="col-md-12 col-sm-12 col-xs-12">
													<span style=" color: #17418e;" >
														<span data-bind="text: txnRecorded"><h4><i class="fa fa-area-chart" ></i> <?php echo $tr->translate("dailyIncomePayment")?></h4></span>
														<p class="month" style="margin: 0 auto;" data-bind="text: lang.lang.transactions_recorded"><?php echo $tr->translate("dailyIncomePaymentDesc")?></p>
													</span>
												</div>
											</div>
											<div class="row d-flex flex-wrap">
												<div class="col-md-3 col-sm-3 col-xs-12 d-flex flex-column align-self-center">
													<div class="d-flex gap-2 align-items-center mb-2 pb-1 flex-wrap">
														<?php 
															$todayTotalIncome = empty($totdayOperation["totalIncome"]) ? 0 : $totdayOperation["totalIncome"];
															$totalLabel = str_replace(".00","",number_format($todayTotalIncome,2));
															if($todayTotalIncome>1000){
																$seperateK = $todayTotalIncome/1000;
																$totalLabel = str_replace(".00","",number_format($seperateK,2))."K";
															}
														?>
													  <h3 class="mb-0 text-success">USD <?php echo $totalLabel;?></h3>
													</div>
													<small><?php echo $tr->translate("TOTAL_INCOME_TODAY")?></small>
												</div>
												<div class="col-md-9 col-sm-9 col-xs-12">
													
													<div id="revenue-statistic" class="morris-donut-inverse" style="width:100%; height:240px;"></div>
													<div class="text-center">
														<i class="fa fa-square " style="color:#337ab7;"></i> <?php echo $tr->translate("INCOME")?>
														&nbsp;&nbsp;
														<i class="fa fa-square " style="color:#ff4c51;"></i> <?php echo $tr->translate("EXPENSE")?>
													</div>
												</div>
											</div>
											<div class="border rounded p-3 mt-4">
												<div class="row">
												  <div class="col-12 col-md-12">
													<div class="d-flex gap-2 align-items-center mb-2 pb-1 flex-wrap">
													  <h4 class="fw-normal"><i class="fa fa-money"></i> <?php echo $tr->translate("TODAY_SUMMARY_DATA")?></h4>
													</div>
												  </div>
												</div>
												  <div class="row gap-4 gap-sm-0">
													<div class="col-12 col-sm-6">
														  <div class="d-flex gap-2 align-items-center">
															<div class="badge rounded bg-label-primary p-1"><i class="fa fa-usd fa-lg p-1"></i></div>
															<h5 class="mb-0 m-0"><?php echo $tr->translate("Earnings")?></h5>
														  </div>
														  <h5 class="my-1 pt-1 fw-normal"><?php echo $tr->translate("CASH")?> <strong>USD <?php echo empty($totdayOperation["totalIncomeCash"]) ? 00 :str_replace(".00","",number_format($totdayOperation["totalIncomeCash"],2));?></strong></h5>
														  <h5 class="my-1 pt-1 fw-normal"><?php echo $tr->translate("BANK")?> <strong>USD <?php echo empty($totdayOperation["totalIncomeBank"]) ? 00 :str_replace(".00","",number_format($totdayOperation["totalIncomeBank"],2));?></strong></h5>
														  <h5 class="my-1 pt-1 fw-normal"><?php echo $tr->translate("CHEQUE")?> <strong>USD <?php echo empty($totdayOperation["totalIncomeCheck"]) ? 00 :str_replace(".00","",number_format($totdayOperation["totalIncomeCheck"],2));?></strong></h5>
														  <div class="progress w-75" style="height:4px">
															<div class="progress-bar" role="progressbar" style="width: 65%" aria-valuenow="65" aria-valuemin="0" aria-valuemax="100"></div>
														  </div>
													</div>
													
													<div class="col-12 col-sm-6">
														<div class="d-flex gap-2 align-items-center">
															<div class="badge rounded bg-label-danger p-1"><i class="fa fa-paypal fa-lg p-1"></i></div>
															<h5 class="mb-0 m-0"><?php echo $tr->translate("Expense")?></h5>
														</div>
														<h5 class="my-1 pt-1 fw-normal"><?php echo $tr->translate("CASH")?> <strong>USD <?php echo empty($totdayOperation["totalExpenseCash"]) ? 00 :str_replace(".00","",number_format($totdayOperation["totalExpenseCash"],2));?></strong></h5>
														<h5 class="my-1 pt-1 fw-normal"><?php echo $tr->translate("BANK")?> <strong>USD <?php echo empty($totdayOperation["totalExpenseBank"]) ? 00 :str_replace(".00","",number_format($totdayOperation["totalExpenseBank"],2));?></strong></h5>
														<h5 class="my-1 pt-1 fw-normal"><?php echo $tr->translate("CHEQUE")?> <strong>USD <?php echo empty($totdayOperation["totalExpenseCheck"]) ? 00 :str_replace(".00","",number_format($totdayOperation["totalExpenseCheck"],2));?></strong></h5>
														<div class="progress w-75" style="height:4px">
															<div class="progress-bar bg-danger" role="progressbar" style="width: 65%" aria-valuenow="65" aria-valuemin="0" aria-valuemax="100"></div>
														</div>
													</div>
												</div>
											</div>
									
										</div>
									</div>
									
								</div>
							</div>
							
						</div>
					</div> <!-- end col -->	  
					<div class="col-lg-3">
					 	
						<div class="clearfix"></div>
						
					</div> <!-- end col -->	  
				</div> <!-- end row -->
				     
			</div>
		</div>
		<!-- END PAGE CONTENT -->
	</div>
	<div class="row-fluid">
					<div style="margin-top: 10px; margin-left: 0;" align="center">
						<p>© 2018<span data-bind="text: lang.lang.all_rights_reserved"><a href="http://www.cam-app.com" target="_blank" > Cam App Teachnology</a>. All rights reserved.</span></p>
					</div>	
				</div>  
</div>


<script src="<?php echo $this->baseUrl()."/"?>dashboard/plugins/morris/morris.min.js"></script>
<script src="<?php echo $this->baseUrl()."/"?>dashboard/plugins/raphael/raphael-min.js"></script>
<script>


Morris.Bar({
  element: 'revenue-statistic',
  data: <?php  echo Zend_Json::encode($arrLine);?>,
  xkey: 'year',
  ykeys: ['income', 'expense'],
  labels: ['<?php echo $tr->translate("INCOME")?>', '<?php echo $tr->translate("EXPENSE")?>'],
  fillOpacity: 0.6,
  hideHover: 'auto',
  behaveLikeLine: true,
  resize: true,
  pointFillColors:['#ffffff'],
  pointStrokeColors: ['black'],
  lineColors:['#337ab7','#ff4c51'],
  barColors:['#337ab7','#ff4c51']
});
</script>