<?php 
	$frm = $this->form_search;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	
	$pageTitle = $tr->translate("RPT_INCOMEBYCATE");
	echo $this->headTitle($pageTitle); 
	
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$dateFormat ="d/m/Y";
?>

<div class="layout-wrapper-report">
	<div id="mainContent" class="main-content-report">
		<div class="report-preview">
			<?php echo $this->controlReport?>
			<div id="main-viewer" class="main-viewer portrait">
				<div id="viewer" class="viewer portrait">
					<div id="divPrint" class="content">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style.css">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style-screen.css">
						<style>
							@media print {
								<?php if(!empty($this->printFormat)){ echo $this->printFormat; } ?>
							}
							tr span{
								line-height:inherit !important;
							}
							tr.line td{ border-bottom: 2px solid #000;padding-top: 5px; }
						</style>
						<table style="background:#fff; margin: 0 auto; width: 100%; padding:0.5cm;font-size: 11px !important;" >
							<tr>
								<td colspan="3"><?php echo $this->rsheader;?></td>
							</tr>
							<tr>
								<td>&nbsp;</td>
							</tr>
							<tr>
								<td width="20%" align="center">
								</td>
								<td width="60%" align="center">
									<div style="color:#000;font-family:'Times New Roman','Khmer OS Muol Light';"><?php echo $tr->translate('RPT_INCOMEBYCATE')?></div>
									<div id="lblBranchId"></div>
									<span style="color:#000;font-family:'Times New Roman','Khmer OS Muol Light';"><?php if(!empty($this->search["start_date"])){?>For <?php echo date($dateFormat,strtotime($this->search["start_date"]))?> to <?php echo date($dateFormat,strtotime($this->search["end_date"]));}?></span>
								</td>
								<td width="20%" align="center"></td>
							</tr>
							<tr>
								<td colspan="3">
									<table id="exportExcel" class="content-data text-color-black text-h16px text-size-12px" width="100%" align="left" style="white-space:nowrap; ">
										<tr class="text-bold bg-ligt-blues">
											<td style="text-align: right;" colspan="2"><?php echo $tr->translate('INCOME_CATEGORY')?></td>
											<td ></td>
											<td ><?php echo $tr->translate('TOTAL_INCOME')?></td>
										</tr>
										  <?php 
											$i=0; 
											$grand_total=0;
											$total_penalty=0;
											$credit_memo= 0;
											$total_otherincome = 0;
											$no=0;
										 ?>
										 <?php if(!empty($this->row)){ foreach($this->row as $key => $rs){ $i++;?>
											<tr class="hover" style="height: 20px;" align="center" >
												<td ></td>
												<td style="text-align: right;"><?php echo $rs['category_name'];?></td>
												<td style="white-space: nowrap;width:200px;">...................................................................................</td>
												<td ><?php echo number_format($rs['total_paidamount'],2);?></td>
											</tr>
												<?php 
													$grand_total = $grand_total + $rs['total_paidamount'];
												?>
										  <?php }}
										  if(!empty($this->row_penalty)){
											foreach ($this->row_penalty as $payment){
												$credit_memo = $credit_memo + $payment['credit_memo'];
												$total_penalty = $total_penalty + $payment['penalty'];
											}
										  }
										  
										  if($total_penalty!=0){ ?>
											<tr class="hover" style="height: 20px;" align="center" >
												<td ></td>
												<td style="text-align: right;"><?php echo $tr->translate('FINE');?></td>
												<td style="white-space: nowrap;width:200px;">...................................................................................</td>
												<td ><?php echo number_format($total_penalty,2);?></td>
											</tr>
										  <?php }if($credit_memo>0){?>
											<tr class="hover" style="height: 20px;" align="center" >
												<td ></td>
												<td style="text-align: right;"><?php echo $tr->translate('Credit Memo');?>(-)</td>
												<td style="white-space: nowrap;width:200px;">...................................................................................</td>
												<td ><?php echo number_format($credit_memo,2);?></td>
											</tr>
										  <?php }?>
										  <tr class="hover" style="height: 20px;" align="center" >
												<td ></td>
												<td style="text-align: right;font-weight:bold;"><?php echo $tr->translate('TOTAL');?></td>
												<td style="white-space: nowrap;width:200px;"></td>
												<td style="padding-left:20px;font-weight: bold;border-bottom: 6px double #000;"><?php echo number_format($grand_total+$total_penalty-$credit_memo,2);?></td>
											</tr>
											
											<?php if(!empty($this->rsincome)){ ?>
												<tr>
													<td height="20px">&nbsp;</td>
												</tr>
												<tr class="text-bold bg-ligt-blues">
													<td style="text-align: right;" colspan="2"><?php echo $tr->translate('OTHER_INCOME')?></td>
													<td style="background-color: #ccd9ff;"></td>
													<td style="background-color: #ccd9ff;"></td>
												</tr>
										   <?php  foreach($this->rsincome as $key => $rs){?>
												<tr class="hover" style="height: 20px;" align="center" >
													<td ></td>
													<td style="text-align: right;"><?php echo $rs['income_category'];?></td>
													<td style="white-space: nowrap;width:200px;">...................................................................................</td>
													<td ><?php echo number_format($rs['total_income'],2);?></td>
												</tr>
												<?php 
													$total_otherincome = $total_otherincome + $rs['total_income'];
												}?>
											 <tr class="hover" style="height: 20px;" align="center" >
												<td ></td>
												<td style="text-align: right;font-weight:bold;"><?php echo $tr->translate('TOTAL');?></td>
												<td style="white-space: nowrap;width:200px;"></td>
												<td style="padding-left:20px;font-weight: bold;border-bottom: 6px double #000;"><?php echo number_format($total_otherincome,2);?></td>
											</tr>
											<?php }?>
											<tr>
												<td colspan="3" style="text-align: right;font-weight:bold;"><?php echo $tr->translate('TOTLE_AMOUNT');?></td>
												<td><strong style="border-bottom: 5px solid #000;">$&nbsp;<?php echo number_format(($grand_total+$total_penalty-$credit_memo)+$total_otherincome,2);?></strong></td>
											</tr>
									</table>
								</td>	
							</tr>	
							<tr>
								<td colspan="3">
									<br />
									<br />
									<table width="100%" class="content-data text-color-black text-h16px text-size-12px">
										<tr style="text-align: center;">
											<td width="30%"><?php echo $tr->translate("CHECKANDAPPROVED");?></td>
											<td width="30%"><?php echo $tr->translate("VERIFIED_BY");?></td>
											<td width="30%"><?php echo $tr->translate("CREATE_WORK_DATE");?></td>
										</tr>
										<tr style="text-align: center;">
											<td width="30%" style="font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("PRINCIPAL_SIGNATURE");?></td>
											<td width="30%"><?php echo $tr->translate("ACCOUNTANT_MNG");?></td>
											<td width="30%"><?php echo $tr->translate("CASHIER");?></td>
										</tr>
									</table>
								</td>	
							</tr>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="right-panel-report" id="rightPanel">
		<div class="card-box">
			<div class="card-search-head col-sm-12 border-botom">
				<div class="col-sm-6 text-left pd-0">
					<h4 class="m-b-0">
					
					<?php echo $tr->translate("SEARCH");?> 
					</h4>
				</div>
				<div class="col-sm-6 text-right pd-0">
				<i class="fa fa-search "></i> 
				</div>
			</div>
			<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
				<div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("branch_id");?>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("start_date");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("end_date");?>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<button class="button-class button-primary fullside" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
<script>
dojo.require("dijit.form.DateTextBox");
document.addEventListener("DOMContentLoaded", function(e) {
	let branchId = dijit.byId("branch_id").get('value');
	if(branchId!=""){
		
		let branchLable = dijit.byId("branch_id").attr('displayedValue');
		$('#lblBranchId').html(branchLable);
	}
  setTimeout(function() {
		setPrintOrientation('portrait');
	}, 500);
});	
</script>