<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('RPT_EXPENSE_DETAIL_REPORT')); 
	$frm=$this->form_search;
	$classHideHeight=classHideHeight;
	//print_r($this->row);

	$recordOrdering = empty($this->search['expRecordOrdering']) ? 0 : $this->search['expRecordOrdering'];
	$columnTitleRecord = $tr->translate('SUPPLIER_NAME');
	if($recordOrdering==2){
		$columnTitleRecord = $tr->translate('EXPENSE_CATEGORY');
	}
	
	$dateFormat ="d/m/Y";
	$dateFormatExp ="d/M/Y";
?>
<div class="layout-wrapper-report">
	<div id="mainContent" class="main-content-report">
		<div class="report-preview">
			<?php echo $this->controlReport?>
			<div id="main-viewer" class="main-viewer portrait">
				<div id="viewer" class="viewer portrait">
					<div id="divPrint" class="content">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style.css">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style-screen.css">
						<style>
							@media print {
								<?php if(!empty($this->printFormat)){ echo $this->printFormat; } ?>
							}
							.noted{
								word-wrap: break-word;
								word-break: break-all;
								font-size: 8px;
								line-height: 10px;
								white-space: normal;
								width: 100px;
								display: block;
							}
							@media print{
								<?php if(!empty($this->printFormat)){ echo $this->printFormat; } ?>
							}

						</style>
						<table  style="background:#fff; margin: 0 auto; ;white-space: nowrap;width: 100%">
							<tr>
								<td colspan="3"><?php echo $this->rsheader;?></td>
							</tr>
							<tr>
								<td width="15%" align="center"></td>
								<td width="70%" align="center">
									<span style="color:#000; font-size: 12px;font-family:'Times New Roman','Khmer OS Muol Light';"><?php echo $tr->translate('RPT_EXPENSE_DETAIL_REPORT')?></span><br />
									<span style="color:#000; font-size: 12px;font-family:'Times New Roman','Khmer OS Muol Light';"><?php if(!empty($this->search['start_date'])){?>&nbsp; <?php echo date($dateFormat,strtotime($this->search["start_date"]))?> <?php echo $tr->translate('TO')?> <?php echo date($dateFormat,strtotime($this->search["end_date"]));}?></span>
								</td>
								<td width="15%" align="center"></td>
							</tr>
							<tr>
								<td colspan="3" id="exportExcel">
									<table class="content-data  bd-w1px text-color-black text-h16px text-size-12px" cellpadding="5"  width="100%" >
										<thead>
											<tr class="styleheader text-bold hpx-25 bd-b-dashed bd-b-w1px bd-dark-grey" align="center">
												<td scope="col"><?php echo $tr->translate('N_O')?></td>
												<td scope="col"><?php echo $tr->translate('BRANCH')?></td>
												<td scope="col"><?php echo $tr->translate('FOR_DATE')?></td>
												<td scope="col"><?php echo $tr->translate('RECEIPT_NO')?></td>
												<td scope="col" align="left"><?php echo $tr->translate('EXPENSE_TITLE')?></td>
												
												<td scope="col"><?php echo $tr->translate('INVOICE_NO')?></td>
												<td scope="col" align="left"><?php echo $columnTitleRecord ?></td>
												<td scope="col" align="right"><?php echo $tr->translate('QTY')?></td>
												<td scope="col" align="right"><?php echo $tr->translate('COST')?></td>
												<td scope="col" align="right"><?php echo $tr->translate('AMOUNT')?></td>
												<td scope="col" ><?php echo $tr->translate('PAYMENT_METHOD')?></td>
												<td scope="col" align="left"><?php echo $tr->translate('RECEIVER')?></td>
												<td scope="col" align="left"><?php echo $tr->translate('DESCRIPTION')?></td>
												<td scope="col" align="left"><?php echo $tr->translate('USER')?></td>
											</tr>
										</thead>
							<?php 
								$paymentSummary = array();
								$amtRc=1; 
								$i=0; 
								
								$recordCondiction="";
								$oldMethodTitle="";
								$totalExpenseByMethod = 0;
								$gTotalExpense = 0;
										if(!empty($this->row)){
											foreach ($this->row AS $kerIndex => $row) { $i++;
											
											$columnTitleValue = $row['sup_name'];
											$headRecordTitle = $row['categoryTitle']."-".$row['categoryAccountCode'];
											$thisRecordId = $row['categoryId'];

											if($recordOrdering==2){
												$columnTitleValue = $row['categoryTitle']."-".$row['categoryAccountCode'];
												$headRecordTitle = $row['sup_name'];
												$thisRecordId = $row['supplierId'];

											}

											$oldMethodTitle = $row['bank_name'];
											if($row['paymentMethodId']==1){
												$oldMethodTitle=$row['paymentMethodTitle'];
											}
										?>
										<?php 
											if($thisRecordId != $recordCondiction ){
												if($kerIndex>0){ 
													
										?>
												<tr class="style hpx-25">
													<td colspan="9" align="right"><strong><?php echo $tr->translate("TOTAL");?>  </strong></td>
												
													<td align="right"><strong><?php echo number_format($totalExpenseByMethod,2);?></strong></td>
													<td colspan="5"></td>
												</tr>
												<?php } 
												$totalExpenseByMethod=0;
												$amtRc=1;
												?>
											<tr class="style bg-light-blues hpx-25">
												<td colspan="14" align="left" class="text-bold "><?php echo $headRecordTitle;?></td>
											</tr>
										<?php } ?>
											
										<tr class="rowEven context-menu-one style hover" oncontextmenu="setrowdata(<?php echo $row['id'];?>);return false;" align="center" <?php if ($row['status']==0){?>style="background: #ffd9d9;"<?php }?> >
											<td data-label="<?php echo $tr->translate("N_O");?>"><?php echo $i;?></td>
											<td data-label="<?php echo $tr->translate("BRANCH");?>"><?php echo $row['branch_name']; ?></td>
											<td data-label="<?php echo $tr->translate("FOR_DATE");?>" class="hideExport"><?php echo date($dateFormat,strtotime($row['date']));?></td>
											<td data-label="<?php echo $tr->translate("FOR_DATE");?>" class="showExport" style="display:none;"><?php echo date($dateFormatExp,strtotime($row['date']));?></td>
											<td data-label="<?php echo $tr->translate("RECEIPT_NO");?>"><?php echo $row['invoice']; ?></td>
											<td data-label="<?php echo $tr->translate("EXPENSE_TITLE");?>" align="left"><?php echo $row['itemTitle']." - ".$row['itemAccountCode']; ?></td>
											
											<td data-label="<?php echo $tr->translate("INVOICE_NO");?>"><?php echo $row['external_invoice']; ?></td>
											<td data-label="<?php echo $tr->translate("SUPPLIER_NAME");?>" align="left"><?php echo $columnTitleValue; ?></td>
											<td data-label="<?php echo $tr->translate("QTY");?>" class="text-bold" align="right"><?php echo $row['qty'];?></td>
											<td data-label="<?php echo $tr->translate("COST");?>" class="text-bold" align="right"><?php echo " ".$row['price'];?></td>
											<td data-label="<?php echo $tr->translate("TOTAL");?>" class="text-bold" align="right"><?php echo " ".$row['total'];?></td>
											<td data-label="<?php echo $tr->translate("PAYMENT_METHOD");?>" ><?php echo $oldMethodTitle; ?></td>
											<td data-label="<?php echo $tr->translate("RECEIVER");?>" align="left"><?php echo $row['receiver']; ?></td>
											<td data-label="<?php echo $tr->translate("DESCRIPTION");?>" align="left"><?php echo $row['description'];?></td>
											<td data-label="<?php echo $tr->translate("USER");?>" align="left"><?php echo $row['first_name'];?></td>
										</tr>	
										<?php 
												$amtRc++;
												if ($row['status'] == 1) {
													$totalExpenseByMethod += $row['total'];
													$gTotalExpense += $row['total'];
													
													$methodTitle = ($row['paymentMethodId'] == 1) ? $row['paymentMethodTitle'] : $row['bank_name'];

													if (!isset($paymentSummary[$methodTitle])) {
														$paymentSummary[$methodTitle] = ['count' => 0, 'total' => 0];
													}
													$paymentSummary[$methodTitle]['count'] += 1;
													$paymentSummary[$methodTitle]['total'] += $row['total'];
												}

												$recordCondiction = $row['categoryId'];
												if($recordOrdering==2){
													$recordCondiction = $row['supplierId'];
												}	
											?>
										<?php }?>
										<tr class="style hpx-25">
											<td colspan="9" align="right"><strong><?php echo $tr->translate("TOTAL");?></strong></td>
										
											<td align="right"><strong><?php echo number_format($totalExpenseByMethod,2);?></strong></td>
											<td colspan="5"></td>
										</tr>
										<tr class="style bd-dark-grey bd-b-double bd-b-w4px bd-t-solid bd-t-w1px hpx-25">
											<td colspan="9" align="right"><strong><?php echo $tr->translate("GRAND_TOTAL");?></strong></td>

											<td align="right"><strong><?php echo number_format($gTotalExpense,2);?></strong></td>
											<td colspan="5"></td>
										</tr>
										
										<?php }?>
											
									</table>
									<div style="display: flex; text-align: right;align-content: end;flex-wrap: wrap;flex-direction: column;margin-top: 10px; ">
											<table  class="content-data text-color-black text-size-12px text-h16px" style=" width:30%; text-align: center; margin: 0 auto; font-weight: bold; border: 0;">
												<tr>
													<td colspan="4" class="bd-head" align="center" ><strong><?php echo $tr->translate("Summary");?></strong></td>
												</tr>
												<tr>
													<td width="25%" align="right" style="white-space:nowrap;"><?php echo $tr->translate("GRAND_TOTAL");?></td>
													<td width="25%" align="right"><?php echo sprintf('%02d', count($this->row));?></td>
													<td width="25%" align="right">$</td>
													<td width="25%" align="right"><?php echo number_format($gTotalExpense,2);?></td>
												</tr>
												<?php if(!empty($paymentSummary)) foreach($paymentSummary as $methodTitle => $summary){ ?>
												<tr>
													<td align="right" style="white-space:nowrap;"><?php echo $methodTitle; ?></td>
													<td align="right"><?php echo sprintf('%02d', $summary["count"]); ?></td>
													<td align="right">$</td>
													<td align="right"><?php echo number_format($summary["total"], 2); ?></td>
												</tr>
												<?php } ?>
											</table>
										</div>
								</td>
							</tr>
							<tr>
								<td colspan="3" width="100%">
									<?php echo $this->rsfooteracc;?>
								</td>
							</tr>
					</table>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="right-panel-report" id="rightPanel">
		<div class="card-box">
			<div class="card-search-head col-sm-12 border-botom">
				<div class="col-sm-6 text-left pd-0">
					<h4 class="m-b-0">
						<?php echo $tr->translate("SEARCH");?> 
						<i class="fa fa-search "></i> 
					</h4>
				</div>
				<div class="col-sm-6 text-right pd-0">
					<button onclick="closeRightPanel()" title="<?php echo $tr->translate("CLOSED");?> " class="btn-close">
						<i class="fa-solid fa-xmark"></i>
					</button>
				</div>
			</div>
			<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-expense-detail-report')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
				<div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("adv_search");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("branch_id");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("expenseCategoryId");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("supplier_id");?>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm->getElement("start_date");?>
					</div>
					<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm->getElement("end_date");?>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm->getElement("receiptStatus");?>
					</div>
					<div class="col-md-6 col-sm-6 col-xs-12">
						<input id="userId" />
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm->getElement("expRecordOrdering");?>
					</div>
					<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm->getElement("receipt_order");?>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<button class="button-class button-primary" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
				</div>
			</form>	
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl();?>/admin/js/global.js" type="text/javascript"></script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.require("dijit.form.CheckBox"); 
dojo.ready(function(){
	new dijit.form.FilteringSelect({
		queryExpr: "*${0}*",
		autoComplete: false,                     
		required: false,                        
		id: "userId",
		name: "userId",  
		class: 'fullside',  
		placeHolder:"<?php echo $tr->translate("SELECT_USER");?>",          
		onChange: function() {  
		}
	}, "userId");

	var branch_id = dijit.byId('branch_id');
	branch_id.on('change', function(evt) {
		 getAllStudentByBranch();
		 getAllUser();
	});
	getAllUser();
	
	setTimeout(function() {
		setPrintOrientation('landscape');
	}, 500);
});

function getAllUser(){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		dijit.byId('branch_id').focus();
		return false;
	}
	let url_user = '<?php echo $this->url(array('module'=>'rsvacl','controller'=>'user','action'=>'get-user')); ?>';
	contentData = {
			'branchId':branch_id
		}
		selectedId = '';
		if('<?php echo $this->search['branch_id']?>'==branch_id){
			selectedId = '<?php echo empty($this->search['userId']) ? 0 : $this->search['userId'];?>';
		}
		getAllUserByBranch(url_user,contentData,selectedId);
}
var row=0;
var url="";
$(function(){
	$.contextMenu({
		selector: '.context-menu-one', 
		callback: function(key, options) {
			var m = "clicked: " + key;
			if(key=="receipt"){
				url='<?php echo $this->baseUrl()."/allreport/accounting/rpt-expensedetail/id/";?>';
			}
			gotoAction();
		},
		items: {
			"receipt": {name: "<?php echo $tr->translate("PAYMENT_VOUCHER");?>", icon: "fa-solid fa-money-bill", accesskey: "c"},
		}
	});
});
function setrowdata(index){
	row = index;
}
var recordid ='';
function gotoAction(){
	 window.open(url+row, '_blank');
}
</script>