<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle('បង្កាន់ដៃបង់ប្រាក់');
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$result = $this->rr;
	$receiptType = RECEIPT_TYPE;

?>
<style>
	#footer{display: none;}
	table tr td strong{
		padding-left: 0px;
	}
	button#portraitBtn,
	button#landscapeBtn,
	button.btn-search {
		display: none !important;
	}
</style>

<div class="layout-wrapper-report">
	<div id="mainContent" class="main-content-report">
		<div class="report-preview">
			<?php echo $this->controlReport?>
			<div id="main-viewer" class="main-viewer portrait">
				<div id="viewer" class="viewer portrait">
					<div id="divPrint" class="content">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style.css">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style-screen.css">
						<style>
							table small{line-height: 3px;}
						</style>
						<?php 
							$amount_print = $this->data['receipt_print'];
							echo $this->officailreceipt;
							?>
					</div>	
				</div>	
			</div>	
			<div id="MainnoteContent" style="display: none;"><?php echo $result['note'];?></div>
			<?php foreach($this->row  as $key=> $rs){ ?>
				<div id="noteContent<?php echo $key?>" style="display: none;"><?php echo $rs['note'];?></div>
			<?php } ?>
		</div>	
	</div>	
</div>	
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script src="<?php echo $this->baseUrl();?>/js/pdbs_js.js"  type="text/javascript"></script>

<script type="text/javascript">
dojo.ready(function(){
	readMoneyInKhmer("<?php echo $this->rr['paid_amount'];?>");
	getbranchHeader();
	setDatatoReceipt();
	<?php if($receiptType==2){ ?>
	getBranchInfo();
	<?php } ?>
	setTimeout(function() {
		setPrintOrientation('landscape','A5',true);
	}, 500);
});
<?php if($receiptType==2){ ?>
var urlGetBrInfo = "<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'getbranchinfodetail')); ?>";
function getBranchInfo(){
	branch_id = '<?php echo $this->rr['branch_id'];?>';
	if(branch_id != ""){
		dojo.xhrPost({
			url: urlGetBrInfo,
			content:{
				'branch_id':branch_id,
				},
			handleAs:"json",
			load: function(data){
				var brAddress = (data.br_address !=null ) ? ' '+data.br_address : "";
				var brTel = (data.branch_tel !=null ) ? ' Tel '+data.branch_tel : "";
				var showReceiptDesc = (data.showReceiptDesc !=null ) ? data.showReceiptDesc : "0";
				$( ".brContactInfo" ).html(brAddress+brTel);
				if(showReceiptDesc=="1"){
					$(".footerNote").removeClass("no_display");
				}
			},
			error: function(err) {
			}
		});	
	} 
}
<?php } ?>
function setDatatoReceipt(){	
		dojo.byId("lb_receipt_no").innerHTML = '<?php echo $result['receipt_number'];?> <?php if ($result['is_void']==1){ echo '<span style="color:red; line-height: inherit;"> (VOID)</span>'; }?>';	
		dojo.byId("lb_date").innerHTML  = '<?php echo date('d-m-Y H:i',strtotime($result['create_date']));?>';
		dojo.byId("lb_stu_id").innerHTML = '<?php echo ($result['data_from']==3)?$result['serial']:$result['stu_code'];?>';	
		dojo.byId("lb_sex").innerHTML = '<?php echo $result['sex'];?>';	

		var strNote = $( '#MainnoteContent').html();
		$('#lbl_note').text(strNote);
		  
		dojo.byId("lb_name").innerHTML = '<?php echo $result['stu_khname'];?>';
		dojo.byId("lb_namelatin").innerHTML = '<?php echo $result['last_name'].' '.$result['stu_enname'];?>';		
		dojo.byId("lb_phone").innerHTML = '<?php echo $result['tel'];?>';	
		dojo.byId("lb_fee_type").innerHTML = '<?php echo $result['term_study'];?>';
		
		var periodStr = '<ul>';
		<?php foreach($this->periodList  as $key=> $period){ ?>
			periodName='<?php echo $period['title']; ?>';
			periodLimited='<?php echo $period['startDateSecondFmt']; ?>';
			periodStr+='<li><span class="terminf titleTerm">'+periodName+'</span><span class="terminf termValidePmt">'+periodLimited+'</span></li>';
		<?php } ?> 
		periodStr+= '</ul>'
		$("#lbl_period_year").append(periodStr);
		
		<?php if($result['photo']){?>
			dojo.byId("lb_photo").innerHTML = '<img style="height:100%;width:100%;" src="<?php echo $this->baseUrl().'/images/photo/'.$result['photo']?>" />' ;
		<?php } ?>
		dojo.byId("lb_total_payment").innerHTML = '<?php echo number_format($result['grand_total'],2);?>';	
		dojo.byId("lb_fine").innerHTML = '<?php echo number_format($result['fine'],2);?>';			
		dojo.byId("lb_credit_memo").innerHTML = '<?php echo number_format($result['credit_memo'],2);?>';
		dojo.byId("lb_paid_amount").innerHTML = '<?php echo number_format($result['paid_amount'],2);?>';	
		dojo.byId("lb_balance_due").innerHTML = '<?php echo number_format($result['balance_due'],2);?>';	
		dojo.byId("lb_paymentmethod").innerHTML = '<?php echo $result['payment_method'];?>';	
		dojo.byId("lb_paymentnumber").innerHTML = '<?php echo "&nbsp;".$result['bankName'];echo !empty($result['number'])?' ('.$result['number'].')':'';?>';
		dojo.byId("lb_byuser").innerHTML = '<?php echo $result['user'];?>';

		dojo.byId("lb_academic_year").innerHTML = '<?php echo empty($result['academic_year'])?"&nbsp;":$result['academic_year'];echo empty($result['session_type'])?"&nbsp;":$result['session_type'];?>';
		dojo.byId("lb_part_time").innerHTML = '<?php echo empty($result['parttimeTitle'])?"&nbsp;":$result['parttimeTitle'];?>';
		dojo.byId("lb_group").innerHTML = '<?php echo empty($result['group_name'])?$result['grade']:$result['group_name'];?>';
		
		<?php if($receiptType==4){?>
				template="";
				 temp='<table class="tableDetail" width="100%" align="center" style="white-space:nowrap; padding: 0px; margin: 0px;font-family: '+"'Times New Roman','Khmer OS Battambang'"+';" id="table">'
					  temp+='<tr class="hearder_table" style="font-size:inherit !important;text-align:center;">';
						  temp+='<td>លេខរៀង<br />No.</td>';
						  temp+='<td><strong style="color:#000;">បរិយាយ<br />Description</strong></td>';
						  temp+='<td><strong style="color:#000;">សម្គាល់<br />Remark</strong></td>';
						  temp+='<td><strong style="color:#000;">បរិមាណ<br />Qty</strong></td>';
						  temp+='<td><strong style="color:#000;">តម្លៃ<br />Price</strong></td>';
						  temp+='<td><strong style="color:#000;">សរុប<br />Total Amount($)</strong></td>';
						  temp+='<td><strong style="color:#000;">សុពលភាព<br />Validation</strong></td>';
					  temp+='</tr>';
					i=1;  
			<?php 
				foreach($this->row  as $key=> $rs) { 
					$label="";
					if($rs['service_type']==1){
						$label="School Fee ";
					}
			?>
						
						var items_type ='<?php echo $rs['service_type']; ?>';
						var term_label = "-";
						if(items_type!=3){
							term_label = '';//dijit.byId("term_"+rowIDArray[n]).attr('displayedValue');
						}
					temp+='<tr style="font-size:inherit;height: 18px;"​ align="center">';
							item_label = '<?php echo addslashes ($label.$rs['service']);?>';
							item_label+='<?php if ($rs['is_onepayment']!=1) { echo "<br />".$rs['payment_term']; }?>';
					  
						temp+='<td align="center">'+i+'</td>';
						temp+='<td align="left">'+item_label+'</td>'; 
					  
							var div = document.getElementById('noteContent');
							var htmlString = $( '#noteContent'+'<?php echo $key;?>').html();
						temp+='<td style="max-width:150px;white-space:normal;line-height:10px;font-size:9px;">'+htmlString+'</td>';
					  
						temp+='<td>'+<?php echo number_format($rs['qty'],2)?>+'</td>';
					  	
							fee='<?php echo number_format($rs['fee'],2);?>';
							extra_fee='<?php echo number_format($rs['extra_fee'],2);?>';
							discount_type='<?php echo $rs['discount_type'];?>';
							discount_amount = '<?php echo $rs['discount_amount']; echo ($rs['discount_percent']>0)?'+'.$rs['discount_percent']."%":"";?>';
							paid='<?php echo number_format($rs['paidamount'],2);?>';
						temp+='<td align="center">'+fee+'</td>';
						temp+='<td>'+paid+'</td>';		
					  	period='<?php if($rs['is_onepayment']!=1){echo date('d/m/Y', strtotime($rs['start_date'])); ?>-<?php echo empty($rs['validate'])?"":date('d/m/Y', strtotime($rs['validate'])); }else{echo'&nbsp;';}?>';		  				  
						temp+='<td align="center">'+period+'</td>';
						
					  
					  temp+='</tr>';
					  i++;
					<?php } ?>
			temp+='</table>';
			dojo.byId('t_amountmoneytype').innerHTML = temp;
		<?php }
		elseif($receiptType==2){//chv
		?>
			template='';
				 temp='<table class="tableDetail" width="100%" id="table">'
					  temp+='<thead><tr class="hearder_table">';
						  temp+='<td class="all-border wt-tdrowNo">ល.រ<small>No. </small></td>';
						  temp+='<td class="all-border">បរិយាយ<small>Description</small></td>';
						  temp+='<td class="all-border wt-td40">បរិមាណ<small>Quantity</small></td>';
						  temp+='<td class="all-border wt-td-record">តម្លៃរាយ<small>Unit Price</small></td>';
						  temp+='<td class="all-border wt-td-record">បញ្ចុះតម្លៃ<small>Discount</small></td>';
						  temp+='<td class="all-border wt-td-record">សេវាផ្សេងៗ<small>Other Services</small></td>';
						  temp+='<td class="all-border wt-td-record">ប្រាក់ត្រូវប​ង់<small>Payment</small></td>';
					  temp+='</tr></thead>';
					i=1;  
						<?php foreach($this->row  as $key=> $rs) { 
							$label="";
							if($rs['service_type']==1){
								$label="School Fee ";
							}
						?>
						var htmlString = $( '#noteContent'+'<?php echo $key;?>').html();

						var items_type ='<?php echo $rs['service_type']; ?>';
						var term_label = "";
						if(items_type!=3){
							term_label = '';
						}
						extra_fee='<?php echo $rs['extra_fee']=='0.00'?'-':number_format($rs['extra_fee'],0);?>';
						discount_amount = '<?php echo ($rs['discount_amount']>0)?str_replace(".00","",$rs['discount_amount']).',':''; echo ($rs['discount_percent']>0)?str_replace(".00","",$rs['discount_percent'])."%":"";?>';
						fee='<?php echo number_format($rs['fee'],2);?>';
						totalpayment='<?php echo number_format($rs['totalpayment'],2);?>';
						temp+='<tr style="line-height:10px;" align="center"><td class="all-border" align="center">'+i+'</td>';
						item_label = '<?php echo addslashes ($label.$rs['service']);?>';
						term = '<?php if($rs['paymentTermId']!=5 AND $rs['paymentTermId']!=6){ echo empty($rs['academicFeeTermTitle'])?"":"-".$rs['academicFeeTermTitle']; }?>';
						temp+='<td class="all-border" align="left" style="line-height:10px;"><label class="descriptionDetail">&nbsp;'+item_label+term+' '+htmlString+'</label></td>'; 
						temp+='<td class="all-border">'+<?php echo number_format($rs['qty'],2);?>+'</td>';
						temp+='<td class="all-border textright p-r5">'+fee+'</td>';
						temp+='<td class="all-border">'+(discount_amount==''?'-':discount_amount)+'</td>';
						temp+='<td class="all-border">'+(extra_fee==''?'-':extra_fee)+'</td>';
						temp+='<td class="all-border p-r5 textright">'+totalpayment+'</td>';
						temp+='</tr>';
					  i++;
					<?php } ?>
			temp+='</table>';
			dojo.byId('t_amountmoneytype').innerHTML = temp;
		<?php }elseif($receiptType==3){?>//psis first
			template="";
				 temp='<table class="tableDetail" width="100%" id="table">'
					  temp+='<tr class="hearder_table">';
						  temp+='<td class="all-border wt-tdrowNo">ល.រ<small>No. </small></td>';
						  temp+='<td class="bordered">បរិយាយ<small>Description</small></td>';
						  temp+='<td class="bordered wt-td40">បរិមាណ<small>Quantity</small></td>';
						  temp+='<td class="bordered wt-td-record">តម្លៃរាយ<small>Unit Price</small></td>';
						  temp+='<td class="bordered wt-td-record">បញ្ចុះតម្លៃ<small>Discount</small></td>';
						  temp+='<td class="bordered wt-td-record">សេវាផ្សេងៗ<small>Other Fee</small></td>';
						  temp+='<td class="bordered wt-td-record">ប្រាក់ត្រូវប​ង់<small>Total Payment</small></td>';
						  temp+='<td class="bordered wt-td-record">សុពលភាព<small>Validity</small></td>';
						  temp+='<td class="bordered wt-td-note-record">សម្គាល់<small>Note</small></td>';
					  temp+='</tr>';
					i=1;  
					<?php if(!empty($this->row))foreach($this->row  as $key=> $rs) { 
							$label="";
						if($rs['service_type']==1){
							$label="School Fee ";
						}
					?>
						
						var items_type ='<?php echo $rs['service_type']; ?>';
						var term_label = "-";
						if(items_type!=3){
							term_label = '';
						}
					  temp+='<tr style="font-size:11px;line-height:10px;">';
					  
						
						item_label = '<?php echo addslashes ($label.$rs['service']);?>';
						qty = '<?php echo number_format($rs['qty'],0);?>'
						fee='<?php echo number_format($rs['fee'],2);?>';
						discount_type='<?php echo $rs['discount_type'];?>';
						discount_amount = '<?php echo $rs['discount_amount']; echo ($rs['discount_percent']>0)?'+'.$rs['discount_percent']."%":"";?>';
						extra_fee='<?php echo number_format($rs['extra_fee'],2);?>';
						period='<?php if($rs['is_onepayment']!=1 AND $rs['paymentTermId']!=5){echo '<span class="spanBlog">'.$rs['start_date'].'</span>'; echo empty($rs['validate'])?"":'<span class="spanBlog">'.$rs['validate'].'</span>';}else{echo'&nbsp;';}?>';	
						totalpayment='<?php echo number_format($rs['totalpayment'],2);?>';
						term = '<?php if($rs['paymentTermId']!=5 AND $rs['paymentTermId']!=6){ echo empty($rs['academicFeeTermTitle'])?"-".$rs['payment_term']:"-".$rs['academicFeeTermTitle']; }?>';
						
						temp+='<td class="bordered" align="center">'+i+'</td>';
						temp+='<td align="left" class="bordered" style="line-height:10px;"><label class="descriptionDetail">&nbsp;'+item_label+term+'</label></td>'; 
						temp+='<td class="bordered" align="center" style="line-height:10px;">'+qty+'</td>';
						temp+='<td class="bordered p-r5 textright">'+fee+'</td>';
						temp+='<td class="bordered p-r5 textright">'+discount_type+' '+discount_amount+'</td>';
						temp+='<td class="bordered p-r5 textright">'+extra_fee+'</td>';
						temp+='<td class="bordered p-r5 textright">'+totalpayment+'</td>';
						temp+='<td align="center" class="bordered">'+period+'</span></td>';
						var htmlString = $( '#noteContent'+'<?php echo $key;?>').html();
						temp+='<td class="bordered" style="max-width:150px;white-space:normal;line-height:10px;font-size:9px;white-space: pre-line;text-align:left;">'+htmlString+'</td>';
					  temp+='</tr>';
					  i++;
					<?php } ?>
			temp+='</table>';
			dojo.byId('t_amountmoneytype').innerHTML = temp;
		<?php }elseif($receiptType==1){ ?>
				template="";
					temp='<table class="tableDetail" width="100%" id="table">'
						temp+='<tr class="hearder_table">';
							temp+='<td class="bordered">ល.រ<small>No. </small></td>';
							temp+='<td class="bordered">បរិយាយ<small>Description</small></td>';
							temp+='<td class="bordered">បង់ជា<small>Pay as</small></td>';
							temp+='<td class="bordered">បរិមាណxតម្លៃរាយ<small>QtyxUnit Price</small></td>';
							temp+='<td class="bordered">បញ្ចុះតម្លៃ<small>Discount</small></td>';
							temp+='<td class="bordered">សេវាផ្សេងៗ<small>Other Fee</small></td>';
							temp+='<td sclass="bordered">ប្រាក់ត្រូវប​ង់<small>Total Payment</small></td>';
							temp+='<td class="bordered">សុពលភាព<small>Valid Date</small></td>';
							temp+='<td class="bordered">សម្គាល់<small>Note</small></td>';
						temp+='</tr>';
						i=1;  
						<?php foreach($this->row  as $key=> $rs) { 
							$label="";
							if($rs['service_type']==1){
								$label="School Fee ";
							}
							?>
							
							var items_type ='<?php echo $rs['service_type']; ?>';
							var term_label = "-";
							if(items_type!=3){
								term_label = '';
							}
						temp+='<tr style="font-size:11px;line-height:10px;" align="center"><td class="bordered" align="center">'+i+'</td>';
						item_label = '<?php echo addslashes ($label.$rs['service']);?>';
						
						temp+='<td align="left" class="bordered" style="line-height:10px;"><label class="notedDescription">&nbsp;'+item_label+'</label></td>'; 
						term = '<?php echo $rs['payment_term'];?>';
						temp+='<td class="bordered" align="center" style="line-height:10px;">'+term+'</td>';
						fee='<?php echo number_format($rs['fee'],2);?>';
						temp+='<td class="bordered p-r5">'+<?php echo number_format($rs['qty'],2);?>+'x'+fee+'</td>';
							
							discount_type='<?php echo $rs['discount_type'];?>';
							discount_amount = '<?php echo $rs['discount_amount']; echo ($rs['discount_percent']>0)?'+'.$rs['discount_percent']."%":"";?>';
						temp+='<td class="bordered">'+discount_type+'<br />'+discount_amount+'</td>';
							
							extra_fee='<?php echo number_format($rs['extra_fee'],2);?>';
						temp+='<td class="bordered">'+extra_fee+'</td>';

						totalpayment='<?php echo number_format($rs['totalpayment'],2);?>';
							temp+='<td align="center" class="bordered p-r5">'+totalpayment+'</td>';
						
						period='<?php if($rs['is_onepayment']!=1 AND $rs['paymentTermId']!=5){echo '<span class="spanBlog">'.$rs['start_date'].'</span>'; echo empty($rs['validate'])?"":'<span class="spanBlog">'.$rs['validate'].'</span>';}else{echo'&nbsp;';}?>';	
												
						temp+='<td align="center" class="bordered">'+period+'</span></td>';
						var htmlString = $( '#noteContent'+'<?php echo $key;?>').html();
	
						temp+='<td class="bordered" style="max-width:150px;white-space:normal;line-height:10px;font-size:9px;white-space: pre-line;text-align:left;">'+htmlString+'</td>';
						temp+='</tr>';
						i++;
						<?php } ?>
					temp+='</table>';
				dojo.byId('t_amountmoneytype').innerHTML = temp;
			<?php } ?>		

			readMoneyInKhmer('<?php echo $result['grand_total'];?>');
			dojo.byId("lbFather").innerHTML = '<?php echo $result['father_enname'].'<br />'.$result['father_phone'];?>';	
			dojo.byId("lbMother").innerHTML = '<?php echo $result['mother_enname'].'<br />'.$result['mother_phone'];?>';	
		
			
}
function readMoneyInKhmer(netTotal){
	var str = netTotal.toString();
    str_cent = 'សេន';
	first_decimal = str.substr(-2);
	last_decimal = str.substr(-1);
    if(first_decimal>0){string=' ចុច ';}else{string="";str_cent=""}
	if(first_decimal!='00' && first_decimal<10 ){str_zero = "សូន្យ";}else{str_zero='';}
	first_money_decimal = read_in_khmer_from_10_to_99(first_decimal);
	last_money_decimal = read_in_khmer_from_0_to_9(last_decimal)
	money_khmer=read_money_in_khmer(netTotal);

	if(first_decimal>0){string_en=' dot ';}else{string_en="";str_cent_en=""}
	if(first_decimal!='00' && first_decimal<10 ){str_zero_en = "Zero";}else{str_zero_en='';}
	first_money_decimal_en = read_in_english_from_10_to_99(first_decimal);
	last_money_decimal_en = read_in_english_from_0_to_9(last_decimal)
	money_english=read_money_in_english(netTotal);
	read_eng = money_english.trim()+string+ first_money_decimal+str_zero+last_money_decimal+'ដុល្លារគត់'
	
	english_amount = ' Dollar Only';
	if(netTotal==0){english_amount='';}
	read_eng = '( '+money_english.trim()+string_en+ first_money_decimal_en+str_zero_en+last_money_decimal_en+english_amount+')'
	khmer_amount = 'ដុល្លារគត់';
	if(netTotal==0){khmer_amount='';}
	dojo.byId("lb_read_khmer").innerHTML =money_khmer.trim()+string+ first_money_decimal+str_zero+last_money_decimal+khmer_amount+read_eng
}


var url_getbranch = "<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'getbranchinfo')); ?>";
function getbranchHeader(){
	branch_id = '<?php echo $this->rr['branch_id'];?>';
	if(branch_id != ""){
		dojo.xhrPost({
			url:url_getbranch,
			content:{
				'branch_id':branch_id,
				},
			handleAs:"json",
			load: function(data){
				dojo.byId('lbl_header').innerHTML=data;
			},
			error: function(err) {
			}
		});	
	} 
}

</script>