<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_PROGAM_TYPE')); 
	$frm= $this->frm;
?>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-graduation-cap " ></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_PROGAM_TYPE');?></h4>
    			</div>
    			<div class="col-sm-4 text-right"></div>
    		</div>
    	</div>
		<form id='add_discount' action="" method="post" dojoType="dijit.form.Form" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">   
  				 if(this.validate()) {
					 loadingBlock();
					dijit.byId("save_new").attr("disabled",true);
   					 return true;
   				}else {
    				return false;
   				}
			</script>
			<div class="card-box">
				<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-briefcase"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("PROGRAM_INFO");?></p>
										</div> 
									</div>
									
									<div class="form-group">
										<label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("TITLE");?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("title");?>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("TITLE_EN");?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("title_en");?>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("SHORTCUT");?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("shortcut");?>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("TYPE");?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("isSingleProgram");?>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("NOTE");?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("note");?>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-briefcase"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("DEGREE");?></p>
										</div> 
									</div>
									<div class="custom-control custom-checkbox ">
										<input type="checkbox" class="checkbox custom-control-input" onchange="checkall();" id="check_all"  name="check_all" checked  >
										<label class="custom-control-label" for="check_all">
											<?php echo $tr->translate('CHECK_ALL');?>
										</label>
									</div>
									<div class="row g-3">
										<ul class="optListRow">
											<?php 
												if (!empty($this->faculty)) foreach ($this->faculty as $rs){
												?>
												<li class="opt-items"> 
													<div class="custom-control custom-checkbox">
														<input type="checkbox" class="checkbox custom-control-input" id="depts<?php echo $rs['id'];?>" value="<?php echo $rs['id'];?>"  name="selector[]" checked >
														<label class="custom-control-label" for="depts<?php echo $rs['id'];?>">
															<?php echo $rs['name'];?>
														</label>
													</div>
												</li>
												
											<?php } ?>
										</ul>
									</div>
													
								</div>
							</div>
						</div>
					</div>
					
					
				</div>
				
				<div class="clearfix"></div>
					 <div class="row">
						<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-2 py-2 text-center">
							<input type="submit" value="save_new" name="save_new" id="save_new" label="<?php echo $tr->translate('SAVE');?>" dojoType="dijit.form.Button" 
							   class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-saved" />
						</div>
					 </div>
			</div>
			 
		</form>
	</div>
</div>
<script type="text/javascript">
	dojo.require('dijit.form.NumberTextBox');
	dojo.require('dijit.form.Textarea');
	function checkall(){
		if ($('#check_all').is(':checked')) {
			$(".checkbox").prop('checked', true);
		}else{
			$(".checkbox").prop('checked', false);
		}
	}
</script>