<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_STUDENT_CHANGE_BRANCH')); 
	$frm = $this->frm;
?>
<div class="card">
	<div class="card-content collapse show">
		<form id="add_car" action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">   
   				if(this.validate()){
					branch_id = dijit.byId('branch_id').get('value');
					if(branch_id==""){
						alert("<?php echo $tr->translate("PLEASE_SELECT_BRANCH");?>");
						dijit.byId("branch_id").focus();
						return false;
					}
					stu_id = dijit.byId('studentid').get('value');
					if(stu_id==""){
						alert("<?php echo $tr->translate("PLEASE_SELECT_STUDENT");?>");
						dijit.byId("studentid").focus();
						return false;
					}
					var degree = dijit.byId('degree').get('value');
					if(degree=="" || degree=="-1"){
						alert("<?php echo $tr->translate("PLEASE_SELECT_DEGREE");?>");
						dijit.byId("degree").focus();
						return false;
					}
					
					var grade = dijit.byId('grade').get('value');
					if(grade=="" || grade=="-1"){
						alert("<?php echo $tr->translate("PLEASE_SELECT_GRADE");?>");
						dijit.byId("grade").focus();
						return false;
					}
					loadingBlock();
       				return true;
  				}else {
  					return false;
  				}
			</script>
			<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-sitemap" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_STUDENT_CHANGE_BRANCH');?></h4>
	    			</div>
	    			<div class="col-sm-4 text-right">
	    			</div>
	    		</div>
	    	</div>
    		<div class="card-box">
	        	<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
								<div class="row"> 
										<div class="col-md-12 col-sm-12 col-xs-12"> 
											<div class="d-flex"> 
												<div class="settings-main-icon ">
													<i class="glyphicon glyphicon-education"></i>
												</div> 
												<div class="col-md-10 col-sm-10 col-xs-12"> 
													<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("STUDENT_INFO");?></p>
												</div> 
											</div>
											<div class="form-group">
												
											</div>
											<div class="form-group">
													<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("BRANCH");?> </label>
													<div class="col-md-7 col-sm-7 col-xs-12">
														<?php echo $frm->getElement("branch_id");?>
													</div>
											</div>
											<div class="form-group">
												<label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("STUDENT");?> <span class="required">*</span>
												</label>
												<div class="col-md-7 col-sm-7 col-xs-12">
														<input id="studentid" />
												</div>
											</div>
											<div class="form-group">
												<label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("NOTE");?>
												</label>
												<div class="col-md-7 col-sm-7 col-xs-12">
														<?php echo $frm->getElement("note");?>
												</div>
											</div>
											<div class="form-group">
											   <div class="col-md-12 col-sm-12 col-xs-12">
													<div class="card-blogform bgInfo">
														<div class="card-body introduction">
															<div class="form-group">
																<div class="d-flex"> 
																	<div class="settings-main-icon ">
																		<i class="fa fa-info-circle" aria-hidden="true"></i>
																	</div> 
																	<div class="col-md-10 col-sm-10 col-xs-12"> 
																		<p class="mb-0 tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("STUDY_INFO")?></p>
																	</div> 
																</div>
															</div>
															<div class="row g-3" id="lbltogroup" name="detail_to_group">
																<div class="col-md-6 col-sm-6 col-xs-12">
																	<p class="text-primary me-2 mb-0"><?php echo $tr->translate("ACADEMIC_YEAR")?>: <strong class="value fromAcademic">N/A</strong></p>
																	<p class="text-primary me-2 mb-0"><?php echo $tr->translate("DEGREE")?>: <strong class="value fromDegree">N/A</strong></p>
																</div>
																<div class="col-md-6 col-sm-6 col-xs-12">
																	<p class="text-primary me-2 mb-0"><?php echo $tr->translate("GRADE")?>: <strong class="value fromGrade">N/A</strong></p>
																	<p class="text-primary me-2 mb-0"><?php echo $tr->translate("SESSION")?>: <strong class="value fromSession">N/A</strong></p>
																	<p class="text-primary me-2 mb-0"><?php echo $tr->translate("ROOM")?>: <strong class="value fromRoom">N/A</strong></p>
																</div>
															</div>
													   </div>
													</div>
											   </div>
											</div>

										</div>
								</div>
						</div>
					</div>
	           </div>

	           <div class="col-md-4 col-sm-4 col-xs-12">
			  	 <div class="card-blogform">
						<div class="card-body"> 
								<div class="row"> 
										<div class="col-md-12 col-sm-12 col-xs-12"> 
											<div class="d-flex"> 
												<div class="settings-main-icon ">
													<i class="glyphicon glyphicon-th-large"></i>
												</div> 
												<div class="col-md-10 col-sm-10 col-xs-12"> 
													<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("GROUP_INFO");?></p>
												</div> 
											</div>

											<div class="form-group">
												
											</div>
											<div class="form-group">
												<label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("TO_BRANCH");?>
												</label>
												<div class="col-md-7 col-sm-7 col-xs-12">
														<input id="to_branch" />
												</div>
											</div>
											<div class="form-group">
												<label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("MOVING_DATE")?>
												</label>
												<div class="col-md-7 col-sm-7 col-xs-12">
														<input dojoType="dijit.form.DateTextBox"  class="fullside" id="moving_date" name="moving_date" value="now" type="text">
												</div>
											</div>
											<div class="form-group">
												<label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("ACADEMIC_YEAR");?>
												</label>
												<div class="col-md-7 col-sm-7 col-xs-12">
														<?php echo $frm->getElement("academic_year");?>
												</div>
											</div>
											<div class="form-group">
												<label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("DEGREE");?>
												</label>
												<div class="col-md-7 col-sm-7 col-xs-12">
														<?php echo $frm->getElement("degree");?>
												</div>
											</div>
											<div class="form-group">
												<label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("GRADE");?>
												</label>
												<div class="col-md-7 col-sm-7 col-xs-12">
														<input id="grade" />
												</div>
											</div>
											<div class="form-group">
												<label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("REASON");?>
												</label>
												<div class="col-md-7 col-sm-7 col-xs-12">
														<?php echo $frm->getElement("reason");?>
												</div>
											</div>
											<div class="form-group">
												<div class="col-md-12 col-sm-12 col-xs-12">
														<div  id="lbltogroup" >
														</div>
												</div>
											</div>
									</div>
							</div>
						</div>
					</div>

	           </div>
       	  </div>
       	  <div class="clearfix"></div>
		    <div class="card-box">
               	<div class="col-sm-12 border-top mt-20 ptb-10 text-center">
               			<input class="button-class button-danger" iconClass="glyphicon glyphicon-erase" type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>" onclick="clear();" dojoType="dijit.form.Button"/>
						<input type="submit" value="save_close" name="save_close" id="save_close" label="<?php echo $tr->translate('SAVE_CLOSE');?>" dojoType="dijit.form.Button" 
						class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-saved" />
						<input type="submit" value="save_new" name="save_new" id="save_new" label="<?php echo $tr->translate('SAVE_NEW');?>" dojoType="dijit.form.Button" 
						class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-open" />
	    		</div>
	    	</div>
       </form>
	</div>
</div>
<style>
.form-group ul {
    list-style-type: none;
    padding: 0;
    margin: 0;
}
.form-group ul li {
    line-height: 28px;
}
.form-group ul li span.lbl-tt {
    min-width: 100px;
    display: inline-block;
    font-weight: bold;
}
.bgInfo {
    background: #feffca !important;
    border: solid 1px #02014a;
}
</style>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.Textarea");
	var grade_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
	var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
	var student_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
	dojo.ready(function(){
		new dijit.form.FilteringSelect({
			store: student_store,
		    queryExpr: "*${0}*",
			autoComplete: false,                     
			required: true,                      
		    id: "studentid",
		    name: "studentid",  
		    class: 'fullside', 
		    readonly:false,
		    required:false,
		    placeHolder:"<?php echo $tr->translate("PLEASE_SELECT_STUDENT");?>",          
		    onChange: function() {  
		    	getStudentInfo();
		    }
		}, "studentid");

		new dijit.form.FilteringSelect({
			store: group_store,
		    queryExpr: "*${0}*",
			autoComplete: false,                     
			required: true,                      
		    id: "to_branch",
		    name: "to_branch",  
		    class: 'fullside', 
		    readonly:false,
		    required:false,
		    placeHolder:"<?php echo $tr->translate("TO_BRANCH");?>",          
		    onChange: function() {  
		    }
		}, "to_branch");

		new dijit.form.FilteringSelect({
			store: grade_store,
			queryExpr: "*${0}*",
			autoComplete: false,                                           
			id: "grade",
			name: "grade",           
			class: 'fullside', 
			placeHolder:"<?php echo $tr->translate("SELECT_GRADE");?>",          
			onChange: function() { 
			}
		}, "grade");
		getallstudentname();
		getAllToBranch();
		
		var branch_id = dijit.byId('branch_id');
		branch_id.on('change', function(evt) {
			getallstudentname();
			getAllToBranch();
		});
	}); 

	function getAllToBranch(){
		var url_data = '<?php echo $this->url(array('module'=>'foundation','controller'=>'changebranch','action'=>'getalltobranch')); ?>';
		dijit.byId('to_branch').reset();
		branch_id = dijit.byId("branch_id").attr("value");
		if(branch_id=='' || branch_id==-1){
			var tobranch_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
			dijit.byId('to_branch').set('store',tobranch_store);  
			dijit.byId('branch_id').focus();
			return false;
		}
		dojo.xhrPost({
			url:url_data,
			content:{
				'branch_id':branch_id
			},
			handleAs:"json",
			load: function(data) {
				tobranch_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('to_branch').set('store',tobranch_store);  
			},
			error: function(err) {
			}
		});
	}
	var url_student = '<?php echo $this->url(array('module'=>'foundation','controller'=>'register','action'=>'getstudentstudyinfo')); ?>';
	function getStudentInfo(){
		studentid = dijit.byId('studentid').get('value');
		if(studentid==0 || studentid==0){
			$(".fromAcademic").html("N/A");
			$(".fromDegree").html("N/A");
			$(".fromGrade").html("N/A");
			$(".fromSession").html("N/A");
			$(".fromGroup").html("N/A");
			$(".fromRoom").html("N/A");
			dijit.byId('studentid').focus();
			return false;
		}
		dojo.xhrPost({
			url:url_student,
			content:{
				'study_id':studentid
				},
			handleAs:"json",
			load: function(data) {
				
				dijit.byId('academic_year').set('value',data.academic_year);  
				dijit.byId('degree').set('value',data.degree);  
				
				$(".fromAcademic").html(data.academicYearTitle);
				$(".fromDegree").html(data.degreeTitle);
				$(".fromGrade").html(data.gradeTitle);
				$(".fromSession").html(data.sessionTitle);
				$(".fromGroup").html(data.groupName);
				$(".fromRoom").html(data.roomName);
				
				setTimeout(function () {
					dijit.byId('grade').set('value',data.grade); 
				}, 500);
			},
			error: function(err) {
				
			}
		});
	}
	
	function getallstudentname(){//
		var url_data = '<?php echo $this->url(array('module'=>'foundation','controller'=>'register','action'=>'getallstudentdata')); ?>';
		dijit.byId('studentid').reset();
		branch_id = dijit.byId("branch_id").attr("value");
		if(branch_id=='' || branch_id==-1){
			var student_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
			dijit.byId('studentid').set('store',student_store);  
			dijit.byId('branch_id').focus();
			return false;
		}
		loadingBlock();
		dojo.xhrPost({
			url:url_data,
			content:{
				'branch_id':branch_id,'is_maingrade':1
			},
			handleAs:"json",
			load: function(data) {
				student_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('studentid').set('store',student_store);  
			    HideloadingBlock();
			},
			error: function(err) {
			}
		});
	}
	
	var url_dept = '<?php echo $this->url(array('module'=>'global','controller'=>'grade','action'=>'get-grade')); ?>';
	function getallGrade(){
		dept_id = dijit.byId('degree').get('value');
		if(dept_id=='' || dept_id==-1){return false;}
		dojo.xhrPost({
			url:url_dept,
			content:{
				'dept_id':dept_id,
				'noaddnew':1
				},
			handleAs:"json",
			load: function(data) {
				dijit.byId('grade').attr('value','');
				grade_store  = getDataStorefromJSON('id','name', data);
				dijit.byId('grade').set('store',grade_store); 
			},
			error: function(err) {
			}
		});
	}
</script>
