<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
$frm = $this->frm_expense;
?>

<title><?php echo $tr->translate("ADD_OTHER_EXPENSE") ?></title>
<div class="card">
	<div class="card-content collapse show">
		<form id='office_receipt' action="<?php echo $this->url(array('module' => 'registrar', 'controller' => 'expense', 'action' => 'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">
				if (this.validate()) {
					condition = checkValidateAddRow();
					if (condition == false) {
						alert("<?php echo $tr->translate('PLEASE_SELECT_CATEGORY_EXPENSE'); ?> !!! ");
						return false;
					}
					loadingBlock();
					return true;
				} else {
					return false;
				}
			</script>
			<div class="card-box">
				<div class="col-sm-12 border-botom">
					<div class="col-sm-8 pd-0">
						<h4 class="m-b-0"><i class="fa fa-money" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_OTHER_EXPENSE'); ?></h4>
					</div>
					<div class="col-sm-4 text-right">
					</div>
				</div>
			</div>
			<div class="card-box">
				<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card-blogform">
						<div class="card-body">
							<div class="row">
								<div class="col-md-12 col-sm-12 col-xs-12">
									<div class="d-flex ">
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-usd" aria-hidden="true"></i>
										</div>
										<div class="col-md-10 col-sm-10 col-xs-12">
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("EXPENSE_INFO"); ?></p>
										</div>
									</div>
									<div class="col-md-12 col-sm-12 col-xs-12">

									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("BRANCH"); ?> <span class="required">*</span>:
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('branch_id'); ?>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("EXPENSE_DATE"); ?> <span class="required">*</span>:
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('Date'); ?>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("RECEIPT_NO"); ?> :
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('invoice'); ?>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("INVOICE"); ?> :
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('external_invoice'); ?>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("RECEIVER"); ?> :
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('receiver'); ?>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("NOTE"); ?> :
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('Description'); ?>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card-blogform">
						<div class="card-body">
							<div class="row">
								<div class="col-md-12 col-sm-12 col-xs-12">
									<div class="d-flex ">
										<div class="settings-main-icon ">
											<i class="material-icons-outlined">payments</i>
										</div>
										<div class="col-md-10 col-sm-10 col-xs-12">
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("EXPENSE_INFO"); ?></p>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("EXPENSE_TITLE"); ?> <span class="required">*</span>:
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('title'); ?>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("TOTAL_EXPENSE"); ?> <span class="required">*</span>:
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('total_amount'); ?>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("PAYMENT_METHOD"); ?> :
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('payment_method'); ?>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("BANK_NAME"); ?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('bank_name'); ?>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("BANK_NOTE"); ?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('cheque_num'); ?>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card-blogform">
						<div class="card-body">
							<div class="row">
								<div class="col-md-12 col-sm-12 col-xs-12">
									<div class="d-flex ">
										<div class="settings-main-icon ">
											<i class="	glyphicon glyphicon-user" aria-hidden="true"></i>
										</div>
										<div class="col-md-6 col-sm-6 col-xs-12">
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("SUPPLIER"); ?></p>
										</div>
										<span class=" col-md-6 col-sm-6 col-xs-12 text-danger">
											<p class="tx-20 font-weight-semibold " style="color:red;">
												<?php echo $tr->translate("OLD_SUPPLIER"); ?>
												<input type="checkbox" name="is_new_cu" id="is_new_cu"  onClick="isNewCustomer()">
											</p>
										</span>
									</div>
									<div class="col-md-12 col-sm-12 col-xs-12 ">
										&nbsp;
									</div>
									<div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("SUPPLIER_NAME"); ?> <span class="required">*</span>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<span id="new_cu">
												<input type="text" dojoType="dijit.form.ValidationTextBox" name="supplier_name" id="supplier_name" value="" class="fullside" required="required">
											</span>
											<span id="old_cu">
												<select dojoType='dijit.form.FilteringSelect' id="sup_id" name="sup_id" onChange="getSuplierInfo();" class="fullside" required="false" ​​ queryExpr="*${0}*" autoComplete="false" placeholder="ជ្រើសរើស ឈ្មោះអ្នកផ្គត់ផ្គង់">
													<option></option>
													<?php if (!empty($this->sup_ids)) foreach ($this->sup_ids as $rs_sup) { ?>
														<option value="<?php echo $rs_sup['id']; ?>"><?php echo $rs_sup['sup_name']; ?></option>
													<?php } ?>
												</select>
											</span>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("SEX"); ?></label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<select dojoType='dijit.form.FilteringSelect' id="sex" name="sex" class="fullside">
												<option value="1"><?php echo $tr->translate("MALE") ?></option>
												<option value="2"><?php echo $tr->translate("FEMALE") ?></option>
											</select>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("Tel"); ?></label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<input type="text" dojoType="dijit.form.TextBox" name="phone" id="phone" value="" class="fullside" placeHolder="<?php echo $tr->translate("Tel"); ?>">
										</div>
									</div>
									<div class="form-group">
										<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("EMAIL"); ?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<input type="text" dojoType="dijit.form.ValidationTextBox" value="" id="email" name="email" class="fullside" />
										</div>
									</div>
									<div class="form-group">
										<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("ADDRESS"); ?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<input type="text" dojoType="dijit.form.ValidationTextBox" value="" id="address" name="address" class="fullside" />
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="card-box">
				<div class="col-md-12 col-sm-12 col-xs-12">
					<div class="card-blogform">
						<div class="card-body">
							<div class="row">
								<div class="col-md-12 col-sm-12 col-xs-12">
									<div class="form-group" style="background: #d8e0e2;padding: 5px 15px;margin: 0;border: solid 1px #697996;border-radius: 2px;margin-top: 10px;">
										<label class="control-label bold col-md-2 col-sm-2 col-xs-12"><?php echo $tr->translate("EXPENSE_ITEM"); ?> </label>
										<div class="col-md-3 col-sm-3 col-xs-12">
											<select style="height: 30px;" type="text" name="parentcategory" id="parentcategory"
												placeHolder="Main Category" class="custome-select-opt fullside"
												autoComplete="false" queryExpr="*${0}*" onchange="filterSubCategory();">
												<option value="0"><?php echo $tr->translate("SELECT_CATEGORY"); ?></option>
												<?php
												echo $this->rsmaincategory;
												?>
											</select>
										</div>
										<div class="col-md-3 col-sm-3 col-xs-12">
											<select style="height: 30px;" required="false" type="text" name="category"
												placeHolder="<?php echo $tr->translate("subCategory"); ?>"
												id="category" class="fullside" dojoType="dijit.form.FilteringSelect"
												autoComplete="false" queryExpr="*${0}*" onchange="getExpenseItem();">
												<option value=""></option>
											</select>
										</div>
										<div class="col-md-3 col-sm-3 col-xs-12">
											<input id="itemId" name="itemId" />
										</div>
										<div class="col-md-1 col-sm-1 col-xs-12">
											<input class="button-class button-primary" iconClass="glyphicon glyphicon-refresh" type="button" label="<?php echo $tr->translate('REFRESH'); ?>" dojoType="dijit.form.Button" onclick="getExpenseItem();" />
										</div>
										<div class="clearfix"></div>
									</div>
									<div class="form-group">
										<table id="table_row" border="1" style="width:100%; border-collapse: collapse; border:1px solid #ccc;">
											<tr id="head-title" class="head-td" align="right"></tr>
										</table>
										<input type="hidden" id="identity" name="identity" />
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="clearfix"></div>
			<div class="card-box mt-20">
				<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
					<input type="submit" label="<?php echo $tr->translate("SAVECLOSE"); ?>" id='saveclose' name='saveclose' value='saveclose' dojoType="dijit.form.Button"
						class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" />
					<input type="button" onclick='cloneReceipt();printSave("");' label="<?php echo $tr->translate("SAVE_PRINT") ?>" name='savenew' value='savenew' dojoType="dijit.form.Button"
						class="button-class button-primary" iconClass="glyphicon glyphicon-print" />
				</div>
			</div>
		</form>
	</div>
</div>
<div class="dijitHidden" style="padding: 0px; margin: 0px;">
	<div data-dojo-type="dijit.Dialog" style="width:21cm;height: 15cm ;" align="center" data-dojo-props="title:'<?php echo $tr->translate("ប័ណ្ណចំណាយ"); ?>'" id="terms">
		<div id="printexpense" style="width: 19cm !important; height: 12.3cm ; padding: 0px; margin-bottom:30px; ">
			<?php echo $this->officailExpensereceipt; ?>
		</div>
		<button dojoType="dijit.form.Button" class="button-class button-danger" iconClass="glyphicon glyphicon-remove"
			type="button" onclick="hideDialog();"><?php echo $tr->translate('CANCEL'); ?></button>
		<button dojoType="dijit.form.Button" class="button-class button-primary" iconClass="glyphicon glyphicon-print"
			type="button" onclick="printSubmit();"><?php echo $tr->translate("SAVE_PRINT"); ?></button>
	</div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>

<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:30%;" id="popup_cate_expense">
		<form name='add_subject_exam' id='add_cate_expense' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table cellspacing="10" width="100%" style="margin: 0 auto;">
				<tr>
					<td>
						<fieldset>
							<legend align="center" style="font-size: 18px;"><strong><?php echo $tr->translate("ADD_CATE_EXPENSE"); ?></strong></legend>
							<table style="margin: 0 auto; width: 95%;white-space: nowrap; line-height: 35px;" cellspacing="10">
								<tr>
									<td><?php echo $tr->translate("TITLE") ?></td>
									<td>
										<input name="account_name" id="account_name" dojoType="dijit.form.ValidationTextBox" required="required" class="fullside" />
									</td>
								</tr>
								<tr>
									<td><?php echo $tr->translate("PARENT") ?></td>
									<td>
										<select name="parent" id="parent" dojoType="dijit.form.FilteringSelect" class="fullside">
											<option value=""></option>
											<?php if (!empty($this->parent)) {
												foreach ($this->parent as $parent) { ?>
													<option value="<?php echo $parent['id'] ?>"><?php echo $parent['name'] ?></option>
											<?php }
											} ?>
										</select>
									</td>
								</tr>
								<tr>
									<td><?php echo $tr->translate("ACCOUNT_CODE") ?></td>
									<td>
										<input name="account_code" id="account_code" dojoType="dijit.form.TextBox" required="required" class="fullside" />
									</td>
								</tr>
								<tr>
									<td colspan="2" align="center">
										<input type="button" onclick="addCateExpense();" value="save_new" name="ex_save_new" id="ex_save_new" label="<?php echo $tr->translate('SAVE_NEW'); ?>" dojoType="dijit.form.Button"
											class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-saved" />
									</td>
								</tr>
							</table>
						</fieldset>
					</td>
				</tr>
			</table>
			<input type="hidden" name="tow_value" id="tow_value" value="" />
		</form>
	</div>
</div>

<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script src="<?php echo $this->baseUrl();?>/admin/js/global.js"></script>
<link href="<?php echo $this->baseUrl()."/admin"?>/3.5.0/select2.css" rel="stylesheet">
<script src="<?php echo $this->baseUrl()."/admin"?>/3.5.0/select2.min.js"></script>
<script type="text/javascript">
	dojo.require("dijit.form.Textarea");
	dojo.require("dijit.form.NumberTextBox");
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dojo.data.ItemFileWriteStore");
	dojo.require("dojo.NodeList-manipulate");

	dojo.ready(function() {
		new dijit.form.FilteringSelect({
		
			queryExpr: "*${0}*",
			autoComplete: false,                     
			required: true,                      
			id: "itemId",
			name: "itemId",  
			class: 'fullside',  
			required:false,
			placeHolder:"<?php echo $tr->translate("SELECT_EXPENSE_ITEM");?>",          
			onChange: function() {  
				exp_item_id   = dijit.byId('itemId').get('value');

				if(exp_item_id==-1 || exp_item_id==''){
					if(exp_item_id==-1){
						addTab('<?php echo $tr->translate("ADD_EXPENSE_ITEM");?>','<?php echo $this->baseUrl() . "/registrar/cateexpense/add".'?inFrame=true'; ?>');
						dijit.byId('itemId').reset();	
					}
					return false;
				}else{

					let indexremove =itemstoreorg.findIndex(obj => obj.id == exp_item_id);
					itemstoreorg.splice(indexremove, 1);
					
					newexpitemstore  = getDataStorefromJSON('id','name', itemstoreorg);
					dijit.byId('itemId').set('store',newexpitemstore);

					var rowId = $('#identity').val();
					if(rowId!=''){ 
						var rowIDArray = rowId.split(',');
						for(var n = 0; n < rowIDArray.length; n++){
							var expense_id = dijit.byId('expense_id_'+rowIDArray[n]).get('value');
							if(expense_id == exp_item_id ){
								dijit.byId('itemId').reset();
								alert("Already Existed !!! ");
								return false;
								
							}
						}
					}
					addRow();
				}
			}
		}, "itemId");

		getReceiptNumber("");
		dijit.byId('payment_method').attr('value', 1);

		isNewCustomer();
		
		$("#parentcategory").select2(
			{dropdownAutoWidth : true,allowClear: "true"}
		);
		getExpenseItem();
	});

	function hideDialog() {
		dijit.byId('terms').hide();
	}

	function isNewCustomer(){
		is_new = $('#is_new_cu').val();
		if($('#is_new_cu').is(':checked')){
			$('#old_cu').show();
			$('#new_cu').hide();
			dijit.byId('supplier_name').attr('required', false);
		}else{
			$('#old_cu').hide();
			$('#new_cu').show();
			dijit.byId("sup_id").attr("value",'');
			dijit.byId("supplier_name").attr("value",'');
			dijit.byId("phone").attr("value",'');
			dijit.byId("email").attr("value",'');
			dijit.byId("address").attr("value",'');
			dijit.byId('supplier_name').attr('required', true);
		}
	}

	var url_getsuplier = "<?php echo $this->url(array('module'=>'stock','controller'=>'purchase','action'=>'get-supplier-info')); ?>";
	function getSuplierInfo(){
		sup_id = dijit.byId('sup_id').get('value');
		if(sup_id !=''){
			dojo.xhrPost({
				url:url_getsuplier,
				content:{
					'sup_id':sup_id
					},
				handleAs:"json",
				load: function(data) {
					dijit.byId("supplier_name").attr("value",data.sup_name);
					dijit.byId("sex").attr("value",data.sex);
					dijit.byId("phone").attr("value",data.tel);
					dijit.byId("email").attr("value",data.email);
					dijit.byId("address").attr("value",data.address);
				},
				error: function(err) {
				}
			});
		}
	}

	var url_get_recceipt_number = "<?php echo $this->url(array('module' => 'registrar', 'controller' => 'expense', 'action' => 'get-receipt-number')); ?>";
	function getReceiptNumber(receipt) {
		branch_id = dijit.byId('branch_id').get('value');
		if (branch_id > 0) {
			dojo.xhrPost({
				url: url_get_recceipt_number,
				content: {
					'branch_id': branch_id
				},
				handleAs: "json",
				load: function(data) {
					dijit.byId('invoice').attr('value', data);
					if (receipt != '') {
						printSave(data);
					}
				},
				error: function(err) {
					alert(err);
				}
			});
		}
	}

	function deleteRecord(index) {
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		for (var i = 0; i < arrays.length; i++) {
			if (arrays[i] == index) arrays.splice(i, 1);
		}
		var strings = arrays.join(',');
		$('#identity').val(strings);
		dojo.query("#row" + index).remove();
		netTotal();
	}

	function calculateTotal(index) {
		netTotal();
	}

	function netTotal() {
		var netTotal = 0;
		var rowId = $('#identity').val();
		var rowIDArray = rowId.split(',');
		for (var n = 0; n < rowIDArray.length; n++) {
			netTotal += dijit.byId('total_' + rowIDArray[n]).get('value');
		}
		dijit.byId('total_amount').attr('value', netTotal);
	}

	var template = '';
	var service = '';
	var col = 0;
	var no = 0;
	var title = 0;
	tmp = '';
	temp = '';
	optexpense = '<?php echo $this->expenseopt; ?>';

	function addRow() {

		label_exp_item = dijit.byId("itemId").attr('displayedValue');
		itemId=dijit.byId("itemId").get("value");

		if(itemId==''){
			return false;
		}

		dijit.byId('itemId').attr('value', '');

		col++;
		no++;
		template = '';
		if (title != 1) {
			temp += '<th><?php echo $tr->translate("DEL"); ?></th>';
			temp += '<th><?php echo $tr->translate("N_O"); ?></th>';
			temp += '<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("CATE_EXPENSE"); ?></th>';
			temp += '<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("PRICE"); ?><span class="required">*</span></th>';
			temp += '<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("QTY"); ?><span class="required">*</span></th>';
			temp += '<th id="lbl_titlemetion" width="150px"><?php echo $tr->translate("TOTAL"); ?></th>';
			temp += '<th><?php echo $tr->translate("REMARK"); ?></th>';
			dojo.query("#head-title").append(temp);
			title = 1;
		}
		template += '<td width="47px" align="center"><img onclick="deleteRecord(' + col + ');calculateTotal(' + col + ');calculatePaidAmount(' + col + ');" src="<?php echo $this->baseUrl(); ?>/images/Delete_16.png"></td>';
		template += '<td width="50px" align="center">' + no + '</td>';
		template += '<td style="width:300px">'+label_exp_item+'<input type="hidden" dojoType="dijit.form.TextBox" required="true" id="label_exp_item_'+col+'" name="label_exp_item_'+col+'" value="'+label_exp_item+'" /><input type="hidden" dojoType="dijit.form.TextBox" required="true" id="expense_id_'+col+'" name="expense_id_'+col+'" value="'+itemId+'" /></td>';
		template += '<td><input type="text" required="1" onkeyup="calculateTotal(' + col + ');" name="price_' + col + '" id="price_' + col + '"  dojoType="dijit.form.NumberTextBox" style="width:120px;" /></td>';
		template += '<td><input type="text" required="1" onkeyup="calculateTotal(' + col + ',1);" name="qty_' + col + '" id="qty_' + col + '" dojoType="dijit.form.NumberTextBox" style="width:120px;" /></td>';
		template += '<td><input type="text" onkeyup="calculateTotal(' + col + ');" readonly="readonly" name="total_' + col + '" id="total_' + col + '" dojoType="dijit.form.NumberTextBox" style="width:150px;" /></td>';
		template += '<td><input type="text" name="remark_' + col + '" id="remark_' + col + '" dojoType="dijit.form.TextBox" placeholder="<?php echo $tr->translate("NOTE"); ?>" style="width:100%;" /><label id="subsub"></label></td>';
		tmp = '<tr id="row' + col + '">';
		tmp += "</tr>";
		dojo.query("#table_row").append(tmp);
		if ($("#identity").val() != "") {
			var identity = $("#identity").val();
			$("#identity").val(identity + ',' + col);
		} else {
			$("#identity").val(col);
		}
		dojo.html.set(dojo.byId("row" + col), template, {
			parseContent: true,
		});

		popupCateExpense(col);
	}

	function calculateTotal(index, type) {
		price = dijit.byId('price_' + index).get('value');
		price = isNaN(price) ? 0 : price;

		qty = dijit.byId('qty_' + index).get('value');
		qty = isNaN(qty) ? 0 : qty;

		dijit.byId('total_' + index).attr('value', price * qty);

		dijit.byId('total_amount').attr('value', netTotal);
		netTotal();
	}

	function printSave(new_receipt) {
		if (dijit.byId('office_receipt').validate()) {

			condition = checkValidateAddRow();
			if (condition == false) {
				alert("Please select category expense !!! ");
				return false;
			}

			if (dijit.byId("payment_method").get("value") == -1) {
				alert("សូមជ្រើសរើសប្រភេទបង់ប្រាក់");
				dijit.byId("payment_method").focus();
				return false;
			}
			if (new_receipt == '') {
				getReceiptNumber(1);
			}
			paid_date = dijit.byId("Date").get('value')
			var today = new Date(paid_date);
			var dd = today.getDate();
			var mon = today.toDateString().substr(4, 3); //January is 0!
			var yyyy = today.getFullYear();
			dojo.byId("bl_branch").innerHTML = dijit.byId("branch_id").attr('displayedValue');
			dojo.byId("lb_paynote").innerHTML = dijit.byId("title").attr('displayedValue');
			dojo.byId("lb_paiddate").innerHTML = dd + '/' + mon + '/' + yyyy;
			dojo.byId("lb_receipt_no").innerHTML = new_receipt;
			dojo.byId("bl_supplier").innerHTML = dijit.byId("sup_id").attr('displayedValue');
			dojo.byId("bl_suppliername").innerHTML = dijit.byId("sup_id").attr('displayedValue');
			dojo.byId("bl_phone").innerHTML = dijit.byId("phone").attr('displayedValue');
			dojo.byId("lb_note").innerHTML = dijit.byId("Description").get('value');
			dojo.byId("lb_receiver").innerHTML = dijit.byId("receiver").get('value');
			dojo.byId("lb_paymentmehtod").innerHTML = dijit.byId("payment_method").attr('displayedValue');
			dojo.byId("lb_bank").innerHTML = dijit.byId("bank_name").attr('displayedValue');
			dojo.byId("lb_cheque").innerHTML = dijit.byId("cheque_num").attr('displayedValue');
			dojo.byId("lb_invoice").innerHTML = dijit.byId("external_invoice").get('value');
			var rowId = $('#identity').val();
			let totalPaid = dojo.number.format(dijit.byId("total_amount").get('value'), {
				places: 2
			});
			var rowIDArray = rowId.split(',');
			template = "";
			temp = '<table class="collape tablesorter"  align="center" style=" width: 100%; padding: 0px; margin: 0px; border-collapse: collapse; border: 1px solid #000; font-size:12px;font-family:Khmer OS Battambang !important;  " id="table">'
			temp += '<tr class="" style="text-align:center; height:25px;">';
			temp += '<td><strong>លរ/No.</div></strong></td>';
			temp += '<td><strong>ប្រភេទចំណាយ/Expense Type</strong></td>';
			temp += '<td><strong>ពណ៌នា/Description</strong></td>';
			temp += '<td><strong>តម្លៃ/Price</strong></td>';
			temp += '<td><strong>ចំនួន/Qty</strong></td>';
			temp += '<td><strong>ចំនួនប្រាក់/Amount</strong></td>';
			temp += '</tr>';
			n = 0;
			i = 1;
			for (var n = 0; n < rowIDArray.length; n++) {
				temp += '<tr style="height: 22px;"​ align="center"><td align="center" style="border:1px solid #000;">' + i + '</td>';
				temp += '<td align="left" style="border:1px solid #000;max-width:200px !important;line-height:18px;">&nbsp;' + dijit.byId("label_exp_item_" + rowIDArray[n]).attr('displayedValue') + '</td>';
				temp += '<td style="border:1px solid #000;">' + dijit.byId("remark_" + rowIDArray[n]).get('value') + '</td>';
				temp += '<td align="center">' + dijit.byId("price_" + rowIDArray[n]).attr('displayedValue') + '</td>';
				temp += '<td align="center">' + dijit.byId("qty_" + rowIDArray[n]).attr('displayedValue') + '</td>';
				temp += '<td align="center">' + dijit.byId("total_" + rowIDArray[n]).attr('displayedValue') + '</td>';
				i++;
				temp += '</tr>';
			}
			for (row = n + 1; row < 4; row++) {
				temp += '<tr style="height: 22px;"​ align="center"><td align="center" style="border:1px solid #000;">' + row + '</td>';
				temp += '<td align="left" style="border:1px solid #000;max-width:200px !important;line-height:18px;">&nbsp;&nbsp;</td>';
				temp += '<td align="center" style="border:1px solid #000;"><span style="font-family: Khmer OS Battambang;color:#000;font-size: 12px;"></td>';
				temp += '<td align="center" style="border:1px solid #000;"><span style="font-family: Khmer OS Battambang;color:#000;font-size: 12px;"></td>';
				temp += '<td align="center" style="border:1px solid #000;"><span style="font-family: Khmer OS Battambang;color:#000;font-size: 12px;"></td>';
				temp += '<td style="border:1px solid #000;"></td>';
				temp += '</tr>';
			}
			temp += '<tr style="height: 22px;"​ align="center">';
			temp += '<td style="border:1px solid #fff !important;border-top:1px solid #000;" colspan="3"></td>';
			temp += '<td colspan="2" align="center" style="border-bottom:1px solid #fff !important;"><span style="font-family: Khmer OS Battambang;color:#000;font-size: 12px;">ចំណាយសរុប/Total Amount</td>';
			temp += '<td style="border:1px solid #000 !important;"><label id="lb_total_received">$ ' + totalPaid + '</label></td>';
			temp += '</tr>';
			temp += '</table>';
			dojo.byId('t_amountmoneytype').innerHTML = temp;
			dijit.byId("terms").show();
		}
	}

	function submitData() {
		if (dijit.byId('office_receipt').validate()) {

			condition = checkValidateAddRow();
			if (condition == false) {
				alert("Please select category expense !!! ");
				return false;
			}
			dijit.byId('saveclose').set('disabled', true);
			dijit.byId('office_receipt').submit();
		}
	}

	function doPrintInvoice() {
		window.frames["print_frame"].document.body.innerHTML = dojo.byId('printexpense').innerHTML;
		window.frames["print_frame"].window.focus();
		window.frames["print_frame"].window.print();
		$('#office_receipt').submit();
	}

	function cloneReceipt() {
		loadingBlock();
		setTimeout(function() {
			<?php if (AMOUNT_RECEIPT > 1) { ?>
				dojo.byId('printblog2').innerHTML = dojo.byId('printexpense').innerHTML;
			<?php } ?>
			HideloadingBlock();
		}, 500);
	}

	function checkValidateAddRow() {
		var rowId = $('#identity').val();
		if (rowId != '') {
			var rowIDArray = rowId.split(',');
			for (var n = 0; n < rowIDArray.length; n++) {
				expense = dijit.byId('expense_id_' + rowIDArray[n]).get('value');
				if (expense <= 0) {
					return false;
				}
			}
		}
	}

	var url_expense = "<?php echo $this->url(array('module'=>'registrar','controller'=>'expense','action'=>'get-expense-info')); ?>";
	function popupCateExpense(index) {
		dijit.byId("ex_save_new").attr("disabled", false);
		expense_id = dijit.byId("expense_id_" + index).get('value');

		sup_id = dijit.byId("sup_id").get('value');
	
		$("#tow_value").val(index);
		if (expense_id == -1) {
			dijit.byId("popup_cate_expense").show();
		}else if(expense_id !=''){
			// get old price 
			dojo.xhrPost({
				url:url_expense,
				content:{
					'expense_id':expense_id,
					'sup_id':sup_id
					},
				handleAs:"json",
				load: function(data) {
					dijit.byId('price_' + index).attr('value', data.price);
				},
				error: function(err) {
				}
			});

		}
	}

	var url_getsuplier = "<?php echo $this->url(array('module'=>'stock','controller'=>'purchase','action'=>'get-supplier-info')); ?>";
	function getSuplierInfo(){
		sup_id = dijit.byId('sup_id').get('value');
		if(sup_id !=''){
			dojo.xhrPost({
				url:url_getsuplier,
				content:{
					'sup_id':sup_id
					},
				handleAs:"json",
				load: function(data) {
					dijit.byId("supplier_name").attr("value",data.sup_name);
					dijit.byId("sex").attr("value",data.sex);
					dijit.byId("phone").attr("value",data.tel);
					dijit.byId("email").attr("value",data.email);
					dijit.byId("address").attr("value",data.address);
				},
				error: function(err) {
				}
			});
		}
	}

	var cate_expense_store = getDataStorefromJSON('id', 'name', <?php print_r(Zend_Json::encode($this->cate_expense)); ?>);
	var url_add_cate_expense = '<?php echo $this->url(array("module" => "registrar", "controller" => "expense", "action" => "add-cate-expense")); ?>';

	function addCateExpense() {
		if (dijit.byId('add_cate_expense').validate()) {
			dijit.byId("ex_save_new").attr("disabled", true);
			dojo.xhrPost({
				url: url_add_cate_expense,
				form: dojo.byId("add_cate_expense"),
				handleAs: "json",
				load: function(data) {
					var Itemmake = {
						id: data.id,
						name: dijit.byId('account_name').get('value')
					};
					index = $("#tow_value").val();
					addDataToSelectbox(dijit.byId('expense_id_' + index), cate_expense_store, Itemmake, data.id);
					optexpense = data.new_array;
					dijit.byId('add_cate_expense').reset();
					dijit.byId("popup_cate_expense").hide();
				},
				error: function(err) {
					alert(err);
				}
			});
		}
	}
</script>

<script>
	require(["dojo/ready"], function(ready) {
		ready(function() {
			getbranchinfo();
		});
	});

	function filterClient() {
		getbranchinfo();
	}

	function setReadonlyCheque() {
		payment_method = dijit.byId('payment_method').get('value');
		if (payment_method == 1) {
			dijit.byId('cheque_num').attr('value', '');
			dijit.byId('bank_name').attr('value', '');
			dijit.byId("bank_name").set('readOnly', true);
		} else {
			dijit.byId("bank_name").set('readOnly', false);

		}
	}
	var url_getbranch = "<?php echo $this->url(array('module' => 'registrar', 'controller' => 'register', 'action' => 'getbranchinfo')); ?>";

	function getbranchinfo() {
		branch_id = dijit.byId('branch_id').get('value');
		if (branch_id != "") {
			dojo.xhrPost({
				url: url_getbranch,
				content: {
					'branch_id': branch_id,
				},
				handleAs: "json",
				load: function(data) {
					dojo.byId('lbl_header').innerHTML = data;
				},
				error: function(err) {
					alert(err);
				}
			});
		}
	}

	function filterSubCategory(){
		var datajson = $('#parentcategory').find(":selected").val();
		dijit.byId("category").attr('value','');
		dijit.byId("itemId").attr('value','');
		if(typeof datajson !=="undefined" ){
			var datajsonparent = ($("#parentcategory").find(':selected').data('jsondata'));
			subcategorystore = getDataStorefromJSON('id', 'name', datajsonparent);
			dijit.byId('category').set('store', subcategorystore);
		}
		getExpenseItem();
	}

	function getExpenseItem(){
		categoryId=dijit.byId("category").get("value");
		parentId = $('#parentcategory').val();
		var urlGet = '<?php echo $this->url(array('module'=>'registrar','controller'=>'cateexpense','action'=>'get-expenseitem')); ?>';
		contentData = {
			'parentId':parentId,
			'categoryId':categoryId,
			'addNew':1,
		}
		dojo.xhrPost({
			url:urlGet,	
			handleAs:"json",
			content:contentData,
			load: function(data) {
				itemstoreorg = data;
				exp_itemstore  = getDataStorefromJSON('id','name', data);		
				dijit.byId('itemId').set('store',exp_itemstore);  
			},
			error: function(err){
			}
		});
	}
	
	function printSubmit() {
		if (dijit.byId('office_receipt').validate()) {

			condition = checkValidateAddRow();
			if (condition == false) {
				alert("Please select category expense !!! ");
				return false;
			}
			dijit.byId('saveclose').set('disabled', true);
			
			var url_submit = '<?php echo $this->url(array('module' => 'registrar', 'controller' => 'expense', 'action' => 'addexpenseaj')); ?>';
			dojo.xhrPost({
				url: url_submit,
				form: dojo.byId("office_receipt"),
				handleAs: "json",
				load: function (data) {
					dojo.byId("lb_receipt_no").innerHTML = data.invoice;
					printSave(data.invoice);
					window.frames["print_frame"].document.body.innerHTML = dojo.byId('printexpense').innerHTML;
					window.frames["print_frame"].window.focus();
					window.frames["print_frame"].window.print();

					dijit.byId('terms').hide();
					window.location.href = "<?php echo $this->baseUrl(); ?>/registrar/expense/add";
				},
				error: function (e) {
					alert('<?php echo $tr->translate('ERROR_PRINTING_ACCURED'); ?>!');
				}
			});
		}
	}
</script>