<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("SCHEDULE_SETTING"));
	
	$formList = new Application_Form_Frmtable();
	$urlCopy = $this->baseUrl()."/issuesetting/schedulesetting/copy/id/";
	$urlEdit = $this->baseUrl()."/issuesetting/schedulesetting/edit/id/";
	$frm =  $this->frm_items;
?>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
       		<div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
	    			<h4 class="m-b-0"><i class="fa fa-calendar " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('SCHEDULE_SETTING');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<div class="card-box">
			<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
				<div class="form-group">
					<div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("advance_search");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("branch_search");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement('status_search');?>
                   </div>
                    <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement('start_date');?>
                   </div>
                    <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement('end_date');?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<button class="button-class button-primary" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
						<input type="hidden" name="recordcopy" id="recordcopy" dojoType="dijit.form.TextBox" />
                   </div>
                </div>
			</form>
		</div>
		<div class="card-box">
			<?php echo $this->list;?>
		</div>
	</div>
</div>


<!-- Modal -->
<div class="modal fade" id="modal-info" tabindex="-1" aria-hidden="true">
	<div class="modal-dialog modal-lg modal-simple modal-dialog-centered modal-add-new-role" style=" width: 450px;">
		<div class="modal-content">
			<div class="modal-body">
				<div class="d-block text-end mb-1 w-100">
					<button type="button" class="btn btn-default btn-xs" data-dismiss="modal" aria-label="Close">
						<span class="text-danger" aria-hidden="true">×</span>
					</button>
				</div>
				<div class="d-flex justify-content-between align-items-center mb-1">
					<h6 class="fw-normal mb-0 ">
						<i class="fa fa-university me-1"></i>
						<span class="modal-top-left"></span>
					</h6>
					<div >
						<span class="d-block rounded bg-label-primary  p-2 mb-10">
							<i class="fa fa-briefcase ti-26px me-1"></i>
							<span class="modal-top-right"></span>
						</span>
					</div>
				</div>
				<div class="text-center mb-10">
				  <h4 class="modal-title text-primary mb-1"></h4>
				  <p class="modal-title-desc mb-0"></p>
				</div>
				
				<div class="col-12 contentInfo">
				</div>
			</div>
		</div>
	</div>
</div>
<!--/ Modal -->

 
<script type="text/javascript">
dojo.require("dijit.form.CheckBox"); 
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.DateTextBox");

	function copyRecord(url){
		 id = dijit.byId('recordcopy').get('value');
		 if(id!=''){
			window.location.href = url+'/id/'+id;
		 }else{
			alert('Please select record you want to copy');
			return false;
		 }
	}

	function setValue(index){
		var recordcopy = $('input[name=copy]:checked').val();
		dijit.byId('recordcopy').attr('value',recordcopy);
	}

	var row=0;
	var url="";
	$(function(){
		$.contextMenu({
			selector: '.context-menu-one', 
			callback: function(key, options) {
			
				var m = "clicked: " + key;
				if(key=="edit"){
					url='<?php echo $urlEdit;?>';
				}else if(key=="copy"){
					url='<?php echo $urlCopy;?>';
				}
				
				gotoAction();
				//window.console && console.log(m) || alert(m); 
			},
			items: {
				"edit": {name: "<?php echo $tr->translate("EDIT");?>", icon: "edit", accesskey: "e"},
				"copy": {name: "<?php echo $tr->translate("COPY");?>", icon: "copy"},
			}
		});
	});
	function setrowdata(index){
		row = index;
	}

	var recordid ='';
	function gotoAction(){
		window.location.href =url+row;
	}
	
var urlGetSchInfo = '<?php echo $this->url(array('module'=>'issuesetting','controller'=>'schedulesetting','action' =>'getschedulesettinginfo')); ?>';
function getScheduleSettingInfo(scheduleSetting,getHtml=1) {
	loadingBlock();
	$(".modal-title").html("");
	$(".modal-top-left").html("");
	$(".contentInfo").html("");
	dojo.xhrPost({
		url: urlGetSchInfo,
		content: {
				'scheduleSetting': scheduleSetting,
				'getHtml': getHtml,
			},
		handleAs: "json",
		load: function(data) {
				$(".modal-top-left").html(data.branchName);
			 $(".modal-title").html(data.title);
			 $(".contentInfo").html(data.htmlContent);
			 
			 $('#modal-info').modal('show');
			HideloadingBlock();
		},
		error: function(err) {
			HideloadingBlock();
		}
	});
	
}
</script> 