<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_credit;
	$row = $this->row;
?>
<title><?php echo $tr->translate("EDIT_TRANSFER_CREDIT");?></title>

<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="glyphicon glyphicon-edit" ></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT_TRANSFER_CREDIT');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
    	<form id='office_receipt' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
			if(this.validate()){
				studentId = dijit.byId('studentId').get('value');
				toStudentId = dijit.byId('toStudentId').get('value');
       			 if(studentId==toStudentId){
					alert('<?php echo $tr->translate("STUDENT_MUST_DIFFERENCE");?>');
					dijit.byId('toStudentId').focus();
					return false;
				}
				total_amount= dijit.byId('total_amount').get('value');
				if(total_amount==0){
					alert('<?php echo $tr->translate("NO_BALANCE_TRANSFER");?>');
					return false;
				}

				dijit.byId("saveclose").set("disabled",true);
					return true;
			}else {
				return false;
			}
			</script>
			<div class="card-box">
				<div class="col-md-3 col-sm-3 col-xs-12">
					<div class="card-blogform">
							<div class="card-body"> 
								<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12">
									<div class="d-flex "> 
										<div class="settings-main-icon ">
											<i class="material-icons-outlined">person</i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("INFORMATION_TO");?></p>
										</div> 
									</div>
									<div class="form-group">
										<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("BRANCH");?> </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
										<?php echo $frm->getElement('branch_id');?>
										<?php echo $frm->getElement('id');?>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("STUDENT_NAME");?> </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<input id="studentId" />
											<input type="hidden" class="fullside" id="walletBalance" name="walletBalance" value=""  dojoType="dijit.form.TextBox"/>
											
										</div>
									</div>
									<div class="form-group">
										<label class="control-label custom-switch float-end "> 
											<a href="javascript:void(0);" class="switchButton status"><?php echo $tr->translate("STATUS");?></a> 
											<input type="checkbox" id="status" name="status" class="custom-switch-input" <?php if(!empty($this->row['status'])){ echo "checked";} ?> > 
											<span class="custom-switch-indicator custom-radius switch-status"></span> 
										</label>
									</div>
									<br />
									<div class="animated flipInY col-md-12 col-sm-12 col-xs-12 p-0">
										<div class="tile-stats">
										  <div class="icon"><i class="glyphicon glyphicon-credit-card"></i></div>
										  <div class="count wallet-amt-info"><?php echo number_format(0,2); ?></div>
										  <h3><?php echo $tr->translate("TOTAL_SPACE");?></h3>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
		         </div>
		         <div class="col-md-3 col-sm-3 col-xs-12">
					 <div class="card-blogform">
						<div class="card-body"> 
								<div class="row"> 
									<div class="col-md-12 col-sm-12 col-xs-12">
										<div class="d-flex "> 
											<div class="settings-main-icon ">
												<i class="material-icons-outlined">transfer_within_a_station</i>
											</div> 
											<div class="col-md-10 col-sm-10 col-xs-12"> 
												<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("INFORMATION_RECEIVE");?></p>
											</div> 
										</div>
										<div class="form-group">
											<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("BRANCH");?> </label>
											<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('to_branchId');?>
											</div>
										</div>
										<div class="form-group">
											<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("STUDENT_NAME");?> </label>
											<div class="col-md-7 col-sm-7 col-xs-12">
												<input id="toStudentId" />
											</div>
										</div>
										<div class="form-group">
											<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("DATE");?> </label>
											<div class="col-md-7 col-sm-7 col-xs-12">
												<?php echo $frm->getElement('for_date');?>
											</div>
										</div>
										<div class="form-group">
											<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("TRAN_AMOUNT");?> </label>
											<div class="col-md-7 col-sm-7 col-xs-12">
												<?php echo $frm->getElement('total_amount');?>
											</div>
										</div>
										<div class="form-group">
											<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("NOTE")?> </label>
											<div class="col-md-7 col-sm-7 col-xs-12">
												<?php echo $frm->getElement('Descriptions');?>
											</div>
										</div>
									</div>
								</div>
							</div>
					</div>
		         </div>
				 <div class="col-md-6 col-sm-6 col-xs-12">
					
					<div class="card-blogform">
						<div class="card-body">
							<div class="img-back"></div>
							<div id="lblstudenttypeinfo"><span class="user-badge bg-warning">Student Type</span></div>
							<div class="form-group">
								<div class="d-flex">
									<div class="settings-main-icon ">
										<i class="material-icons-outlined">
										badge
										</i>
									</div>
									<div class="col-md-10 col-sm-10 col-xs-12">
										<p class="tx-20 font-weight-semibold d-flex ">
										<?php echo $tr->translate("INFORMATION_RECEIVE"); ?></p>
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-md-8 col-sm-8 col-xs-12">
									<div id="lbl_blog">
										<div class="col-md-3 col-sm-3 col-xs-12">
											<div class="form-group">
												<div class="thumb-xl member-thumb m-b-10 center-block">
													<?php
													$photo = $this->baseUrl() . "/images/no-profile.png";
													?>
													<img src="<?php echo $photo; ?>" class=" img-thumbnail" alt="profile-image">
													<input id="lbl_photoname" id="lbl_photoname" value="abc" type="hidden" />
												</div>
											</div>
										</div>
										<div class="col-md-9 col-sm-9 col-xs-12">
											<div class="form-group">
												<div class="member-card card-display-reg">
													<p class="text-muted info-list font-13">
														<span class="title-info"><?php echo $tr->translate("STUDENT_CODE"); ?></span><span id="lbl_stucode" class="inf-value"></span>
														<span class="title-info"><?php echo $tr->translate("STUDENT_NAMEKHMER"); ?></span><span id="lbl_namekh" class="inf-value"></span>
														<span class="title-info"><?php echo $tr->translate("NAME_ENGLISH"); ?></span><span id="lbl_nameen" class="inf-value"></span>
														<span class="title-info"><?php echo $tr->translate("DOB"); ?></span><span id="lbl_dob" class="inf-value"></span>
														<span class="title-info"><?php echo $tr->translate('PHONE'); ?></span><span id="lbl_phone" class="inf-value"></span>
														<span class="title-info"><?php echo $tr->translate('Year Enrolled'); ?></span><span id="lbl_enroll_year" class="inf-value"></span>
														<span class="title-info"><?php echo $tr->translate('STUDENT_TYPE'); ?></span><span id="lbl_student_type" class="inf-value"></span>
													</p>
												</div>
											</div>
										</div>
										<div class="clear"></div>
									</div>
								</div>
								<div class="col-md-4 col-sm-4 col-xs-12">
									<div id="lblstudyinfo">
										<p class="text-muted info-list font-13">
											<span class="title-info"><?php echo $tr->translate('DEGREE'); ?></span> :
											<span id="lbl_degree" class="inf-value"></span>
											<span class="title-info"><?php echo $tr->translate('GRADE'); ?></span> :
											<span id="lbl_grade" class="inf-value"></span>
											<span class="title-info"><?php echo $tr->translate('GROUP'); ?></span> :
											<span id="lbl_group" class="inf-value"></span>
											<span class="title-info"><?php echo $tr->translate('PART_TIME_LIST'); ?></span>
											: <span id="lbl_part_time" class="inf-value"></span>
										</p>
									</div>
								</div>
							</div>
							<div class="animated flipInY col-md-12 col-sm-12 col-xs-12 p-0">
									<div class="tile-stats">
									  <div class="icon"><i class="glyphicon glyphicon-credit-card"></i></div>
									  <div class="count to-wallet-amt-info"><?php echo number_format(0,2); ?></div>
									  <h3><?php echo $tr->translate("TOTAL_SPACE");?></h3>
									</div>
								</div>
						</div>
					</div>
		         </div>
		         <div class="clearfix"></div>
			       	<div class="card-box mt-20">
		               	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
						 	<input type="button" label="<?php echo $tr->translate('GO_BACK');?>" id="back" dojoType="dijit.form.Button" 
							 class="button-class button-primary" iconClass="glyphicon glyphicon-refresh" onclick="window.location = '<?php echo $this->url(array('module'=>'accounting','controller'=>"tcredit",'action'=>'index'),null,true); ?>';" />
							<input type="submit" label="<?php echo $tr->translate("SAVECLOSE");?>" name='saveclose' id="saveclose" value='saveclose' dojoType="dijit.form.Button"
								class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-open"/>
		               	</div>
		             </div>
		             </div>
				</form>
		</div>
  </div>
 <style>
	span.user-badge.bg-warning {
		position: absolute;
		top: 5px;
		right: 0;
		padding: 5px 15px;
		border-radius: 10px;
		color: #ffffff;
		font-size: 11px;
		text-transform: uppercase;
		font-weight: bold;
	}

	.bg-warning {
		background: #009bcc !important;
	}

	.thumb-xl.member-thumb {
		position: relative;
	}

	.thumb-xl.member-thumb {
		height: 130px;
		width: 92px;
	}

	.member-card p.text-muted.info-list {
		text-align: left;
		color: #0f2a5b;
	}

	.member-card img.img-thumbnail {
		width: 100%;
		height: 100%;
	}

	.member-card h4 {
		margin: 0;
		padding: 2px 0;
	}

	.img-thumbnail {
		max-height: 110px;
	}

	.text-active,
	.text-deactive {
		position: absolute;
		font-size: 30px;
		left:0px;
		bottom:0px;
	}

	span.title-info {
		min-width: 30%;
		display: inline-block;
		font-weight: 500;
		color: #0f2a5b;
	}

	span.inf-value {
		white-space: nowrap;
		text-overflow: ellipsis;
		display: inline-block;
		width: 55%;
		overflow: hidden;
		vertical-align: bottom;
	}

	.member-card .member-star {
		position: absolute;
		bottom: 10px;
		right: 5px;
		background-color: #ffffff;
		height: 30px;
		width: 30px;
		border-radius: 50%;
		line-height: 26px;
		text-align: center;
		font-size: 18px;
		border: solid 2px;
	}

	.text-active {
		color: #009688;
	}

	.text-deactive {
		color: #ff1203;
	}

	a.btn.btn-default.btn-detail {
		background: #009688;
		padding: 10px;
		color: #fff;
	}

	a.btn.btn-default.btn-detail:hover {
		opacity: 0.8;
	}

	.blue {
		color: #08086b;
	}

	label {
		font-weight: 500;
	}

	table.collape tbody td {
		padding: 0px !important;
	}

	.hover:hover {
		background: #ddd;
	}

	#lbl_header {
		display: initial !important;
	}

	tr.head-td th {
		padding: 5px 2px;
	}

	#lbl_blog span {
		line-height: 25px;
		font-size: 14px;
	}

	#table_row td {
		vertical-align: top;
		padding: 8px 2px;
	}

	.listBox {
		/*box-shadow: rgba(0, 0, 0, 0.1) 0px 1px 3px 0px, rgba(0, 0, 0, 0.06) 0px 1px 2px 0px;
	border-radius: 10px*/
		border-bottom: 1px solid #eee;
	}

	.ItemPayment td {
		padding-top: 20px;
	}

	label.control-td {
		font-size: 11px;
		display: block;
		margin-bottom: 0;
	}

	label.control-td small {
		font-size: 70%;
		color: #fff;
	}

	tr.balance {
		background: #fff4f4;
	}

	.groupinfo {
		font-size: 16px !important;
		font-weight: bold !important;
		color: red;
	}

	.input-box {
		display: flex;
		align-items: center;
		border-radius: 2px;
		overflow: hidden;
	}

	.input-box .prefix {
		color: #999;
		width: 40px;
	}

	.input-box input {
		flex-grow: 1;
		background: #fff;
	}

	span.custom-switch-indicator {
		line-height: 20px;
	}

	.fullwidth {
		width: 100% !important;
	}

	.removePadding .col-md-6,
	.removePadding .col-sm-6,
	.removePadding .col-xs-12 {
		padding-right: 2px;
		padding-left: 2px
	}
	ul.top_profiles{
		height:auto !important;
	}
	.fixed_height_160{height: 160px !important;overflow-y: scroll;}
	.media .date{width: 60px;}
	.usdright{float: right;padding-right: 2px;}
	.hover a{color:#000;}
	.tab-content.vertical div.tab-pane{
		min-height: 10px;
	}
</style>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script src="<?php echo $this->baseUrl();?>/admin/js/global.js"  type="text/javascript"></script>
<script type="text/javascript">
require(["dijit/form/DateTextBox","dijit/form/NumberTextBox"]);
dojo.require("dijit.form.Textarea");
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.ready(function(){

	new dijit.form.FilteringSelect({
		autoComplete: false,
		queryExpr: "*${0}*",                     
		id: "studentId",
		name: "studentId",   
		required:true,   
		readOnly:true,   
		class: 'fullside', 
		placeHolder:"<?php echo $tr->translate("SELECT_STUDENT_NAME");?>",          
		onChange: function() {  
			getStudentInfo();
		}
	}, "studentId");

	new dijit.form.FilteringSelect({
		autoComplete: false,
		queryExpr: "*${0}*",                     
		id: "toStudentId",
		name: "toStudentId",   
		readOnly:true,  
		required:true,        
		class: 'fullside', 
		placeHolder:"<?php echo $tr->translate("SELECT_STUDENT_NAME");?>",          
		onChange: function() {  
			getStudentInfo(1);
		}
	}, "toStudentId");
	
	getAllstudentBranch();
	getallstudentname();

	var branch_id = dijit.byId('branch_id');
	branch_id.on('change', function(evt) {
		getAllstudentBranch();
	});
	
	var to_branchId = dijit.byId('to_branchId');
	to_branchId.on('change', function(evt) {
		getallstudentname();
	});
	
	var totalAmount = dijit.byId('total_amount');
	totalAmount.on('keyUp', function(evt) {
		checkValidateAmount();
	});
});
var urlGet = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'getliststudenturl')); ?>';
function getAllstudentBranch(){
	dijit.byId("studentId").reset();
	branchId = dijit.byId('branch_id').get('value');
	if(branchId==''){
		 dijit.byId('branch_id').focus();
	}
	selectedId = '<?php echo $this->row['fromStuId'];?>';
	contentData = {
			'branchId':branchId,
			'joinGroup': 1,
			'activeStudent':1,
			'customerType':1,
			'onlyHasCredit':1,
			}
	getAllStudentByBranch(urlGet,contentData,selectedId);
}
function getallstudentname(){
	var toBranchId = dijit.byId("to_branchId").attr("value");
	if(toBranchId==''){  
		dijit.byId("to_branchId").focus();
		return false;
	}
	dojo.xhrPost({
		url:urlGet,
		content:{
			'branch_id':toBranchId,
			'joinGroup': 1,
			'activeStudent':1,
			//'customer_type':1
		},
		handleAs:"json",
		load: function(data) {
			student_store  = getDataStorefromJSON('id','name', data);
			dijit.byId('toStudentId').set('store',student_store);  
			<?PHP if(!empty($this->row['student_id'])) {?>
			dijit.byId('toStudentId').set('value','<?php echo $this->row['student_id'];?>');  
			<?PHP } ?>
		},
		error: function(err) {
		}
	});
}
function getStudentInfo(type=0){
	
		var url_getdata = '<?php echo $this->url(array('module' => 'registrar', 'controller' => 'register', 'action' => 'getstudentinfo')); ?>';
		var studentId = dijit.byId('studentId').get('value');
		if(type==1){
			studentId = dijit.byId('toStudentId').get('value');
		}
		if (studentId == '') { return false; }
		data_from = 1;
		
		dojo.xhrPost({
			url: url_getdata,
			content: {
				'student_id': studentId,
				'data_from': data_from,
				'customer_type': 1
			},
			handleAs: "json",
			load: function (data) {
				if (data) {
					if(type==1){
						dojo.byId("lbl_blog").innerHTML = data.studentInfo;
						dojo.byId("lblstudenttypeinfo").innerHTML = data.studenttypeinfo;
						dojo.byId("lblstudyinfo").innerHTML = data.studyinfo;
						$(".to-wallet-amt-info").html(data.studentData.walletBalance);
					}else{
						dijit.byId("walletBalance").set('value', data.studentData.walletBalance);
						$(".wallet-amt-info").html(data.studentData.walletBalance);
					}
				}
				

			},
			error: function (err) {
			}
		});
}

function checkValidateAmount(){
	var walletBalance = parseFloat(dijit.byId('walletBalance').get('value'));
	walletBalance = isNaN(walletBalance) ? 0 : walletBalance;
	
	var totalAmount = parseFloat(dijit.byId('total_amount').get('value'));
	totalAmount = isNaN(totalAmount) ? 0 : totalAmount;
	if(totalAmount>walletBalance){
		alert("<?php echo $tr->translate("TRAN_AMT_CAN_NOT_BIGGER_THAN_WALLET_AMOUNT");?>");
		dijit.byId("total_amount").set('value', walletBalance);
	}
	
	
}
</script>