<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate('EDIT_EXPENSE_ITEM')); 
$frm = $this->frm_expense;
?>
 <script>
		require(["dijit/form/DateTextBox","dijit/form/NumberTextBox"]);
 </script>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<div class="card">
	<div class="card-content collapse show">
		<form id='frm_add_tran'  dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
					loadingBlock();
					return true;
				}else {
					return false;
				}
			</script>
			<div class="card-box">
	             <div class="col-sm-12 border-botom">
			    	<div class="col-sm-8 pd-0">
			    		<h4 class="m-b-0"><i class="fa fa-edit" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT_EXPENSE_ITEM');?></h4>
	    			</div>
	    			<div class="col-sm-4 text-right">
	    			</div>
	    		</div>
	    	</div>
	    	<div class="card-box">
	        	<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="fa fa-sitemap"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("CATE_EXPENSE");?></p>
										</div> 
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("ACCOUNT_CODE");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<input type="text" name="accountCode" id="accountCode" value="<?php echo $this->rs['accountCode'];?>" dojoType="dijit.form.TextBox" class="fullside" />
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("TITLE");?> <span class="required">*</span>:
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<input type="text" name="title" id="title" required="1" value="<?php echo $this->rs['categoryTitle'];?>" dojoType="dijit.form.ValidationTextBox" class="fullside" />
									   </div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("CATEGORY");?> :
										</label>
										<div class="col-md-5 col-sm-5 col-xs-12">
											<input  id="categoryId" >
										</div>
										<div class="col-md-2 col-sm-2 col-xs-12">
											<input class="button-class button-primary" iconClass="glyphicon glyphicon-refresh" type="button" label="<?php echo $tr->translate('REFRESH');?>" dojoType="dijit.form.Button" onclick="getRefreshItems();"/>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label custom-switch float-end "> 
											<a href="javascript:void(0);" class="switchButton status"><?php echo $tr->translate("STATUS");?></a> 
											<input type="checkbox" id="status" name="status" class="custom-switch-input"  <?php if(!empty($this->rs['status'])){ echo "checked";} ?> > 
											<span class="custom-switch-indicator custom-radius switch-status"></span> 
										</label>
									</div>
									<div class="clearfix"></div>
									 <div class="card-box mt-20">
										<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
											<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-remove" value="save_close" name="save_close" label="<?php echo $tr->translate('GO_EDIT');?>" dojoType="dijit.form.Button"  />
										</div>
									 </div>
								 </div>
							 </div>
						 </div>
					 </div>
	             </div>
	          </div>
		</form>
	</div>
</div>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script type="text/javascript">
    dojo.require("dijit.form.Textarea");
    dojo.require("dijit.form.NumberTextBox");
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dojo.NodeList-manipulate");

	var category_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->parent));?> );
	dojo.ready(function(){ 
		new dijit.form.FilteringSelect({
			store: category_store,
    		name: "categoryId",
    		id: "categoryId",
    		autoComplete: false,
    		queryExpr: "*${0}*",     
    		searchAttr: "name",
    		class: 'fullside',
    		onChange: function() {
    			checkaddItems();
    	    }
    	}, "categoryId");
		getRefreshItems();
	});	

	function checkaddItems(){
		categoryId = dijit.byId('categoryId').get('value');
		if(categoryId==-1){
			window.open('<?php echo Zend_Controller_Front::getInstance()->getBaseUrl()."/registrar/expensecategory/add?addCate=1";?>','_blank');
			dijit.byId('categoryId').reset();	
		}
	}
	oldcategoryId = '<?php echo $this->rs['categoryId']; ?>';
	function getRefreshItems(){
		var url_getItems = '<?php echo $this->url(array("module"=>"registrar","controller"=>"expensecategory","action"=>"refresh-category"));?>';	
			dijit.byId('categoryId').reset();									
			loadingBlock();
			dojo.xhrPost({
				url: url_getItems,
				handleAs:"json",
				load: function(data) {
					category_store  = getDataStorefromJSON('id','name', data);
					dijit.byId('categoryId').set('store',category_store);  
					document.getElementsByClassName("overlay")[0].style.display="none";
					if(oldcategoryId!=''){
						dijit.byId('categoryId').set('value',oldcategoryId);  
					} 
				},
				error: function(err) {
					document.getElementsByClassName("overlay")[0].style.display="none";
				}
			});
	}

</script>




