<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('REPORT_PRODUCT_NEAR_OUT_STOCK')); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$frm =  $this->form_search;
	$dateFormat ="d/m/Y";
?>
<div class="layout-wrapper-report">
	<div id="mainContent" class="main-content-report">
		<div class="report-preview">
			<?php echo $this->controlReport?>
			<div id="main-viewer" class="main-viewer portrait">
				<div id="viewer" class="viewer portrait">
					<div id="divPrint" class="content">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style.css">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style-screen.css">
						<style>
							@media print {
								<?php if(!empty($this->printFormat)){ echo $this->printFormat; } ?>
							}
						</style>
						<table style="width:90%; margin: 0 auto;white-space: nowrap;width: 100%;">
							<tr>
								<td colspan="3"><?php echo $this->rsheader;?></td>
							</tr>
							<tr>
								<td width="15%" align="center">
								</td>
								<td align="center" width="70%">
									<span <?php echo TITLE_REPORT;?>><?php echo $tr->translate('REPORT_PRODUCT_NEAR_OUT_STOCK');?></span>
								</td>
								<td width="15%" align="center">
								</td>
							</tr>
							<tr>
								<td  colspan="3"  id="exportExcel" >
									<table class="content-data bd-dark-grey text-color-black text-h16px text-size-12px" cellpadding="5" border="1" >
										<thead>
											<tr class="styleheader bg-head text-bold hpx-25 bd-w1px bd-solid" align="center">
												<td scope="col"><?php echo $tr->translate('N_O');?></td>
												<td scope="col"><?php echo $tr->translate('PRODUCT_CATEGORY');?></td>
												<td scope="col"><?php echo $tr->translate('PRODUCT_CODE');?></td>
												<td scope="col"><?php echo $tr->translate('PRODUCT_NAME');?></td>
												<td scope="col"><?php echo $tr->translate('CURRENT_QTY');?></td>
												<td scope="col"><?php echo $tr->translate('NOTE');?></td>
										   </tr>
									   </thead>
									<?php 
										$branch_name =''; $i=0;
										if(!empty($this->pro_loc))foreach ($this->pro_loc AS $rs) { 
											$i++;
												if($branch_name!=$rs['brand_name']){
											?>
												<tr class="hover text-h16px text-size-12px"  align="center">
													  <td colspan="9" ><?php echo $rs['brand_name']; ?></td>
												</tr>
											<?php } $branch_name=$rs['brand_name'];?>
												<tr class="style hover" align="center">
													<td data-label="<?php echo $tr->translate("N_O");?>"> <?php echo $i; ?></td>
													<td data-label="<?php echo $tr->translate("PRODUCT_CATEGORY");?>" align="left"><?php echo $rs['category_name'];?></td>
													<td data-label="<?php echo $tr->translate("PRODUCT_CODE");?>" style="color:red;"><?php echo $rs['pro_code'];?></td>
													<td data-label="<?php echo $tr->translate("PRODUCT_NAME");?>" style="color:red;" align="left"><?php echo $rs['pro_name'];?></td>
													<td data-label="<?php echo $tr->translate("QTY");?>" style="color:red;"><?php echo number_format($rs['pro_qty'],0); ?></td>
													<td data-label="<?php echo $tr->translate("NOTE");?>"></td>
												</tr>
									<?php
										}
									?>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="3" width="100%">
									<?php echo $this->rsfooteracc;?>
								</td>
							</tr>	
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="right-panel-report" id="rightPanel">
		<div class="card-box">
			<div class="card-search-head col-sm-12 border-botom">
				<div class="col-sm-6 text-left pd-0">
					<h4 class="m-b-0">
						<?php echo $tr->translate("SEARCH");?> 
						<i class="fa fa-search "></i> 
					</h4>
				</div>
				<div class="col-sm-6 text-right pd-0">
					<button onclick="closeRightPanel()" title="<?php echo $tr->translate("CLOSED");?> " class="btn-close">
						<i class="fa-solid fa-xmark"></i>
					</button>
				</div>
			</div>
			<form  id='foundation_class' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
				<div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("adv_search");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("branch_id");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("category_id");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<input id="product" />
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("product_type");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<button class="button-class button-primary fullside" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button"showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>

<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script>
	dojo.require("dojo.data.ItemFileWriteStore");  
	
	require(["dojo/ready"], function(ready){
		ready(function(){
			getProductByCate();
			setTimeout(function() {
				setPrintOrientation('portrait');
			}, 500);
		});
		new dijit.form.FilteringSelect({
			store: item_store,
			autoComplete: false,
			queryExpr: "*${0}*",                     
			id: "product",
			name: "product",   
			required:false,        
			class: 'fullside', 
		}, "product");
	});
	
	var item_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	var url_dept = '<?php echo $this->url(array('module'=>'allreport','controller'=>'stock','action'=>'get-productbycate')); ?>';
	function getProductByCate(){
		cate_id = dijit.byId("category_id").get("value");
			dojo.xhrPost({
				url:url_dept,
				content:{
					'cate_id':cate_id,
					},
				handleAs:"json",
				load: function(data) {
					item_store  = getDataStorefromJSON('id','name', data);
					dijit.byId('product').set('store',item_store);  	
					dijit.byId('product').attr('value',"<?php echo $this->search['product']?>");
				},
				error: function(err) {
				}
			});
	}
</script>