<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('RPT_SUMMARY_STOCK')); 
	$frm =  $this->form_search;
	$db=new Allreport_Model_DbTable_DbRptSummaryStock();
	$dateFormat ="d/m/y";
?>
<style>
.hover:hover{ background:#ccc;}
</style>
<div class="layout-wrapper-report">
	<div id="mainContent" class="main-content-report">
		<div class="report-preview">
			<?php echo $this->controlReport?>
			<div id="main-viewer" class="main-viewer portrait">
				<div id="viewer" class="viewer portrait">
					<div id="divPrint" class="content">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style.css">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style-screen.css">
						<style>
							@media print {
								<?php if(!empty($this->printFormat)){ echo $this->printFormat; } ?>
							}
						</style>
						<table width="100%" style="font-family: 'Times New Roman','Khmer OS Battambang';">
							<tr>
								<td colspan="3"><?php echo $this->rsheader;?></td>
							</tr>
							<tr>
								<td width="15%" align="center">
								</td>
								<td align="center" width="70%">
									<span <?php echo TITLE_REPORT;?>><?php echo $tr->translate('RPT_SUMMARY_STOCK');?></span> 
								</td>
								<td width="15%" align="center">
								</td>
							</tr>
							<tr>
								<td colspan="3">
									<table class="content-data text-size-11px text-h16px text-color-black bd-dark-grey bd-solid bd-w1px" cellpadding="5" border="1" >
										<thead>
											<tr class="text-bold bg-head bd-t-w2px bd-t-dark-grey bd-t-solid bd-l-dark-grey hpx-25" align="center" >
												<td class="bd-dark-grey bd-solid bd-w1px" rowspan="2"><?php echo $tr->translate("NUM");?></td>
												<td class="bd-dark-grey bd-solid bd-w1px" rowspan="2"><?php echo $tr->translate("BRANCH");?></td>
												<td class="bd-dark-grey bd-solid bd-w1px" colspan="3"><?php echo $tr->translate("PRODUCT_INFO");?></td>
												<td class="bd-dark-grey bd-solid bd-w1px" rowspan="2"><?php echo $tr->translate("BEGINNING_STOCK");?>	</td>
												<td class="bd-dark-grey bd-solid bd-w1px" colspan="3"><?php echo $tr->translate("STOCK_IN");?></td>
												<td class="bd-dark-grey bd-solid bd-w1px" colspan="3"><?php echo $tr->translate("STOCK_OUT");?></td>
												<td class="bd-dark-grey bd-solid bd-w1px" rowspan="2"><?php echo $tr->translate("ADJUST_STOCK");?></td>
												<td class="bd-dark-grey bd-solid bd-w1px" rowspan="2"><?php echo $tr->translate("CURRENT_STOCK_QTY");?></td>
											</tr>
											<tr class="text-bold bg-head bd-t-w2px bd-t-dark-grey bd-t-solid bd-l-dark-grey hpx-25" align="center" >
												<td class="bd-dark-grey bd-solid bd-w1px"><?php echo $tr->translate("CATEGORY");?></td>
												<td class="bd-dark-grey bd-solid bd-w1px"><?php echo $tr->translate("PRODUCT_CODE");?></td>
												<td class="bd-dark-grey bd-solid bd-w1px"><?php echo $tr->translate("PRODUCT_NAME");?></td>
												<td class="bd-dark-grey bd-solid bd-w1px"><?php echo $tr->translate("PURCHASE_IN");?></td>
												<td class="bd-dark-grey bd-solid bd-w1px"><?php echo $tr->translate("RETURN_QTY");?></td>
												<td class="bd-dark-grey bd-solid bd-w1px"><?php echo $tr->translate("TRANSFER_IN");?></td>
												<td class="bd-dark-grey bd-solid bd-w1px"><?php echo $tr->translate("STOCK_CUT");?></td>
												<td class="bd-dark-grey bd-solid bd-w1px"><?php echo $tr->translate("REQUEST_QTY");?></td>
												<td class="bd-dark-grey bd-solid bd-w1px"><?php echo $tr->translate("TRANSFER_OUT");?></td>
											</tr>
										</thead>
										<?php 
										$oldclosingId='';
										$gender=array(1=>"Male",2=>"Female");
										$i=0;
										if(!empty($this->rows)) foreach($this->rows As $key=> $rs_row){	
											$i++;

											if($oldclosingId!=$rs_row['closingId']){ 
										?>
											<tr class="style hover bg-ligt-blues hpx-25" align="center" >
												<td colspan="14"><?php echo $tr->translate("OPENING_AND_CLOSING_STOCK_DATE");?> : 
													<?php
														$format = 'd-M-Y';
														$dateString = $rs_row['openingDate'];
														$date = new DateTime($dateString);
														$openingDate = $date->format($format); 
														echo $openingDate;  
														
														if(!empty($rs_row['closingDate'])){ 

															$closingDateString = $rs_row['closingDate'];
															$closedate = new DateTime($closingDateString);
															$closingDate = $closedate->format($format); 
															echo ' '.$tr->translate("TO").' '.$closingDate; 
														}
													?>
												</td>
											</tr>
											<?php } 
												$oldclosingId = $rs_row['closingId'];
											?>
											<tr class="style hover" align="center">
												<td data-label="<?php echo $tr->translate("NUM");?>">&nbsp;<?php echo $i; ?>&nbsp;</td>
												<td data-label="<?php echo $tr->translate("BRANCH");?>" align="left">&nbsp;<?php echo $rs_row['branchName']; ?>&nbsp;</td>
												<td data-label="<?php echo $tr->translate("CATEGORY");?>" align="left">&nbsp;<?php echo $rs_row['categoryName']; ?>&nbsp;</td>
												<td data-label="<?php echo $tr->translate("PRODUCT_CODE");?>">&nbsp;<?php echo $rs_row['proCode']; ?>&nbsp;</td>
												<td data-label="<?php echo $tr->translate("PRODUCT_NAME");?>" align="left">&nbsp;<?php echo $rs_row['productName']; ?>&nbsp;</td>
												<td data-label="<?php echo $tr->translate("BEGINNING_STOCK");?>">&nbsp;<?php if($rs_row['qtyBegining']>0){echo number_format($rs_row['qtyBegining']);}else{ echo "-";} ?>&nbsp;</td>
												<td data-label="<?php echo $tr->translate("PURCHASE_IN");?>">&nbsp;<?php if($rs_row['purchaseQty']>0){echo number_format($rs_row['purchaseQty']);}else{ echo "-";} ?>&nbsp;</td>
												<td data-label="<?php echo $tr->translate("RETURN_QTY");?>">&nbsp;<?php if($rs_row['qtyReturn']>0){echo number_format($rs_row['qtyReturn']);}else{ echo "-";} ?>&nbsp;</td>
												<td data-label="<?php echo $tr->translate("TRANSFER_IN");?>">&nbsp;<?php if(!empty($rs_row['qtyTransferIn'])){echo number_format($rs_row['qtyTransferIn']);}else{ echo "-";} ?>&nbsp;</td>
												<td data-label="<?php echo $tr->translate("SELL_OUT");?>">&nbsp;<?php if($rs_row['saleqty']>0){echo number_format($rs_row['saleqty']);}else{ echo "-";} ?>&nbsp;</td>
												<td data-label="<?php echo $tr->translate("REQUEST_QTY");?>">&nbsp;<?php if($rs_row['qtyUsage']>0){echo number_format($rs_row['qtyUsage']);}else{ echo "-";} ?>&nbsp;</td>
												<td data-label="<?php echo $tr->translate("TRANSFER_OUT");?>">&nbsp;<?php if(!empty($rs_row['qtyTransferOut'])){echo number_format(-1*$rs_row['qtyTransferOut']);}else{ echo "-";} ?>&nbsp;</td>
												<td data-label="<?php echo $tr->translate("ADJUST_STOCK");?>">&nbsp;<?php if(!empty($rs_row['qtyAdjust'])){echo number_format(-1*$rs_row['qtyAdjust']);}else{ echo "-";} ?>&nbsp;</td>
												<td data-label="<?php echo $tr->translate("CURRENT_QTY");?>" class=" <?php if($rs_row['isClosed']==1){ echo "text-bold text-color-red"; } ?> ">
													<?php 
														if($rs_row['isClosed']==1){
															echo number_format($rs_row['qtyClosing']);
														}else{
															if($rs_row['currentQty']>0){
																echo number_format($rs_row['currentQty']);
															}else{ 
																echo "-";
															} 
														}
													?>
												</td>
											</tr>
										<?php
											}
										?>
									</table>
								</td>
							</tr>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="right-panel-report" id="rightPanel">
		<div class="card-box">
			<div class="card-search-head col-sm-12 border-botom">
				<div class="col-sm-6 text-left pd-0">
					<h4 class="m-b-0">
						<?php echo $tr->translate("SEARCH");?> 
						<i class="fa fa-search "></i> 
					</h4>
				</div>
				<div class="col-sm-6 text-right pd-0">
					<button onclick="closeRightPanel()" title="<?php echo $tr->translate("CLOSED");?> " class="btn-close">
						<i class="fa-solid fa-xmark"></i>
					</button>
				</div>
			</div>
			<form action="" dojoType="dijit.form.Form" method="post">
				 <div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement('adv_search');?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement('branch_id');?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<input id="closeStockId" />
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("product_type");?>
					</div>
				</div>
				 <div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("category_id");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<input id="product" />
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("sort_by");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<button class="button-class button-primary fullside" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>		

<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script>
	dojo.require("dojo.data.ItemFileWriteStore");  
	
	require(["dojo/ready"], function(ready){
		ready(function(){

			var branch_id = dijit.byId('branch_id');
			branch_id.on('change', function (evt) {
				getAllClosingStock();
			});
			getProductByCate();
			getAllClosingStock();
			setTimeout(function() {
				setPrintOrientation('landscape');
			}, 500);
		});
		new dijit.form.FilteringSelect({
			store: item_store,
			autoComplete: false,
			queryExpr: "*${0}*",                     
			id: "product",
			name: "product",   
			required:false,        
			class: 'fullside', 
			placeHolder:'<?= $tr->translate("SELECT_PRODUCT") ?>',
		}, "product");
		new dijit.form.FilteringSelect({
			store: closingdate_store,
			autoComplete: false,
			queryExpr: "*${0}*",                     
			id: "closeStockId",
			name: "closeStockId",  
			placeHolder:'<?= $tr->translate("SELECT_REPORT_DATE") ?>', 
			required:false,        
			class: 'fullside', 
		}, "closeStockId");
	
	});
	
	var item_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	var url_dept = '<?php echo $this->url(array('module'=>'allreport','controller'=>'stock','action'=>'get-productbycate')); ?>';
	function getProductByCate(){
		cate_id = dijit.byId("category_id").get("value");
			dojo.xhrPost({
				url:url_dept,
				content:{
					'cate_id':cate_id,
					},
				handleAs:"json",
				load: function(data) {
					item_store  = getDataStorefromJSON('id','name', data);
					dijit.byId('product').set('store',item_store);  	
					dijit.byId('product').attr('value',"<?php echo $this->search['product']?>");
				},
				error: function(err) {
				}
			});
	}

	var closingdate_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	var url_closingdate = '<?php echo $this->url(array('module'=>'stock','controller'=>'stockclosing','action'=>'get-allclosingdate')); ?>';
	function getAllClosingStock(){
		branch_id = dijit.byId("branch_id").get("value");
		dojo.xhrPost({
			url:url_closingdate,
			content:{
				'branch_id':branch_id,
				},
			handleAs:"json",
			load: function(data) {
				closingdate_store  = getDataStorefromJSON('id','name', data);
				dijit.byId('closeStockId').set('store',closingdate_store);  	
				dijit.byId('closeStockId').attr('value',"<?php echo $this->search['closeStockId']?>");
			},
			error: function(err) {
			}
		});
	}
</script>