<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('RPT_PURCHASE_ALL')); 
	$frm = $this->form_search;
	$classHideHeight=classHideHeight;
	$dateFormat ="d/m/Y";
?>	
<meta charset="utf-8">
<style>
.hover:hover{ background:#ccc;}
table.content-data tr.style-head,
table.tb-footer tr.style-head {
   font-weight: bold !important;
}
</style>
<div class="layout-wrapper-report">
	<div id="mainContent" class="main-content-report">
		<div class="report-preview">
			<?php echo $this->controlReport?>
			<div id="main-viewer" class="main-viewer portrait">
				<div id="viewer" class="viewer portrait">
					<div id="divPrint" class="content">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style.css">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style-screen.css">
						<style>
							@media print {
								<?php if(!empty($this->printFormat)){ echo $this->printFormat; } ?>
							}
							.p-right10{padding-right: 10px;}
							td.underLine{text-decoration: underline;}
						</style>
						<table style="width:90%; margin: 0 auto;white-space: nowrap;width: 100%;">
							<tr>
								<td colspan="3"><?php echo $this->rsheader;?></td>
							</tr>
							<tr>
								<td width="15%" align="center"></td>
								<td align="center" width="70%">
									<span <?php echo TITLE_REPORT;?>><?php echo $tr->translate('RPT_PURCHASE_ALL');?></span><br>
									<span style="font-size: 12px; "><?php if(!empty($this->search['start_date'])){?><?php echo date($dateFormat,strtotime($this->search['start_date']));?> &nbsp;<?php echo $tr->translate('TO');?>&nbsp; <?php echo date($dateFormat,strtotime($this->search['end_date']));}?></span>
								</td>
								<td width="15%" align="center"></td>
							</tr>
							<tr>
								<td colspan="3" id="exportExcel">
									<table class="content-data bd-dark-grey text-color-black text-h16px text-size-12px" cellpadding="5">
										<thead>
											<tr class="style">
											<td scope="col"><span><?php echo $tr->translate("NUM");?></span></td>
											<td scope="col"><span><?php echo $tr->translate('BRANCH');?></span></td>
											<td scope="col"><span><?php echo $tr->translate('INVOICE_NO');?></span></td>
											<td scope="col"><span><?php echo $tr->translate('PURCHASE_NO');?></span></td>
											<td scope="col"><span><?php echo $tr->translate('PURCHASE_DATE');?></span></td>
											<td scope="col"><span><?php echo $tr->translate('SUPPLIER_NAME');?></span></td>
											<td scope="col"><span><?php echo $tr->translate('PRODUCT_NAME');?></span></td>
											<td scope="col"><span><?php echo $tr->translate('QTY');?></span></td>
											<td scope="col"><span><?php echo $tr->translate('COST');?></span></td>
											<td scope="col"><span><?php echo $tr->translate('TOTAL');?></span></td>
										   </tr>
									   </thead>
									<?php 
										$grandTotal=0;
										$totalbalance = 0;
										$oldPoId = 0;
										$i = 0;
									if (!empty($this->pur_all)) {
										foreach ($this->pur_all as $key=> $rs){ 
											if($oldPoId!=$rs["id"]){
												$i++;
											if ($key > 0) {
											?>
												<tr class="style hover bd-t-w1px bd-t-dashed bd-dark-grey">
													<td colspan="9"></td>
													<td class="underLine text-right hpx-25" valign="top"><strong><?php echo number_format($totalbalance, 2); ?></strong></td>
												</tr> 
											<?php
												$totalbalance = 0;
											} ?>
										<?php }
										$link = "addTab('" . $tr->translate('PURCHASE_NO')." ".$rs['purchaseNo'] . "', '" . $this->baseUrl() . "/allreport/stock/rpt-purchase-supplier/id/" . $rs['id'] . "?inFrame=true')";
										?>
										 <tr class="style hover">
												<td><?php echo $oldPoId!=$rs["id"]?$i:""; ?></td>
												<td><a class="text-color-black" href="javascript:void(0);" onClick="<?php echo $link; ?>"><?php echo $oldPoId!=$rs["id"]?$rs['brand_name']:""; ?></a></td>
												<td><a class="text-color-black" href="javascript:void(0);" onClick="<?php echo $link; ?>"><?php echo $oldPoId!=$rs["id"]?$rs['invoice_no']:""; ?></a></td>
												<td><a class="text-color-black" href="javascript:void(0);" onClick="<?php echo $link; ?>"><strong><?php echo $oldPoId!=$rs["id"]?$rs['purchaseNo']:""; ?></strong></a></td>
												<td><a class="text-color-black" href="javascript:void(0);" onClick="<?php echo $link; ?>"><?php echo $oldPoId!=$rs["id"]?date($dateFormat, strtotime($rs['date'])):""; ?></a></td>
												<td><a class="text-color-black" href="javascript:void(0);" onClick="<?php echo $link; ?>"><?php echo $oldPoId!=$rs["id"]?$rs['sup_name']:""; ?></a></td>
												<td><?php echo $rs['productName']; ?></td>
												<td><?php echo number_format($rs['qty'], 0); ?></td>
												<td><?php echo $rs['cost']; ?></td>
												<td class="text-right"><?php echo number_format($rs['amount'],2); ?></td>
											</tr>
										<?php
											$totalbalance += $rs['amount'];
											$grandTotal += $rs['amount'];
											$oldPoId = $rs["id"];
											}
										}?>	
										 <?php if(!empty($this->pur_all)){?>
											<tr class="style hover">
												<td colspan="9"></td>
												<td class="underLine text-right hpx-25" valign="top"><strong><?php echo number_format($totalbalance,2);?></strong></td>
											</tr> 
											<tr class="style hover bd-t-w1px bd-t-dashed bd-dark-grey">
												<td colspan="9" align="right" class="font-14 p-right10">សរុបរួម/Grand Total</td>
												<td><strong class="double-underLine font-14"><?php echo number_format($grandTotal,2);?></strong></td>
											</tr> 
										 <?php }?>
									</table>	
								</td>
							</tr>
						</table>
					</div>
				</div>					
			</div>					
		</div>					
	</div>		
	<div class="right-panel-report" id="rightPanel">
		<div class="card-box">
			<div class="card-search-head col-sm-12 border-botom">
				<div class="col-sm-6 text-left pd-0">
					<h4 class="m-b-0">
						<?php echo $tr->translate("SEARCH");?> 
						<i class="fa fa-search "></i> 
					</h4>
				</div>
				<div class="col-sm-6 text-right pd-0">
					<button onclick="closeRightPanel()" title="<?php echo $tr->translate("CLOSED");?> " class="btn-close">
						<i class="fa-solid fa-xmark"></i>
					</button>
				</div>
			</div>	
			<form action="" dojoType="dijit.form.Form" method="post">
				<div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("title");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("location");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("supplier_id");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("category_id");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<input id="product" />
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("product_type");?>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm->getElement("start_date");?>
					</div>
					<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm->getElement("end_date");?>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("status_search");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<button class="button-class button-primary fullside" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button"
								showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
				</div>
			</form>
		</div>	
	</div>					
</div>	
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script>
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dojo.NodeList-manipulate");
	
	require(["dojo/ready"], function(ready){
		ready(function(){
			getProductByCate();
			setTimeout(function() {
				setPrintOrientation('landscape');
			}, 500);
		});
		new dijit.form.FilteringSelect({
			store: item_store,
			autoComplete: false,
			queryExpr: "*${0}*",                     
			id: "product",
			name: "product",   
			required:false,        
			class: 'fullside', 
		}, "product");
	});
	
	var item_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	var url_dept = '<?php echo $this->url(array('module'=>'allreport','controller'=>'stock','action'=>'get-productbycate')); ?>';
	function getProductByCate(){
		cate_id = dijit.byId("category_id").get("value");
			dojo.xhrPost({
				url:url_dept,
				content:{
					'cate_id':cate_id,
					},
				handleAs:"json",
				load: function(data) {
					item_store  = getDataStorefromJSON('id','name', data);
					dijit.byId('product').set('store',item_store);  	
					dijit.byId('product').attr('value',"<?php echo $this->search['product']?>");
				},
				error: function(err) {
				}
			});
	}
</script>