<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('RPT_ADJUST_STOCK'));
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$frm =  $this->form_search;
	$rows=$this->rows;
	$classHideHeight=classHideHeight;
	$dateFormat ="d/m/y";
?>
<div class="layout-wrapper-report">
	<div id="mainContent" class="main-content-report">
		<div class="report-preview">
			<?php echo $this->controlReport?>
			<div id="main-viewer" class="main-viewer portrait">
				<div id="viewer" class="viewer portrait">
					<div id="divPrint" class="content">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style.css">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style-screen.css">
						<style>
							.hide{visibility: hidden;}
							@media print {
								<?php if(!empty($this->printFormat)){ echo $this->printFormat; } ?>
								.hide{visibility: visible; height: <?php echo $classHideHeight;?>;}
									
							}
						</style>
						<table width="100%" style="margin: 0 auto; width: 100%;font-family:'Times New Roman','Khmer OS Battambang' ">
							<tr>
								<td colspan="3"><?php echo $this->rsheader;?></td>
							</tr>
							<tr>
								<td></td>
							</tr>
							<tr>
								<td width="15%" align="center">
								</td>
								<td align="center" width="70%">
									<span <?php echo TITLE_REPORT;?>><?php echo $tr->translate('RPT_ADJUST_STOCK');?></span><br>
									<span style="font-size: 12px; "><?php if(!empty($this->search['start_date'])){?><?php echo date($dateFormat,strtotime($this->search['start_date']));?> <?php echo $tr->translate('TO');?> <?php echo date($dateFormat,strtotime($this->search['end_date']));}?></span>
								</td>
								<td width="15%" align="center">
								</td>
							</tr>
							<tr>
								<td></td>
							</tr>
							<tr>
								<td colspan="3" id="exportExcel">
									<table cellpadding="4" class="content-data text-size-11px text-h16px text-color-black bd-dark-grey bd-solid bd-w1px"  border="1" >
										<thead>
											<tr class="styleheader bg-head text-bold hpx-25 bd-w1px bd-solid " align="center">
												<td scope="col" rowspan="2"><?php echo $tr->translate("NUM");?></td>
												<td scope="col" rowspan="2"><?php echo $tr->translate("BRANCH");?></td>
												<td scope="col" colspan="2"><?php echo $tr->translate("PRODUCT_INFO");?></td>
												<td scope="col" colspan="7"><?php echo $tr->translate("ADJUST_INFO");?></td>
												<td scope="col" rowspan="2"><?php echo $tr->translate("USER");?></td>
												<td scope="col" rowspan="2"><?php echo $tr->translate("STATUS");?></td>
											</tr>
											<tr class="styleheader bg-head text-bold hpx-25 bd-w1px bd-solid " align="center">
												<td scope="col"><?php echo $tr->translate("CATEGORY");?></td>
												<td scope="col"><?php echo $tr->translate("PRODUCT_NAME");?></td>
												
												<td scope="col"><?php echo $tr->translate("ADJUST_NO");?></td>
												<td scope="col"><?php echo $tr->translate("TITLE");?></td>
												<td scope="col"><?php echo $tr->translate("QTY_BEFOR");?></td>
												<td scope="col"><?php echo $tr->translate("QUANTITY_NEW");?></td>
												<td scope="col"><?php echo $tr->translate("STOCK_SPACING");?></td>
												<td scope="col"><?php echo $tr->translate("NOTE");?></td>
												<td scope="col"><?php echo $tr->translate("ADJUST_DATE");?></td>
											</tr>
										</thead>
										<?php 
										$gender=array(1=>"Male",2=>"Female");
										if(!empty($rows))foreach($rows As $key=> $rs_row){
										?>
										<tr class="style hover"  class="hover" >
											<td data-label="<?php echo $tr->translate("NUM");?>"><?php echo $key+1; ?></td>
											<td data-label="<?php echo $tr->translate("BRANCH");?>"><?php echo $rs_row['branch_name']; ?></td>
											<td data-label="<?php echo $tr->translate("CATEGORY");?>"><?php echo $rs_row['category']; ?></td>
											<td data-label="<?php echo $tr->translate("PRODUCT_NAME");?>"><?php echo $rs_row['pro_name']; ?></td>
											
											<td data-label="<?php echo $tr->translate("ADJUST_NO");?>" align="center"><strong><?php echo $rs_row['adjust_no']; ?></strong></td>
											<td data-label="<?php echo $tr->translate("TITLE");?>" ><?php echo $rs_row['request_name']; ?></td>
											
											<td data-label="<?php echo $tr->translate("QTY_BEFOR");?>" align="center"><?php if($rs_row['qty_befor']!=0) echo $rs_row['qty_befor']; ?></td>
											<td data-label="<?php echo $tr->translate("QUANTITY_NEW");?>" align="center"><?php if($rs_row['qty_after']!=0) echo $rs_row['qty_after']; ?></td>
											<td data-label="<?php echo $tr->translate("STOCK_SPACING");?>" align="center"><?php if($rs_row['difference']!=0) echo $rs_row['difference']; ?></td>
											<td data-label="<?php echo $tr->translate("NOTE");?>" ><?php echo $rs_row['note']; ?></td>
											<td data-label="<?php echo $tr->translate("ADJUST_DATE");?>" align="center"><?php echo date($dateFormat,strtotime($rs_row['request_date'])); ?></td>
											<td data-label="<?php echo $tr->translate("USER");?>" align="center"><?php echo $rs_row['user_name']; ?></td>
											<td data-label="<?php echo $tr->translate("STATUS");?>" align="center"><?php if ($rs_row['status']==1){ echo $tr->translate("ACTIVE"); }else{ echo $tr->translate("DEACTIVE");} ?></td>
										</tr>
										<?php
										}
										?>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="3">
									<?php echo $this->rsfooteracc;?>
								</td>
							</tr>
						</table>
					</div>	
				</div>	
			</div>	
		</div>	
	</div>
	<div class="right-panel-report" id="rightPanel">
		<div class="card-box">
			<div class="card-search-head col-sm-12 border-botom">
				<div class="col-sm-6 text-left pd-0">
					<h4 class="m-b-0">
						<?php echo $tr->translate("SEARCH");?> 
						<i class="fa fa-search "></i> 
					</h4>
				</div>
				<div class="col-sm-6 text-right pd-0">
					<button onclick="closeRightPanel()" title="<?php echo $tr->translate("CLOSED");?> " class="btn-close">
						<i class="fa-solid fa-xmark"></i>
					</button>
				</div>
			</div>
			<form action="" dojoType="dijit.form.Form" method="post">
				<div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement('title');?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement('branch_id');?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("category_id");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<input id="product" />
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("product_type");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement('user');?>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm->getElement('start_date');?>
					</div>
					<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm->getElement('end_date');?>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<button class="button-class button-primary fullside" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
				</div>
			</form>
		</div>	
	</div>	
</div>	

<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script>
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dojo.NodeList-manipulate");
	
	require(["dojo/ready"], function(ready){
		ready(function(){
			getProductByCate();
			setTimeout(function() {
				setPrintOrientation('landscape');
			}, 500);
		});
		new dijit.form.FilteringSelect({
			store: item_store,
			autoComplete: false,
			queryExpr: "*${0}*",                     
			id: "product",
			name: "product",   
			required:false,        
			class: 'fullside', 
		}, "product");
	});
	
	var item_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	var url_dept = '<?php echo $this->url(array('module'=>'allreport','controller'=>'stock','action'=>'get-productbycate')); ?>';
	function getProductByCate(){
		cate_id = dijit.byId("category_id").get("value");
		//if(cate_id>0){
			dojo.xhrPost({
				url:url_dept,
				content:{
					'cate_id':cate_id,
					},
				handleAs:"json",
				load: function(data) {
					item_store  = getDataStorefromJSON('id','name', data);
					dijit.byId('product').set('store',item_store);  	
					dijit.byId('product').attr('value',"<?php echo $this->search['product']?>");
				},
				error: function(err) {
				}
			});
		//}
	}
</script>