<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('TRANSFER'));
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$frm =  $this->form_search;
	$formList = new Application_Form_Frmtable();
	$classHideHeight=classHideHeight;
	$urlReceipt = $this->baseUrl()."/allreport/stock/rpt-transferdetail/id/";
	$rows =$this->all_transfer;
	$dateFormat ="d/m/Y";
?>
<style>
.hover:hover{ background:#ccc;}
table.content-data tr.style-head,
table.tb-footer tr.style-head {
   font-weight: bold !important;
}
</style>
<div class="layout-wrapper-report">
	<div id="mainContent" class="main-content-report">
		<div class="report-preview">
			<?php echo $this->controlReport?>
			<div id="main-viewer" class="main-viewer portrait">
				<div id="viewer" class="viewer portrait">
					<div id="divPrint" class="content">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style.css">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style-screen.css">
						<style>
							@media print {
								<?php if(!empty($this->printFormat)){ echo $this->printFormat; } ?>
							}
							thead td span {
								text-align: left;
								text-decoration: underline;
								font-weight: 800;
							}
							td.underLine{text-decoration: underline;}
							.p-right10{padding-right: 10px;}
						</style>
						<table  style="background:#fff; margin: 0 auto; ;white-space: nowrap;width: 100%">
							<tr>
								<td colspan="3"><?php echo $this->rsheader;?></td>
							</tr>
							<tr>
								<td>&nbsp;</td>
							</tr>
							<tr >
								<td width="15%" align="center">
								</td>
								<td width="70%" align="center">
									<span <?php echo TITLE_REPORT;?>><?php echo $tr->translate('TRANSFER')?></span><br />					
									<span style="color:#000; font-size: 12px;"><?php if(!empty($this->search['start_date'])){?><?php echo date($dateFormat,strtotime($this->search["start_date"]))?> &nbsp;<?php echo $tr->translate('TO');?> &nbsp;<?php echo date($dateFormat,strtotime($this->search["end_date"]));}?></span> 
								</td>
								<td width="15%" align="center">
								</td>
							</tr>
							<tr>
								<td>&nbsp;</td>
							</tr>
							<tr >
								<td colspan="3" id="exportExcel" >
									<table class="content-data bd-dark-grey text-color-black text-h16px text-size-12px" >
										<thead>
											<tr class="style" >
												<td scope="col"><span><?php echo $tr->translate("N_O");?></span></td>
												<td scope="col"><span><?php echo $tr->translate("TRANSFER_NUMBER");?></span></td>
												<td scope="col"><span><?php echo $tr->translate("TRANSFER_DATE");?></span></td>
												<td scope="col"><span><?php echo $tr->translate("FROM_LOCATION");?></span></td>
												<td scope="col"><span><?php echo $tr->translate("TO_LOCATION");?></span></td>
												<td scope="col"><span><?php echo $tr->translate("STATUS");?></span></td>
												<td scope="col"><span><?php echo $tr->translate("NOTE");?></span></td>
												<td scope="col"><span><?php echo $tr->translate('PRODUCT_CODE');?></span></td>
												<td scope="col"><span><?php echo $tr->translate('PRODUCT_NAME');?></span></td>
												<td scope="col"><span><?php echo $tr->translate('QTY_TRANSFER');?></span></td>
											</tr>
										</thead>
										<?php 

										$i = 0;
										$oldTransferId = null;
										$totalTransfer = 0;
										$gtotalTransfer = 0;

										if (!empty($rows)) {
											foreach ($rows as $key => $rs_row) {  
												if ($oldTransferId !== $rs_row['id']) {
													// If new request ID, show a header row for it
													if ($oldTransferId !== null) {
														?>
														<tr class="bg-light-blues text-bold" >
															<td colspan='8'></td><td  align='center'></td>
															<td class="text-right"><?php echo number_format($totalTransfer, 2)  ?></td>
														</tr>
													<?php 	}
													
													$i++;
													$totalTransfer = 0; // Reset for new group
													$totalRecieved = 0; // Reset for new group
													$totalReturn = 0; // Reset for new group
													$link = "addTab('" . $tr->translate('TRANSFER_NUMBER')." ".$rs_row['transfer_no']. "', '" . $this->baseUrl() . "/allreport/stock/rpt-transferdetail/id/" . $rs_row['id'] . "?inFrame=true')";
													
													?>
													
											<?php } ?>
												<tr class="style hover">
													<td><?php echo $oldTransferId!=$rs_row["id"]?$i:""; ?></td>
													<td><a class="text-color-black" href="javascript:void(0);" onClick="<?php echo $link; ?>"><strong><?php echo $oldTransferId!=$rs_row["id"]?$rs_row['transfer_no']:""; ?></strong></a></td>
													<td>
														<a class="text-color-black" href="javascript:void(0);" onClick="<?php echo $link; ?>"><?php 
															echo ($oldTransferId != $rs_row["id"]) 
																? (!empty($rs_row['transfer_date']) ? date($dateFormat, strtotime($rs_row['transfer_date'])) : "") 
																: ""; 
															?>
														</a>
													</td>
													<td><a class="text-color-black" href="javascript:void(0);" onClick="<?php echo $link; ?>"><?php echo $oldTransferId!=$rs_row["id"]?$rs_row['from_location']:""; ?></a></td>
													<td><a class="text-color-black" href="javascript:void(0);" onClick="<?php echo $link; ?>"><?php echo $oldTransferId!=$rs_row["id"]?$rs_row['to_location']:""; ?></a></td>
													<td><a class="text-color-black" href="javascript:void(0);" onClick="<?php echo $link; ?>"><?php echo $oldTransferId!=$rs_row["id"]?$rs_row['transferStatus']:""; ?></a></td>
													<td><a class="text-color-black" href="javascript:void(0);" onClick="<?php echo $link; ?>"><?php echo $oldTransferId!=$rs_row["id"]?$rs_row['note']:""; ?></a></td>
													
													
													<td><?php echo $rs_row['code']; ?></td>
													<td><?php echo $rs_row['title']; ?></td>
													<td class="text-right"><?php echo !empty($rs_row['qty'])? number_format($rs_row['qty'],2): '0.00'; ?></td>
												</tr>
												<?php
											
												$totalTransfer += $rs_row['qty'];
												$gtotalTransfer += $rs_row['qty'];
												
												$oldTransferId = $rs_row['id'];
											}
											?>
											<tr class="bg-light-blues text-bold" >
												<td colspan='8'></td><td  align='center'></td>
												<td class="text-right"><?php echo number_format($totalTransfer, 2)  ?></td>
											</tr>
											<tr class="bg-head text-bold" >
												<td colspan='7'></td><td colspan='2' align='center'><?php echo $tr->translate('TOTAL_AMOUNT');?></td>
												<td class="text-right"><?php echo number_format($gtotalTransfer, 2)  ?></td>
											</tr>
									<?php } ?>
									</table>
								</td>	
							</tr>
							<tr>
								<td colspan="3">
									<?php echo $this->rsfooteracc;?>
								</td>
							</tr>
						</table>
					</div>	
				</div>	
			</div>	
		</div>	
	</div>
	<div class="right-panel-report" id="rightPanel">
		<div class="card-box">
			<div class="card-search-head col-sm-12 border-botom">
				<div class="col-sm-6 text-left pd-0">
					<h4 class="m-b-0">
						<?php echo $tr->translate("SEARCH");?> 
						<i class="fa fa-search "></i> 
					</h4>
				</div>
				<div class="col-sm-6 text-right pd-0">
					<button onclick="closeRightPanel()" title="<?php echo $tr->translate("CLOSED");?> " class="btn-close">
						<i class="fa-solid fa-xmark"></i>
					</button>
				</div>
			</div>
			<form action="" dojoType="dijit.form.Form" method="post">
				<div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("adv_search");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("branch_id");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("transfer_status");?>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm->getElement("start_date");?>
					</div>
					<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm->getElement("end_date");?>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<button class="button-class button-primary fullside" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>	
<div style="min-height:26cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">	
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('TRANSFER');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	
	<style>
		#footer{display: none;}
	</style>	
	<div style="min-height:22cm; margin:0 auto;">
		<div id="divPrint">
			
		</div>	
	</div>
</div>
<script>
	dojo.require('dijit.form.Button');
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.TextBox");
	
	document.addEventListener("DOMContentLoaded", function(e) {
	  setTimeout(function() {
			setPrintOrientation('landscape');
		}, 500);
	});	

	var row=0;
	var url="";
	$(function(){
		$.contextMenu({
			selector: '.context-menu-one', 
			callback: function(key, options) {
				var m = "clicked: " + key;
				if(key=="receipt"){
					url='<?php echo $urlReceipt;?>';
				}
				gotoAction();
			},
			items: {
				"receipt": {name: "<?php echo $tr->translate("TRANSFER_STOCK_VOUCHER");?>", icon: "fa-print", accesskey: "c"},
			}
		});
	});
	function setrowdata(index){
		row = index;
	}
	var recordid ='';
	function gotoAction(){
		window.open(url+row, '_blank');
	}

</script>