<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('SUPPLIER_BALANCE_REPORT')); 
	$frm =  $this->form_search;
	$dateFormat ="d/m/Y";
?>	
<meta charset="utf-8">
<style>
.hover:hover{ background:#ccc;}
</style>
<div class="layout-wrapper-report">
	<div id="mainContent" class="main-content-report">
		<div class="report-preview">
			<?php echo $this->controlReport?>
			<div id="main-viewer" class="main-viewer portrait">
				<div id="viewer" class="viewer portrait">
					<div id="divPrint" class="content">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style.css">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style-screen.css">
						<style>
							@media print {
								<?php if(!empty($this->printFormat)){ echo $this->printFormat; } ?>
							}
							tr.sumarry-data td{text-align: center; border: 1px solid #fff;border-top: 1px solid #000;}
							tr.sumarry-data td strong{
								text-decoration: underline;
							}
						</style>
						<table style="width:90%; margin: 0 auto;white-space: nowrap;width: 100%;">
							<tr>
								<td colspan="3"><?php echo $this->rsheader;?></td>
							</tr>
							<tr>
								<td width="15%" align="center">
								</td>
								<td align="center" width="70%">
									<span <?php echo TITLE_REPORT;?>><?php echo $tr->translate('SUPPLIER_BALANCE_REPORT');?></span><br>
									<span style="font-size: 12px; "><?php if(!empty($this->search['start_date'])){?><?php echo date($dateFormat,strtotime($this->search['start_date']));?> &nbsp;<?php echo $tr->translate('TO');?>&nbsp; <?php echo date($dateFormat,strtotime($this->search['end_date']));}?></span>
								</td>
								<td width="15%" align="center"></td>
							</tr>
							<tr>
								<td colspan="3" id="exportExcel">
									<table class="content-data bd-dark-grey text-color-black text-h16px text-size-12px" cellpadding="5" border="1" >
									<thead>
										<tr class="styleheader bg-head text-bold hpx-25 " align="center">
											<th><?= $tr->translate('N_O') ?></th>
											<th><?= $tr->translate('BRANCH') ?></th>
											<th><?= $tr->translate('PURCHASE_NO') ?></th>
											<th><?= $tr->translate('INVOICE_NO') ?></th>
											<th><?= $tr->translate('PURCHASE_DATE') ?></th>
											<th><?= $tr->translate('SUPPLIER_NAME') ?></th>
											<th><?= $tr->translate('TOTAL_AMOUNT') ?></th>
											<th><?= $tr->translate('PAID_AMOUNT') ?></th>
											<th><?= $tr->translate('REMAIN_BALANCE') ?></th>
										</tr>
									</thead>
									<?php
										$i=0;
										$totalpaid=0;
										$totalremainbalance=0;
										$totalbalance=0; 
										if(!empty($this->pur_code))foreach ($this->pur_code AS $rs) { 
											$i++;
											$totalpaid +=$rs['paid_amount'];
											$balance = $rs['amount_due']-$rs['paid_amount'];
											$totalbalance+=$rs['amount_due'];
											$totalremainbalance+=$balance;
											$link = "addTab('" . $tr->translate('PURCHASE_NO')." ".$rs['invoice_no'] . "', '" . $this->baseUrl() . "/allreport/stock/rpt-purchase-supplier/id/" . $rs['id'] . "?inFrame=true')";
									  ?>
											<tr class="hover" align="center">
													<td><?= $i; ?></td>
													<td align="left"><?= $rs['branch_name']; ?></td>
													<td>
														<a title="View Purchase Order" class="text-color-black" href="javascript:void(0);" onClick="<?php echo $link; ?>">
															<?= $rs['purchaseNo']; ?>
														</a>
													</td>
													<td align="left">
														<a title="View Purchase Order" class="text-color-black" href="javascript:void(0);" onClick="<?php echo $link; ?>">
															<?= $rs['invoice_no']; ?>
														</a>
													</td>
													<td>
														<a title="View Purchase Order" class="text-color-black" href="javascript:void(0);" onClick="<?php echo $link; ?>">
														<?= date($dateFormat, strtotime($rs['date'])); ?>
														</a>
													</td>
													<td align="left"><?= $rs['sup_name']; ?></td>
													<td align="right"><?= number_format($rs['amount_due'], 2); ?></td>
													<td align="right"><?= number_format($rs['paid_amount'], 2); ?></td>
													<td align="right"><?= number_format($balance, 2); ?></td>
											</tr>
										<?php 
											}
										?>	 
										<tr class="sumarry-data">
											<td colspan="5" align="right"> សរុប/Total</td>
											<td><strong><?= number_format($totalbalance, 2) ?></strong></td>
											<td><strong><?= number_format($totalpaid, 2) ?></strong></td>
											<td><strong><?= number_format($totalremainbalance, 2) ?></strong></td>
											<td colspan="1"></td>
										</tr>
									</table>	
								</td>
							</tr>
						</table>
					</div>					
				</div>					
			</div>					
		</div>					
	</div>	
	<div class="right-panel-report" id="rightPanel">
		<div class="card-box">
			<div class="card-search-head col-sm-12 border-botom">
				<div class="col-sm-6 text-left pd-0">
					<h4 class="m-b-0">
						<?php echo $tr->translate("SEARCH");?> 
						<i class="fa fa-search "></i> 
					</h4>
				</div>
				<div class="col-sm-6 text-right pd-0">
					<button onclick="closeRightPanel()" title="<?php echo $tr->translate("CLOSED");?> " class="btn-close">
						<i class="fa-solid fa-xmark"></i>
					</button>
				</div>
			</div>
			<form action="" dojoType="dijit.form.Form" method="post">
				<div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("adv_search");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("branch_id");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("supplier_id");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("paymentstatus");?>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm->getElement("start_date");?>
					</div>
					<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm->getElement("end_date");?>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<button class="button-class button-primary fullside" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button"
								showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
				</div>
			</form>			
		</div>		
	</div>					
</div>	
<script>
document.addEventListener("DOMContentLoaded", function(e) {
  setTimeout(function() {
		setPrintOrientation('portrait');
	}, 500);
});	
</script>	





