<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("RPT_BYPRODUCT_SOLD")); 
	$frm =  $this->form_search;
	$classHideHeight=classHideHeight;
	$dateFormat ="d/m/Y";
?>
<style>
.hover:hover{ background:#ccc;}
table.content-data tr.style-head,

</style>
<div class="layout-wrapper-report">
	<div id="mainContent" class="main-content-report">
		<div class="report-preview">
			<?php echo $this->controlReport?>
			<div id="main-viewer" class="main-viewer portrait">
				<div id="viewer" class="viewer portrait">
					<div id="divPrint" class="content">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style.css">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style-screen.css">
						<style>
							@media print {
								<?php if(!empty($this->printFormat)){ echo $this->printFormat; } ?>
							}
							.small{white-space:normal;}
							
							td.hideborder{border-left: 1px solid #fff;border-bottom: 1px solid #fff;}
						</style>
						<table style=" margin: 0 auto;white-space: nowrap;width: 100%;font-family:'Times New Roman','Khmer OS Battambang'">
							<tr>
								<td colspan="3" id="exportExcel">
									<table width="100%">
									<tr>
										<td colspan="3"><?php echo $this->rsheader;?></td>
									</tr>
									<tr>
										<td width="15%" align="right"></td>
										<td align="center"  width="70%">
											<span <?php echo TITLE_REPORT;?>><?php echo $tr->translate("RPT_BYPRODUCT_SOLD"); ?></span><br />
											<span style="font-size: 12px;"><?php if(!empty($this->search['start_date'])){?><?php echo date($dateFormat,strtotime($this->search["start_date"]))?> <?php echo $tr->translate("TO"); ?> <?php echo date($dateFormat,strtotime($this->search["end_date"]));}?></span>
										</td>
										<td width="15%" align="right"></td>
									</tr>
									</table>
									<table class="content-data bd-dark-grey text-color-black text-h14px text-size-11px" cellpadding="0" border="1" >
										<thead>
										<tr class="styleheader bg-head text-bold hpx-25 " align="center">
												<td scope="col" rowspan="2"><?php echo $tr->translate("NUM");?></td>
												<td scope="col" rowspan="2"><?php echo $tr->translate("BRANCH");?></td>
												<td scope="col" colspan="3"><?php echo $tr->translate("PRODUCT_INFO");?></td>
												<td scope="col" colspan="5"><?php echo $tr->translate("SALE_INFO");?></td>
											</tr>
										<tr class="styleheader bg-head text-bold hpx-25 " align="center">
											<td scope="col"><?php echo $tr->translate("CATEGORY");?></td>
											<td scope="col"><?php echo $tr->translate("PRODUCT_CODE");?></td>
											<td scope="col"><?php echo $tr->translate("PRODUCT_NAME");?></td>
											<td scope="col"><?php echo $tr->translate("QTY");?></td>
											<td scope="col"><?php echo $tr->translate("TOTAL_SALE");?></td>
											<td scope="col"><?php echo $tr->translate("TOTAL_COST");?></td>
											<td scope="col"><?php echo $tr->translate("TOTAL_PROFIT");?></td>
										</tr>
										</thead>
									<?php 
									$total_qty=0;
									$grand_totalsale=0;
									$grand_totalcost=0;
									 if (!empty($this->rspro)) foreach ($this->rspro as $key=> $rs){?>
										<tr class="style hover" align="center">
											<td data-label="<?php echo $tr->translate("NUM");?>"><?php echo $key+1; ?></td>
											<td data-label="<?php echo $tr->translate("BRANCH");?>" align="left"><?php echo $rs['branch_name'];?></td>
											<td  data-label="<?php echo $tr->translate("CATEGORY");?>" align="left">
												<?php echo $rs['category'];?>
											</td>
											<td align="left" data-label="<?php echo $tr->translate("PRODUCT_CODE");?>">
												<?php echo $rs['code'];?>
											</td>
											<td data-label="<?php echo $tr->translate("PRODUCT_NAME");?>" align="left" >
												<span class="wrapcontent wpx-150"><?php echo $rs['items_name'];?></span>
											</td>
											<td data-label="<?php echo $tr->translate("QTY");?>"><?php echo number_format($rs['qty'],2);?></td>
											<td data-label="<?php echo $tr->translate("TOTAL_SALE");?>"><?php echo number_format($rs['subtotalsale'],2);?></td>
											<td data-label="<?php echo $tr->translate("TOTAL_COST");?>"> <?php echo number_format($rs['subtotalcost'],2);?></td>
											<td data-label="<?php echo $tr->translate("TOTAL_PROFIT");?>"> <?php echo number_format($rs['subtotalsale']-$rs['subtotalcost'],2);?></td>
										</tr>
									<?php
									$total_qty = $total_qty + $rs['qty'];
									$grand_totalsale = $grand_totalsale + $rs['subtotalsale'];
									$grand_totalcost = $grand_totalcost + $rs['subtotalcost'];
									}?>
										<tr style="font-size:12px; height: 20px;border: 1px solid #000;" align="center" class="hover" >
											<td colspan="5" align="right" class="hideborder"><?php echo $tr->translate("TOTLE_AMOUNT");?></td>
											<td><strong><?php echo number_format($total_qty,2);?></strong></td>
											<td><strong><?php echo "$ ".number_format($grand_totalsale,2);?></strong></td>
											<td><strong><?php echo "$ ".number_format($grand_totalcost,2);?></strong></td>
											<td align="center" style="border: 1px solid #000;"><strong><?php echo "$ ".number_format($grand_totalsale-$grand_totalcost,2);?></strong></td>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="3">
									<?php echo $this->rsfooteracc;?>
								</td>
							</tr>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="right-panel-report" id="rightPanel">
		<div class="card-box">
			<div class="card-search-head col-sm-12 border-botom">
				<div class="col-sm-6 text-left pd-0">
					<h4 class="m-b-0">
						<?php echo $tr->translate("SEARCH");?> 
						<i class="fa fa-search "></i> 
					</h4>
				</div>
				<div class="col-sm-6 text-right pd-0">
					<button onclick="closeRightPanel()" title="<?php echo $tr->translate("CLOSED");?> " class="btn-close">
						<i class="fa-solid fa-xmark"></i>
					</button>
				</div>
			</div>
			<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
				<div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("adv_search");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("branch_id");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("category_id");?>
					</div>
					<div class="col-md-12 col-sm-12 col-xs-12">
						<input id="product" />
					</div>
				 </div>
				 <div class="form-group">
					<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm->getElement("start_date");?>
					</div>
					<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm->getElement("end_date");?>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("user_id");?>
					</div>
					 <div class="col-md-12 col-sm-12 col-xs-12">
							<button class="button-class button-primary fullside" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
							<input type="hidden" name="recordcopy" id="recordcopy" dojoType="dijit.form.TextBox" />
					 </div>
				</div>
			</form>
		</div>	
	</div>
</div>
					
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>	
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script>
	dojo.require("dojo.data.ItemFileWriteStore");  
	
	require(["dojo/ready"], function(ready){
		ready(function(){
			getProductByCate();
			setTimeout(function() {
				setPrintOrientation('portrait');
			}, 500);
		});
		new dijit.form.FilteringSelect({
			store: item_store,
			autoComplete: false,
			queryExpr: "*${0}*",                     
			id: "product",
			name: "product",  
			placeholder:'<?php echo $tr->translate("SELECT_PRODUCT");?>', 
			required:false,        
			class: 'fullside', 
		}, "product");
	});
	
	var item_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	var url_dept = '<?php echo $this->url(array('module'=>'allreport','controller'=>'stock','action'=>'get-productbycate')); ?>';
	function getProductByCate(){
		cate_id = dijit.byId("category_id").get("value");
			dojo.xhrPost({
				url:url_dept,
				content:{
					'cate_id':cate_id,
					},
				handleAs:"json",
				load: function(data) {
					item_store  = getDataStorefromJSON('id','name', data);
					dijit.byId('product').set('store',item_store);  	
					dijit.byId('product').attr('value',"<?php echo $this->search['product']?>");
				},
				error: function(err) {
				}
			});
	}
</script>