<?php
$url_save = $this->url(array('module' => 'accounting', 'controller' => 'productcategory', 'action' => 'add'));
$this->tr = Application_Form_FrmLanguages::getCurrentlanguage();
$status_view = $this->status_view;
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$payment_term = $this->payment_term;
?>
<style>
	#table tr td {
		border: 1px solid #cccccc;
		text-align: center;
	}

	#table tr th {
		background: #cccccc;
		border: 1px solid #ddd;
	}

	table#table_row tr th {
		background: #3d6b82;
		padding: 5px 0;
		color: #fff;
	}
</style>
<title><?php echo $this->tr->translate("ADD_INVOICE") ?></title>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
			<div class="col-sm-12 border-botom">
				<div class="col-sm-8 pd-0">
					<h4 class="m-b-0"><i class="fa fa-newspaper-o"
							aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_INVOICE'); ?></h4>
				</div>
				<div class="col-sm-4 text-right">
				</div>
			</div>
		</div>
		<form id="add_province" action="" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
			<script type="dojo/method" event="onSubmit">
				   if(this.validate()) {
					   studentId=dijit.byId("studentId").get("value");
					if(studentId=="" || studentId==-1){
						   alert("Please Select Student Name or Student Id");
					}
						branch_id=dijit.byId("branch_id").get("value");
					if(branch_id=="" || branch_id==0){
						   alert("Please Select Branch");
						  return false;
					}
					identity = dijit.byId('identity').get('value');
					if(identity==''){
						alert('Please Select service');
						dijit.byId('item').focus();
						return false;
					}
					var rowId = $('#identity').val();
					if(rowId!=''){ 
						var rowIDArray = rowId.split(',');
						for(var n = 0; n < rowIDArray.length; n++){
							
						}
					}
					dijit.byId("save_new").attr("disabled",true);	
					dijit.byId("save_close").attr("disabled",true);
					loadingBlock();
					return true;
				   }else {
					return false;
				   }
			</script>
			<div class="card-box">
				<div class="col-md-5 col-sm-5 col-xs-12">
					<div class="card-blogform">
						<div class="card-body">
							<div class="row">
								<div class="col-md-12 col-sm-12 col-xs-12">
									<div class="d-flex ">
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-list-alt"></i>
										</div>
										<div class="col-md-10 col-sm-10 col-xs-12">
											<p class="tx-20 font-weight-semibold d-flex ">
												<?php echo $tr->translate("DETAIL_INFORMATION"); ?>
											</p>
										</div>
									</div>
									<div class="col-md-12 col-sm-12 col-xs-12">
										&nbsp;
									</div>
									<div class="form-group">
										<label
											class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("BRANCH"); ?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<select id="branch_id" name="branch_id" queryExpr="*${0}*"
												autoComplete="false" required="true" class="fullside"
												dojoType="dijit.form.FilteringSelect">
												<option value=""><?php echo $tr->translate("SELECT_BRANCH"); ?></option>
												<?php if (!empty($this->branch)) {
													foreach ($this->branch as $branch_na) { ?>
														<option value="<?php echo $branch_na['id'] ?>">
															<?php echo $branch_na['name'] ?>
														</option>
													<?php }
												} ?>
											</select>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("INVOICE_TYPE"); ?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<select id="invoice_type" name="invoice_type" onchange="resetForm();" queryExpr="*${0}*"
												autoComplete="false" required="true" class="fullside"
												dojoType="dijit.form.FilteringSelect">
												<option value="1"><?php echo $tr->translate("Outstanding Fee"); ?></option>
												<option value="2"><?php echo $tr->translate("Draft Information Invoice"); ?></option>
											</select>
										</div>
									</div>
									<div class="form-group">
										<label
											class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("STUDENT_NAME"); ?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<input id="studentId" />
										</div>
									</div>
									<div class="form-group">
										<label
											class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("ACADEMIC_YEAR"); ?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<select type="text" id="academic_year" name="academic_year"
												queryExpr="*${0}*" autoComplete="false" required="true" class="fullside"
												dojoType="dijit.form.FilteringSelect">
												<?php if (!empty($this->acadimicYear)) {
													foreach ($this->acadimicYear as $year) { ?>
														<option value="<?php echo $year['id'] ?>">
															<?php echo $year['name'] ?>
														</option>
													<?php }
												} ?>
											</select>
										</div>
									</div>
									<div class="form-group">
										<label
											class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("INPUT_DATE"); ?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<input type="text" name="input_date" id="input_date"
												constraints="{datePattern:'dd/MM/yyyy'}" value="now" class="fullside"
												dojoType="dijit.form.DateTextBox" />
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-5 col-sm-5 col-xs-12">
					<div class="card-blogform">
						<div class="card-body">
							<div class="row">
								<div class="col-md-12 col-sm-12 col-xs-12">
									<div class="d-flex ">
										<div class="settings-main-icon ">
											<i class="material-icons-outlined">receipt_long</i>
										</div>
										<div class="col-md-10 col-sm-10 col-xs-12">
											<p class="tx-20 font-weight-semibold d-flex ">
												<?php echo $tr->translate("INVOICE"); ?>
											</p>
										</div>
									</div>
									<div class="col-md-12 col-sm-12 col-xs-12">
										&nbsp;
									</div>
									<div class="form-group">
										<label
											class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("INVOICE_NO"); ?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<input dojoType="dijit.form.ValidationTextBox" class="fullside"
												id="invoice_num" name="invoice_num" readonly type="text"
												required="required">
										</div>
									</div>
									<div class="form-group">
										<label
											class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("INVOICE_DATE"); ?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<input type="text" name="invoice_date" id="invoice_date"
												constraints="{datePattern:'dd/MM/yyyy'}" value="now" class="fullside"
												dojoType="dijit.form.DateTextBox" />
										</div>
									</div>
									<div class="form-group">
										<label
											class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("EXPIRE_DATE"); ?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<input type="text" name="expire_date" id="expire_date"
												constraints="{datePattern:'dd/MM/yyyy'}" class="fullside"
												dojoType="dijit.form.DateTextBox" required />
										</div>
									</div>
									<div class="form-group">
										<label
											class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("REMARK"); ?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<input dojoType="dijit.form.TextBox" class="fullside" id="remark"
												name="remark" value="" type="text">
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
				</div>
			</div>
			<div class="card-box">
				<div class="form-group"
					style="background: #d8e0e2; padding: 5px 15px; margin: 0; border: solid 1px #697996; border-radius: 2px;">
					<div class="col-md-3 col-sm-3 col-xs-12">
						<div class="form-group">
							<label class="control-label  col-md-3 col-sm-3 col-xs-12"></label>
							<div class="col-md-9 col-sm-9 col-xs-12">
								<select style="height: 30px;" required="false" type="text" name="parentcategory"
										placeHolder="Main Category"
											id="parentcategory" class="custome-select-opt fullside" 
											autoComplete="false" queryExpr="*${0}*" onchange="filterSubCategory();">
											<option></option>
										<?php
											echo $this->rsmaincategory;
										?>
									</select>
							</div>
						</div>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<div class="form-group">
								<select style="height: 30px;" required="false" type="text" name="category"
									placeHolder="<?php echo $tr->translate("subCategory"); ?>"
									id="category" class="fullside" dojoType="dijit.form.FilteringSelect"
									autoComplete="false" queryExpr="*${0}*" onchange="getItemDetail(1,1,2);">
									<option value="-1"></option>
									<?php if (!empty($this->rs_type)) {
										foreach ($this->rs_type as $rs) { ?>
											<option value="<?php echo $rs['id'] ?>"><?php echo $rs['name'] ?></option>
										<?php }
									} ?>
								</select>
						</div>
					</div>
					<div class="col-md-5 col-sm-5 col-xs-12">
						<div class="form-group">
							<label class="control-label  col-md-5 col-sm-5 col-xs-12"
								style="font-size: 16px;text-align:center"><?php echo $tr->translate("LEVEL/SERVICE"); ?></label>
							<div class="col-md-7 col-sm-7 col-xs-12">
								<input id="item" name="item" />
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="card-box">
				<div class="col-md-12 col-sm-12 col-xs-12 mt-20 ">
					<table class="collape tablesorter" style="width:100%; white-space: nowrap;border:1px solid #ddd;">
						<thead>
							<tr id="head-title" class="head-td" align="right" style="width: 100%;">
							</tr>
						</thead>
						<tbody id="table_row">
						</tbody>
					</table>
					<input type="hidden" name="identity" id="identity" dojoType="dijit.form.TextBox" value="">
				</div>
				<div class="col-md-6 col-sm-6 col-xs-12">
				</div>
				<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="form-group">
						<label
							class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("TOTLE_AMOUNT"); ?>
						</label>
						<div class="col-md-7 col-sm-7 col-xs-12">
							<input dojoType="dijit.form.ValidationTextBox" readonly class="fullside" id="total_amount"
								name="total_amount" value="00.00" type="text" required="required">
						</div>
					</div>
				</div>
			</div>
			<div class="clearfix"></div>
			<div class="card-box mt-20 ">
				<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
					<input type="reset" value="Clear" label="<?php echo $tr->translate("CLEAR"); ?>"
						dojoType="dijit.form.Button" class="button-class button-danger"
						iconClass="glyphicon glyphicon-erase" />
					<input type="submit" value="save_close" id="save_close" name="save_close"
						label="<?php echo $tr->translate("SAVE_CLOSE"); ?>" dojoType="dijit.form.Button"
						class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-saved" />
					<input type="submit" value="save_new" name="save_new" id="save_new"
						label="<?php echo $tr->translate("SAVE_NEW"); ?>" dojoType="dijit.form.Button"
						class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-open" />
				</div>
			</div>
		</form>
	</div>
</div>
<script src="<?php echo $this->baseUrl(); ?>/js/help.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/admin/js/global.js" type="text/javascript"></script>
<link href="<?php echo $this->baseUrl()."/admin"?>/3.5.0/select2.css" rel="stylesheet">
<script src="<?php echo $this->baseUrl()."/admin"?>/3.5.0/select2.min.js"></script>

<script>
	dojo.require("dojo.data.ItemFileWriteStore");
	dojo.require("dojo.NodeList-manipulate");
	dojo.require('dijit.form.NumberTextBox');
	dojo.require("dijit.form.DateTextBox");

	item_store = getDataStorefromJSON('id', 'name');

	dojo.ready(function () {
		new dijit.form.FilteringSelect({
			store: item_store,
			autoComplete: false,
			queryExpr: "*${0}*",
			id: "item",
			name: "item",
			required: false,
			class: 'fullside',
			onChange: function () {
				addRow();
			}
		}, "item");
		new dijit.form.FilteringSelect({
			autoComplete: false,
			queryExpr: "*${0}*",
			id: "studentId",
			name: "studentId",
			required: false,
			class: 'fullside',
			placeHolder: "<?php echo $tr->translate("SELECT_STUDENT_NAME"); ?>",
			onChange: function () {
				getItemDetail();
			}
		}, "studentId");
		getallstudentname();
		var branch_id = dijit.byId('branch_id');
		branch_id.on('change', function (evt) {
			getallstudentname();
		});

		$("#parentcategory").select2(
		{
			dropdownAutoWidth : true,
			allowClear: "true"
		}
		);
	});

	function filterSubCategory(){
		var datajson = $('#parentcategory').find(":selected").val();
		if(typeof datajson !=="undefined" &&  datajson!=''){
			var datajsonparent = ($("#parentcategory").find(':selected').data('jsondata'));
			subcategorystore = getDataStorefromJSON('id', 'name', datajsonparent);
			dijit.byId('category').set('store', subcategorystore);
		}
		if(datajson==''){
			dijit.byId('category').set('store', categoryStore);
		}
		getItemDetail();
	}

	var url_dept = '<?php echo $this->url(array('module' => 'registrar', 'controller' => 'register', 'action' => 'get-gradeproduct')); ?>';
	function getItemDetail() {
		studentId = dijit.byId("studentId").get("value");

		ItemTypeId = dijit.byId("category").get("value");
		parentCategoryId = $('#parentcategory').val();

		if (studentId < 0) {
			dijit.byId("studentId").focus();
		}
		groupDetailId = 0;
		student_type = 1;//old student
		is_stutested = 0;
		dojo.xhrPost({
			url: url_dept,
			content: {
				'student_id': studentId,
				'parentcagetoryId':parentCategoryId,
				'dept_id': ItemTypeId,
				'is_stutested': is_stutested,
				'groupDetailId': groupDetailId
			},
			handleAs: "json",
			load: function (data) {
				item_store = getDataStorefromJSON('id', 'name', data);
				dijit.byId('item').set('store', item_store);
			},
			error: function (err) {
			}
		});
	}

	function getallstudentname() {
		dijit.byId("studentId").reset();
		branchId = dijit.byId('branch_id').get('value');
		if (branchId == '') {
			dijit.byId('branch_id').focus();
			return false;
		}
		let urlGet = '<?php echo $this->url(array('module' => 'registrar', 'controller' => 'register', 'action' => 'getliststudenturl')); ?>';

		contentData = {
			'branchId': branchId,
			'customerType': 1,
			'joinGroup': 1,
			'activeStudent': 1
		}
		getAllStudentByBranch(urlGet, contentData);
	}

	var col = 0; 
	var no = 0;
	var title = 0;
	var temp = '';
	function addRow() {
		let invoiceType = dijit.byId('invoice_type').get('value');
		if(title!=1){
			$("#head-title").html("");  
			if(invoiceType==1){
				temp+='<th>លុប</th>';
				temp+='<th>ល.រ</th>';
				temp+='<th>Service</th>';
				temp+='<th>ឆ្នាំសិក្សា</th>';			
				temp+='<th>បង់ជា</th>';	
				temp+='<th>សុពលភាព</th>';	
				temp+='<th><?php echo $tr->translate("START_DATE"); ?></th>';
				temp+='<th><?php echo $tr->translate("END_DATE"); ?></th>';	
				temp+='<th>ចំនួន</th>';			
				temp+='<th>តម្លៃ</th>';			
				temp+='<th>ការបញ្ចុះតម្លៃ</th>';			
				temp+='<th>ប្រាក់ត្រូវបង់</th>';	
			}else{
				temp+='<th width="4%"><?php echo $tr->translate("DELETE"); ?></th>';
				temp+='<th><?php echo $tr->translate("N_O"); ?></th>';
				temp+='<th><?php echo $tr->translate("SERVICES"); ?></th>';
				<?php $s = 0; ?>
				<?php foreach ($payment_term as $value) { ?>
					<?php echo"temp+='<th>$value</th>';"; ?>		
				<?php } ?>
				temp+='<th><?php echo $tr->translate("REMARK"); ?></th>';
			}
			dojo.query("#head-title").append(temp);
			title=1;
		}

		item_Label = dijit.byId("item").attr('displayedValue');
		item = dijit.byId("item").get("value");

		var iden = $("#identity").val();
		var arrays = iden.split(',');
		if (arrays != "") {
			for (var i = 0; i < arrays.length; i++) {
				readychoose = dijit.byId('service_' + arrays[i]).get('value');
				if (readychoose == item) {
					alert("<?php echo $tr->translate("Choosen ready") ?>");
					return false;
				}
			}
		}

		col++; no++;
		template = '';
		if(invoiceType==1){
			template = generateRowData(0,item,item_Label);
		}else{
			template += '<td align="center"><img onclick="deleteRecord(' + col + ');" src="<?php echo $this->baseUrl(); ?>/images/Delete_16.png"></td>';
			template += '<td align="center" width="2%">' + no + '</td>';
			template += '<td > <input type="hidden" dojoType="dijit.form.TextBox" required="true" id="service_' + col + '" name="service_' + col + '" value="' + item + '" /> <input type="hidden" dojoType="dijit.form.TextBox" name="service_type_' + col + '" id="service_type_' + col + '" />';
			template += item_Label + '</td>';
			template += '<td style="width:100px;"><input dojoType="dijit.form.NumberTextBox" onkeyup="calulator(' + col + ');" class="fullside" id="amount_' + col + '" name="amount_' + col + '" value="0" type="text" required="required" ></td>';
			template += '<td style="width:100px;"><input dojoType="dijit.form.NumberTextBox" onkeyup="calulator(' + col + ');" class="fullside" id="term_' + col + '" name="term_' + col + '" value="0" type="text" required="required" ></td>';
			template += '<td style="width:100px;"><input dojoType="dijit.form.NumberTextBox" onkeyup="calulator(' + col + ');" class="fullside" id="semester_' + col + '" name="semester_' + col + '" value="0" type="text" required="required" ></td>';
			template += '<td style="width:100px;"><input dojoType="dijit.form.NumberTextBox" onkeyup="calulator(' + col + ');" class="fullside" id="year_' + col + '" name="year_' + col + '" value="0" type="text" required="required" ></td>';
			template += '<td style="width:100px;"><input dojoType="dijit.form.NumberTextBox" onkeyup="calulator(' + col + ');" class="fullside" id="onepayment_' + col + '" name="onepayment_' + col + '" value="0" type="text" required="required" ></td>';
			template += '<td style="width:200px;" ><input dojoType="dijit.form.ValidationTextBox" class="fullside" id="remark_' + col + '" name="remark_' + col + '" value="" type="text"  ></td>';
			
			tmp = '<tr id="row' + col + '">';
			tmp += "</tr>";
			dojo.query("#table_row").append(tmp);
			if ($("#identity").val() != "") {
				var identity = $("#identity").val();
				$("#identity").val(identity + ',' + col);
			} else { $("#identity").val(col); }
			dojo.html.set(dojo.byId("row" + col), template, {
				parseContent: true,
			});
		}
		
	}
	function resetForm(){
		title=0;
		temp="";
		no=0;
		dojo.query("#table_row").append("");
		$("#head-title").html("");  
		$("#identity").val("");
	}
	let academicOption='';
	let discountOptionList='';
	let term_option='';
	let term_study_option = '';

	function generateRowData(index,itemId,ItemLabel){
		term_study_option = '';
		isInititilize = 1;
		if (itemId == '' && init == 0) {
			return false;
		}

		if (itemId != '') {
			isInititilize = 0;
		}
		branch_id = dijit.byId('branch_id').get('value');
		if (branch_id == '') {
			dijit.byId('branch_id').focus(); return false;
		}

		studentId = dijit.byId('studentId').get('value');
		if (studentId == '') {
			dijit.byId('studentId').focus(); return false;
		}
		var thisFeeId = 0;
		isAutopayment = '3';
		
		var urlRequest = "<?php echo $this->url(array('module' => 'registrar', 'controller' => 'register', 'action' => 'getitemforpaymentrecord')); ?>";
	
		contentData = {
			'branch_id': branch_id,
			'feeId': thisFeeId,
			'studentId': studentId,
			'grade': itemId,
			'studentType': 1,
			'isCurrent': 1,
			'stopType': 0,
			'isAutopayment': isAutopayment,
			'isInititilize': isInititilize,
			'isFinished':0
		}
		
		dojo.xhrPost({
			url: urlRequest,
			content: contentData,
			handleAs: "json",
			load: function (data) {
				col++;
				//HideloadingBlock();
				
				for (eRow = 0; eRow < data.length; eRow++) {
					discountOptionList = data[eRow].discountOptionList;
					term_option = data[eRow].termTypeList;
					academicOption = data[eRow].academicYearList;
					serviceType = data[eRow].itemType;
					term_study_option =data[eRow].studyPeriodList;

					template = '';
					template += '<td style="width:10px" align="center"><img onclick="deleteRecord(' + col + ');" src="<?php echo $this->baseUrl(); ?>/images/Delete_16.png"></td>';
					template += '<td style="width:10px" align="center">' + no + '</td>';
					template += '<td > <input type="hidden" dojoType="dijit.form.TextBox" required="true" id="service_' + col + '" name="service_' + col + '" value="' + item + '" /> <input type="hidden" dojoType="dijit.form.TextBox" name="service_type_' + col + '" id="service_type_' + col + '" value="'+serviceType+'"/>';
					template += item_Label + '</td>';
					template += '<td style="width:150px"><select class="custome-select-opt fullside" onchange="getservicefee(' + col + ',7);getValidate(' + col + ');" placeHolder="<?php echo $tr->translate('ACADEMIC_YEAR'); ?>" required="false" name="academic_year_' + col + '" id="academic_year_' + col + '" >' + academicOption + '</select></td>';
					template += '<td style="width:100px"><select class="custome-select-opt fullside" required="false" onchange="getservicefee(' + col + ');getValidate(' + col + ')" id="term_' + col + '" name="term_' + col + '" >' + term_option + '</select></td>';
					template += '<td style="width:150px"><select class="custome-select-opt fullside" required="false" onchange="getTermStudy(' + col + ');"  id="term_study' + col + '" name="term_study' + col + '" >' + term_study_option + '</select></td>';
					template += '<td style="width:110px;"><input constraints=' + '{datePattern:"dd/MM/yyyy"}' + ' dojoType="dijit.form.DateTextBox" class="fullside" id="startdate_' + col + '" name="startdate_' + col + '" value="" type="text" ></td>';
					template += '<td style="width:110px;"><input constraints=' + '{datePattern:"dd/MM/yyyy"}' + ' dojoType="dijit.form.DateTextBox" class="fullside" id="enddate_' + col + '" name="enddate_' + col + '" value="" type="text" ></td>';
					template += '<td style="width:50px"><input required="true" type="text" placeHolder="<?php echo $tr->translate('QTY'); ?>" class="fullside" onkeyup="calculateTotal(' + col + ');getValidate(' + col + ');" name="qty_' + col + '" id="qty_' + col + '" value="1" dojoType="dijit.form.NumberTextBox"  /></td>';
					template += '<td style="width:50px"><input  required="true" type="text" placeHolder="<?php echo $tr->translate('PRICE'); ?>" class="fullside" onkeyup="calculateTotal(' + col + ');" name="price_' + col + '" id="price_' + col + '"  value="0" dojoType="dijit.form.NumberTextBox" /></td>';
					template += '<td style="width:150px"><select novalidate onchange="calculateTotal('+col+');" placeHolder="<?php echo $tr->translate('DISCOUNT_TYPE'); ?>" class="custome-select-opt fullside"  id="discount_type' + col + '" name="discount_type' + col + '" >' + discountOptionList + '</select></td>';
					template += '<td style="width:50px"><input type="text" class="fullside" readonly="readonly"  name="total_amount' + col + '" value="0" id="total_amount' + col + '" dojoType="dijit.form.NumberTextBox"  /></td>';
					
					
					tmp = '<tr id="row' + col + '">';
					tmp += "</tr>";
					dojo.query("#table_row").append(tmp);
					if ($("#identity").val() != "") {
						var identity = $("#identity").val();
						$("#identity").val(identity + ',' + col);
					} else { $("#identity").val(col); }
					dojo.html.set(dojo.byId("row" + col), template, {
						parseContent: true,
					});
					$("#discount_type"+col).select2({
						dropdownAutoWidth : true,
						allowClear: "true",
						});
					$("#term_"+col).select2({
							allowClear: "true",
					});
					$("#term_study"+col).select2({
							allowClear: "true",
					});
					
					$("#academic_year_"+col).select2({
							allowClear: "false",
					});
					getservicefee(col);
				}
			
			},
			error: function (err) {
				HideloadingBlock();
			}
		});
	}
	function getValidate(key) {
		start_date = dijit.byId('startdate_' + key).get('value');
		term = $('#term_' + key).val();//
		service_type = $('#service_type_' + key).val();
		if((term == 2 || term==3 || term==4) && service_type==1){
			$('#academic_term').val(term).trigger('change');
		}
		if (term != 1) {
			return;
		}

		if (start_date != null) {
			amount = dijit.byId('qty_' + key).get('value');
			
			if (term == 1) {
				var a = new Date(start_date);
				mm = a.getMonth() + amount + 1;
			}
			else if (term == 2) {
				var a = new Date(start_date);
				mm = a.getMonth() + (amount * 3) + 1;
			}
			else if (term == 3) {
				var a = new Date(start_date);
				mm = a.getMonth() + (amount * 6) + 1;
			}
			else if (term == 4) {
				var a = new Date(start_date);
				mm = a.getMonth() + (amount * 12) + 1;
			}
			else if (term == 5) {
				dijit.byId("date_start_" + key).reset();
				dijit.byId("validate_" + key).reset();
				return false;
			}
			else {
				var a = new Date(start_date);
				mm = a.getMonth() + 1;
			}
			var dd = a.getDate();
			if (dd < 10) {
				dd = "0" + dd;
			}
			if (mm < 10) {
				mm = "0" + mm;
			}
			var y = a.getFullYear();
			var epx_date = y + '-' + mm + '-' + dd;
			dijit.byId('validate_' + key).attr('value', epx_date);
			if (term == 6) {
				dijit.byId("validate_" + key).attr("value", null);
			}
		}
	}
	var url_service_fee = "<?php echo $this->url(array('module' => 'accounting', 'controller' => 'servicecharge', 'action' => 'getservicefee')); ?>";
	function getservicefee(key) {
		stu_type = 1;
		studentid = dijit.byId('studentId').get('value');
		branch_id = dijit.byId('branch_id').get('value');
		if (branch_id == '') { dijit.byId('branch_id').focus(); return false; }

		item_id = dijit.byId('service_' + key).get('value');
		serviceType = dijit.byId('service_type_' + key).get('value');

		termRecord = $('#term_' + key).val();
		
		if (termRecord == '') {
			return false;
		}
		if (termRecord == 6) {//other term
			return 0;
		} else {
			dijit.byId("price_" + key).set('readOnly', true);
		}

		study_year = $('#academic_year_' + key).val();
		dojo.xhrPost({
			url: url_service_fee,
			content: {
				'term': termRecord,
				'service': item_id,
				'degreeId': '',
				'serviceType': serviceType,
				'year': study_year,
				'studentid': studentid,
				'branch_id': branch_id,
				'option':1
			},
			handleAs: "json",
			load: function (data) {
				resultFee = data.resultFee;
				dijit.byId("price_" + key).attr("value", resultFee.price);
				dijit.byId("service_type_" + key).attr("value", resultFee.items_type);
				calculateTotal(key);
				$('#term_study'+key).empty().trigger("change");
				$('#term_study'+key).append(data.resultPeriod).trigger('change');
				
				getTermStudy(key);
			},
			error: function (err) {
			}
		});
	}
	
	function calculateTotal(index) {
		
		price = dijit.byId('price_' + index).get('value');
		qty = dijit.byId('qty_' + index).get('value');
		qty = isNaN(qty) ? 0 : qty;
		subtotal = price * qty;
		
		discountType = ($("#discount_type"+index).find(':selected').data('data-discountype')); 
		if(discountType==1){//percentage
			discount_percent = $("#discount_type"+index).val(); 
			discount_percent = isNaN(discount_percent) ? 0 : discount_percent;
			totalDiscountPercent = Math.round((subtotal * discount_percent / 100));
		}else{
			totalDiscountPercent = ($("#discount_type"+index).find(':selected').data('discount-value')); 
			totalDiscountPercent = isNaN(totalDiscountPercent) ? 0 : totalDiscountPercent;
		}

		total_pay = parseFloat(subtotal) - totalDiscountPercent;
		dijit.byId('total_amount' + index).attr('value', total_pay);
		netTotal();
	}
	function netTotal() {
		var rowId = $('#identity').val();
		var rowIDArray = rowId.split(',');
		var totalPayment = 0;
		if(rowId!=""){
			for (var n = 0; n < rowIDArray.length; n++) {
				totalPayment += dijit.byId('total_amount' + rowIDArray[n]).get('value');
			}
		}
		dijit.byId('total_amount').attr('value', totalPayment);
	}
	function getTermStudy(key) {
		start_date = ($("#term_study"+key).find(':selected').data('start-date')); 
		end_date = ($("#term_study"+key).find(':selected').data('end-date')); 
		dijit.byId("startdate_" + key).attr("value", start_date);
		dijit.byId("enddate_" + key).attr("value", end_date);
	}


	function deleteRecord(index) {
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		for (var i = 0; i < arrays.length; i++) {
			if (arrays[i] == index) arrays.splice(i, 1);
		}
		var strings = arrays.join(',');
		$('#identity').val(strings);
		dojo.query("#row" + index).remove();
		calulator(arrays['i']);
	}
	function calulator(index) {
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		var amount = 0;
		for (var i = 0; i < arrays.length; i++) {
			var a = dijit.byId("amount_" + arrays[i]).get('value');
			var term = dijit.byId("term_" + arrays[i]).get('value');
			var semester = dijit.byId("semester_" + arrays[i]).get('value');
			var year = dijit.byId("year_" + arrays[i]).get('value');
			amount = amount + parseFloat(a) + parseFloat(term) + parseFloat(semester) + parseFloat(year);
		}
		dijit.byId("total_amount").attr('value', amount);
	}
</script>