<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_callteral;
	echo $this->headTitle($tr->translate("CHANGE_PROGRAM"));
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$frm= $this->frm;
	
?>
<div class="card">
	<div class="card-content collapse show">
		<form id="add_car" action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
					branch_id = dijit.byId('branch_id').get('value');
					if(branch_id==''){
						dijit.byId('branch_id').focus();
						return false;
					}
					academicYear = dijit.byId('academicYear').get('value');
					if(academicYear=='' || academicYear==-1){
						dijit.byId('academicYear').focus();
						return false;
					}
					var rowStudent = $('#identity_student').val();
					if (rowStudent == '') {
						alert("<?php echo $tr->translate('PLEASE_ADD_STUDENT_RECORD');?>");
						return false;
					}
					var isMulti = $('#isSingleToProgram').val();
					if( isMulti == 2 ){
						var identityStudy = $('#identity_study').val();
						if(identityStudy==''){
							alert("<?php echo $tr->translate("PLEASE_SET_STUDY_INFORMATION");?>");
							dijit.byId("degreeAddRow").focus();
							return false;
						}
					}
					loadingBlock();
					return true;
				}else {
					return false;
				}
			</script>
			<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-sitemap" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_STUDENT_CHANGE_BRANCH');?></h4>
	    			</div>
	    			<div class="col-sm-4 text-right">
	    			</div>
	    		</div>
	    	</div>
    		<div class="card-box">
	        	<div class="col-md-3 col-sm-3 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-education"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("STUDY_INFO");?></p>
										</div> 
									</div>
									<div class="form-group">
										
									</div>
									<div class="form-group">
										<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("BRANCH");?> </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("branch_id");?>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("DEGREE");?> <span class="required">*</span> :
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("academicYear");?>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("STUDY_PROGRAM")?> :
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<select class="custome-select-opt fullside" onchange="getProgramInfo();getStudentOption();" placeHolder="<?php echo $tr->translate("SELECT_PROGRAM_TYPE"); ?>" required="false" name="programType" id="programType" ></select>
											<input type="hidden" name="degreeList" id="degreeList" value="" />
											<input type="hidden" name="isSingleProgram" id="isSingleProgram" value="" />
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
	           </div>
	           <div class="col-md-3 col-sm-3 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
						<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-th-large"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("CHANGE_DATE");?></p>
										</div> 
									</div>

									<div class="form-group">
										
									</div>
									<div class="form-group">
										<label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("TO_STUDY_PROGRAM");?> :
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
												<?php echo $frm->getElement("chagneDate");?>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label  col-md-5 col-sm-5 col-xs-12" >
											<?php echo $tr->translate("MOVING_DATE")?> :
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<select class="custome-select-opt fullside" onchange="getProgramInfo(1);" placeHolder="<?php echo $tr->translate("SELECT_PROGRAM_TYPE"); ?>" required="false" name="toProgramType" id="toProgramType" ></select>
											<input type="hidden" name="toDegreeList" id="toDegreeList" value="" />
											<input type="hidden" name="isSingleToProgram" id="isSingleToProgram" value="" />
										</div>
									</div>
									<div class="form-group">
										<label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("NOTE");?> :
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
												<?php echo $frm->getElement("note");?>
										</div>
									</div>
									
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="card card-form mb-4 subClassInfo">
						<div class="card-header bg-label-primary pb-2 rounded">
							<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("SCHOOL_OPTIONS_INFO");?></h5>
							<div class="form-group">
								<div class="col-md-3 col-sm-3 col-xs-12">
									<input id="degreeAddRow" />
								</div>
								<div class="col-md-3 col-sm-3 col-xs-12">
									<input id="gradeAddRow" />
								</div>
								<div class="col-md-3 col-sm-3 col-xs-12">
									<input id="groupAddRow" />
								</div>
								<div class="col-md-3 col-sm-3 col-xs-12">
									<input class="button-class button-warning" iconClass="glyphicon glyphicon-sort-by-attributes" type="button" label="<?php echo $tr->translate('Add Study Record');?>" dojoType="dijit.form.Button" onclick="addRowStudy();" />
								</div>
							</div>
						</div>
						<div class="card-body p-0">
							<div class="row g-3">
								<table class="responsiveTable" style="border-collapse: collapse; border:1px solid #ccc;">
									<thead>
										<tr id="head-title_study" class="head-td" align="right" style="white-space:nowrap;"></tr>
									</thead>
									<tbody id="table_row_study" >
									</tbody>
								</table>
								<input type="hidden" name="identity_study" id="identity_study"  />
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12 col-sm-12 col-xs-12">
					<div class="card card-form mb-4 ">
						<div class="card-header bg-label-primary pb-2 rounded">
							<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("STUDENT_INFO");?></h5>
							<div class="form-group">
								<div class="col-md-3 col-sm-3 col-xs-12">
									<input id="degree" />
								</div>
								<div class="col-md-3 col-sm-3 col-xs-12">
									<input id="grade" />
								</div>
								<div class="col-md-3 col-sm-3 col-xs-12">
									<select class="custome-select-opt fullside" placeHolder="<?php echo $tr->translate("SELECT_STUDENT"); ?>" name="studentId" id="studentId" ></select>
								</div>
								<div class="col-md-3 col-sm-3 col-xs-12">
									<input class="button-class button-warning" iconClass="ti ti-chevrons-down" type="button" label="<?php echo $tr->translate('ADD_ROW');?>" dojoType="dijit.form.Button" onclick="addRowStudent();" />
								</div>
							</div>
						</div>
						<div class="card-body p-0">
							<div class="row g-3">
								<table class="responsiveTable" style="border-collapse: collapse; border:1px solid #ccc;">
									<thead>
										<tr id="head-title_student" class="head-td" align="right" style="white-space:nowrap;"></tr>
									</thead>
									<tbody id="table_row_student" >
									</tbody>
								</table>
								<input type="hidden" name="identity_student" id="identity_student"  />
							</div>
						</div>
					</div>
				</div>
			</div>
       	  <div class="clearfix"></div>
		    <div class="card-box">
               	<div class="col-sm-12 border-top mt-20 ptb-10 text-center">
               			<input class="button-class button-danger" iconClass="glyphicon glyphicon-erase" type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>" onclick="clear();" dojoType="dijit.form.Button"/>
						<input type="submit" value="save_close" name="save_close" id="save_close" label="<?php echo $tr->translate('SAVE_CLOSE');?>" dojoType="dijit.form.Button" 
						class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-saved" />
						<input type="submit" value="save_new" name="save_new" id="save_new" label="<?php echo $tr->translate('SAVE_NEW');?>" dojoType="dijit.form.Button" 
						class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-open" />
	    		</div>
	    	</div>
       </form>
	</div>
</div>
<link href="<?php echo $this->baseUrl()."/admin"?>/3.5.0/select2.css" rel="stylesheet">
<script src="<?php echo $this->baseUrl()."/admin"?>/3.5.0/select2.min.js"></script>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.Textarea");
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.data.ObjectStore");
var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
var degree_store = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );

dojo.ready(function(){
	
	new dijit.form.FilteringSelect({
		store: degree_store,
		queryExpr: "*${0}*",
		autoComplete: false,                     
		required: false,
		id: "degree",
		name: "degree",           
		class: "fullside", 
		placeHolder:"<?php echo $tr->translate("SELECT_DEGREE");?>",          
		onChange: function() {  
			getallGrade();
			 getStudentOption();
		}
	}, "degree");
	
	new dijit.form.FilteringSelect({
	    queryExpr: "*${0}*",
		autoComplete:false,                     
		required: false,                   
	    id: "grade",
	    name: "grade",  
	    tabindex: "16",  
	    class: 'fullside',  
	    placeHolder:"<?php echo $tr->translate("SELECT_GRADE");?>",          
	    onChange: function() {  
			 getStudentOption();
	    }
	}, "grade");
	getallGrade();
	
	new dijit.form.FilteringSelect({
		store: degree_store,
		queryExpr: "*${0}*",
		autoComplete: false,                     
		required: false,
		id: "degreeAddRow",
		name: "degreeAddRow",           
		class: "fullside", 
		placeHolder:"<?php echo $tr->translate("SELECT_DEGREE");?>",          
		onChange: function() {  
			getallGrade(1);
			getAllGroup(1);
		}
	}, "degreeAddRow");
	
	new dijit.form.FilteringSelect({
		queryExpr: "*${0}*",
		autoComplete:false,                     
		required: false,                   
		id: "gradeAddRow",
		name: "gradeAddRow",  
		tabindex: "16",  
		class: 'fullside',  
		placeHolder:"<?php echo $tr->translate("SELECT_GRADE");?>",          
		onChange: function() {  
			getAllGroup(1);
		}
	}, "gradeAddRow");
	getallGrade(1);
	
	new dijit.form.FilteringSelect({
		queryExpr: "*${0}*",
		autoComplete:false,                     
		required: false,                        
		id: "groupAddRow",
		name: "groupAddRow",  
		class: 'fullside', 
		readonly:false,
		required:false,
		placeHolder:"<?php echo $tr->translate("SELECT_GROUP");?>",          
		onChange: function() {  
		}
	}, "groupAddRow");
	
	var academicYear = dijit.byId('academicYear');
	 academicYear.on('change', function(evt) {
		 getStudentOption();
	});
	var branch_id = dijit.byId('branch_id');
	 branch_id.on('change', function(evt) {
		 getRefreshItems();
		 getRefreshItems(1);
		 getStudentOption();
	});
	$(".custome-select-opt").select2(
		{dropdownAutoWidth : true,allowClear: "true"}
	);
	getProgramTypeList();
	getProgramInfo();
	
	
	setTimeout(function () {   
		getProgramTypeList(1);
		getProgramInfo(1);
		
		getRefreshItems();
		 getRefreshItems(1);
	}, 1000);
	
});
function getProgramTypeList(type=0) {
	let urlGetProgramList = '<?php echo $this->url(array('module' => 'global', 'controller' => 'programtype', 'action' => 'get-program-list')); ?>';
	var thisIsSingleProgram="";
	if(type==1){
		thisIsSingleProgram = $('#isSingleProgram').val();
	}
	contentData = {
		'option':1,
		'isNotThisOpt':thisIsSingleProgram,
	}
	dojo.xhrPost({
		url: urlGetProgramList,
		content:contentData,
		handleAs:"json",
		load: function(data){
			if(type==1){
				$('#toProgramType').empty().trigger("change");
				$('#toProgramType').append(data).trigger('change');
			}else{
				$('#programType').empty().trigger("change");
				$('#programType').append(data).trigger('change');
			}
			
		},
		error: function(err) {
		}
	});
}
function getProgramInfo(type=0){
	if(type==1){
		var programType = $('#toProgramType').find(":selected").val();
		if(typeof programType !=="undefined" ){
			if( programType >0){
				var programTypeInfo = ($("#toProgramType").find(':selected').data('record-info'));
				if(programTypeInfo !="undefined" ){
					$('#isSingleToProgram').val(programTypeInfo.isSingleProgram);
				}
			}
		}
	}else{
		var programType = $('#programType').find(":selected").val();
		if(typeof programType !=="undefined" ){
			if( programType >0){
				var programTypeInfo = ($("#programType").find(':selected').data('record-info'));
				if(programTypeInfo !="undefined" ){
					$('#isSingleProgram').val(programTypeInfo.isSingleProgram);
				}
			}
		}
		getProgramTypeList(1);
	}
	checkingProgramInfo(type);
	
}

function checkingProgramInfo(type=0){
	if(type==1){
		var isSingleToProgram = $('#isSingleToProgram').val();
		if(isSingleToProgram==1){
			$("div.subClassInfo").addClass("d-none");
			$('#identity_study').val("");
			$('#table_row_study').html("");
		}else{
			$("div.subClassInfo").removeClass("d-none");
		}
	}
}

url_getallgroup = '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'getallgroup'));?>';
function getAllGroup(type=0){
	
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		if(type==1){
			dijit.byId('groupAddRow').set('store',group_store);   
		}else{
			dijit.byId('group').set('store',group_store);   
		}  
		dijit.byId('branch_id').focus();
		return false;
	}
	degree = dijit.byId('degree').get('value');
	if(degree=='' || degree==-1){
		degree ="";
	}
	
	grade = dijit.byId('grade').get('value');
	if(grade=='' || grade==-1){
		grade ="";
	}
	if(type==1){
		degree = dijit.byId('degreeAddRow').get('value');
		grade = dijit.byId('gradeAddRow').get('value');
		dijit.byId('groupAddRow').reset();  
	}else{
		dijit.byId('group').reset();  
	}
	dojo.xhrPost({
		url: url_getallgroup,
		content:{
			'branch_id':branch_id,
			'degree':degree,
			'grade':grade,
			'noaddnew':1
		},
		handleAs:"json",
		load: function(data) {
		    group_store  = getDataStorefromJSON('id','name', data); 
			if(type==1){
				dijit.byId('groupAddRow').set('store',group_store);   
			}else{
				dijit.byId('group').set('store',group_store);   
			}			
		},
		error: function(err) {
		}
	});
}
function getRefreshItems(type=0){
	var degreeList = "";
	if(type==1){
		dijit.byId('degreeAddRow').reset();  
		degreeList = $('#toDegreeList').val();
	}else{
		degreeList = $('#degreeList').val();
		dijit.byId('degree').reset();  
	}
	var url_getItems = '<?php echo $this->url(array("module"=>"global","controller"=>"degree","action"=>"refreshitems"));?>';										
	dojo.xhrPost({
		url: url_getItems,
		content:{
			'items_type': 1,
			'degreeList': degreeList,
			},
		handleAs:"json",
		load: function(data) {
			degree_store  = getDataStorefromJSON('id','name', data);
			if(type==1){
				dijit.byId('degreeAddRow').set('store',degree_store);
			}else{
				dijit.byId('degree').set('store',degree_store);
			}
		    HideloadingBlock();
		},
		error: function(err) {
			HideloadingBlock();
		}
	});
}
var grade_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
var url_dept = '<?php echo $this->url(array('module'=>'global','controller'=>'grade','action'=>'get-grade')); ?>';
function getallGrade(type=0){
	dept_id = dijit.byId('degree').get('value');
	if(type==1){
		dept_id = dijit.byId('degreeAddRow').get('value');
	}
	if(dept_id==''){return false;}
		dojo.xhrPost({
			url:url_dept,
			content:{
				'dept_id':dept_id,
				'noaddnew':1
				},
			handleAs:"json",
			load: function(data) {
				grade_store  = getDataStorefromJSON('id','name', data);
				if(type==1){
					 dijit.byId('gradeAddRow').set('store',grade_store);   
				}else{
					 dijit.byId('grade').set('store',grade_store);   
				}
			},
			error: function(err) {
			}
		});
}

var urlGetData = '<?php echo $this->url(array('module' => 'setting', 'controller' => 'photomg', 'action' => 'get-record-list')); ?>';
function getStudentOption(){
	
	var recordType = 1;
	branchId = dijit.byId("branch_id").get("value");
	if (branchId == '') {
		//dijit.byId("branchId").focus();
		return false;
	}
	var currentProgramType = 0;
	var programType = $('#programType').find(":selected").val();
	if(typeof programType !=="undefined" ){
		if( programType >0){
			currentProgramType = programType;
		}
	}
	academicYear = dijit.byId('academicYear').get('value');
	degree = dijit.byId('degree').get('value');
	grade = dijit.byId('grade').get('value');
	
	dojo.xhrPost({
		url: urlGetData,
		content: {
			'branchId': branchId
			,'recordType': recordType
			,'joinGroup': 1
			,'itemType': 1
			,'isMaingrad': 1
			,'isCurrent': 1
			,'activStudent': 1
			,'customerType': 1
			,'option': 1
			,'programType': currentProgramType
			,'academicYear': academicYear
			,'degree': degree
			,'grade': grade
			
		},
		handleAs: "json",
		load: function (data) {
			$('#studentId').empty().trigger("change");
			$('#studentId').append(data).trigger('change');
		},
		error: function (err) {
		}
	});
}

var col_study = 0;
var no_study = 0;
var title_study = 0;
tmp_study = '';
temp_study='';
function addRowStudy() {
	var degreeAddRow = dijit.byId('degreeAddRow').get('value');
	if(degreeAddRow==''){
		dijit.byId('degreeAddRow').focus();
		return false;
	}
	degreelabel = dijit.byId("degreeAddRow").attr('displayedValue');
	gradelabel = dijit.byId("gradeAddRow").attr('displayedValue');
	groupabel = dijit.byId("groupAddRow").attr('displayedValue');
	var gradeAddRow = dijit.byId('gradeAddRow').get('value');
	if(gradeAddRow==''){
		gradeAddRow = "";
		gradelabel="";
	}
	groupAddRow = dijit.byId('groupAddRow').get('value');
	if(groupAddRow==''){
		groupAddRow = "";
		groupabel="";
	}
	col_study++;
	no_study++;
	
	template_study='';
	if(title_study!=1){
		temp_study+='<th><?php echo $tr->translate("DEL");?></th>';
		temp_study+='<th><?php echo $tr->translate("N_O");?></th>';
		temp_study+='<th ><?php echo $tr->translate("DEGREE");?></th>';
		temp_study+='<th ><?php echo $tr->translate("GRADE");?></th>';
		temp_study+='<th ><?php echo $tr->translate("GROUP");?></th>';
		dojo.query("#head-title_study").append(temp_study);
		title_study=1;
	}
		template_study+='<td width="4%"align="center"><img onclick="deleteRecord_study('+col_study+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
		template_study+='<td width="4%" align="center">'+no_study+'</td>';
		template_study+='<td>&nbsp;<input style="width:100%;" placeholder="<?php echo $tr->translate("DEGREE");?>" dojoType="dijit.form.TextBox" class="fullside" name="degree_'+col_study+'" id="degree_'+col_study+'" value="'+degreeAddRow+'" type="hidden">'+degreelabel+'&nbsp;</td>';
		template_study+='<td>&nbsp;<input style="width:100%;" placeholder="<?php echo $tr->translate("GRADE");?>" dojoType="dijit.form.TextBox" class="fullside" name="grade_'+col_study+'" id="grade_'+col_study+'" value="'+gradeAddRow+'" type="hidden">'+gradelabel+'&nbsp;</td>';
		template_study+='<td>&nbsp;<input style="width:100%;" placeholder="<?php echo $tr->translate("GROUP");?>" dojoType="dijit.form.TextBox" class="fullside" name="group_'+col_study+'" id="group_'+col_study+'" value="'+groupAddRow+'" type="hidden">'+groupabel+'&nbsp;</td>';
		
	tmp_study='<tr id="row_study'+col_study+'">';
	tmp_study+="</tr>";
	dojo.query("#table_row_study").append(tmp_study);

	if($("#identity_study").val()!="") {
		var identity_study = $("#identity_study").val();
		$("#identity_study").val(identity_study+','+col_study);
	} else {$("#identity_study").val(col_study);}
	dojo.html.set(dojo.byId("row_study"+col_study),template_study , {
		 parseContent: true,
	});
	dijit.byId('degreeAddRow').reset();
	dijit.byId('gradeAddRow').reset();
	dijit.byId('groupAddRow').reset();
}
function deleteRecord_study(index) {
	var identity = $('#identity_study').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
	if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity_study').val(strings);
	dojo.query("#row_study"+index).remove();
}


var col_student = 0;
var no_student = 0;
var title_student = 0;
tmp_student= '';
temp_student='';
function addRowStudent() {
	
	let stuCode = "";
	let stuName = "";
	let degreeLabel = "";
	let gradeLabel = "";
	let groupLabel = "";
	let currentStudentId = 0;
	let thisDegree= "";
	let thisGrade = "";
	let thisGroup = "";
	var studentId = $('#studentId').find(":selected").val();
	if(typeof studentId !=="undefined" ){
		if( studentId >0){
			currentStudentId = studentId;
			var recordInfo = ($("#studentId").find(':selected').data('record-info'));
			if(recordInfo !="undefined" ){
				stuCode = recordInfo.studentCode;
				stuName = recordInfo.studentNameKh;
				degreeLabel = recordInfo.degreeTitle;
				gradeLabel = recordInfo.gradeTitle;
				groupLabel = recordInfo.groupCode;
				
				thisDegree = recordInfo.degree;
				thisGrade = recordInfo.grade;
				thisGroup = recordInfo.groupId;
			}
			$("#studentId").val(null).trigger("change"); 
		}
	}
	
	if(currentStudentId==0){
		return false;
	}
	var alreadySeleted= false;
	var identityStudent = $('#identity_student').val();
	var arrayStu = identityStudent.split(',');
	if(identityStudent!=""){
		for (var p = 1; p <= arrayStu.length; p++) {
			var thisRow = dijit.byId('studentId'+p).get('value');
			if(thisRow==currentStudentId){
				alreadySeleted = true;
				break;
			}
		}
	}
	if(alreadySeleted){
		alert("<?php echo $tr->translate("ALREADY_SELECTED");?>");
		return false;
	}
	
	
	
	col_student++;
	no_student++;
	
	template_student='';
	if(title_student!=1){
		temp_student+='<th><?php echo $tr->translate("DEL");?></th>';
		temp_student+='<th><?php echo $tr->translate("N_O");?></th>';
		temp_student+='<th><?php echo $tr->translate("STU_CODE");?></th>';
		temp_student+='<th><?php echo $tr->translate("STU_NAME");?></th>';
		temp_student+='<th ><?php echo $tr->translate("DEGREE");?></th>';
		temp_student+='<th ><?php echo $tr->translate("GRADE");?></th>';
		temp_student+='<th ><?php echo $tr->translate("GROUP");?></th>';
		dojo.query("#head-title_student").append(temp_student);
		title_student=1;
	}
		template_student+='<td width="4%"align="center"><img onclick="deleteRecordStudent('+col_student+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
		template_student+='<td width="4%" align="center">'+no_student+'</td>';
		template_student+='<td align="center">'+stuCode+'</td>';
		template_student+='<td align="center">'+stuName+'</td>';
		template_student+='<input dojoType="dijit.form.TextBox" class="fullside" name="studentId'+col_student+'" id="studentId'+col_student+'" value="'+currentStudentId+'" type="hidden">';
		template_student+='<input dojoType="dijit.form.TextBox" class="fullside" name="studentDegree'+col_student+'" id="studentDegree'+col_student+'" value="'+thisDegree+'" type="hidden">';
		template_student+='<input dojoType="dijit.form.TextBox" class="fullside" name="studentGrade'+col_student+'" id="studentGrade'+col_student+'" value="'+thisGrade+'" type="hidden">';
		template_student+='<input dojoType="dijit.form.TextBox" class="fullside" name="studentGroup'+col_student+'" id="studentGroup'+col_student+'" value="'+thisGroup+'" type="hidden">';
		template_student+='</td>';
		template_student+='<td align="center">'+degreeLabel+'</td>';
		template_student+='<td align="center">'+gradeLabel+'</td>';
		template_student+='<td align="center">'+groupLabel+'</td>';
		
	tmp_student='<tr id="row_student'+col_student+'">';
	tmp_student+="</tr>";
	dojo.query("#table_row_student").append(tmp_student);

	if($("#identity_student").val()!="") {
		var identity_student = $("#identity_student").val();
		$("#identity_student").val(identity_student+','+col_student);
	} else {$("#identity_student").val(col_student);}
	dojo.html.set(dojo.byId("row_student"+col_student),template_student , {
		 parseContent: true,
	});
}
function deleteRecordStudent(index) {
	var identity = $('#identity_student').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
	if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity_student').val(strings);
	dojo.query("#row_student"+index).remove();
}

</script>
