<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate('SEARCH_TEACHER'));
$formList = new Application_Form_Frmtable();
$frm =  $this->formSearch;

$parameterserch =  basename($_SERVER['REQUEST_URI']);
$urlsting = str_replace("&pages=" . $this->currentPage, "", $parameterserch);
$urlsting = str_replace("searchteacher", "", $urlsting);

$sign = "?";
if (!empty($urlsting)) {
	$sign = "&";
}
$db_student = new Home_Model_DbTable_DbStudent();
$dbreportGr = new Allreport_Model_DbTable_DbRptGroup();
?>
<style>
	.search-list {
		min-height: 400px;
	}
	ul.nav.navbar-right.panel_toolbox.stusearch {
		min-width: 0;
	}
	ul.nav.navbar-right.panel_toolbox.stusearch li.dropdown a.dropdown-toggle {
		padding: 10px;
	}
	.teacherName{
		line-height: 26px !important;
	}
	.content-teachinginfo {
		min-height: 160px;
	}
	.odd-row {
		background: #e4e4e466;
	}
</style>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="x_panel">
		<div class="x_title">
			<h2><i class="fa fa-filter"></i> <?php echo $tr->translate("FINDING_ALL_TEACHING_INFORMATION");?> <small><?php echo $tr->translate("TEACHER_INFO");?></small></h2>
			<ul class="nav navbar-right panel_toolbox">
			  <li>
				<a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
			  </li>
			</ul>
			<div class="clearfix"></div>
		</div>
		<div class="x_content" >
			<form id='foundation_class' action="" dojoType="dijit.form.Form" method="get" enctype="application/x-www-form-urlencoded">
				<div class="form-group">
					<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement("adv_search"); ?>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement("branch_id"); ?>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement("academic_year"); ?>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement("degree"); ?>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<input id="grade" />
					</div>
				</div>
				<div class="clearfix"></div>
				<div class="form-group">
					<div class="col-md-2 col-sm-2 col-xs-12">
						<input id="group" />
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<button class="button-class button-primary" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" name="search" type="submit"><?php echo $tr->translate("SEARCH"); ?></button>
					</div>
				</div>
			</form>
		</div>
	</div>
	<div class="card-content collapse show">
		
		<div class="card-box search-list">
			<?php if (!empty($this->row)) foreach ($this->row as $key => $rs) { 
			
				$btnClass = "btn-primary";
				$classStudentStatus = "bg-gradient-blue";
				if ($rs['status'] == 0) {
					$classStudentStatus = "bg-gradient-red";
					$btnClass = "btn-danger";
				}
			?>
				<div class="col-md-4 col-sm-6 col-xs-6 mt-10">
					<div class="card student-card text-center  border border-1 border-grey p-0">
						<div class="card-body p-0">
							<div class="row g-3">
								<div class="col-md-4 col-sm-4 col-xs-12 <?php echo $classStudentStatus;?> mt-0 rounded card-info-left">
									<?php
										$photo = $this->baseUrl() . "/images/user.png";
										if (!empty($rs['photo'])) {
											if (file_exists(PUBLIC_PATH . "/images/photo/" . $rs['photo'])) {
												$photo = $this->baseUrl() . '/images/photo/' . $rs['photo'];
											}
										}
										$detail = json_decode($rs['jsonData'], TRUE);
										$teacherName = $rs['teacherNameKh'];
										$teacherName = empty($teacherName) ? $rs['teacherNameEn'] : $teacherName;
									?>
									<div class="user-avatar-section">
									  <div class=" d-flex align-items-center flex-column card-profile">
										<div class="flex-shrink-0 img-profile">
											<img src="<?php echo $photo; ?>" alt="user image" class="d-block h-auto ms-0 ms-sm-6 rounded user-profile-img">
											<?php if ($rs['sex'] == 1) { ?>
												<i class="fa fa-male member-star text-active" title="verified user"></i>
											<?php } else { ?>
												<i class="fa fa-female member-star text-deactive" title="verified user"></i>
											<?php } ?>
										</div>
										<span class="addtional-info top-info">
											<?php echo $rs['teacherDeptTitle']; ?>
										</span>
										<span class="addtional-info bottom-info">
											<small><?php echo !empty($rs['branchName']) ? $rs['branchName'] : "N/A"; ?></small>
											<br>
											<a title="<?php echo $tr->translate('VIEW_DETAIL'); ?>" class="btn btn-xs btn-round rounded-pill <?php echo $btnClass;?> waves-effect m-t-10 waves-effect waves-light" href="<?php echo $this->baseUrl() . "/home/searchteacher/detail?id=" . $rs['teacherId']."&academicYear=". $rs['academicYear']; ?>">
												<small>
												<i class="fa fa-eye"></i> <?php echo $tr->translate('VIEW_DETAIL'); ?>...
												</small>
											</a>
											<br>
										</span>
									
									  </div>
									</div>
								</div>
								
								<div class="col-md-8 col-sm-8 col-xs-12 m-0 p-0 card-info-right">
									<div class="card-addtional">
										<div class="card-body <?php echo $classStudentStatus;?> py-2 px-1">
											<ul class="nav navbar-right panel_toolbox stusearch">
												<li class="dropdown">
													<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="true"><i class="fa fa-ellipsis-v"></i></a>
													<ul class="dropdown-menu" role="menu">
														<li><a href="javascript:void(0);" onClick="addTab('<?php echo $tr->translate("APPOINTMENT_LETTER");?>','<?php echo $this->baseUrl() . "/allreport/allstaff/appointment-letter?id=". $rs['teacherId']."&appointment_date=". date("d-m-Y")."&year_id=". $rs['academicYear']."&year_value=". $rs['academicYearTtitle']."&inFrame=true"; ?>');"><?php echo $tr->translate('APPOINTMENT_LETTER'); ?></a></li>
													</ul>
												</li>
											</ul>
											<p class="mb-0 text-primary text-truncate"><?php echo $rs['teacherCode']; ?></p>
											<h4 class="teacherName mb-0 mt-0 text-primary text-truncate"><?php echo $teacherName; ?></h4>
											
											<div class="row w-100 align-items-center">
											  <div class="col-sm-4 mb-1 mb-sm-0 mb-lg-1 mb-xxl-0 mt-0  text-start">
												<small class="mb-0 fw-normal text-truncate"><?php echo $tr->translate('NATION'); ?></small>
											  </div>
											  <div class="col-sm-8 d-flex justify-content-sm-end mt-0 ">
												<small class="text-truncate"><?php echo !empty($rs['nation']) ? $rs['nation'] : "N/A"; ?></small>
											  </div>
											</div>
											<div class="row w-100 align-items-center">
											  <div class="col-sm-4 mb-1 mb-sm-0 mb-lg-1 mb-xxl-0 mt-0  text-start">
												<small class="mb-0 fw-normal text-truncate"><?php echo $tr->translate('NATIONALITY'); ?></small>
											  </div>
											  <div class="col-sm-8 d-flex justify-content-sm-end mt-0 ">
												<small class="text-truncate"><?php echo !empty($rs['nationality']) ? $rs['nationality'] : "N/A"; ?></small>
											  </div>
											</div>
											<div class="row w-100 align-items-center">
											  <div class="col-sm-4 mb-1 mb-sm-0 mb-lg-1 mb-xxl-0 mt-0  text-start">
												<small class="mb-0 fw-normal text-truncate"><?php echo $tr->translate('CULTURE_LEVEL'); ?></small>
											  </div>
											  <div class="col-sm-8 d-flex justify-content-sm-end mt-0 ">
												<small class="text-truncate"><?php echo !empty($rs['educationTitle']) ? $rs['educationTitle'] : "N/A"; ?></small>
											  </div>
											</div>
											<div class="row w-100 align-items-center">
											  <div class="col-sm-4 mb-1 mb-sm-0 mb-lg-1 mb-xxl-0 mt-0  text-start">
												<small class="mb-0 fw-normal text-truncate"><?php echo $tr->translate('TEL'); ?></small>
											  </div>
											  <div class="col-sm-8 d-flex justify-content-sm-end mt-0 ">
												<small class="text-truncate"><?php echo !empty($rs['tel']) ? $rs['tel'] : "N/A"; ?></small>
											  </div>
											</div>
											<div class="row w-100 align-items-center">
											  <div class="col-sm-4 mb-1 mb-sm-0 mb-lg-1 mb-xxl-0 mt-0  text-start">
												<small class="mb-0 fw-normal text-truncate"><?php echo $tr->translate('EMAIL'); ?></small>
											  </div>
											  <div class="col-sm-8 d-flex justify-content-sm-end mt-0 ">
												<small class="text-truncate"><?php echo !empty($rs['email']) ? $rs['email'] : "N/A"; ?></small>
											  </div>
											</div>
										</div>
									</div>
									<div class="card-body py-2 px-1">
										<p class="mb-0 text-primary text-truncate"><?php echo $rs['teacherCode']; ?></p>
										<h4 class="teacherName mb-0 mt-0 text-primary text-truncate"><?php echo $teacherName; ?></h4>
										
										<div class="row w-100 align-items-center">
										  <div class="col-sm-4 mb-1 mb-sm-0 mb-lg-1 mb-xxl-0 mt-0  text-start">
											<small class="mb-0 fw-normal text-truncate"><?php echo $tr->translate('NATION'); ?></small>
										  </div>
										  <div class="col-sm-8 d-flex justify-content-sm-end mt-0 ">
											<small class="text-truncate"><?php echo !empty($rs['nation']) ? $rs['nation'] : "N/A"; ?></small>
										  </div>
										</div>
										<div class="row w-100 align-items-center">
										  <div class="col-sm-4 mb-1 mb-sm-0 mb-lg-1 mb-xxl-0 mt-0  text-start">
											<small class="mb-0 fw-normal text-truncate"><?php echo $tr->translate('NATIONALITY'); ?></small>
										  </div>
										  <div class="col-sm-8 d-flex justify-content-sm-end mt-0 ">
											<small class="text-truncate"><?php echo !empty($rs['nationality']) ? $rs['nationality'] : "N/A"; ?></small>
										  </div>
										</div>
										<div class="row w-100 align-items-center">
										  <div class="col-sm-4 mb-1 mb-sm-0 mb-lg-1 mb-xxl-0 mt-0  text-start">
											<small class="mb-0 fw-normal text-truncate"><?php echo $tr->translate('CULTURE_LEVEL'); ?></small>
										  </div>
										  <div class="col-sm-8 d-flex justify-content-sm-end mt-0 ">
											<small class="text-truncate"><?php echo !empty($rs['educationTitle']) ? $rs['educationTitle'] : "N/A"; ?></small>
										  </div>
										</div>
										<div class="row w-100 align-items-center">
										  <div class="col-sm-4 mb-1 mb-sm-0 mb-lg-1 mb-xxl-0 mt-0  text-start">
											<small class="mb-0 fw-normal text-truncate"><?php echo $tr->translate('TEL'); ?></small>
										  </div>
										  <div class="col-sm-8 d-flex justify-content-sm-end mt-0 ">
											<small class="text-truncate"><?php echo !empty($rs['tel']) ? $rs['tel'] : "N/A"; ?></small>
										  </div>
										</div>
										<div class="row w-100 align-items-center">
										  <div class="col-sm-4 mb-1 mb-sm-0 mb-lg-1 mb-xxl-0 mt-0  text-start">
											<small class="mb-0 fw-normal text-truncate"><?php echo $tr->translate('EMAIL'); ?></small>
										  </div>
										  <div class="col-sm-8 d-flex justify-content-sm-end mt-0 ">
											<small class="text-truncate"><?php echo !empty($rs['email']) ? $rs['email'] : "N/A"; ?></small>
										  </div>
										</div>
										
									</div>
								</div>
							</div>
							<div class="row g-3">
								<div class="col-md-12 col-sm-12 col-xs-12 mt-0 rounded card-info-left">
									<div class="content-teachinginfo">
										<div class="row w-100 align-items-center mt-10">
											<small ><?php echo $tr->translate("TEACHING_INFO");?> <strong><?php echo $rs["academicYearTtitle"];?></strong></small>
											<br>
											<small class="fw-normal">
												<?php echo $tr->translate('AMT_SUBJECT'); echo " <strong>".sprintf('%02d',$rs['countSubject'])."</strong>"; echo " ".$tr->translate('AMT_CLASS')." "; echo " <strong>".sprintf('%02d',$rs['countClass'])."</strong> "; ?>
											</small>
										</div>
										<?php if(!empty($detail)){ 
											foreach($detail as $k => $rowDe){
												$classR = (($k%2)==0) ? "" : "odd-row";
										?>
										<div class="<?php echo $classR; ?> row w-100 align-items-center">
											<div class="col-sm-8 mb-1 mb-sm-0 mb-lg-1 mb-xxl-0 mt-0  text-start text-truncate">
												<small class="mb-0 fw-normal "><?php echo $k+1; ?> <strong><?php echo $rowDe["subj"]; ?></strong> <?php echo $rowDe["subjSho"]; ?></small>
											</div>
											<div class="col-sm-4 d-flex justify-content-sm-end mt-0 ">
												<small class="text-truncate"><?php echo $rowDe["class"]; ?></small>
											</div>
										</div>
										<?php if($k==4){break;} } ?>
										<?php } ?>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			<?php } ?>
			<?php
			if ($this->countPages > 1) {
				$statpage = $this->currentPage - 5;
				$endpage = $this->currentPage + 5;
				if ($this->currentPage <= 5) {
					$statpage = 1;
					$endpage = 10;
				}
				if (!empty($this->countPages)) {
			?>
					<div class="clearfix"></div>
					<div class="pagin text-center">
						<nav aria-label="Page navigation example">
							<ul class="pagination">
								<?php if ($this->currentPage != 1) { ?>
									<li class="page-item"><a class="page-link" href="<?php echo $urlsting . $sign . "pages=" . $this->previousPage; ?>"><?php echo $tr->translate('Previous'); ?></a></li>
								<?php } ?>
								<?php $i = 0;
								for ($i = 1; $i <= $this->countPages; $i++) { ?>
									<?php if ($statpage <= $i && $endpage >= $i) { ?>
										<li class="page-item <?php if ($i == $this->currentPage) {
																	echo "active";
																} ?>">
											<a class="page-link" href="<?php echo $urlsting . $sign . "pages=" . $i; ?>"><?php echo $i; ?></a>
										</li>
								<?php }
								} ?>
								<?php if ($this->countPages != $this->currentPage) { ?>
									<li class="page-item"><a class="page-link" href="<?php echo $urlsting . $sign . "pages=" . $this->nextPage; ?>"><?php echo $tr->translate('Next'); ?></a></li>
								<?php } ?>
							</ul>
						</nav>
						<span><?php echo $tr->translate('Total Pages') . " : " . $this->countPages . " " . $tr->translate('Pages'); ?></span>
					</div>
			<?php }
			} ?>
		</div>
	</div>
</div>

<script src="<?php echo $this->baseUrl(); ?>/js/help.js" type="text/javascript"></script>
<script type="text/javascript">
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dojo.data.ObjectStore");
	dojo.require("dojo.data.ItemFileWriteStore");

	var group_store = getDataStorefromJSON('id', 'name', <?php print_r(Zend_Json::encode(array())); ?>);
	var grade_store = getDataStorefromJSON('id', 'name', <?php print_r(array()) ?>);
	var oldBranch = "<?php echo empty($this->adv_search['branch_id']) ? 0 : $this->adv_search['branch_id']; ?>";

	dojo.ready(function() {
		new dijit.form.FilteringSelect({
			queryExpr: "*${0}*",
			autoComplete: false,
			required: false,
			id: "grade",
			name: "grade",
			class: 'fullside',
			placeHolder: "<?php echo $tr->translate("SELECT_GRADE"); ?>",
			onChange: function() {

			}
		}, "grade");

		new dijit.form.FilteringSelect({
			store: group_store,
			queryExpr: "*${0}*",
			autoComplete: false,
			required: false,
			id: "group",
			name: "group",
			class: 'fullside',
			readonly: false,
			placeHolder: "<?php echo $tr->translate("SELECT_GROUP"); ?>",
			onChange: function() {

			}
		}, "group");


		getallGrade();
		getAllGroupByAcademic();

		var branch_id = dijit.byId('branch_id');
		branch_id.on('change', function(evt) {
			getAllGroupByAcademic();
		});
		academicYear = dijit.byId('academic_year');
		academicYear.on('change', function(evt) {
			getAllGroupByAcademic();
		});
	});

	url_getgroupbyAca = '<?php echo $this->url(array('module' => 'foundation', 'controller' => 'group', 'action' => 'getallgroup')); ?>';

	function getAllGroupByAcademic() {
		dijit.byId('group').reset();

		study_year = dijit.byId('academic_year').get('value');
		if (study_year == '' || study_year == -1) {
			var group_store = getDataStorefromJSON('id', 'name', <?php print_r(Zend_Json::encode(array())); ?>);
			dijit.byId('group').set('store', group_store);
			getAllGroupByBranch();
			return false;
		}
		dojo.xhrPost({
			url: url_getgroupbyAca,
			content: {
				'academic_year': study_year,
				'noaddnew': 1
			},
			handleAs: "json",
			load: function(data) {
				group_store = getDataStorefromJSON('id', 'name', data);
				dijit.byId('group').set('store', group_store);
				dijit.byId('group').set('value', '<?php echo $this->adv_search['group'] ?>');
			},
			error: function(err) {}
		});
	}

	url_getgroup = '<?php echo $this->url(array('module' => 'foundation', 'controller' => 'group', 'action' => 'getgroupbybranch')); ?>';

	function getAllGroupByBranch() {
		dijit.byId('group').reset();
		branch_id = dijit.byId('branch_id').get('value');
		if (branch_id == '' || branch_id == -1) {
			var group_store = getDataStorefromJSON('id', 'name', <?php print_r(Zend_Json::encode(array())); ?>);
			dijit.byId('group').set('store', group_store);
			dijit.byId('branch_id').focus();
			return false;
		}
		dojo.xhrPost({
			url: url_getgroup,
			content: {
				'branch_id': branch_id,
				'noaddnew': 1
			},
			handleAs: "json",
			load: function(data) {
				group_store = getDataStorefromJSON('id', 'name', data);
				dijit.byId('group').set('store', group_store);
				if (oldBranch == branch_id) {
					dijit.byId('group').set('value', '<?php echo $this->adv_search['group'] ?>');
				}
			},
			error: function(err) {}
		});
	}

	var url_dept = '<?php echo $this->url(array('module' => 'global', 'controller' => 'grade', 'action' => 'get-grade')); ?>';

	function getallGrade() {
		dept_id = dijit.byId('degree').get('value');
		if (dept_id == '') {
			return false;
		}
		dojo.xhrPost({
			url: url_dept,
			content: {
				'dept_id': dept_id,
				'noaddnew': 1
			},
			handleAs: "json",
			load: function(data) {
				grade_store = getDataStorefromJSON('id', 'name', data);
				dijit.byId('grade').set('store', grade_store);
				dijit.byId('grade').attr('value', '<?php echo $this->adv_search['grade'] ?>');
			},
			error: function(err) {
				alert(err);
			}
		});
	}

	function copyRecord(url) {
		id = dijit.byId('recordcopy').get('value');
		if (id != '') {
			window.location.href = url + '/id/' + id;
		} else {
			alert('Please select record you want to copy');
			return false;
		}
	}

	function setValue(index) {
		var recordcopy = $('input[name=copy]:checked').val();
		dijit.byId('recordcopy').attr('value', recordcopy);
	}
</script>