<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$this->headTitle($tr->translate('RPT_PRE_REGISTER_ACCOUNT'));
echo $this->headTitle('');
$frm =  $this->form_search;
$classHideHeight = "110px";
$dateFormat ="d/m/Y";
$dateFormatExpt ="d/M/Y";
?>
<style>
	.hover:hover {
		background: #ccc;
	}

	.hidden {
		visibility: visible !important;
		display: table-cell !important;
	}
</style>
<div class="layout-wrapper-report">
	<div id="mainContent" class="main-content-report">
		<div class="report-preview">
			<?php echo $this->controlReport?>
			<div id="main-viewer" class="main-viewer portrait">
				<div id="viewer" class="viewer portrait">
					<div id="divPrint" class="content">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style.css">
						<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/build/css/report-style-screen.css">
						<style>
							@media print {
								<?php if(!empty($this->printFormat)){ echo $this->printFormat; } ?>
							}
						</style>
						<table border="0" style="background:#fff; margin: 0 auto; width: 100%; ">
							<tr>
								<td colspan="3"><?php echo $this->rsheader; ?></td>
							</tr>
							<tr>
								<td width="15%" align="center">
								</td>
								<td width="70%" align="center">
									<strong style="font-weight:normal;font-family: Arial Black;color:#000; font-size: 14px;font-family:'Khmer OS Muol Light';"><?php echo $tr->translate("RPT_PRE_REGISTER_ACCOUNT"); ?></strong><br />
									<strong style="font-weight:normal;font-family: Arial Black;color:#000; font-size: 12px;font-family:'Khmer OS Muol Light';"><?php if (!empty($this->search['start_date'])) { ?><?php echo date($dateFormat, strtotime($this->search['start_date'])); ?> <?php echo $tr->translate("TO"); ?> <?php echo date($dateFormat, strtotime($this->search['end_date']));
																																																																														} ?> </strong>
								</td>
								<td width="15%" align="center">
								</td>
							</tr>
							<tr>
								<td colspan="3">
									<div id="exportExcel">
										<table class="content-data text-color-black text-h16px text-size-12px" cellpadding="4" border="1">
											<thead>
												<tr class="styleheader bg-head text-bold hpx-25" align="center">
													<th scope="col"><?php echo $tr->translate("NUM"); ?></th>
													<th scope="col"><?php echo $tr->translate("STUDENT_NAMEKHMER"); ?></th>
													<th scope="col"><?php echo $tr->translate("NAME_ENGLISH"); ?></th>
													<th scope="col"><?php echo $tr->translate("DATE_OF_BIRTH"); ?></th>
													<th scope="col"><?php echo $tr->translate("SEX"); ?></th>
													<th scope="col"><?php echo $tr->translate("PHONE"); ?></th>
													<th scope="col"><?php echo $tr->translate("EMAIL"); ?></th>
													<th scope="col"><?php echo $tr->translate("DEGREE"); ?></th>
													<th scope="col"><?php echo $tr->translate("GRADE"); ?></th>
													<th scope="col"><?php echo $tr->translate("CREATE_DATE"); ?></th>
												</tr>
											</thead>
											<?php $i = 0;
											$degree = 0;
											foreach ($this->rs as $row) {
												$i++;
												$degree = $row['degree']; 
												$dateString = $row["dob"];
												$date = new DateTime($dateString);
												$dobDate = $date->format($dateFormat);
												$dobDateExpt = $date->format($dateFormatExpt);
												
												$dateString = $row["createDate"];
												$date = new DateTime($dateString);
												$createDate = $date->format($dateFormat);
												$createDateExpt = $date->format($dateFormatExpt);
												?>
												<tr align="center" class="hover style">
													<td><?php echo $i; ?></td>
													<td align="left"><?php echo $row['fullKhName']; ?></td>
													<td align="left"><?php echo $row['lastName'] . " " . $row['firstName']; ?></td>
													<td class="hideExport"><?php echo $dobDate; ?></td>
													<td class="showExport" style="display:none;"><?php echo $dobDateExpt; ?></td>
													<td align="left"><?php echo  $row['sex']; ?></td>
													<td align="left"><?php echo $row['countryCode'] . " " . $row['phoneNumber']; ?></td>
													<td align="left"><?php echo  $row['email']; ?></td>
													<td align="left"><?php echo $row['degree']; ?></td>
													<td align="left"><?php echo $row['grade']; ?></td>

													<td class="hideExport"><?php echo $createDate; ?></td>
													<td class="showExport" style="display:none;"><?php echo $createDateExpt; ?></td>
												</tr>
											<?php } ?>
										</table>
									</div>
								</td>
							</tr>
							<tr>
								<td colspan="3">
									<?php echo $this->rsfooteracc; ?>
								</td>
							</tr>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="right-panel-report" id="rightPanel">
		<div class="card-box">
			<div class="card-search-head col-sm-12 border-botom">
				<div class="col-sm-6 text-left pd-0">
					<h4 class="m-b-0">
						<?php echo $tr->translate("SEARCH");?> 
						<i class="fa fa-search "></i> 
					</h4>
				</div>
				<div class="col-sm-6 text-right pd-0">
					<button onclick="closeRightPanel()" title="<?php echo $tr->translate("CLOSED");?> " class="btn-close">
						<i class="fa-solid fa-xmark"></i>
					</button>
				</div>
			</div>
			<form id='foundation_class' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
				<div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<?php echo $frm->getElement("adv_search"); ?>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm->getElement("degree"); ?>
					</div>
					<div class="col-md-6 col-sm-6 col-xs-12">
						<input id="grade" />
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm->getElement("start_date"); ?>
					</div>
					<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $frm->getElement("end_date"); ?>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-6 col-sm-6 col-xs-12">
						<button class="button-class button-primary fullside" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" name="search" type="submit"><?php echo $tr->translate("SEARCH"); ?></button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl(); ?>/js/help.js"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");
	var group_store = getDataStorefromJSON('id', 'name', <?php print_r(Zend_Json::encode(array())); ?>);
	dojo.ready(function() {
		new dijit.form.FilteringSelect({
			queryExpr: "*${0}*",
			autoComplete: false,
			required: false,
			id: "grade",
			name: "grade",
			class: 'fullside',
			placeHolder: "<?php echo $tr->translate("SELECT_GRADE"); ?>",
			onChange: function() {}
		}, "grade");

		getallGrade();
		setTimeout(function() {
			setPrintOrientation('landscape');
		}, 500);
	});

	var url_dept = '<?php echo $this->url(array('module' => 'global', 'controller' => 'grade', 'action' => 'get-grade')); ?>';

	function getallGrade() {
		dept_id = dijit.byId('degree').get('value');
		if (dept_id == '' || dept_id == -1) {
			return false;
		}
		dojo.xhrPost({
			url: url_dept,
			content: {
				'dept_id': dept_id,
				'noaddnew': 1
			},
			handleAs: "json",
			load: function(data) {
				dijit.byId('grade').attr('value', '');
				grade_store = getDataStorefromJSON('id', 'name', data);
				dijit.byId('grade').set('store', grade_store);
				dijit.byId('grade').attr('value', '<?php echo $this->search['grade'] ?>');
			},
			error: function(err) {}
		});
	}
</script>